"""Defends ``test_metadata_models_are_immutable`` behavior for the ``gcode`` production unit.

A failure means this boundary no longer preserves its observable contract.
"""

from __future__ import annotations

from dataclasses import FrozenInstanceError
from pathlib import Path

import pytest

from printstash_core.gcode import (
    GcodeMetadata,
    MaterialRequirement,
    parse,
    parse_duration,
    to_legacy_dict,
)


def test_metadata_models_are_immutable() -> None:
    requirement = MaterialRequirement(0, "PLA", "#FF0000")
    metadata = GcodeMetadata(material_requirements=(requirement,))

    with pytest.raises(FrozenInstanceError):
        requirement.material_type = "PETG"
    with pytest.raises(FrozenInstanceError):
        metadata.slicer_name = "changed"


def test_parser_preserves_multi_tool_materials_and_colors(tmp_path: Path) -> None:
    path = tmp_path / "multi.gcode"
    path.write_text(
        "; generated by BambuStudio 2.0\n"
        "; filament_type = PLA;PETG\n"
        "; filament_colour = FF0000FF;#00FF00\n"
        "; printer_model = Bambu Lab P1S\n"
        "; layer_height = 0.16\n"
        "; estimated printing time = 1h 2m 3s\n",
        encoding="utf-8",
    )

    metadata = parse(path)

    assert metadata == GcodeMetadata(
        slicer_name="BambuStudio",
        slicer_version="BambuStudio 2.0",
        printer_model="Bambu Lab P1S",
        layer_height_mm=0.16,
        estimated_time_s=3723,
        material_type="PLA",
        material_requirements=(
            MaterialRequirement(0, "PLA", "#FF0000"),
            MaterialRequirement(1, "PETG", "#00FF00"),
        ),
    )


def test_legacy_serializer_has_the_exact_application_shape() -> None:
    metadata = GcodeMetadata(
        material_type="PLA",
        material_requirements=(MaterialRequirement(0, "PLA", None),),
    )

    assert to_legacy_dict(metadata) == {
        "slicer_name": None,
        "slicer_version": None,
        "printer_model": None,
        "nozzle_diameter_mm": None,
        "layer_height_mm": None,
        "first_layer_height_mm": None,
        "infill_percent": None,
        "wall_loops": None,
        "top_shell_layers": None,
        "bottom_shell_layers": None,
        "support_material": None,
        "nozzle_temperature_c": None,
        "bed_temperature_c": None,
        "estimated_time_s": None,
        "filament_weight_g": None,
        "filament_length_mm": None,
        "filament_cost": None,
        "material_type": "PLA",
        "material_brand": None,
        "material_requirements": [
            {"tool_index": 0, "material_type": "PLA", "color_hex": None}
        ],
        "printer_preset_name": None,
    }


@pytest.mark.parametrize(
    ("value", "expected"),
    [
        ("1h 23m 45s", 5025),
        ("1.5h", 5400),
        ("3600", 3600),
        ("-5", None),
        ("not a duration", None),
    ],
)
def test_parse_duration(value: str, expected: int | None) -> None:
    assert parse_duration(value) == expected


def test_missing_file_returns_empty_metadata(tmp_path: Path) -> None:
    assert parse(tmp_path / "missing.gcode") == GcodeMetadata()
