"""Slicer metadata out of free-text G-code comments, from five slicers.

Every value this module reads is a comment written by a program PrintStash does
not control: PrusaSlicer, OrcaSlicer, BambuStudio, SuperSlicer, and Cura each
spell their keys differently, disagree on units, and change both between
releases. The parser's contract is therefore not "read the file correctly" but
**never raise, and never invent a value**. A model uploads fine with no metadata;
it does not upload at all if the parse throws.

That shapes what the tests check. Most rows are a specific spelling from a
specific slicer, or a malformed value that must come back `None` rather than as a
zero — because a zero is a claim. `layer_height_mm = 0` would be rendered to the
user as a real setting, and `filament_weight_g = 0` would be posted to the
filament ledger as a free print.

Two behaviours are load-bearing beyond the field mapping:

**Only the ends of the file are read.** A G-code file for a large print is
hundreds of megabytes of movement commands with the metadata block at the very
end, and this runs in the API process. The parser reads a window from each end
and nothing in between, so cost is constant in file size.

**Multi-tool prints keep per-tool detail.** `filament_type = PLA;PETG` is two
materials in tool order, and collapsing it to the first would attribute the whole
print's filament to one spool.

Binary containers reach the same typed result through `bgcode.read_metadata_text`,
which renders their blocks as comment lines so one parser serves both formats.
"""

from __future__ import annotations

from dataclasses import FrozenInstanceError
from pathlib import Path

import pytest

from printstash_core.gcode import (
    GcodeMetadata,
    MaterialRequirement,
    parse,
    parse_duration,
    parser,
    to_legacy_dict,
)


class TestGcodeMetadata:
    def test_cannot_be_mutated_after_parsing(self) -> None:
        metadata = GcodeMetadata(slicer_name="PrusaSlicer")

        # Parsed metadata is cached and shared; a mutable copy would let one
        # consumer's edit reach the next.
        with pytest.raises(FrozenInstanceError):
            metadata.slicer_name = "changed"

    def test_defaults_every_field_to_unknown(self) -> None:
        metadata = GcodeMetadata()

        # Absent, not zero: a zero here would be rendered to the user as a real
        # setting and posted to the filament ledger as a real weight.
        assert metadata.layer_height_mm is None
        assert metadata.filament_weight_g is None
        # `None`, not `()`: no material block was found, which is different
        # from a slicer reporting an empty one.
        assert metadata.material_requirements is None


class TestMaterialRequirement:
    def test_cannot_be_mutated_after_parsing(self) -> None:
        requirement = MaterialRequirement(0, "PLA", "#FF0000")

        with pytest.raises(FrozenInstanceError):
            requirement.material_type = "PETG"

    def test_defaults_its_colour_to_unknown(self) -> None:
        assert MaterialRequirement(0, "PLA").color_hex is None


class TestParseDuration:
    @pytest.mark.parametrize(
        ("value", "seconds"),
        [
            ("1h 23m 45s", 5025),
            ("1.5h", 5400),
            ("3600", 3600),
        ],
    )
    def test_reads_every_duration_spelling_slicers_use(
        self, value: str, seconds: int
    ) -> None:
        assert parse_duration(value) == seconds

    @pytest.mark.parametrize("value", ["-5", "not a duration"])
    def test_says_it_cannot_read_an_unusable_duration(self, value: str) -> None:
        # A negative or unparseable estimate must not become a print time the
        # queue then schedules against.
        assert parse_duration(value) is None


class TestParse:
    def test_keeps_one_material_entry_per_tool(self, tmp_path: Path) -> None:
        path = tmp_path / "multi.gcode"
        path.write_text(
            "; generated by BambuStudio 2.0\n"
            "; filament_type = PLA;PETG\n"
            "; filament_colour = FF0000FF;#00FF00\n"
            "; printer_model = Bambu Lab P1S\n"
            "; layer_height = 0.16\n"
            "; estimated printing time = 1h 2m 3s\n",
            encoding="utf-8",
        )

        # Collapsing this to the first material would attribute the whole
        # print's filament to one spool. Note the RGBA colour losing its alpha
        # and the bare hex gaining its `#`.
        assert parse(path) == GcodeMetadata(
            slicer_name="BambuStudio",
            slicer_version="BambuStudio 2.0",
            printer_model="Bambu Lab P1S",
            layer_height_mm=0.16,
            estimated_time_s=3723,
            material_type="PLA",
            material_requirements=(
                MaterialRequirement(0, "PLA", "#FF0000"),
                MaterialRequirement(1, "PETG", "#00FF00"),
            ),
        )

    def test_returns_empty_metadata_for_a_missing_file(self, tmp_path: Path) -> None:
        # A queued parse races the library: the artifact can be purged between
        # the job being enqueued and the parse starting.
        assert parse(tmp_path / "missing.gcode") == GcodeMetadata()

    def test_returns_empty_metadata_for_a_file_with_no_comments(
        self, tmp_path: Path
    ) -> None:
        path = tmp_path / "bare.gcode"
        path.write_text("G28\nG1 X10 Y10\n", encoding="utf-8")

        # Hand-written or post-processed G-code carries no slicer block. That is
        # a model with no metadata, not a failed upload.
        assert parse(path) == GcodeMetadata()

    def test_returns_empty_metadata_for_a_binary_container_with_no_metadata_block(
        self, tmp_path: Path
    ) -> None:
        import struct

        # A valid `.bgcode` whose only block is the printable body. The binary
        # path has to reach the same "no metadata" answer as the text path
        # rather than fall through to parsing the container's bytes as comments.
        gcode_block = struct.pack("<HHI", 1, 0, 4) + struct.pack("<H", 2) + b"body"
        path = tmp_path / "gcode-only.bgcode"
        path.write_bytes(b"GCDE" + struct.pack("<IH", 1, 0) + gcode_block)

        assert parse(path) == GcodeMetadata()

    @pytest.mark.parametrize("colour", ["not-a-colour", "#12", "GGGGGG", "#FF00", ""])
    def test_drops_a_colour_it_cannot_read(self, tmp_path: Path, colour: str) -> None:
        path = tmp_path / "colour.gcode"
        path.write_text(
            f"; generated by PrusaSlicer 2.8.0\n"
            f"; filament_type = PLA\n"
            f"; filament_colour = {colour}\n",
            encoding="utf-8",
        )

        metadata = parse(path)

        # An unreadable colour must not become a swatch the UI renders; the
        # material itself is still worth keeping.
        assert metadata.material_requirements == (MaterialRequirement(0, "PLA"),)


class TestToLegacyDict:
    def test_emits_every_field_the_application_reads(self) -> None:
        metadata = GcodeMetadata(
            material_type="PLA",
            material_requirements=(MaterialRequirement(0, "PLA", None),),
        )

        # This exact shape is what the API returns and what the database column
        # holds, so a renamed or dropped key is a contract change.
        assert to_legacy_dict(metadata) == {
            "slicer_name": None,
            "slicer_version": None,
            "printer_model": None,
            "nozzle_diameter_mm": None,
            "layer_height_mm": None,
            "first_layer_height_mm": None,
            "infill_percent": None,
            "wall_loops": None,
            "top_shell_layers": None,
            "bottom_shell_layers": None,
            "support_material": None,
            "nozzle_temperature_c": None,
            "bed_temperature_c": None,
            "estimated_time_s": None,
            "filament_weight_g": None,
            "filament_length_mm": None,
            "filament_cost": None,
            "material_type": "PLA",
            "material_brand": None,
            "material_requirements": [
                {"tool_index": 0, "material_type": "PLA", "color_hex": None}
            ],
            "printer_preset_name": None,
        }


class TestParseHelpers:
    """The small conversions that turn slicer comment text into typed values.

    Slicer comments are free text written by five different programs, so every one of
    these has to answer "I could not tell" rather than guess. A wrong number here becomes
    a wrong cost estimate or a wrong print time on a card, which nobody checks.
    """

    @pytest.mark.parametrize(
        ("value", "expected"),
        [
            pytest.param("1h 30m", 5400, id="hours-and-minutes"),
            pytest.param("2d", 172800, id="days"),
            pytest.param("45s", 45, id="seconds"),
            pytest.param("90", 90, id="bare-seconds"),
            pytest.param("90.7", 90, id="fractional-seconds"),
        ],
    )
    def test_reads_a_duration(self, value: str, expected: int) -> None:
        assert parser.parse_duration(value) == expected

    @pytest.mark.parametrize(
        "value",
        [
            pytest.param("", id="empty"),
            pytest.param("not a duration", id="prose"),
            pytest.param("-30", id="negative"),
        ],
    )
    def test_says_it_cannot_read_a_duration(self, value: str) -> None:
        assert parser.parse_duration(value) is None

    @pytest.mark.parametrize(
        ("value", "expected"),
        [
            pytest.param("1.5", 1.5, id="plain"),
            pytest.param("  -2.25 mm", -2.25, id="signed-with-unit"),
            pytest.param("+3", 3.0, id="explicit-plus"),
        ],
    )
    def test_reads_a_number_out_of_a_comment(self, value: str, expected: float) -> None:
        assert parser._to_float(value) == expected

    @pytest.mark.parametrize("value", [None, "no digits here"], ids=["absent", "prose"])
    def test_says_it_cannot_read_a_number(self, value: str | None) -> None:
        assert parser._to_float(value) is None

    def test_reads_the_first_of_a_comma_separated_integer_list(self) -> None:
        # Multi-tool slicers write one value per tool; the first is the one the
        # single-value fields describe.
        assert parser._to_int("3,4,5") == 3

    @pytest.mark.parametrize("value", [None, "abc"], ids=["absent", "prose"])
    def test_says_it_cannot_read_an_integer(self, value: str | None) -> None:
        assert parser._to_int(value) is None

    @pytest.mark.parametrize(
        "value",
        ["1", "true", "yes", "on", "enabled", "generated", "TRUE"],
        ids=["one", "true", "yes", "on", "enabled", "generated", "uppercase"],
    )
    def test_reads_every_spelling_of_yes(self, value: str) -> None:
        assert parser._to_bool(value) is True

    @pytest.mark.parametrize(
        "value",
        ["0", "false", "no", "off", "disabled", "none", "not generated"],
        ids=["zero", "false", "no", "off", "disabled", "none", "not-generated"],
    )
    def test_reads_every_spelling_of_no(self, value: str) -> None:
        assert parser._to_bool(value) is False

    @pytest.mark.parametrize("value", [None, "maybe"], ids=["absent", "unknown"])
    def test_says_it_cannot_read_a_flag(self, value: str | None) -> None:
        # Guessing `False` here would silently claim a feature was off.
        assert parser._to_bool(value) is None

    @pytest.mark.parametrize(
        ("version", "expected"),
        [
            pytest.param("OrcaSlicer 2.1", "OrcaSlicer", id="orca"),
            pytest.param("PrusaSlicer 2.7", "PrusaSlicer", id="prusa"),
            pytest.param("BambuStudio 1.9", "BambuStudio", id="bambu"),
            pytest.param("SuperSlicer 2.5", "SuperSlicer", id="super"),
            pytest.param("Cura_SteamEngine 5.6", "Cura", id="cura"),
        ],
    )
    def test_names_the_slicer_from_its_version_string(
        self, version: str, expected: str
    ) -> None:
        assert parser._slicer_name(version) == expected

    @pytest.mark.parametrize(
        "version", [None, "SomeNewSlicer 1.0"], ids=["absent", "unknown"]
    )
    def test_says_it_does_not_recognise_a_slicer(self, version: str | None) -> None:
        assert parser._slicer_name(version) is None


class TestParseWindow:
    """Only the head and tail of a file are read, because a G-code file is huge.

    Slicers write their metadata as comments at the very top and the very bottom, so the
    parser reads two bounded windows rather than the whole file. A 2 GB print would
    otherwise be 2 GB of memory to learn its layer height.
    """

    def test_reads_metadata_from_the_end_of_a_large_file(self, tmp_path: Path) -> None:
        path = tmp_path / "big.gcode"
        padding = b"G1 X1 Y1 E1\n" * 200_000
        path.write_bytes(
            b"; generated by OrcaSlicer 2.1\n" + padding + b"; layer_height = 0.2\n"
        )

        metadata = parser.parse(path)

        assert metadata.slicer_name == "OrcaSlicer"
        assert metadata.layer_height_mm == 0.2

    def test_ignores_the_middle_of_a_large_file(self, tmp_path: Path) -> None:
        path = tmp_path / "middle.gcode"
        path.write_bytes(
            b"; generated by OrcaSlicer 2.1\n"
            + b"G1 X1 Y1 E1\n" * 200_000
            + b"; layer_height = 0.9\n"
            + b"G1 X1 Y1 E1\n" * 200_000
            + b"; nozzle_diameter = 0.4\n"
        )

        metadata = parser.parse(path)

        # The buried value is deliberately not found: reading it would mean
        # reading the whole file.
        assert metadata.layer_height_mm is None

    def test_survives_bytes_that_are_not_valid_utf8(self, tmp_path: Path) -> None:
        path = tmp_path / "binary.gcode"
        path.write_bytes(
            b"; generated by OrcaSlicer 2.1\n\xff\xfe\n; layer_height = 0.2\n"
        )

        # A slicer profile name can carry any encoding somebody typed; a decode
        # error must not lose the rest of the metadata.
        assert parser.parse(path).slicer_name == "OrcaSlicer"

    def test_converts_curas_metres_to_millimetres(self, tmp_path: Path) -> None:
        path = tmp_path / "cura.gcode"
        path.write_bytes(b"; generated by Cura_SteamEngine 5.6\n;Filament used: 1.5m\n")

        # Cura reports metres while every other slicer reports millimetres, and
        # the stored field is millimetres.
        assert parser.parse(path).filament_length_mm == 1500
