"""Reading PrusaSlicer binary G-code containers without trusting them.

A `.bgcode` file is a length-prefixed block container that arrives by upload,
which makes every framing field in it attacker-controlled: block count, declared
data length, declared *uncompressed* length, compression scheme, parameter
length, checksum type. This reader's job is to answer questions about such a file
— is it valid, what metadata does it carry, what thumbnail — while never letting
one of those numbers decide how much memory to allocate.

Three defences, and each has its own rows below.

**Sizes are checked before any read.** A declared length is compared against the
real file size first, so a block claiming a gigabyte cannot make the parser
reserve one. Metadata and thumbnails have their own output ceilings.

**Decompression is bounded and exact.** A deflate stream is decoded with an
explicit output limit, and the decoded length must equal the header's claim. A
header that disagrees with its own payload is the shape of a decompression bomb,
and a partial or trailing-garbage stream is refused rather than accepted with
whatever came out.

**The printable body is skipped, never decoded.** G-code blocks use heatshrink,
which this reader does not implement and does not need to: validation seeks past
them. That is also why a printable block may legitimately be larger than the
metadata cap.

Everything is failure-tolerant by design. A partially written file — a slicer
interrupted mid-export — must read as "no metadata" rather than crash an ingest
job, and an unreadable path must answer `False` rather than raise. The upload
succeeded; the parse is a best effort on top of it.
"""

from __future__ import annotations

import struct
import zlib
from pathlib import Path

from printstash_core.gcode import (
    GcodeMetadata,
    MaterialRequirement,
    bgcode,
    is_valid_container,
    parse,
)

_FILE_METADATA = 0
_GCODE = 1
_SLICER_METADATA = 2
_THUMBNAIL = 5
# Block type 99 is not in the spec, so it declares no parameter bytes.
_UNKNOWN_BLOCK = 99


def _block(
    block_type: int,
    params: bytes,
    data: bytes,
    *,
    compression: int,
) -> bytes:
    body = zlib.compress(data) if compression == 1 else data
    header = struct.pack("<HHI", block_type, compression, len(data))
    if compression != 0:
        header += struct.pack("<I", len(body))
    return header + params + body


def _container(*blocks: bytes) -> bytes:
    return b"GCDE" + struct.pack("<IH", 1, 0) + b"".join(blocks)


def _gcode_block(body: bytes = b"body") -> bytes:
    """A minimal printable block — a container needs one to be valid."""

    return _block(_GCODE, struct.pack("<H", 2), body, compression=0)


def _sample_container() -> bytes:
    """One metadata block, one thumbnail, one heatshrink-compressed body."""

    metadata = _block(
        _FILE_METADATA,
        struct.pack("<H", 0),
        b"Producer=PrusaSlicer 2.8.0\nfilament_type=PETG\n",
        compression=1,
    )
    thumbnail = _block(
        _THUMBNAIL,
        struct.pack("<HHH", 0, 16, 16),
        b"thumbnail-bytes",
        compression=1,
    )
    gcode = _block(
        _GCODE,
        struct.pack("<H", 2),
        b"opaque-heatshrink",
        compression=3,
    )
    return _container(metadata, thumbnail, gcode)


def _written(path: Path, payload: bytes) -> Path:
    path.write_bytes(payload)
    return path


class TestIsBgcode:
    def test_recognises_the_container_magic(self, tmp_path: Path) -> None:
        path = tmp_path / "sample.bgcode"
        path.write_bytes(_sample_container())

        assert bgcode.is_bgcode(path) is True

    def test_rejects_a_file_that_is_not_binary_gcode(self, tmp_path: Path) -> None:
        path = tmp_path / "plain.gcode"
        path.write_bytes(b"; generated by PrusaSlicer\nG28\n")

        # The magic is the only cheap way to tell the two formats apart before
        # committing to a parse, and a plain G-code file must take the text path.
        assert bgcode.is_bgcode(path) is False

    def test_rejects_a_file_shorter_than_the_magic(self, tmp_path: Path) -> None:
        path = tmp_path / "tiny.bgcode"
        path.write_bytes(b"GC")

        assert bgcode.is_bgcode(path) is False

    def test_reports_an_unreadable_file_as_not_bgcode(self, tmp_path: Path) -> None:
        # A directory is the portable way to make `open` raise OSError. An
        # unreadable file is not a bgcode file, and it must not propagate.
        assert bgcode.is_bgcode(tmp_path) is False


class TestIsValidContainerFraming:
    """Every framing field is attacker-controlled, so each gets its own refusal."""

    def test_rejects_a_wrong_magic(self, tmp_path: Path) -> None:
        path = tmp_path / "bad.bgcode"
        path.write_bytes(b"NOPE" + struct.pack("<IH", 1, 0))

        assert is_valid_container(path) is False

    def test_rejects_a_header_shorter_than_ten_bytes(self, tmp_path: Path) -> None:
        path = tmp_path / "short.bgcode"
        path.write_bytes(b"GCDE" + struct.pack("<I", 1))

        # The header carries a version and a checksum type; a truncated one means
        # the checksum length is unknown and every subsequent offset is a guess.
        assert is_valid_container(path) is False

    def test_rejects_a_container_with_no_blocks(self, tmp_path: Path) -> None:
        path = tmp_path / "empty.bgcode"
        path.write_bytes(_container())

        assert is_valid_container(path) is False

    def test_rejects_a_block_header_cut_short(self, tmp_path: Path) -> None:
        path = tmp_path / "cut.bgcode"
        path.write_bytes(_container(struct.pack("<HH", _GCODE, 0)))

        assert is_valid_container(path) is False

    def test_rejects_a_missing_compressed_size(self, tmp_path: Path) -> None:
        path = tmp_path / "nosize.bgcode"
        # Declares deflate, so a 4-byte compressed size must follow the header.
        path.write_bytes(_container(struct.pack("<HHI", _GCODE, 1, 10)))

        assert is_valid_container(path) is False

    def test_rejects_params_cut_short(self, tmp_path: Path) -> None:
        path = tmp_path / "noparams.bgcode"
        # A G-code block declares two parameter bytes; supply one.
        path.write_bytes(_container(struct.pack("<HHI", _GCODE, 0, 0) + b"\x00"))

        assert is_valid_container(path) is False

    def test_rejects_a_block_that_declares_more_data_than_the_file_holds(
        self, tmp_path: Path
    ) -> None:
        path = tmp_path / "overrun.bgcode"
        header = struct.pack("<HHI", _GCODE, 0, 1_000_000) + struct.pack("<H", 0)
        path.write_bytes(_container(header + b"short"))

        # The declared size is checked against the real file size *before* any
        # read, so a hostile length cannot make the parser allocate for it.
        assert is_valid_container(path) is False

    def test_rejects_an_unknown_compression_scheme(self, tmp_path: Path) -> None:
        path = tmp_path / "weird.bgcode"
        metadata = _block(
            _FILE_METADATA, struct.pack("<H", 0), b"Producer=X\n", compression=1
        )
        # Compression 7 does not exist. The scheme is an allowlist rather than a
        # blocklist, so an unknown value is refused rather than passed through.
        weird = struct.pack("<HHI", _FILE_METADATA, 7, 4) + struct.pack("<I", 4)
        weird += struct.pack("<H", 0) + b"data"
        gcode = _block(_GCODE, struct.pack("<H", 2), b"body", compression=0)
        path.write_bytes(_container(metadata, weird, gcode))

        assert is_valid_container(path) is False

    def test_rejects_a_decoded_size_that_disagrees_with_the_header(
        self, tmp_path: Path
    ) -> None:
        path = tmp_path / "lying.bgcode"
        body = zlib.compress(b"Producer=X\n")
        # Claim 9999 uncompressed bytes while the stream holds far fewer.
        header = struct.pack("<HHI", _FILE_METADATA, 1, 9999)
        header += struct.pack("<I", len(body)) + struct.pack("<H", 0)
        gcode = _block(_GCODE, struct.pack("<H", 2), b"body", compression=0)
        path.write_bytes(_container(header + body, gcode))

        # A header that disagrees with its own payload is the shape of a
        # decompression bomb, so the two are compared after decoding.
        assert is_valid_container(path) is False

    def test_skips_a_checksum_between_blocks(self, tmp_path: Path) -> None:
        path = tmp_path / "crc.bgcode"
        metadata = (
            _block(
                _FILE_METADATA,
                struct.pack("<H", 0),
                b"Producer=PrusaSlicer 2.8.0\n",
                compression=1,
            )
            + b"\x00\x00\x00\x00"
        )
        gcode = _block(_GCODE, struct.pack("<H", 2), b"body", compression=0)
        gcode += b"\x00\x00\x00\x00"
        # checksum_type 1 means every block carries a trailing CRC32.
        path.write_bytes(b"GCDE" + struct.pack("<IH", 1, 1) + metadata + gcode)

        # A parser that ignored the checksum length would read it as the next
        # block header and reject a perfectly valid file.
        assert is_valid_container(path) is True

    def test_reports_an_unreadable_path_as_invalid(self, tmp_path: Path) -> None:
        assert is_valid_container(tmp_path / "missing.bgcode") is False


class TestReadMetadataText:
    def test_returns_the_decoded_metadata_block(self, tmp_path: Path) -> None:
        path = tmp_path / "sample.bgcode"
        path.write_bytes(_sample_container())

        text = bgcode.read_metadata_text(path)

        assert text is not None
        assert "Producer=PrusaSlicer 2.8.0" in text

    def test_returns_nothing_for_a_file_that_is_not_bgcode(
        self, tmp_path: Path
    ) -> None:
        path = tmp_path / "plain.gcode"
        path.write_bytes(b"G28\n")

        assert bgcode.read_metadata_text(path) is None

    def test_returns_nothing_for_a_missing_file(self, tmp_path: Path) -> None:
        # A queued parse races the library: the artifact can be purged between
        # the job being enqueued and the parse starting.
        assert bgcode.read_metadata_text(tmp_path / "gone.bgcode") is None

    def test_returns_nothing_when_the_metadata_block_is_absent(
        self, tmp_path: Path
    ) -> None:
        path = tmp_path / "gcode-only.bgcode"
        path.write_bytes(
            _container(_block(_GCODE, struct.pack("<H", 2), b"body", compression=0))
        )

        # A container with a printable body and no metadata is valid; there is
        # simply nothing to report, which is different from a parse failure.
        assert bgcode.read_metadata_text(path) is None

    def test_stops_at_a_truncated_block_without_raising(self, tmp_path: Path) -> None:
        path = tmp_path / "truncated.bgcode"
        path.write_bytes(_container(struct.pack("<HH", _FILE_METADATA, 0)))

        # A partially written file is common — a slicer interrupted mid-export —
        # and it must read as "no metadata" rather than crash the ingest job.
        assert bgcode.read_metadata_text(path) is None


class TestIterThumbnails:
    def test_yields_the_embedded_preview_with_its_dimensions(
        self, tmp_path: Path
    ) -> None:
        path = tmp_path / "sample.bgcode"
        path.write_bytes(_sample_container())

        thumbnails = list(bgcode.iter_thumbnails(path))

        assert [(width, height) for _fmt, width, height, _data in thumbnails] == [
            (16, 16)
        ]

    def test_yields_nothing_for_a_container_without_one(self, tmp_path: Path) -> None:
        path = tmp_path / "no-thumb.bgcode"
        path.write_bytes(
            _container(_block(_GCODE, struct.pack("<H", 2), b"body", compression=0))
        )

        assert list(bgcode.iter_thumbnails(path)) == []

    def test_yields_nothing_for_a_missing_file(self, tmp_path: Path) -> None:
        assert list(bgcode.iter_thumbnails(tmp_path / "gone.bgcode")) == []

    def test_yields_nothing_for_a_file_that_is_not_bgcode(self, tmp_path: Path) -> None:
        path = tmp_path / "plain.gcode"
        path.write_bytes(b"G28\n")

        assert list(bgcode.iter_thumbnails(path)) == []


class TestBlockParamLen:
    def test_reports_six_parameter_bytes_for_a_thumbnail(self) -> None:
        # Format, width, height — the reader needs all three to emit a preview.
        assert bgcode._block_param_len(_THUMBNAIL) == 6

    def test_reports_two_parameter_bytes_for_every_block_kind(self) -> None:
        assert bgcode._block_param_len(_FILE_METADATA) == 2
        assert bgcode._block_param_len(_GCODE) == 2

    def test_reports_no_parameter_bytes_for_a_block_type_it_does_not_know(
        self,
    ) -> None:
        # A future block type must be skippable: guessing a parameter length
        # would shift every subsequent offset and reject a valid file.
        assert bgcode._block_param_len(_UNKNOWN_BLOCK) == 0


class TestDecompress:
    def test_returns_stored_data_unchanged(self) -> None:
        assert bgcode._decompress(0, b"metadata", max_output=1024) == b"metadata"

    def test_refuses_stored_data_over_the_output_limit(self) -> None:
        assert bgcode._decompress(0, b"x" * 2048, max_output=1024) is None

    def test_inflates_a_deflate_stream(self) -> None:
        assert (
            bgcode._decompress(1, zlib.compress(b"metadata"), max_output=1024)
            == b"metadata"
        )

    def test_refuses_a_stream_that_inflates_past_the_limit(self) -> None:
        # The bomb case: 8 KiB of zeroes compresses to almost nothing.
        assert (
            bgcode._decompress(1, zlib.compress(b"x" * 8192), max_output=1024) is None
        )

    def test_refuses_a_truncated_stream(self) -> None:
        # Accepting a partial inflate would silently return half the metadata.
        valid = zlib.compress(b"metadata")

        assert bgcode._decompress(1, valid[:-1], max_output=1024) is None

    def test_refuses_a_stream_with_trailing_bytes(self) -> None:
        # Trailing data means the declared length was wrong, or something is
        # hidden after the stream; either way the block is not what it claims.
        valid = zlib.compress(b"metadata")

        assert bgcode._decompress(1, valid + b"trailing", max_output=1024) is None

    def test_refuses_a_stream_that_is_not_deflate_at_all(self) -> None:
        assert bgcode._decompress(1, b"not-deflate", max_output=1024) is None

    def test_refuses_a_compression_scheme_it_does_not_implement(self) -> None:
        # Heatshrink (2 and 3) is deliberately unimplemented: only the printable
        # body uses it, and validation seeks past that.
        assert bgcode._decompress(3, b"opaque", max_output=1024) is None


class TestValidContainer:
    def test_accepts_a_slicer_written_container(self, tmp_path: Path) -> None:
        path = _written(tmp_path / "sample.bgcode", _sample_container())

        assert is_valid_container(path) is True

    def test_accepts_a_printable_body_larger_than_the_metadata_cap(
        self, tmp_path: Path
    ) -> None:
        path = tmp_path / "large-sparse.bgcode"
        body_size = bgcode._MAX_BLOCK_DATA + 1
        with path.open("wb") as file:
            file.write(b"GCDE" + struct.pack("<IH", 1, 0))
            file.write(struct.pack("<HHI", _GCODE, 0, body_size))
            file.write(struct.pack("<H", 2))
            file.seek(body_size - 1, 1)
            file.write(b"\0")

        # Printable blocks are seeked past rather than read, so a large print is
        # not capped by the metadata ceiling. A sparse file keeps this cheap.
        assert is_valid_container(path) is True

    def test_accepts_a_block_type_it_does_not_recognise(self, tmp_path: Path) -> None:
        unknown = struct.pack("<HHI", _UNKNOWN_BLOCK, 0, 4) + b"data"
        path = _written(tmp_path / "future.bgcode", _container(unknown, _gcode_block()))

        # Forward compatibility: a container gaining a block type must not
        # become unreadable in older PrintStash releases.
        assert is_valid_container(path) is True

    def test_rejects_a_container_with_no_printable_block(self, tmp_path: Path) -> None:
        metadata_only = _container(
            _block(
                _FILE_METADATA,
                struct.pack("<H", 0),
                b"Producer=PrusaSlicer 2.8.0\n",
                compression=0,
            )
        )
        path = _written(tmp_path / "metadata-only.bgcode", metadata_only)

        # Nothing to print. Accepting it would let a metadata-only file be
        # queued and fail on the printer instead of at upload.
        assert is_valid_container(path) is False

    def test_rejects_a_truncated_file(self, tmp_path: Path) -> None:
        path = _written(tmp_path / "truncated.bgcode", _sample_container()[:40])

        assert is_valid_container(path) is False

    def test_rejects_a_metadata_block_whose_deflate_stream_is_corrupt(
        self, tmp_path: Path
    ) -> None:
        corrupt_metadata = (
            struct.pack("<HHI", _FILE_METADATA, 1, 1000)
            + struct.pack("<I", len(b"not-deflate"))
            + struct.pack("<H", 0)
            + b"not-deflate"
        )
        path = _written(
            tmp_path / "corrupt.bgcode",
            _container(corrupt_metadata, _gcode_block()),
        )

        assert is_valid_container(path) is False

    def test_rejects_a_block_declaring_more_output_than_the_metadata_cap(
        self, tmp_path: Path
    ) -> None:
        body = zlib.compress(b"Producer=X\n")
        # Claims 9 MiB of output from a few compressed bytes. The claim is
        # rejected before the stream is inflated, so the bomb never expands.
        header = struct.pack("<HHI", _FILE_METADATA, 1, 9 * 1024 * 1024)
        header += struct.pack("<I", len(body)) + struct.pack("<H", 0)
        path = _written(
            tmp_path / "oversize.bgcode", _container(header + body, _gcode_block())
        )

        assert is_valid_container(path) is False

    def test_rejects_a_container_with_more_blocks_than_the_cap(
        self, tmp_path: Path
    ) -> None:
        # A hostile file can declare an unbounded number of tiny blocks; the
        # loop is bounded so validation cannot be made to run forever.
        blocks = b"".join(
            struct.pack("<HHI", _UNKNOWN_BLOCK, 0, 0)
            for _ in range(bgcode._MAX_BLOCKS + 1)
        )
        path = _written(tmp_path / "many.bgcode", _container(blocks, _gcode_block()))

        assert is_valid_container(path) is False


class TestParse:
    def test_reads_typed_metadata_out_of_a_container(self, tmp_path: Path) -> None:
        path = _written(tmp_path / "sample.bgcode", _sample_container())

        assert parse(path) == GcodeMetadata(
            slicer_name="PrusaSlicer",
            slicer_version="PrusaSlicer 2.8.0",
            material_type="PETG",
            material_requirements=(MaterialRequirement(0, "PETG"),),
        )


class TestReadMetadataTextTolerance:
    def test_reads_every_metadata_block_in_the_container(self, tmp_path: Path) -> None:
        file_metadata = _block(
            _FILE_METADATA,
            struct.pack("<H", 0),
            b"Producer=PrusaSlicer 2.8.0\n",
            compression=0,
        )
        slicer_metadata = _block(
            _SLICER_METADATA,
            struct.pack("<H", 0),
            b"filament_type=PETG\n",
            compression=0,
        )
        path = _written(
            tmp_path / "both.bgcode",
            _container(file_metadata, slicer_metadata, _gcode_block()),
        )

        text = bgcode.read_metadata_text(path)

        # The four metadata block types carry different halves of what the
        # parser needs; reading only the first would lose the material.
        assert text is not None
        assert "Producer=PrusaSlicer 2.8.0" in text
        assert "filament_type=PETG" in text

    def test_synthesizes_the_generated_by_line_a_text_parser_expects(
        self, tmp_path: Path
    ) -> None:
        path = _written(tmp_path / "sample.bgcode", _sample_container())

        text = bgcode.read_metadata_text(path)

        # The binary container has no comment header, but the shared text
        # parser identifies the slicer from `; generated by …`. Emitting it here
        # is what lets one parser serve both formats.
        assert text is not None
        assert "; generated by PrusaSlicer 2.8.0" in text

    def test_skips_a_blank_line_in_a_metadata_block(self, tmp_path: Path) -> None:
        metadata = _block(
            _FILE_METADATA,
            struct.pack("<H", 0),
            b"Producer=X\n\n   \nfilament_type=PETG\n",
            compression=0,
        )
        path = _written(
            tmp_path / "blanks.bgcode", _container(metadata, _gcode_block())
        )

        text = bgcode.read_metadata_text(path)

        # A blank comment line would read as an empty key to the text parser.
        assert text == ("; Producer=X\n; generated by X\n; filament_type=PETG\n")

    def test_skips_a_block_it_cannot_decode(self, tmp_path: Path) -> None:
        corrupt = (
            struct.pack("<HHI", _FILE_METADATA, 1, 11)
            + struct.pack("<I", len(b"not-deflate"))
            + struct.pack("<H", 0)
            + b"not-deflate"
        )
        good = _block(
            _SLICER_METADATA,
            struct.pack("<H", 0),
            b"filament_type=PETG\n",
            compression=0,
        )
        path = _written(
            tmp_path / "partial.bgcode", _container(corrupt, good, _gcode_block())
        )

        text = bgcode.read_metadata_text(path)

        # One unreadable block is not a reason to lose the rest: a model with
        # partial metadata is better than a model with none.
        assert text is not None
        assert "filament_type=PETG" in text

    def test_stops_reading_once_the_metadata_budget_is_spent(
        self, tmp_path: Path
    ) -> None:
        chunk = b"a=" + b"b" * (5 * 1024 * 1024) + b"\n"
        blocks = b"".join(
            _block(_FILE_METADATA, struct.pack("<H", 0), chunk, compression=0)
            for _ in range(2)
        )
        path = _written(tmp_path / "huge.bgcode", _container(blocks, _gcode_block()))

        text = bgcode.read_metadata_text(path)

        # Two blocks each under the per-block cap can still exceed the total, so
        # the budget is cumulative. What was already read is kept.
        assert text is not None
        assert len(text) < 2 * len(chunk)

    def test_stops_at_a_block_declaring_a_missing_compressed_size(
        self, tmp_path: Path
    ) -> None:
        # Declares deflate, so four bytes of compressed size must follow.
        path = _written(
            tmp_path / "nosize.bgcode",
            _container(struct.pack("<HHI", _FILE_METADATA, 1, 10)),
        )

        assert bgcode.read_metadata_text(path) is None

    def test_stops_at_a_block_whose_parameters_are_cut_short(
        self, tmp_path: Path
    ) -> None:
        path = _written(
            tmp_path / "noparams.bgcode",
            _container(struct.pack("<HHI", _FILE_METADATA, 0, 0) + b"\x00"),
        )

        assert bgcode.read_metadata_text(path) is None

    def test_stops_at_a_block_whose_body_is_cut_short(self, tmp_path: Path) -> None:
        header = struct.pack("<HHI", _FILE_METADATA, 0, 100) + struct.pack("<H", 0)
        path = _written(tmp_path / "shortbody.bgcode", _container(header + b"short"))

        assert bgcode.read_metadata_text(path) is None

    def test_refuses_a_block_declaring_more_data_than_the_reader_will_hold(
        self, tmp_path: Path
    ) -> None:
        # The declared length exceeds the hard per-block ceiling, so the walk
        # stops rather than attempting a 64 MiB+ read for a hostile header.
        header = struct.pack("<HHI", _FILE_METADATA, 0, bgcode._MAX_BLOCK_DATA + 1)
        header += struct.pack("<H", 0)
        path = _written(tmp_path / "huge-block.bgcode", _container(header))

        assert bgcode.read_metadata_text(path) is None

    def test_reads_metadata_past_a_checksum(self, tmp_path: Path) -> None:
        metadata = (
            _block(
                _FILE_METADATA,
                struct.pack("<H", 0),
                b"Producer=PrusaSlicer 2.8.0\n",
                compression=0,
            )
            + b"\x00\x00\x00\x00"
        )
        payload = b"GCDE" + struct.pack("<IH", 1, 1) + metadata
        path = _written(tmp_path / "crc-metadata.bgcode", payload)

        # A reader that ignored the checksum length would read it as the next
        # block header. Here the metadata comes first, so the read succeeds
        # either way — the assertion is that nothing after it is misparsed.
        text = bgcode.read_metadata_text(path)

        assert text is not None
        assert "Producer=PrusaSlicer 2.8.0" in text


class TestIterThumbnailsTolerance:
    def test_yields_the_image_bytes_with_their_format(self, tmp_path: Path) -> None:
        path = _written(tmp_path / "sample.bgcode", _sample_container())

        assert list(bgcode.iter_thumbnails(path)) == [(0, 16, 16, b"thumbnail-bytes")]

    def test_skips_a_thumbnail_whose_parameters_are_too_short_to_read(
        self, tmp_path: Path
    ) -> None:
        # `_block_param_len` asks for six bytes and gets them, but the block
        # body is what carries the image — a header claiming a thumbnail with
        # unreadable dimensions must be skipped, not yield a 0x0 preview.
        short = struct.pack("<HHI", _THUMBNAIL, 3, 4) + struct.pack("<I", 4)
        short += struct.pack("<HHH", 0, 16, 16) + b"data"
        path = _written(
            tmp_path / "undecodable.bgcode", _container(short, _gcode_block())
        )

        assert list(bgcode.iter_thumbnails(path)) == []

    def test_yields_every_thumbnail_in_the_container(self, tmp_path: Path) -> None:
        small = _block(
            _THUMBNAIL, struct.pack("<HHH", 0, 16, 16), b"small", compression=0
        )
        large = _block(
            _THUMBNAIL, struct.pack("<HHH", 1, 220, 124), b"large", compression=0
        )
        path = _written(
            tmp_path / "two-thumbs.bgcode",
            _container(small, large, _gcode_block()),
        )

        # PrusaSlicer embeds several sizes; the caller picks one, so all must
        # reach it.
        assert [(fmt, w, h) for fmt, w, h, _data in bgcode.iter_thumbnails(path)] == [
            (0, 16, 16),
            (1, 220, 124),
        ]
