"""Unit tests for embedded thumbnail extraction."""

from __future__ import annotations

import base64
import io
from pathlib import Path

import numpy as np
import pytest
from PIL import Image
from printstash_core.mesh.rasterizer import RenderedPixels, encode_rendered_pixels

from app.core.config import _overlay
from app.modules.media.thumbnail import _MAX_BLOCK_LINES, extract, to_webp
from tests.paths import FIXTURES_DIR


def _block(width: int, height: int, payload: bytes) -> str:
    b64 = base64.b64encode(payload).decode()
    return f"; thumbnail begin {width}x{height} {len(b64)}\n; {b64}\n; thumbnail end\n"


class TestExtract:
    def test_extract_sample_gcode(self) -> None:
        fixture = FIXTURES_DIR / "sample.gcode"
        result = extract(fixture)
        assert result is not None
        assert len(result) > 0
        assert result[:4] == b"\x89PNG"  # PNG magic bytes

    def test_extract_missing_file(self, tmp_path: Path) -> None:
        result = extract(tmp_path / "nonexistent.gcode")
        assert result is None

    def test_extract_no_thumbnail(self, tmp_path: Path) -> None:
        f = tmp_path / "no_thumb.gcode"
        f.write_text("G28\nG1 X10 Y10\nM84\n")
        result = extract(f)
        assert result is None

    def test_picks_largest_block_by_area(self, tmp_path: Path) -> None:
        small = b"small-preview"
        large = b"large-preview-data" * 4
        f = tmp_path / "multi.gcode"
        f.write_text(
            "; generated by PrusaSlicer\n"
            + _block(16, 16, small)
            + _block(640, 480, large)
            + "G1 X0 Y0\n"
        )
        assert extract(f) == large

    def test_an_unterminated_block_is_bounded_before_giving_up(
        self, tmp_path: Path
    ) -> None:
        # Regression: a "thumbnail begin" with no "thumbnail end" must not buffer
        # the whole file; it is abandoned past the cap and yields nothing.
        f = tmp_path / "runaway.gcode"
        f.write_text(
            "; thumbnail begin 16x16 100\n" + "; AAAA\n" * (_MAX_BLOCK_LINES + 5000)
        )
        assert extract(f) is None

    def test_recovers_valid_block_after_runaway(self, tmp_path: Path) -> None:
        real = b"the-real-thumbnail"
        f = tmp_path / "recover.gcode"
        f.write_text(
            "; thumbnail begin 8x8 10\n"
            + "; ZZZZ\n" * (_MAX_BLOCK_LINES + 50)  # unterminated, abandoned
            + _block(64, 64, real)
            + "G1 X0\n"
        )
        assert extract(f) == real


@pytest.fixture
def detailed_preview() -> Image.Image:
    """A shaded surface with fine detail and a smoothly antialiased silhouette."""
    y, x = np.indices((480, 640), dtype=np.float32)
    shade = 100 + 40 * np.sin(x / 20) + 30 * np.cos(y / 15)
    detail = (x * 17 + y * 31) % 7
    alpha = np.clip(
        (1 - ((x - 320) / 255) ** 2 - ((y - 240) / 190) ** 2) * 1000, 0, 255
    )
    rgba = np.stack((shade + detail, shade + 20, shade + 40, alpha), axis=-1)
    return Image.fromarray(rgba.astype(np.uint8))


class TestWebpNormalization:
    def test_embedded_preview_is_centered_on_the_canonical_canvas(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        from PIL import Image

        source = io.BytesIO()
        Image.new("RGB", (100, 200), "white").save(source, format="PNG")
        monkeypatch.setitem(_overlay, "model_thumbnail_width", 320)

        encoded = to_webp(source.getvalue())

        with Image.open(io.BytesIO(encoded)) as result:
            assert result.size == (320, 240)
            assert result.mode == "RGBA"
            alpha = result.getchannel("A")
            bounds = alpha.getbbox()
            assert bounds is not None
            assert bounds[0] > 0
            assert bounds[1] > 0
            assert bounds[2] < result.width
            assert bounds[3] < result.height

    def test_empty_transparent_preview_is_rejected(self) -> None:
        from PIL import Image

        source = io.BytesIO()
        Image.new("RGBA", (64, 64), (0, 0, 0, 0)).save(source, format="PNG")

        with pytest.raises(ValueError, match="thumbnail_empty"):
            to_webp(source.getvalue())

    def test_canonical_renderer_webp_is_validated_without_reencoding(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        from PIL import Image, ImageDraw

        monkeypatch.setitem(_overlay, "model_thumbnail_width", 320)
        image = Image.new("RGBA", (320, 240), (0, 0, 0, 0))
        ImageDraw.Draw(image).rectangle((32, 24, 287, 215), fill=(90, 130, 210, 255))
        encoded = encode_rendered_pixels(
            RenderedPixels(320, 240, image.tobytes()), output_format="WEBP"
        )

        assert to_webp(encoded, renderer_encoded=True) == encoded

    def test_compresses_detailed_canonical_previews(self, detailed_preview) -> None:
        source = io.BytesIO()
        detailed_preview.save(
            source, format="WEBP", lossless=True, exact=True, method=6
        )

        encoded = to_webp(source.getvalue(), width=640)

        assert len(encoded) < len(source.getvalue()) * 0.6
        assert Image.open(io.BytesIO(encoded)).size == (640, 480)

    def test_preserves_thumbnail_transparency_exactly(self, detailed_preview) -> None:
        source = io.BytesIO()
        detailed_preview.save(source, format="PNG")

        encoded = to_webp(source.getvalue(), width=640)

        decoded = Image.open(io.BytesIO(encoded)).convert("RGBA")
        assert (
            decoded.getchannel("A").tobytes()
            == detailed_preview.getchannel("A").tobytes()
        )

    def test_preserves_visible_thumbnail_detail(self, detailed_preview) -> None:
        source = io.BytesIO()
        detailed_preview.save(source, format="PNG")

        encoded = to_webp(source.getvalue(), width=640)

        actual = np.asarray(
            Image.open(io.BytesIO(encoded)).convert("RGBA"), dtype=float
        )
        expected = np.asarray(detailed_preview, dtype=float)
        visible = expected[:, :, 3] > 0
        assert np.abs(actual[:, :, :3] - expected[:, :, :3])[visible].mean() < 4

    def test_normalizes_mismatched_renderer_dimensions(self, detailed_preview) -> None:
        encoded = encode_rendered_pixels(
            RenderedPixels(640, 480, detailed_preview.tobytes()), output_format="WEBP"
        )

        resized = to_webp(encoded, width=320, renderer_encoded=True)

        assert Image.open(io.BytesIO(resized)).size == (320, 240)

    def test_rejects_empty_renderer_output(self) -> None:
        encoded = encode_rendered_pixels(
            RenderedPixels(320, 240, bytes(320 * 240 * 4)), output_format="WEBP"
        )

        with pytest.raises(ValueError, match="thumbnail_empty"):
            to_webp(encoded, width=320, renderer_encoded=True)


class TestInvalidThumbnailInput:
    def test_invalid_base64_has_no_embedded_preview(self, tmp_path):
        path = tmp_path / "invalid.gcode"
        path.write_text("; thumbnail begin 16x16 4\n; !!!!\n; thumbnail end\n")
        assert extract(path) is None

    def test_unterminated_line_has_no_embedded_preview(self, tmp_path):
        path = tmp_path / "truncated.gcode"
        path.write_text("; thumbnail begin 16x16 4")
        assert extract(path) is None
