"""Accepted revisions revalidate authority and recover committed source writes."""

import json

import pytest
from sqlmodel import select

from app.core.config import settings
from app.db.models import ArtifactUploadState, File
from app.db.session import get_session_factory
from app.modules.ingestion.artifact_uploads.handoff import run_verified_upload_ingestion
from app.runtime.jobs import registry
from tests._env import use_local_storage


@pytest.fixture
def accepted_revision(
    db_session, make_user, make_model, make_artifact_upload, tmp_path
):
    use_local_storage(tmp_path)
    actor = make_user(superuser=True)
    model = make_model()
    job_id = registry.create(owner_user_id=actor.id)
    upload = make_artifact_upload(
        actor,
        state=ArtifactUploadState.INGESTING,
        purpose="revision",
        target_role="model",
        target_id=str(model.id),
        filename="revision.gcode",
        job_id=job_id,
        request_json=json.dumps({"revision_label": "New"}),
    )
    path = settings.incoming_dir / "artifact-uploads" / upload.id / "assembled.gcode"
    path.parent.mkdir(parents=True)
    path.write_text("; generated by OrcaSlicer\nG28\nG1 X10 Y10 E1\n")
    return (
        actor,
        model,
        upload,
        dict(
            upload_id=upload.id,
            job_id=job_id,
            staged_path=path,
            session_factory=get_session_factory(),
        ),
    )


class TestHandoffContract:
    def test_rejects_a_revision_whose_actor_was_disabled(self, db_session, accepted_revision):
        actor, model, upload, arguments = accepted_revision
        actor.is_active = False
        db_session.add(actor)
        db_session.commit()
        run_verified_upload_ingestion(**arguments)
        db_session.expire_all()
        assert db_session.exec(select(File).where(File.model_id == model.id)).all() == []
        assert upload.state == ArtifactUploadState.FAILED


    def test_recovers_a_revision_committed_before_worker_loss(self,
        db_session, accepted_revision, monkeypatch
    ):
        _, model, upload, arguments = accepted_revision

        def interrupted(*_args, **_kwargs):
            raise SystemExit("worker stopped after source commit")

        with monkeypatch.context() as stopped:
            stopped.setattr(registry, "finish", interrupted)
            with pytest.raises(SystemExit, match="worker stopped after source commit"):
                run_verified_upload_ingestion(**arguments)
        run_verified_upload_ingestion(**arguments)
        db_session.expire_all()
        assert upload.state == ArtifactUploadState.COMPLETED
        files = db_session.exec(select(File).where(File.model_id == model.id)).all()
        assert len(files) == 1
        assert files[0].ingestion_key == arguments["job_id"]
