use flate2::{write::ZlibEncoder, Compression};
use printstash_libbgcode::inspect;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

const FILE_METADATA: u16 = 0;
const GCODE: u16 = 1;
const THUMBNAIL: u16 = 5;
const NONE: u16 = 0;
const DEFLATE: u16 = 1;
static SEQUENCE: AtomicU64 = AtomicU64::new(0);

fn compressed(data: &[u8]) -> Vec<u8> {
    let mut encoder = ZlibEncoder::new(Vec::new(), Compression::default());
    encoder.write_all(data).unwrap();
    encoder.finish().unwrap()
}

fn block(
    block_type: u16,
    compression: u16,
    declared_size: u32,
    params: &[u8],
    data: &[u8],
    valid_checksum: bool,
) -> Vec<u8> {
    let mut block = Vec::new();
    block.extend_from_slice(&block_type.to_le_bytes());
    block.extend_from_slice(&compression.to_le_bytes());
    block.extend_from_slice(&declared_size.to_le_bytes());
    if compression != NONE {
        block.extend_from_slice(&(data.len() as u32).to_le_bytes());
    }
    block.extend_from_slice(params);
    block.extend_from_slice(data);
    let checksum = crc32fast::hash(&block) ^ u32::from(!valid_checksum);
    block.extend_from_slice(&checksum.to_le_bytes());
    block
}

fn container(blocks: &[Vec<u8>]) -> Vec<u8> {
    let mut output = b"GCDE".to_vec();
    output.extend_from_slice(&1u32.to_le_bytes());
    output.extend_from_slice(&1u16.to_le_bytes());
    for block in blocks {
        output.extend_from_slice(block);
    }
    output
}

fn with_file(bytes: &[u8], assertion: impl FnOnce(&Path)) {
    let path = std::env::temp_dir().join(format!(
        "printstash-libbgcode-{}-{}",
        std::process::id(),
        SEQUENCE.fetch_add(1, Ordering::Relaxed)
    ));
    fs::write(&path, bytes).unwrap();
    assertion(&path);
    fs::remove_file(path).unwrap();
}

fn fixture(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name)
}

#[test]
fn reads_the_official_prusa_container() {
    let result = inspect(&fixture("prusaslicer.bgcode"), true, true).unwrap();
    assert!(result.valid);
    assert!(result.saw_block);
    assert!(result.saw_gcode);
    assert!(result.metadata_text.contains("generated by PrusaSlicer"));
}

#[test]
fn reads_both_official_heatshrink_modes() {
    for name in [
        "metadata-heatshrink-11-4.bgcode",
        "metadata-heatshrink-12-4.bgcode",
    ] {
        let result = inspect(&fixture(name), false, false).unwrap();
        assert!(result.valid, "{name}");
        assert!(result.metadata_text.contains("filament_type=PETG"));
    }
}

#[test]
fn rejects_deterministic_corruptions_of_the_official_container() {
    let original = fs::read(fixture("prusaslicer.bgcode")).unwrap();
    let positions = [
        0,
        4,
        8,
        10,
        original.len() / 4,
        original.len() / 2,
        original.len() * 3 / 4,
        original.len() - 1,
    ];
    for position in positions {
        let mut mutated = original.clone();
        mutated[position] ^= 0x5a;
        with_file(&mutated, |path| {
            let result = inspect(path, false, true).unwrap();
            assert!(
                !(result.valid && result.saw_block && result.saw_gcode),
                "byte {position}"
            );
        });
    }
    for length in [0, 1, 4, 9, 10, original.len() / 2, original.len() - 1] {
        with_file(&original[..length], |path| {
            let result = inspect(path, false, true).unwrap();
            assert!(
                !(result.valid && result.saw_block && result.saw_gcode),
                "length {length}"
            );
        });
    }
}

#[test]
fn tolerates_blank_and_non_key_metadata_lines() {
    let metadata = b"Producer=X\n\n loose text \nfilament_type=PETG\n";
    let block = block(
        FILE_METADATA,
        NONE,
        metadata.len() as u32,
        &0u16.to_le_bytes(),
        metadata,
        true,
    );
    with_file(&container(&[block]), |path| {
        let result = inspect(path, false, false).unwrap();
        assert!(result.valid);
        assert_eq!(
            result.metadata_text,
            "; Producer=X\n; generated by X\n; loose text\n; filament_type=PETG\n"
        );
    });
}

#[test]
fn replaces_invalid_utf8_without_losing_metadata() {
    let metadata = b"Producer=X\xff\nfilament_type=PETG\n";
    let block = block(
        FILE_METADATA,
        NONE,
        metadata.len() as u32,
        &0u16.to_le_bytes(),
        metadata,
        true,
    );
    with_file(&container(&[block]), |path| {
        let result = inspect(path, false, false).unwrap();
        assert!(result.valid);
        assert!(result.metadata_text.contains("Producer=X\u{fffd}"));
        assert!(result.metadata_text.contains("filament_type=PETG"));
    });
}

#[test]
fn accepts_only_exact_complete_deflate_streams() {
    let metadata = b"Producer=PrusaSlicer 2.8.0\nfilament_type=PETG\n";
    let encoded = compressed(metadata);
    let exact = block(
        FILE_METADATA,
        DEFLATE,
        metadata.len() as u32,
        &0u16.to_le_bytes(),
        &encoded,
        true,
    );
    with_file(&container(&[exact]), |path| {
        let result = inspect(path, false, false).unwrap();
        assert!(result.valid);
        assert!(result.metadata_text.contains("filament_type=PETG"));
    });

    for declared_size in [metadata.len() as u32 - 1, metadata.len() as u32 + 1] {
        let invalid = block(
            FILE_METADATA,
            DEFLATE,
            declared_size,
            &0u16.to_le_bytes(),
            &encoded,
            true,
        );
        with_file(&container(&[invalid]), |path| {
            let result = inspect(path, false, false).unwrap();
            assert!(!result.valid);
            assert!(result.metadata_text.is_empty());
        });
    }

    let mut trailing = encoded;
    trailing.extend_from_slice(b"trailing");
    let invalid = block(
        FILE_METADATA,
        DEFLATE,
        metadata.len() as u32,
        &0u16.to_le_bytes(),
        &trailing,
        true,
    );
    with_file(&container(&[invalid]), |path| {
        assert!(!inspect(path, false, false).unwrap().valid);
    });
}

#[test]
fn extracts_a_bounded_deflate_thumbnail() {
    let image = b"thumbnail-bytes";
    let encoded = compressed(image);
    let mut params = Vec::new();
    params.extend_from_slice(&0u16.to_le_bytes());
    params.extend_from_slice(&16u16.to_le_bytes());
    params.extend_from_slice(&16u16.to_le_bytes());
    let thumbnail = block(
        THUMBNAIL,
        DEFLATE,
        image.len() as u32,
        &params,
        &encoded,
        true,
    );
    with_file(&container(&[thumbnail]), |path| {
        let result = inspect(path, true, false).unwrap();
        assert!(result.valid);
        assert_eq!(result.thumbnails.len(), 1);
        assert_eq!(result.thumbnails[0].data, image);
    });
}

#[test]
fn metadata_reads_skip_the_printable_body() {
    let gcode = block(
        GCODE,
        NONE,
        1024 * 1024,
        &2u16.to_le_bytes(),
        &vec![b'G'; 1024 * 1024],
        false,
    );
    with_file(&container(&[gcode]), |path| {
        let bounded = inspect(path, false, false).unwrap();
        assert!(bounded.valid);
        assert!(bounded.saw_gcode);
        let full_validation = inspect(path, false, true).unwrap();
        assert!(!full_validation.valid);
    });
}

#[test]
fn rejects_truncated_and_oversized_blocks_without_allocating_them() {
    let header_only = block(
        FILE_METADATA,
        NONE,
        64 * 1024 * 1024 + 1,
        &0u16.to_le_bytes(),
        &[],
        true,
    );
    with_file(&container(&[header_only]), |path| {
        assert!(!inspect(path, false, false).unwrap().valid);
    });

    with_file(b"GCDE\x01\x00", |path| {
        assert!(!inspect(path, false, false).unwrap().valid);
    });
}

#[test]
fn rejects_unknown_block_types_and_compression_before_skipping_payloads() {
    let unknown_type = block(99, NONE, 0, &[], &[], true);
    with_file(&container(&[unknown_type]), |path| {
        assert!(!inspect(path, false, false).unwrap().valid);
    });

    let unknown_compression = block(GCODE, 99, 0, &2u16.to_le_bytes(), &[], true);
    with_file(&container(&[unknown_compression]), |path| {
        assert!(!inspect(path, false, false).unwrap().valid);
    });
}

#[test]
fn charges_failed_metadata_against_the_total_decode_budget() {
    let declared = 5 * 1024 * 1024;
    let corrupt = block(
        FILE_METADATA,
        DEFLATE,
        declared,
        &0u16.to_le_bytes(),
        b"not-deflate",
        true,
    );
    let valid_text = b"Producer=must-not-be-decoded\n";
    let valid = block(
        FILE_METADATA,
        NONE,
        declared,
        &0u16.to_le_bytes(),
        &{
            let mut bytes = valid_text.to_vec();
            bytes.resize(declared as usize, b' ');
            bytes
        },
        true,
    );
    with_file(&container(&[corrupt, valid]), |path| {
        let result = inspect(path, false, false).unwrap();
        assert!(!result.valid);
        assert!(result.metadata_text.is_empty());
    });
}

#[test]
fn charges_failed_thumbnails_against_the_total_decode_budget() {
    let params = [0_u16, 16, 16]
        .into_iter()
        .flat_map(u16::to_le_bytes)
        .collect::<Vec<_>>();
    let corrupt = block(
        THUMBNAIL,
        DEFLATE,
        32 * 1024 * 1024,
        &params,
        b"not-deflate",
        true,
    );
    let valid = block(THUMBNAIL, NONE, 1, &params, b"x", true);
    with_file(&container(&[corrupt.clone(), corrupt, valid]), |path| {
        let result = inspect(path, true, false).unwrap();
        assert!(!result.valid);
        assert!(result.thumbnails.is_empty());
    });
}
