"""OrcaSlicer, PrusaSlicer, Bambu Studio, and Cura metadata parser."""

from __future__ import annotations

import logging
import re
from pathlib import Path

from .bgcode import is_bgcode, read_metadata_text
from .models import GcodeMetadata, MaterialRequirement

logger = logging.getLogger(__name__)

_HEAD_BYTES = 64 * 1024
_TAIL_BYTES = 64 * 1024

_PATTERNS: dict[str, tuple[re.Pattern[str], ...]] = {
    "slicer_version": (
        re.compile(r";\s*generated by\s+(.+?)(?:\s+on\b|[\r\n])", re.IGNORECASE),
        re.compile(r";\s*generated with\s+([^\r\n]+)", re.IGNORECASE),
    ),
    "printer_model": (
        re.compile(r";\s*printer_model\s*=\s*(.+)", re.IGNORECASE),
        re.compile(r";\s*printer_settings_id\s*=\s*(.+)", re.IGNORECASE),
        re.compile(r";\s*machine_name\s*=\s*(.+)", re.IGNORECASE),
    ),
    "printer_preset_name": (
        re.compile(r";\s*printer_settings_id\s*=\s*(.+)", re.IGNORECASE),
    ),
    "nozzle_diameter_mm": (
        re.compile(r";\s*nozzle_diameter\s*=\s*([\d.]+)", re.IGNORECASE),
        re.compile(r";\s*nozzle diameter\s*[:=]\s*([\d.]+)", re.IGNORECASE),
    ),
    "layer_height_mm": (
        re.compile(r";\s*layer_height\s*=\s*([\d.]+)", re.IGNORECASE),
        re.compile(r";\s*layer height\s*[:=]\s*([\d.]+)", re.IGNORECASE),
    ),
    "first_layer_height_mm": (
        re.compile(r";\s*first_layer_height\s*=\s*([\d.]+)", re.IGNORECASE),
        re.compile(r";\s*first layer height\s*[:=]\s*([\d.]+)", re.IGNORECASE),
        re.compile(r";\s*initial_layer_print_height\s*=\s*([\d.]+)", re.IGNORECASE),
    ),
    "infill_percent": (
        re.compile(r";\s*sparse_infill_density\s*=\s*([\d.]+)\s*%?", re.IGNORECASE),
        re.compile(r";\s*infill_density\s*=\s*([\d.]+)\s*%?", re.IGNORECASE),
        re.compile(r";\s*fill_density\s*=\s*([\d.]+)\s*%?", re.IGNORECASE),
        re.compile(r";\s*fill density\s*[:=]\s*([\d.]+)\s*%?", re.IGNORECASE),
    ),
    "wall_loops": (
        re.compile(r";\s*wall_loops\s*=\s*(\d+)", re.IGNORECASE),
        re.compile(r";\s*wall loops\s*[:=]\s*(\d+)", re.IGNORECASE),
        re.compile(r";\s*perimeters\s*=\s*(\d+)", re.IGNORECASE),
        re.compile(r";\s*wall_line_count\s*=\s*(\d+)", re.IGNORECASE),
    ),
    "top_shell_layers": (
        re.compile(r";\s*top_shell_layers\s*=\s*(\d+)", re.IGNORECASE),
        re.compile(r";\s*top shell layers\s*[:=]\s*(\d+)", re.IGNORECASE),
        re.compile(r";\s*top_solid_layers\s*=\s*(\d+)", re.IGNORECASE),
        re.compile(r";\s*top_layers\s*=\s*(\d+)", re.IGNORECASE),
    ),
    "bottom_shell_layers": (
        re.compile(r";\s*bottom_shell_layers\s*=\s*(\d+)", re.IGNORECASE),
        re.compile(r";\s*bottom shell layers\s*[:=]\s*(\d+)", re.IGNORECASE),
        re.compile(r";\s*bottom_solid_layers\s*=\s*(\d+)", re.IGNORECASE),
        re.compile(r";\s*bottom_layers\s*=\s*(\d+)", re.IGNORECASE),
    ),
    "support_material_raw": (
        re.compile(r";\s*enable_support\s*=\s*([^\r\n;]+)", re.IGNORECASE),
        re.compile(r";\s*support_material\s*=\s*([^\r\n;]+)", re.IGNORECASE),
        re.compile(r";\s*support_enable\s*=\s*([^\r\n;]+)", re.IGNORECASE),
        re.compile(r";\s*support\s*[:=]\s*([^\r\n;]+)", re.IGNORECASE),
    ),
    "nozzle_temperature_c": (
        re.compile(r";\s*nozzle_temperature\s*=\s*([\d.]+)", re.IGNORECASE),
        re.compile(r";\s*filament_temperature\s*=\s*([\d.]+)", re.IGNORECASE),
        re.compile(r";\s*temperature\s*[:=]\s*([\d.]+)", re.IGNORECASE),
        re.compile(r";\s*print_temperature\s*=\s*([\d.]+)", re.IGNORECASE),
    ),
    "bed_temperature_c": (
        re.compile(r";\s*bed_temperature\s*=\s*([\d.]+)", re.IGNORECASE),
        re.compile(r";\s*hot_plate_temp\s*=\s*([\d.]+)", re.IGNORECASE),
        re.compile(r";\s*filament_bed_temperature\s*=\s*([\d.]+)", re.IGNORECASE),
        re.compile(r";\s*bed temperature\s*[:=]\s*([\d.]+)", re.IGNORECASE),
        re.compile(r";\s*print_bed_temperature\s*=\s*([\d.]+)", re.IGNORECASE),
    ),
    "estimated_time_raw": (
        re.compile(r";\s*estimated printing time.*?=\s*(.+)", re.IGNORECASE),
        re.compile(r";\s*estimated_printing_time\s*=\s*(.+)", re.IGNORECASE),
        re.compile(r";\s*time\s*:\s*(\d+)", re.IGNORECASE),
    ),
    "filament_weight_g": (
        re.compile(r";\s*total filament used \[g\]\s*=\s*([\d.]+)", re.IGNORECASE),
        re.compile(r";\s*filament used \[g\]\s*=\s*([\d.]+)", re.IGNORECASE),
    ),
    "filament_length_mm": (
        re.compile(r";\s*total filament length \[mm\]\s*=\s*([\d.]+)", re.IGNORECASE),
        re.compile(r";\s*filament used \[mm\]\s*=\s*([\d.]+)", re.IGNORECASE),
        re.compile(r";\s*filament used\s*:\s*([\d.]+)\s*m", re.IGNORECASE),
    ),
    "filament_cost": (
        re.compile(r";\s*total filament cost\s*=\s*([\d.]+)", re.IGNORECASE),
        re.compile(r";\s*filament cost\s*=\s*([\d.]+)", re.IGNORECASE),
    ),
    "material_type": (
        re.compile(r";\s*filament_type\s*=\s*([^\r\n]+)", re.IGNORECASE),
        re.compile(r";\s*filament type\s*[:=]\s*([^\r\n]+)", re.IGNORECASE),
    ),
    "material_brand": (
        re.compile(r";\s*filament_brand\s*=\s*([^\n;]+)", re.IGNORECASE),
        re.compile(r";\s*filament_vendor\s*=\s*([^\n;]+)", re.IGNORECASE),
        re.compile(r";\s*filament_settings_id\s*=\s*([^\n;]+)", re.IGNORECASE),
    ),
}

_FILAMENT_COLOR_PATTERNS = (
    re.compile(r";\s*filament_colou?r\s*=\s*([^\r\n]+)", re.IGNORECASE),
    re.compile(r";\s*filament colou?r\s*[:=]\s*([^\r\n]+)", re.IGNORECASE),
)
_DURATION_RE = re.compile(r"(\d+(?:\.\d+)?)\s*([dhms])", re.IGNORECASE)
_DURATION_UNITS = {"d": 86400, "h": 3600, "m": 60, "s": 1}
_CURA_METERS_RE = re.compile(r"filament used\s*:\s*[\d.]+\s*m", re.IGNORECASE)
_MM_LENGTH_RE = re.compile(r"filament[^\r\n]*\[mm\]", re.IGNORECASE)


def parse_duration(value: str) -> int | None:
    """Parse slicer duration text into whole seconds."""
    if not value:
        return None
    matches = _DURATION_RE.findall(value)
    if not matches:
        try:
            seconds = int(float(value.strip()))
        except ValueError:
            return None
        return seconds if seconds >= 0 else None
    total = sum(
        float(amount) * _DURATION_UNITS[unit.lower()] for amount, unit in matches
    )
    return int(total)


def _read_window(path: Path) -> str:
    size = path.stat().st_size
    with path.open("rb") as file:
        head = file.read(min(_HEAD_BYTES, size))
        if size > _HEAD_BYTES + _TAIL_BYTES:
            file.seek(-_TAIL_BYTES, 2)
            tail = file.read(_TAIL_BYTES)
        else:
            tail = b""
    return (head + b"\n" + tail).decode("utf-8", errors="replace")


def _first_match(text: str, patterns: tuple[re.Pattern[str], ...]) -> str | None:
    for pattern in patterns:
        match = pattern.search(text)
        if match:
            return match.group(1).strip()
    return None


def _value(text: str, key: str) -> str | None:
    return _first_match(text, _PATTERNS[key])


def _to_float(value: str | None) -> float | None:
    if value is None:
        return None
    match = re.search(r"[-+]?\d+(?:\.\d+)?", value)
    return float(match.group(0)) if match else None


def _to_int(value: str | None) -> int | None:
    if value is None:
        return None
    try:
        return int(float(value.split(",", 1)[0].strip()))
    except ValueError:
        return None


def _to_bool(value: str | None) -> bool | None:
    if value is None:
        return None
    normalised = value.split(",", 1)[0].strip().lower()
    if normalised in {"1", "true", "yes", "on", "enabled", "generated"}:
        return True
    if normalised in {
        "0",
        "false",
        "no",
        "off",
        "disabled",
        "none",
        "not generated",
    }:
        return False
    return None


def _normalise_material(value: str | None) -> str | None:
    if value is None:
        return None
    return value.split(";", 1)[0].split(",", 1)[0].strip()


def _split_slicer_list(value: str | None) -> list[str]:
    if not value:
        return []
    return [part.strip() for part in re.split(r"[;,]", value) if part.strip()]


def _normalise_color(value: str) -> str | None:
    cleaned = value.strip().upper()
    if re.fullmatch(r"#[0-9A-F]{6}(?:[0-9A-F]{2})?", cleaned):
        return cleaned[:7]
    if re.fullmatch(r"[0-9A-F]{6}(?:[0-9A-F]{2})?", cleaned):
        return f"#{cleaned[:6]}"
    return None


def _slicer_name(version: str | None) -> str | None:
    if version is None:
        return None
    lower = version.lower()
    if "orca" in lower:
        return "OrcaSlicer"
    if "prusa" in lower:
        return "PrusaSlicer"
    if "bambu" in lower:
        return "BambuStudio"
    if "super" in lower:
        return "SuperSlicer"
    if "cura" in lower:
        return "Cura"
    return None


def parse(path: Path) -> GcodeMetadata:
    """Extract typed slicer metadata without raising on malformed input."""
    if is_bgcode(path):
        text = read_metadata_text(path)
        if text is None:
            return GcodeMetadata()
    else:
        try:
            text = _read_window(path)
        except OSError as error:
            logger.warning("gcode parse: cannot read %s: %s", path, error)
            return GcodeMetadata()

    slicer_version = _value(text, "slicer_version")
    material_text = _value(text, "material_type")
    material_values = _split_slicer_list(material_text)
    color_values = _split_slicer_list(_first_match(text, _FILAMENT_COLOR_PATTERNS))
    material_requirements = (
        tuple(
            MaterialRequirement(
                tool_index=index,
                material_type=material,
                color_hex=(
                    _normalise_color(color_values[index])
                    if index < len(color_values)
                    else None
                ),
            )
            for index, material in enumerate(material_values)
        )
        if material_values
        else None
    )

    filament_length_mm = _to_float(_value(text, "filament_length_mm"))
    if (
        filament_length_mm is not None
        and not _MM_LENGTH_RE.search(text)
        and _CURA_METERS_RE.search(text)
    ):
        filament_length_mm *= 1000

    estimated_time = _value(text, "estimated_time_raw")
    return GcodeMetadata(
        slicer_name=_slicer_name(slicer_version),
        slicer_version=slicer_version,
        printer_model=_value(text, "printer_model"),
        nozzle_diameter_mm=_to_float(_value(text, "nozzle_diameter_mm")),
        layer_height_mm=_to_float(_value(text, "layer_height_mm")),
        first_layer_height_mm=_to_float(_value(text, "first_layer_height_mm")),
        infill_percent=_to_float(_value(text, "infill_percent")),
        wall_loops=_to_int(_value(text, "wall_loops")),
        top_shell_layers=_to_int(_value(text, "top_shell_layers")),
        bottom_shell_layers=_to_int(_value(text, "bottom_shell_layers")),
        support_material=_to_bool(_value(text, "support_material_raw")),
        nozzle_temperature_c=_to_float(_value(text, "nozzle_temperature_c")),
        bed_temperature_c=_to_float(_value(text, "bed_temperature_c")),
        estimated_time_s=(
            parse_duration(estimated_time) if estimated_time is not None else None
        ),
        filament_weight_g=_to_float(_value(text, "filament_weight_g")),
        filament_length_mm=filament_length_mm,
        filament_cost=_to_float(_value(text, "filament_cost")),
        material_type=_normalise_material(material_text),
        material_brand=_normalise_material(_value(text, "material_brand")),
        material_requirements=material_requirements,
        printer_preset_name=_value(text, "printer_preset_name"),
    )
