"""Byte builders: the *file content* a test uploads, stages, or parses.

Distinct from the row builders beside them. These return `bytes` and touch no
database — they stand in for what a slicer, a browser, or a user's NAS would
hand PrintStash. They live in this package because "construct test data" is one
thing to go looking for, not two.

**Prefer a real fixture file.** `backend/tests/fixtures/` holds genuine output
from Orca, PrusaSlicer, Cura and Bambu Studio, including real MK4 and Ender-3
files. A parser test should read one of those; a synthetic body only proves the
parser handles bodies this module happens to produce. Reach for a builder here
when the test needs content shaped a particular way — over a size limit, a
deliberately malformed archive, a PNG that lies about its dimensions — which is
exactly what a real file cannot give you.

Nothing here is a credential, and nothing here is large: a builder that needs to
be megabytes says so in its name (`oversized_gcode`).
"""

from __future__ import annotations

import io
import struct
import zipfile
import zlib

_STL_TRIANGLE = struct.Struct("<12fH")

MINIMAL_GCODE = b"; generated by PrusaSlicer 2.7.0\nG90\nG21\nG28\nG1 X1 Y1 E1\n"


def gcode(*, slicer: str = "PrusaSlicer 2.7.0", marker: str | None = None) -> bytes:
    """A small, parseable G-code body.

    `marker` appends a unique trailer so the bytes hash distinctly, which is what
    makes two uploads two deduplicated models rather than one. Omit it and a
    second upload of this content is a *duplicate* — which is sometimes the
    behaviour under test, so it is not defaulted away.
    """
    body = f"; generated by {slicer}\nG90\nG21\nG28\nG1 X1 Y1 E1\n".encode()
    if marker is not None:
        body += f"; unique-marker {marker}\nG1 X0 Y0\n".encode()
    return body


def oversized_gcode(min_bytes: int = 1_200_000) -> bytes:
    """A body past nginx's default 1 MB limit, which the app must still accept.

    The size is the point: a reverse proxy in front of PrintStash rejects a body
    this large by default, and the app's own limit is deliberately higher, so
    this is the case that proves the app is not the one refusing.
    """
    padding = b"; padding to exceed the default proxy body limit\n"
    return MINIMAL_GCODE + padding * (min_bytes // len(padding) + 1)


def binary_stl(
    *, triangles: int = 12, offset: tuple[float, float, float] = (0, 0, 0)
) -> bytes:
    """A valid binary STL of *triangles* facets, laid out in a readable grid.

    `offset` translates the whole mesh, which is how a test checks that framing
    centres on the geometry rather than on the origin.
    """
    facets = []
    for index in range(triangles):
        x = float(index % 4) + offset[0]
        y = float(index // 4) + offset[1]
        z = offset[2]
        facets.append(
            _STL_TRIANGLE.pack(
                0.0,
                0.0,
                1.0,
                x,
                y,
                z,
                x + 0.8,
                y,
                z,
                x,
                y + 0.8,
                z,
                0,
            )
        )
    return (
        b"printstash-test".ljust(80, b"\0")
        + struct.pack("<I", triangles)
        + b"".join(facets)
    )


def ascii_stl() -> bytes:
    """A one-facet ASCII STL, correctly terminated."""
    return (
        b"solid printstash\n"
        b"facet normal 0 0 1\n"
        b" outer loop\n"
        b"  vertex 0 0 0\n"
        b"  vertex 1 0 0\n"
        b"  vertex 0 1 0\n"
        b" endloop\n"
        b"endfacet\n"
        b"endsolid printstash\n"
    )


def png(*, width: int = 8, height: int = 8) -> bytes:
    """A real, decodable PNG.

    Use this rather than `b"\\x89PNG\\r\\n\\x1a\\n" + b"..."`: the preview paths
    *decode* every candidate image rather than trusting its magic bytes, so a
    stub is correctly rejected and the test ends up asserting against no image at
    all. That is a false pass, and it happened here.
    """
    from PIL import Image

    buffer = io.BytesIO()
    Image.new("RGBA", (width, height), (90, 140, 210, 255)).save(buffer, format="PNG")
    return buffer.getvalue()


def png_declaring(width: int, height: int) -> bytes:
    """A structurally valid PNG whose header *claims* width x height pixels.

    A decompression bomb in a few hundred bytes: Pillow reads the dimensions out
    of IHDR and refuses before decoding a row, which is how a hostile image is
    rejected without allocating for it.
    """

    def chunk(kind: bytes, payload: bytes) -> bytes:
        return (
            struct.pack(">I", len(payload))
            + kind
            + payload
            + struct.pack(">I", zlib.crc32(kind + payload) & 0xFFFFFFFF)
        )

    header = struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0)
    return (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", header)
        + chunk(b"IDAT", zlib.compress(b"\0"))
        + chunk(b"IEND", b"")
    )


def zip_bytes(entries: dict[str, bytes], *, compress: bool = True) -> bytes:
    """A ZIP archive of *entries*, keyed by entry path.

    `compress=False` writes stored entries, which is how a test makes the
    on-disk size and the uncompressed size equal — relevant whenever the code
    under test reads one and acts on the other.
    """
    buffer = io.BytesIO()
    mode = zipfile.ZIP_DEFLATED if compress else zipfile.ZIP_STORED
    with zipfile.ZipFile(buffer, "w", mode) as archive:
        for name, content in entries.items():
            archive.writestr(name, content)
    return buffer.getvalue()


def compression_bomb_3mf(*, preview: bool = True) -> bytes:
    """A real 3MF that is tiny on disk and enormous decompressed.

    The guard under test reads the *uncompressed* size from the zip directory and
    skips the mesh without decompressing it, so the archive has to genuinely
    deflate — a stub with a declared size would not exercise it. With `preview`,
    the embedded plate image stands in for the mesh the app refused to load.
    """
    entries: dict[str, bytes] = {"3D/3dmodel.model": b"<triangle/>" * 2_000_000}
    if preview:
        entries["Metadata/thumbnail.png"] = png()
    return zip_bytes(entries)


def three_mf(*, model: bytes | None = None, preview: bool = True) -> bytes:
    """A minimal, well-formed 3MF container."""
    entries: dict[str, bytes] = {
        "3D/3dmodel.model": model or b'<?xml version="1.0"?><model/>',
        "[Content_Types].xml": b'<?xml version="1.0"?><Types/>',
    }
    if preview:
        entries["Metadata/thumbnail.png"] = png()
    return zip_bytes(entries)
