/*
 * Getting something into the library, and watching it arrive.
 *
 * A gallery upload has to queue a task and be *trackable to completion*. The
 * tracking is the feature: an upload that succeeds silently leaves the user
 * refreshing to find out whether it worked.
 *
 * URL capture is reviewable before it imports, reports a partial result honestly
 * when some files failed, and restores a source override the user had set. That
 * last one is the subtle case — re-capturing must not overwrite a field the user
 * corrected by hand.
 */
import { expect, test } from "@playwright/test";

import { setExternalLibrariesEnabled } from "./mock-api";
import { collectPageProblems, useMockApi } from "./_setup";

useMockApi();

test.describe("upload and capture", () => {
  test("gallery upload queues a task and tracks it to completion", async ({ page }) => {
    const problems = await collectPageProblems(page);

    // Auth is seeded in beforeEach.
    await page.goto("/");

    await expect(page.getByRole("link", { name: /upload/i })).toHaveCount(0);
    await page.getByRole("button", { name: "Upload", exact: true }).click();
    await expect(page.getByRole("dialog", { name: "Upload model" })).toBeVisible();

    await page.locator('input[accept=".gcode,.g,.gco"]').setInputFiles({
      name: "cube.gcode",
      mimeType: "text/plain",
      buffer: Buffer.from("; generated by test\n"),
    });
    await page.getByPlaceholder("e.g. Bracket v2").fill("Cube");
    await page.getByRole("button", { name: /upload to vault/i }).click();

    await expect(page.getByRole("dialog", { name: "Upload model" })).toHaveCount(0);
    await page.getByRole("button", { name: "Notifications" }).click();
    await expect(page.getByText("Upload Cube")).toBeVisible();
    await expect(page.getByText("completed", { exact: true })).toBeVisible();
    await expect(page.getByText("running", { exact: true })).toHaveCount(0);

    expect(problems).toEqual([]);
  });

  test("URL capture is reviewable, reports a partial result, and restores a source override", async ({
    page,
  }) => {
    const problems = await collectPageProblems(page);

    await page.goto("/");
    await page.getByRole("button", { name: "Upload", exact: true }).click();
    await page.getByRole("button", { name: "From URL" }).click();
    await page
      .getByPlaceholder("Model page, collection, or direct .stl/.zip link")
      .fill("https://www.printables.com/model/41-capture-bracket");
    await page.getByRole("button", { name: "Review URL" }).click();

    await expect(page).toHaveURL(/\/inbox\/41$/);
    await expect(page.getByRole("heading", { name: "Capture bracket" })).toBeVisible();
    const files = page.getByRole("group", { name: "Files to import" });
    await expect(files.getByRole("checkbox", { name: "Select capture-bracket.stl" })).toBeChecked();
    await files.getByRole("checkbox", { name: "Select capture-bracket.3mf" }).press("Space");
    await expect(page.getByRole("button", { name: "Import selected" })).toBeEnabled();
    await page.getByRole("button", { name: "Import selected" }).click();
    await expect(page.getByRole("heading", { name: "Results" })).toBeVisible();
    await expect(page.getByText("capture-bracket.3mf")).toBeVisible();
    await expect(page.getByRole("button", { name: "Retry failed files" })).toBeVisible();

    await page.getByRole("link", { name: "Open model" }).click();
    await page.getByRole("tab", { name: "Source" }).click();
    await expect(page.getByText("Fixture maker")).toBeVisible();
    await expect(page.getByText("CC BY 4.0")).toBeVisible();
    await expect(page.getByText("Print with supports.")).toBeVisible();
    // Each field's edit control names the field it edits, so this addresses the
    // Creator row directly. It used to walk two levels up from the heading
    // (`h3 -> label+badge wrapper -> row`) because every button was called
    // "Edit" — a DOM-shape dependency that silently targeted whichever field the
    // API returned first, and drove the wrong widget for months.
    const editCreator = page.getByRole("button", { name: "Edit Creator", exact: true });
    await editCreator.click();
    await page.getByLabel("Creator override").fill("Corrected maker");
    await page.getByRole("button", { name: "Save" }).click();
    await expect(page.getByText("Corrected maker")).toBeVisible();
    await expect(page.getByText("Edited")).toBeVisible();
    await editCreator.click();
    await page.getByRole("button", { name: "Restore captured value" }).click();
    const dialog = page.getByRole("dialog", { name: "Restore captured value?" });
    await expect(dialog).toBeVisible();
    await dialog.getByRole("button", { name: "Restore" }).click();
    await expect(page.getByText("Fixture maker")).toBeVisible();
    await expect(page.getByText("Source").last()).toBeVisible();

    expect(problems).toEqual([]);
  });
});

test.describe("shared volumes enabled", () => {
  test.beforeEach(() => setExternalLibrariesEnabled(true));
  test.afterEach(() => setExternalLibrariesEnabled(false));

  test("upload modal surfaces the shared-volume write-back destination selector", async ({
    page,
  }) => {
    const problems = await collectPageProblems(page);

    await page.goto("/");
    await page.getByRole("button", { name: "Upload", exact: true }).click();
    await expect(page.getByRole("dialog", { name: "Upload model" })).toBeVisible();

    // With mirroring on and a volume present, the "Store in" selector appears,
    // defaulting to vault and offering the shared volume as a write-back target.
    const destination = page.getByRole("combobox").filter({ hasText: "Vault storage" });
    await expect(destination).toBeVisible();
    await expect(page.getByRole("option", { name: /nas-main \(shared volume\)/ })).toBeAttached();

    expect(problems).toEqual([]);
  });
});
