import {
  collectPageProblems,
  expect,
  installMockApiHooks,
  setExternalLibrariesEnabled,
  test,
} from "./helpers";

installMockApiHooks();

test("gallery upload queues a task and tracks it to completion", async ({ page }) => {
  const problems = await collectPageProblems(page);

  // Auth is seeded in beforeEach.
  await page.goto("/");

  await expect(page.getByRole("link", { name: /upload/i })).toHaveCount(0);
  await page.getByRole("button", { name: "Upload", exact: true }).click();
  await expect(page.getByRole("dialog", { name: "Upload model" })).toBeVisible();

  await page.locator('input[accept=".gcode,.g,.gco"]').setInputFiles({
    name: "cube.gcode",
    mimeType: "text/plain",
    buffer: Buffer.from("; generated by test\n"),
  });
  await page.getByPlaceholder("e.g. Bracket v2").fill("Cube");
  await page.getByRole("button", { name: /upload to vault/i }).click();

  await expect(page.getByRole("dialog", { name: "Upload model" })).toHaveCount(0);
  await page.getByRole("button", { name: "Notifications" }).click();
  await expect(page.getByText("Upload Cube")).toBeVisible();
  await expect(page.getByText("completed", { exact: true })).toBeVisible();
  await expect(page.getByText("running", { exact: true })).toHaveCount(0);

  expect(problems).toEqual([]);
});

test.describe("shared volumes enabled", () => {
  test.beforeEach(() => setExternalLibrariesEnabled(true));
  test.afterEach(() => setExternalLibrariesEnabled(false));

  test("upload modal surfaces the shared-volume write-back destination selector", async ({
    page,
  }) => {
    const problems = await collectPageProblems(page);

    await page.goto("/");
    await page.getByRole("button", { name: "Upload", exact: true }).click();
    await expect(page.getByRole("dialog", { name: "Upload model" })).toBeVisible();

    // With mirroring on and a volume present, the "Store in" selector appears,
    // defaulting to vault and offering the shared volume as a write-back target.
    const destination = page.getByRole("combobox").filter({ hasText: "Vault storage" });
    await expect(destination).toBeVisible();
    await expect(page.getByRole("option", { name: /nas-main \(shared volume\)/ })).toBeAttached();

    expect(problems).toEqual([]);
  });
});
