"""Generate the TypeScript representation of shared printer contracts."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Sequence

from .catalog import catalog_document

HEADER = "// Generated by printstash_core.printers.codegen. Do not edit.\n"


def render_typescript() -> str:
    """Render stable TypeScript with literal types inferred from the catalog."""

    body = json.dumps(catalog_document(), ensure_ascii=False, indent=2)
    return (
        f"{HEADER}"
        f"export const SHARED_PRINTER_CONTRACT = {body} as const;\n\n"
        "export type SharedPrinterProviderId = "
        "keyof typeof SHARED_PRINTER_CONTRACT.providers;\n"
        "export type SharedPrinterCapability = "
        "(typeof SHARED_PRINTER_CONTRACT.capabilities)[number];\n"
        "export type SharedPrinterSetupOption = "
        "(typeof SHARED_PRINTER_CONTRACT.setupOptions)[number];\n"
    )


def write_typescript(output: Path, *, check: bool = False) -> bool:
    """Write generated output, or return whether an existing file is current."""

    rendered = render_typescript()
    if check:
        return output.is_file() and output.read_text(encoding="utf-8") == rendered
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8")
    return True


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args(argv)
    return 0 if write_typescript(arguments.output, check=arguments.check) else 1


if __name__ == "__main__":  # pragma: no cover - exercised through the CLI
    raise SystemExit(main())
