"""Tests for G-code revision metadata on model files."""

from __future__ import annotations

import io
import zipfile
from pathlib import Path

import pytest
from fastapi.testclient import TestClient
from sqlmodel import Session

from app.core.config import _overlay
from app.core.time import utcnow
from app.db.models import (
    Collection,
    CollectionPermission,
    CollectionRole,
    File,
    FileType,
    Metadata,
    Model,
    Printer,
    PrinterFile,
    PrintJob,
    PrintJobState,
    User,
)
from app.services.auth import create_access_token, hash_password


def _model(db_session: Session, *, slug: str = "bracket") -> Model:
    model = Model(name="Bracket", slug=slug, hash=f"{slug:0<64}"[:64])
    db_session.add(model)
    db_session.commit()
    db_session.refresh(model)
    return model


def _file(
    db_session: Session,
    model: Model,
    *,
    file_type: FileType = FileType.GCODE,
    version: int = 1,
    sha: str = "a",
) -> File:
    file_row = File(
        model_id=model.id,
        path=f"/data/files/{model.slug}/v{version}/file-{version}.gcode",
        original_filename=f"file-{version}.gcode",
        file_type=file_type,
        version=version,
        size_bytes=123,
        sha256=sha * 64,
    )
    db_session.add(file_row)
    db_session.commit()
    db_session.refresh(file_row)
    return file_row


def _configure_storage(tmp_path: Path) -> None:
    _overlay["data_dir"] = tmp_path / "files"
    _overlay["thumb_dir"] = tmp_path / "thumbs"
    _overlay["staging_dir"] = tmp_path / "staging"


def _large_gcode(min_bytes: int = 1_200_000) -> bytes:
    payload = b"; generated by OrcaSlicer\nG90\nG1 X1 Y1 E1\n"
    payload += b"; padding to exceed nginx default body limit\n" * (min_bytes // 45)
    return payload


def _regular_user(session: Session, username: str = "regular") -> User:
    user = User(
        username=username,
        hashed_password=hash_password("Password123"),
        is_active=True,
        is_superuser=False,
    )
    session.add(user)
    session.commit()
    session.refresh(user)
    return user


def _headers_for(user: User) -> dict[str, str]:
    scope = "admin" if user.is_superuser else "write"
    token = create_access_token(user.id, user.username, scope=scope)
    return {"Authorization": f"Bearer {token}"}


# --------------------------------------------------------------------------- #
# Batch operations.
# --------------------------------------------------------------------------- #


# --------------------------------------------------------------------------- #
# Library archive export / import.
# --------------------------------------------------------------------------- #

__all__ = [
    "Collection",
    "CollectionPermission",
    "CollectionRole",
    "FileType",
    "Metadata",
    "Path",
    "PrintJob",
    "PrintJobState",
    "Printer",
    "PrinterFile",
    "Session",
    "TestClient",
    "_configure_storage",
    "_file",
    "_headers_for",
    "_large_gcode",
    "_model",
    "_regular_user",
    "io",
    "pytest",
    "utcnow",
    "zipfile",
]
