"""G-code revisions: adding one, labelling it, and taking one away.

A model accumulates G-code over time — reprints, tuned profiles, a fix for a warping
corner — and the library's job is to say which one to print *now*. That is the recommended
revision, and the invariant behind every test here is that a model with G-code has
**exactly one**: the first upload becomes it automatically, marking a new one demotes the
old one, and deleting the recommended one promotes the newest survivor rather than leaving
a model with G-code and nothing to print.

"Exactly one" is also scoped per model. Promoting a revision on one model must not touch
another's, which is the kind of thing a `WHERE` clause forgets.

Deletes are soft, so a revision can come back, and the file's own metadata comes back with
it. What must not survive a delete is a stale pointer: a model whose thumbnail came from
the deleted file has to let go of it, or the grid renders a thumbnail for bytes that are
no longer part of the model.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from fastapi.testclient import TestClient
from sqlmodel import Session

from app.core.time import utcnow
from app.db.models import FileType, Model
from app.services import storage

GCODE = b"; generated by OrcaSlicer\nG28\n"


def _gcode_files(body: dict) -> list[dict]:
    return [row for row in body["files"] if row["file_type"] == "gcode"]


def _large_gcode(min_bytes: int = 1_200_000) -> bytes:
    """A body over nginx's default 1 MB limit, which the app must still accept."""
    payload = b"; generated by OrcaSlicer\nG90\nG1 X1 Y1 E1\n"
    payload += b"; padding to exceed nginx default body limit\n" * (min_bytes // 45)
    return payload


@pytest.fixture
def model(make_model) -> Model:
    return make_model("Bracket")


class TestAddGcodeRevision:
    def test_adds_the_revision_to_the_model(
        self, client: TestClient, auth_headers, model: Model, local_storage
    ) -> None:
        response = client.post(
            f"/api/v1/models/{model.id}/gcode-revisions",
            headers=auth_headers,
            files={"file": ("tighter-fit.gcode", GCODE, "text/plain")},
        )

        assert response.status_code == 200, response.text
        assert len(_gcode_files(response.json())) == 1

    def test_numbers_revisions_in_upload_order(
        self,
        client: TestClient,
        auth_headers,
        model: Model,
        make_file,
        local_storage,
    ) -> None:
        make_file(model)

        response = client.post(
            f"/api/v1/models/{model.id}/gcode-revisions",
            headers=auth_headers,
            files={"file": ("tighter-fit.gcode", GCODE, "text/plain")},
        )

        assert [
            row["gcode_revision_number"] for row in _gcode_files(response.json())
        ] == [
            1,
            2,
        ]

    def test_records_the_revision_metadata_it_was_given(
        self, client: TestClient, auth_headers, model: Model, local_storage
    ) -> None:
        response = client.post(
            f"/api/v1/models/{model.id}/gcode-revisions",
            headers=auth_headers,
            files={"file": ("tighter-fit.gcode", GCODE, "text/plain")},
            data={
                "revision_label": "Tighter fit",
                "revision_notes": "Reduced clearance",
            },
        )

        latest = _gcode_files(response.json())[-1]
        assert latest["revision_label"] == "Tighter fit"
        assert latest["revision_notes"] == "Reduced clearance"

    def test_starts_a_new_revision_as_untested(
        self, client: TestClient, auth_headers, model: Model, local_storage
    ) -> None:
        response = client.post(
            f"/api/v1/models/{model.id}/gcode-revisions",
            headers=auth_headers,
            files={"file": ("tighter-fit.gcode", GCODE, "text/plain")},
        )

        assert _gcode_files(response.json())[-1]["revision_status"] == "needs_test"

    def test_recommends_the_first_revision_even_when_not_asked_to(
        self, client: TestClient, auth_headers, model: Model, local_storage
    ) -> None:
        response = client.post(
            f"/api/v1/models/{model.id}/gcode-revisions",
            headers=auth_headers,
            files={"file": ("first.gcode", GCODE, "text/plain")},
            data={"is_recommended": "false"},
        )

        # A model with G-code and nothing recommended has nothing to print.
        assert _gcode_files(response.json())[0]["is_recommended"] is True

    def test_demotes_the_old_recommendation_when_a_new_one_is_marked(
        self,
        client: TestClient,
        db_session: Session,
        auth_headers,
        model: Model,
        make_file,
        local_storage,
    ) -> None:
        first = make_file(model)
        first.is_recommended = True
        db_session.add(first)
        db_session.commit()

        response = client.post(
            f"/api/v1/models/{model.id}/gcode-revisions",
            headers=auth_headers,
            files={"file": ("tighter-fit.gcode", GCODE, "text/plain")},
            data={"is_recommended": "true"},
        )

        assert response.status_code == 200, response.text
        db_session.refresh(first)
        assert first.is_recommended is False

    def test_leaves_the_recommendation_alone_when_a_later_one_is_unmarked(
        self,
        client: TestClient,
        db_session: Session,
        auth_headers,
        model: Model,
        make_file,
        local_storage,
    ) -> None:
        first = make_file(model)
        first.is_recommended = True
        db_session.add(first)
        db_session.commit()

        response = client.post(
            f"/api/v1/models/{model.id}/gcode-revisions",
            headers=auth_headers,
            files={"file": ("second.gcode", GCODE, "text/plain")},
            data={"is_recommended": "false"},
        )

        files = {row["id"]: row for row in response.json()["files"]}
        assert files[first.id]["is_recommended"] is True
        assert sum(1 for row in files.values() if row["is_recommended"]) == 1

    def test_accepts_a_body_over_the_default_reverse_proxy_limit(
        self, client: TestClient, auth_headers, model: Model, local_storage
    ) -> None:
        response = client.post(
            f"/api/v1/models/{model.id}/gcode-revisions",
            headers=auth_headers,
            files={"file": ("large-revision.gcode", _large_gcode(), "text/plain")},
        )

        # Real slicer output routinely exceeds nginx's 1 MB default.
        assert response.status_code == 200, response.text
        assert _gcode_files(response.json())[0]["size_bytes"] > 1_000_000

    def test_refuses_a_file_that_is_not_gcode(
        self, client: TestClient, auth_headers, model: Model, local_storage
    ) -> None:
        response = client.post(
            f"/api/v1/models/{model.id}/gcode-revisions",
            headers=auth_headers,
            files={
                "file": ("part.stl", b"solid part\nendsolid part\n", "application/sla")
            },
        )

        assert response.status_code == 400, response.text
        assert response.json()["detail"] == "unsupported_file_type"

    def test_refuses_a_file_with_no_name(
        self, client: TestClient, auth_headers, model: Model, local_storage
    ) -> None:
        boundary = "revisionboundary"
        body = (
            f"--{boundary}\r\n"
            'Content-Disposition: form-data; name="file"; filename=""\r\n'
            "Content-Type: text/plain\r\n\r\n"
            "hi\r\n"
            f"--{boundary}--\r\n"
        ).encode()

        response = client.post(
            f"/api/v1/models/{model.id}/gcode-revisions",
            content=body,
            headers={
                **auth_headers,
                "content-type": f"multipart/form-data; boundary={boundary}",
            },
        )

        assert response.status_code == 400, response.text
        assert response.json()["detail"] == "filename_required"

    def test_refuses_a_file_past_the_upload_cap(
        self,
        client: TestClient,
        auth_headers,
        model: Model,
        local_storage,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        def too_large(*_args: object, **_kwargs: object):
            raise storage.UploadTooLarge("upload_too_large")

        monkeypatch.setattr("app.api.v1.models.storage.stream_to_path", too_large)

        response = client.post(
            f"/api/v1/models/{model.id}/gcode-revisions",
            headers=auth_headers,
            files={"file": ("rev.gcode", GCODE, "text/plain")},
        )

        # The route's own per-file cap, which a client can now actually see: the
        # request ceiling sits above it, so a file over the file limit reaches
        # route code instead of being answered as `request_too_large`.
        assert response.status_code == 413, response.text
        assert response.json()["detail"] == "upload_too_large"

    def test_removes_the_staged_file_when_the_import_fails(
        self,
        client: TestClient,
        auth_headers,
        model: Model,
        local_storage,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        staged: list[Path] = []

        def failing(**kwargs):
            staged.append(kwargs["staged_path"])
            raise RuntimeError("boom")

        monkeypatch.setattr("app.api.v1.models.add_gcode_revision_to_model", failing)

        with pytest.raises(RuntimeError, match="boom"):
            client.post(
                f"/api/v1/models/{model.id}/gcode-revisions",
                headers=auth_headers,
                files={"file": ("rev.gcode", GCODE, "text/plain")},
            )

        # A staged file nobody owns is a staging directory that only grows.
        assert staged and not staged[0].exists()

    def test_rejects_an_unauthenticated_caller(
        self, client: TestClient, model: Model, local_storage
    ) -> None:
        response = client.post(
            f"/api/v1/models/{model.id}/gcode-revisions",
            files={"file": ("rev.gcode", GCODE, "text/plain")},
        )

        assert response.status_code == 401, response.text


class TestUpdateRevision:
    def test_records_a_status_change_with_its_justification(
        self, client: TestClient, auth_headers, model: Model, make_file
    ) -> None:
        row = make_file(model)

        response = client.patch(
            f"/api/v1/models/{model.id}/files/{row.id}/revision",
            headers=auth_headers,
            json={
                "revision_status": "known_good",
                "revision_notes": "Printed cleanly in PETG",
                "is_recommended": True,
            },
        )

        assert response.status_code == 200, response.text
        revision = response.json()["files"][0]
        assert revision["revision_status"] == "known_good"
        assert revision["revision_notes"] == "Printed cleanly in PETG"
        assert revision["is_recommended"] is True

    def test_records_the_label_it_was_given(
        self, client: TestClient, auth_headers, model: Model, make_file
    ) -> None:
        row = make_file(model)

        response = client.patch(
            f"/api/v1/models/{model.id}/files/{row.id}/revision",
            headers=auth_headers,
            json={"revision_label": "PETG baseline"},
        )

        assert response.json()["files"][0]["revision_label"] == "PETG baseline"

    def test_treats_a_whitespace_only_label_as_no_label(
        self,
        client: TestClient,
        db_session: Session,
        auth_headers,
        model: Model,
        make_file,
    ) -> None:
        row = make_file(model)
        row.revision_label = "Old label"
        db_session.add(row)
        db_session.commit()

        response = client.patch(
            f"/api/v1/models/{model.id}/files/{row.id}/revision",
            headers=auth_headers,
            json={"revision_label": "   "},
        )

        assert response.json()["files"][0]["revision_label"] is None

    def test_clears_a_status_that_is_set_to_nothing(
        self,
        client: TestClient,
        db_session: Session,
        auth_headers,
        model: Model,
        make_file,
    ) -> None:
        row = make_file(model)
        row.revision_status = "known_good"
        db_session.add(row)
        db_session.commit()

        response = client.patch(
            f"/api/v1/models/{model.id}/files/{row.id}/revision",
            headers=auth_headers,
            json={"revision_status": None},
        )

        assert response.json()["files"][0]["revision_status"] is None

    def test_treats_whitespace_only_notes_as_no_notes(
        self,
        client: TestClient,
        db_session: Session,
        auth_headers,
        model: Model,
        make_file,
    ) -> None:
        row = make_file(model)
        row.revision_notes = "Old note"
        db_session.add(row)
        db_session.commit()

        response = client.patch(
            f"/api/v1/models/{model.id}/files/{row.id}/revision",
            headers=auth_headers,
            json={"revision_notes": "   "},
        )

        assert response.json()["files"][0]["revision_notes"] is None

    def test_keeps_exactly_one_recommendation_per_model(
        self, client: TestClient, auth_headers, model: Model, make_file
    ) -> None:
        first = make_file(model)
        second = make_file(model)
        client.patch(
            f"/api/v1/models/{model.id}/files/{first.id}/revision",
            headers=auth_headers,
            json={"is_recommended": True},
        )

        response = client.patch(
            f"/api/v1/models/{model.id}/files/{second.id}/revision",
            headers=auth_headers,
            json={"is_recommended": True},
        )

        files = {row["id"]: row for row in response.json()["files"]}
        assert files[first.id]["is_recommended"] is False
        assert files[second.id]["is_recommended"] is True

    def test_leaves_another_models_recommendation_alone(
        self,
        client: TestClient,
        db_session: Session,
        auth_headers,
        make_model,
        make_file,
    ) -> None:
        one = make_model("One")
        two = make_model("Two")
        theirs = make_file(one)
        mine = make_file(two)
        theirs.is_recommended = True
        db_session.add(theirs)
        db_session.commit()

        client.patch(
            f"/api/v1/models/{two.id}/files/{mine.id}/revision",
            headers=auth_headers,
            json={"is_recommended": True},
        )

        # "Exactly one" is scoped per model — the kind of thing a WHERE forgets.
        db_session.refresh(theirs)
        assert theirs.is_recommended is True

    def test_rejects_a_status_it_does_not_recognise(
        self, client: TestClient, auth_headers, model: Model, make_file
    ) -> None:
        row = make_file(model)

        response = client.patch(
            f"/api/v1/models/{model.id}/files/{row.id}/revision",
            headers=auth_headers,
            json={"revision_status": "perfect_enough"},
        )

        assert response.status_code == 422, response.text

    def test_refuses_a_file_that_is_not_gcode(
        self, client: TestClient, auth_headers, model: Model, make_file
    ) -> None:
        row = make_file(model, file_type=FileType.STL)

        response = client.patch(
            f"/api/v1/models/{model.id}/files/{row.id}/revision",
            headers=auth_headers,
            json={"revision_status": "known_good"},
        )

        assert response.status_code == 400, response.text
        assert response.json()["detail"] == "revision_not_supported"

    def test_refuses_a_file_that_is_in_the_trash(
        self,
        client: TestClient,
        db_session: Session,
        auth_headers,
        model: Model,
        make_file,
    ) -> None:
        row = make_file(model)
        row.deleted_at = utcnow()
        db_session.add(row)
        db_session.commit()

        response = client.patch(
            f"/api/v1/models/{model.id}/files/{row.id}/revision",
            headers=auth_headers,
            json={"revision_status": "failed"},
        )

        assert response.status_code == 404, response.text
        assert response.json()["detail"] == "file_not_found"

    def test_refuses_a_file_that_belongs_to_another_model(
        self, client: TestClient, auth_headers, make_model, make_file
    ) -> None:
        one = make_model("One")
        two = make_model("Two")
        row = make_file(two)

        response = client.patch(
            f"/api/v1/models/{one.id}/files/{row.id}/revision",
            headers=auth_headers,
            json={"revision_status": "failed"},
        )

        assert response.status_code == 404, response.text
        assert response.json()["detail"] == "file_not_found"

    def test_rejects_an_unauthenticated_caller(
        self, client: TestClient, model: Model, make_file
    ) -> None:
        row = make_file(model)

        response = client.patch(
            f"/api/v1/models/{model.id}/files/{row.id}/revision",
            json={"revision_status": "failed"},
        )

        assert response.status_code == 401, response.text


class TestDeleteRevision:
    def test_hides_the_revision_from_the_model(
        self, client: TestClient, auth_headers, model: Model, make_file
    ) -> None:
        keep = make_file(model)
        drop = make_file(model)

        response = client.delete(
            f"/api/v1/models/{model.id}/files/{drop.id}/revision", headers=auth_headers
        )

        assert response.status_code == 200, response.text
        assert [row["id"] for row in response.json()["files"]] == [keep.id]

    def test_keeps_the_row_so_the_revision_can_come_back(
        self,
        client: TestClient,
        db_session: Session,
        auth_headers,
        model: Model,
        make_file,
    ) -> None:
        make_file(model)
        drop = make_file(model)

        client.delete(
            f"/api/v1/models/{model.id}/files/{drop.id}/revision", headers=auth_headers
        )

        db_session.refresh(drop)
        assert drop.deleted_at is not None

    def test_promotes_the_newest_survivor_when_the_recommended_one_goes(
        self,
        client: TestClient,
        db_session: Session,
        auth_headers,
        model: Model,
        make_file,
    ) -> None:
        make_file(model)
        middle = make_file(model)
        newest = make_file(model)
        middle.is_recommended = True
        db_session.add(middle)
        db_session.commit()

        response = client.delete(
            f"/api/v1/models/{model.id}/files/{middle.id}/revision",
            headers=auth_headers,
        )

        # Otherwise the model still has G-code and nothing to print.
        recommended = [
            row["id"] for row in response.json()["files"] if row["is_recommended"]
        ]
        assert recommended == [newest.id]

    def test_leaves_nothing_recommended_when_the_last_revision_goes(
        self,
        client: TestClient,
        db_session: Session,
        auth_headers,
        model: Model,
        make_file,
    ) -> None:
        only = make_file(model)
        only.is_recommended = True
        db_session.add(only)
        db_session.commit()

        response = client.delete(
            f"/api/v1/models/{model.id}/files/{only.id}/revision", headers=auth_headers
        )

        assert response.json()["files"] == []
        db_session.refresh(only)
        assert only.is_recommended is False

    def test_lets_go_of_a_thumbnail_that_came_from_the_deleted_file(
        self,
        client: TestClient,
        db_session: Session,
        auth_headers,
        model: Model,
        make_file,
    ) -> None:
        row = make_file(model)
        model.thumbnail_file_id = row.id
        model.thumbnail_path = "thumbs/stale.webp"
        db_session.add(model)
        db_session.commit()

        client.delete(
            f"/api/v1/models/{model.id}/files/{row.id}/revision", headers=auth_headers
        )

        # Otherwise the grid renders a picture of bytes no longer in the model.
        db_session.refresh(model)
        assert model.thumbnail_file_id is None
        assert model.thumbnail_path is None

    def test_refuses_a_file_that_is_not_gcode(
        self, client: TestClient, auth_headers, model: Model, make_file
    ) -> None:
        row = make_file(model, file_type=FileType.STL)

        response = client.delete(
            f"/api/v1/models/{model.id}/files/{row.id}/revision", headers=auth_headers
        )

        assert response.status_code == 400, response.text
        assert response.json()["detail"] == "revision_not_supported"

    def test_refuses_a_file_that_belongs_to_another_model(
        self, client: TestClient, auth_headers, make_model, make_file
    ) -> None:
        one = make_model("One")
        two = make_model("Two")
        row = make_file(two)

        response = client.delete(
            f"/api/v1/models/{one.id}/files/{row.id}/revision", headers=auth_headers
        )

        assert response.status_code == 404, response.text
        assert response.json()["detail"] == "file_not_found"

    def test_rejects_an_unauthenticated_caller(
        self, client: TestClient, model: Model, make_file
    ) -> None:
        row = make_file(model)

        response = client.delete(f"/api/v1/models/{model.id}/files/{row.id}/revision")

        assert response.status_code == 401, response.text
