from __future__ import annotations

from pathlib import Path
from datetime import timedelta
from typing import Any, Callable

from fastapi.testclient import TestClient
from sqlmodel import Session, select

from app.core.config import _overlay
from app.core.time import utcnow
from app.db.models import (
    File,
    FileType,
    FilamentProfile,
    Metadata,
    Model,
    PrinterProfile,
)
from app.services.storage_backend import get_backend


PNG_MAGIC = b"\x89PNG\r\n\x1a\n"
WEBP_MAGIC = b"RIFF"


def _cube_stl() -> bytes:
    return b"""solid cube
facet normal 0 0 -1
outer loop
vertex 0 0 0
vertex 1 1 0
vertex 1 0 0
endloop
endfacet
facet normal 0 0 -1
outer loop
vertex 0 0 0
vertex 0 1 0
vertex 1 1 0
endloop
endfacet
facet normal 0 0 1
outer loop
vertex 0 0 1
vertex 1 0 1
vertex 1 1 1
endloop
endfacet
facet normal 0 0 1
outer loop
vertex 0 0 1
vertex 1 1 1
vertex 0 1 1
endloop
endfacet
facet normal 0 -1 0
outer loop
vertex 0 0 0
vertex 1 0 0
vertex 1 0 1
endloop
endfacet
facet normal 0 -1 0
outer loop
vertex 0 0 0
vertex 1 0 1
vertex 0 0 1
endloop
endfacet
facet normal 1 0 0
outer loop
vertex 1 0 0
vertex 1 1 0
vertex 1 1 1
endloop
endfacet
facet normal 1 0 0
outer loop
vertex 1 0 0
vertex 1 1 1
vertex 1 0 1
endloop
endfacet
facet normal 0 1 0
outer loop
vertex 1 1 0
vertex 0 1 0
vertex 0 1 1
endloop
endfacet
facet normal 0 1 0
outer loop
vertex 1 1 0
vertex 0 1 1
vertex 1 1 1
endloop
endfacet
facet normal -1 0 0
outer loop
vertex 0 1 0
vertex 0 0 0
vertex 0 0 1
endloop
endfacet
facet normal -1 0 0
outer loop
vertex 0 1 0
vertex 0 0 1
vertex 0 1 1
endloop
endfacet
endsolid cube
"""


def _large_gcode(min_bytes: int = 1_200_000) -> bytes:
    payload = b"; generated by OrcaSlicer\nG90\nG1 X1 Y1 E1\n"
    payload += b"; padding to exceed nginx default body limit\n" * (
        min_bytes // 45
    )
    return payload


def _large_cube_stl(min_bytes: int = 1_200_000) -> bytes:
    lines = _cube_stl().splitlines()
    body = b"\n".join(lines[1:-1]) + b"\n"
    repeat_count = min_bytes // len(body) + 1
    return b"solid large-cube\n" + body * repeat_count + b"endsolid large-cube\n"


def _configure_storage(tmp_path: Path) -> None:
    _overlay["data_dir"] = tmp_path / "files"
    _overlay["thumb_dir"] = tmp_path / "thumbs"
    _overlay["staging_dir"] = tmp_path / "staging"


def _completed_job(client: TestClient, response) -> dict:
    assert response.status_code == 202, response.text
    job_id = response.json()["job_id"]
    headers = {}
    auth = response.request.headers.get("authorization")
    if auth:
        headers["Authorization"] = auth
    job = client.get(f"/api/v1/ingest/jobs/{job_id}", headers=headers)
    assert job.status_code == 200, job.text
    payload = job.json()
    assert payload["state"] == "completed", payload
    assert payload["model_id"] is not None
    assert payload["file_id"] is not None
    return payload


def _assert_file_created(session: Session, file_id: int, file_type: FileType) -> File:
    file_row = session.get(File, file_id)
    assert file_row is not None
    assert file_row.file_type == file_type
    assert file_row.size_bytes > 0
    assert get_backend().exists(file_row.path)
    metadata = session.exec(select(Metadata).where(Metadata.file_id == file_id)).one()
    assert metadata.file_id == file_id
    model = session.get(Model, file_row.model_id)
    assert model is not None
    assert model.thumbnail_file_id == file_id
    assert model.thumbnail_path
    assert get_backend().exists(model.thumbnail_path)
    return file_row


def test_ingest_orca_gcode_creates_db_blob_and_thumbnail(
    tmp_path: Path,
    client: TestClient,
    db_session: Session,
    auth_headers: dict[str, str],
) -> None:
    _configure_storage(tmp_path)
    gcode = (Path(__file__).parent / "fixtures" / "sample.gcode").read_bytes()

    payload = _completed_job(
        client,
        client.post(
            "/api/v1/ingest/orca",
            headers=auth_headers,
            files={"file": ("sample.gcode", gcode, "text/plain")},
            data={"model_name": "Sample G-code"},
        ),
    )
    file_id = payload["file_id"]
    _assert_file_created(db_session, file_id, FileType.GCODE)

    download = client.get(f"/api/v1/files/{file_id}/download", headers=auth_headers)
    assert download.status_code == 200, download.text
    assert b"; generated by OrcaSlicer" in download.content

    thumbnail = client.get(f"/api/v1/files/{file_id}/thumbnail", headers=auth_headers)
    assert thumbnail.status_code == 200, thumbnail.text
    assert thumbnail.headers["content-type"] == "image/webp"
    assert thumbnail.content.startswith(WEBP_MAGIC)

    filament_profile = db_session.exec(
        select(FilamentProfile).where(FilamentProfile.name == "Generic PLA")
    ).one()
    assert filament_profile.material_type == "PLA"
    assert filament_profile.cost_per_kg == 28

    printer_profile = db_session.exec(
        select(PrinterProfile).where(PrinterProfile.name == "Ender-3 V3 SE")
    ).one()
    assert printer_profile.slicer_name == "OrcaSlicer"
    assert printer_profile.nozzle_diameter_mm == 0.4


def test_ingest_orca_accepts_payload_over_nginx_default_limit(
    tmp_path: Path,
    client: TestClient,
    db_session: Session,
    auth_headers: dict[str, str],
) -> None:
    _configure_storage(tmp_path)

    payload = _completed_job(
        client,
        client.post(
            "/api/v1/ingest/orca",
            headers=auth_headers,
            files={"file": ("large.gcode", _large_gcode(), "text/plain")},
            data={"model_name": "Large G-code"},
        ),
    )

    file_row = db_session.get(File, payload["file_id"])
    assert file_row is not None
    assert file_row.file_type == FileType.GCODE
    assert file_row.size_bytes > 1_000_000
    assert get_backend().exists(file_row.path)
    metadata = db_session.exec(
        select(Metadata).where(Metadata.file_id == file_row.id)
    ).one()
    assert metadata.file_id == file_row.id


def test_ingest_orca_stages_upload_in_threadpool(
    tmp_path: Path,
    client: TestClient,
    auth_headers: dict[str, str],
    monkeypatch,
) -> None:
    _configure_storage(tmp_path)
    called: dict[str, str] = {}

    async def fake_threadpool(
        func: Callable[..., Any], *args: Any, **kwargs: Any
    ) -> Any:
        called["func"] = func.__name__
        return func(*args, **kwargs)

    monkeypatch.setattr("app.api.v1.ingest.run_in_threadpool", fake_threadpool)

    response = client.post(
        "/api/v1/ingest/orca",
        headers=auth_headers,
        files={"file": ("sample.gcode", b"G28\n", "text/plain")},
        data={"model_name": "Threadpool Check"},
    )

    assert response.status_code == 202
    assert called == {"func": "_stage_upload"}


def test_ingest_stl_creates_db_blob_and_thumbnail(
    tmp_path: Path,
    client: TestClient,
    db_session: Session,
    auth_headers: dict[str, str],
) -> None:
    _configure_storage(tmp_path)

    payload = _completed_job(
        client,
        client.post(
            "/api/v1/ingest/model",
            headers=auth_headers,
            files={"file": ("cube.stl", _cube_stl(), "application/sla")},
            data={"model_name": "Cube"},
        ),
    )
    file_id = payload["file_id"]
    _assert_file_created(db_session, file_id, FileType.STL)

    download = client.get(f"/api/v1/files/{file_id}/download", headers=auth_headers)
    assert download.status_code == 200, download.text
    assert b"solid cube" in download.content

    thumbnail = client.get(f"/api/v1/files/{file_id}/thumbnail", headers=auth_headers)
    assert thumbnail.status_code == 200, thumbnail.text
    assert thumbnail.headers["content-type"] == "image/webp"
    assert thumbnail.content.startswith(WEBP_MAGIC)


def test_ingest_model_accepts_payload_over_nginx_default_limit(
    tmp_path: Path,
    client: TestClient,
    db_session: Session,
    auth_headers: dict[str, str],
    monkeypatch,
) -> None:
    _configure_storage(tmp_path)
    monkeypatch.setattr(
        "app.services.mesh_processing.analyze_mesh",
        lambda _path, report=None: ({"bbox_x_mm": 1.0}, None),
    )

    payload = _completed_job(
        client,
        client.post(
            "/api/v1/ingest/model",
            headers=auth_headers,
            files={"file": ("large-cube.stl", _large_cube_stl(), "application/sla")},
            data={"model_name": "Large Cube"},
        ),
    )

    file_row = db_session.get(File, payload["file_id"])
    assert file_row is not None
    assert file_row.file_type == FileType.STL
    assert file_row.size_bytes > 1_000_000
    assert get_backend().exists(file_row.path)
    metadata = db_session.exec(
        select(Metadata).where(Metadata.file_id == file_row.id)
    ).one()
    assert metadata.bbox_x_mm == 1.0


def test_reuploading_deleted_model_restores_it(
    tmp_path: Path,
    client: TestClient,
    db_session: Session,
    auth_headers: dict[str, str],
) -> None:
    _configure_storage(tmp_path)

    first = _completed_job(
        client,
        client.post(
            "/api/v1/ingest/model",
            headers=auth_headers,
            files={"file": ("cube.stl", _cube_stl(), "application/sla")},
            data={"model_name": "Cube"},
        ),
    )
    model_id = first["model_id"]

    delete = client.delete(f"/api/v1/models/{model_id}", headers=auth_headers)
    assert delete.status_code == 204
    assert (
        client.get(f"/api/v1/models/{model_id}", headers=auth_headers).status_code
        == 404
    )

    second = _completed_job(
        client,
        client.post(
            "/api/v1/ingest/model",
            headers=auth_headers,
            files={"file": ("cube.stl", _cube_stl(), "application/sla")},
            data={"model_name": "Cube"},
        ),
    )

    assert second["model_id"] == model_id
    model = db_session.get(Model, model_id)
    assert model is not None
    assert model.deleted_at is None
    detail = client.get(f"/api/v1/models/{model_id}", headers=auth_headers)
    assert detail.status_code == 200, detail.text
    assert len(detail.json()["files"]) == 2


def test_trash_can_restore_and_purge_model(
    tmp_path: Path,
    client: TestClient,
    db_session: Session,
    auth_headers: dict[str, str],
) -> None:
    _configure_storage(tmp_path)

    payload = _completed_job(
        client,
        client.post(
            "/api/v1/ingest/model",
            headers=auth_headers,
            files={"file": ("cube.stl", _cube_stl(), "application/sla")},
            data={"model_name": "Cube"},
        ),
    )
    model_id = payload["model_id"]
    file_row = db_session.get(File, payload["file_id"])
    assert file_row is not None
    blob_path = file_row.path
    thumb_path = get_backend().thumbnail_key(file_row.id)

    delete = client.delete(f"/api/v1/models/{model_id}", headers=auth_headers)
    assert delete.status_code == 204

    trash = client.get("/api/v1/models/trash", headers=auth_headers)
    assert trash.status_code == 200, trash.text
    assert trash.json()[0]["id"] == model_id
    assert trash.json()[0]["file_count"] == 1
    assert trash.json()[0]["expires_at"] is not None

    restored = client.post(f"/api/v1/models/{model_id}/restore", headers=auth_headers)
    assert restored.status_code == 200, restored.text
    assert restored.json()["id"] == model_id
    assert client.get("/api/v1/models/trash", headers=auth_headers).json() == []

    delete = client.delete(f"/api/v1/models/{model_id}", headers=auth_headers)
    assert delete.status_code == 204
    purged = client.delete(f"/api/v1/models/{model_id}/purge", headers=auth_headers)
    assert purged.status_code == 200, purged.text
    assert purged.json() == {"purged_model_ids": [model_id], "purged_count": 1}
    db_session.expire_all()
    assert db_session.get(Model, model_id) is None
    assert db_session.get(File, payload["file_id"]) is None
    assert not get_backend().exists(blob_path)
    assert not get_backend().exists(thumb_path)


def test_purge_expired_trash_uses_retention_setting(
    tmp_path: Path,
    client: TestClient,
    db_session: Session,
    auth_headers: dict[str, str],
) -> None:
    _configure_storage(tmp_path)
    _overlay["trash_retention_days"] = 30
    old_model = Model(
        name="Old Cube",
        slug="old-cube",
        hash="old-cube".ljust(64, "0"),
        deleted_at=utcnow() - timedelta(days=31),
    )
    fresh_model = Model(
        name="Fresh Cube",
        slug="fresh-cube",
        hash="fresh-cube".ljust(64, "0"),
        deleted_at=utcnow() - timedelta(days=3),
    )
    db_session.add(old_model)
    db_session.add(fresh_model)
    db_session.commit()
    db_session.refresh(old_model)
    db_session.refresh(fresh_model)

    old_file = File(
        model_id=old_model.id,
        path=str(tmp_path / "files" / "old-cube.stl"),
        original_filename="old-cube.stl",
        file_type=FileType.STL,
        version=1,
        size_bytes=4,
        sha256="a" * 64,
    )
    fresh_file = File(
        model_id=fresh_model.id,
        path=str(tmp_path / "files" / "fresh-cube.stl"),
        original_filename="fresh-cube.stl",
        file_type=FileType.STL,
        version=1,
        size_bytes=4,
        sha256="b" * 64,
    )
    db_session.add(old_file)
    db_session.add(fresh_file)
    db_session.commit()
    old_model_id = old_model.id
    fresh_model_id = fresh_model.id
    old_file_path = old_file.path
    fresh_file_path = fresh_file.path
    Path(old_file.path).parent.mkdir(parents=True, exist_ok=True)
    Path(old_file.path).write_bytes(b"old")
    Path(fresh_file.path).write_bytes(b"new")

    purged = client.delete("/api/v1/models/trash/expired", headers=auth_headers)

    assert purged.status_code == 200, purged.text
    assert purged.json() == {"purged_model_ids": [old_model_id], "purged_count": 1}
    db_session.expire_all()
    assert db_session.get(Model, old_model_id) is None
    assert db_session.get(Model, fresh_model_id) is not None
    assert not Path(old_file_path).exists()
    assert Path(fresh_file_path).exists()


def test_force_rebuild_refreshes_existing_mesh_thumbnail(
    tmp_path: Path,
    client: TestClient,
    auth_headers: dict[str, str],
    monkeypatch,
) -> None:
    _configure_storage(tmp_path)

    payload = _completed_job(
        client,
        client.post(
            "/api/v1/ingest/model",
            headers=auth_headers,
            files={"file": ("cube.stl", _cube_stl(), "application/sla")},
            data={"model_name": "Cube"},
        ),
    )
    file_id = payload["file_id"]
    model_id = payload["model_id"]
    replacement = PNG_MAGIC + b"forced-thumbnail"

    monkeypatch.setattr(
        "app.services.mesh_processing.render_thumbnail",
        lambda _path: replacement,
    )

    response = client.post(
        "/api/v1/files/thumbnails/rebuild?force=true",
        headers=auth_headers,
    )

    assert response.status_code == 202, response.text
    job_id = response.json()["job_id"]
    job = client.get(f"/api/v1/ingest/jobs/{job_id}", headers=auth_headers)
    assert job.status_code == 200, job.text
    payload = job.json()
    assert payload["state"] == "completed", payload
    assert payload["result"]["rebuilt"] == [model_id]

    thumbnail = client.get(f"/api/v1/files/{file_id}/thumbnail", headers=auth_headers)
    assert thumbnail.status_code == 200, thumbnail.text
    assert thumbnail.content == replacement
