from __future__ import annotations

from pathlib import Path

from fastapi.testclient import TestClient
from sqlmodel import Session, select

from app.core.config import _overlay
from app.db.models import File, FileType, Metadata, Model
from app.services.storage_backend import get_backend


PNG_MAGIC = b"\x89PNG\r\n\x1a\n"


def _cube_stl() -> bytes:
    return b"""solid cube
facet normal 0 0 -1
outer loop
vertex 0 0 0
vertex 1 1 0
vertex 1 0 0
endloop
endfacet
facet normal 0 0 -1
outer loop
vertex 0 0 0
vertex 0 1 0
vertex 1 1 0
endloop
endfacet
facet normal 0 0 1
outer loop
vertex 0 0 1
vertex 1 0 1
vertex 1 1 1
endloop
endfacet
facet normal 0 0 1
outer loop
vertex 0 0 1
vertex 1 1 1
vertex 0 1 1
endloop
endfacet
facet normal 0 -1 0
outer loop
vertex 0 0 0
vertex 1 0 0
vertex 1 0 1
endloop
endfacet
facet normal 0 -1 0
outer loop
vertex 0 0 0
vertex 1 0 1
vertex 0 0 1
endloop
endfacet
facet normal 1 0 0
outer loop
vertex 1 0 0
vertex 1 1 0
vertex 1 1 1
endloop
endfacet
facet normal 1 0 0
outer loop
vertex 1 0 0
vertex 1 1 1
vertex 1 0 1
endloop
endfacet
facet normal 0 1 0
outer loop
vertex 1 1 0
vertex 0 1 0
vertex 0 1 1
endloop
endfacet
facet normal 0 1 0
outer loop
vertex 1 1 0
vertex 0 1 1
vertex 1 1 1
endloop
endfacet
facet normal -1 0 0
outer loop
vertex 0 1 0
vertex 0 0 0
vertex 0 0 1
endloop
endfacet
facet normal -1 0 0
outer loop
vertex 0 1 0
vertex 0 0 1
vertex 0 1 1
endloop
endfacet
endsolid cube
"""


def _configure_storage(tmp_path: Path) -> None:
    _overlay["data_dir"] = tmp_path / "files"
    _overlay["thumb_dir"] = tmp_path / "thumbs"
    _overlay["staging_dir"] = tmp_path / "staging"


def _completed_job(client: TestClient, response) -> dict:
    assert response.status_code == 202, response.text
    job_id = response.json()["job_id"]
    job = client.get(f"/api/v1/ingest/jobs/{job_id}")
    assert job.status_code == 200, job.text
    payload = job.json()
    assert payload["state"] == "completed", payload
    assert payload["model_id"] is not None
    assert payload["file_id"] is not None
    return payload


def _assert_file_created(session: Session, file_id: int, file_type: FileType) -> File:
    file_row = session.get(File, file_id)
    assert file_row is not None
    assert file_row.file_type == file_type
    assert file_row.size_bytes > 0
    assert get_backend().exists(file_row.path)
    metadata = session.exec(select(Metadata).where(Metadata.file_id == file_id)).one()
    assert metadata.file_id == file_id
    model = session.get(Model, file_row.model_id)
    assert model is not None
    assert model.thumbnail_file_id == file_id
    assert model.thumbnail_path
    assert get_backend().exists(model.thumbnail_path)
    return file_row


def test_ingest_orca_gcode_creates_db_blob_and_thumbnail(
    tmp_path: Path,
    client: TestClient,
    db_session: Session,
    auth_headers: dict[str, str],
) -> None:
    _configure_storage(tmp_path)
    gcode = (Path(__file__).parent / "fixtures" / "sample.gcode").read_bytes()

    payload = _completed_job(
        client,
        client.post(
            "/api/v1/ingest/orca",
            headers=auth_headers,
            files={"file": ("sample.gcode", gcode, "text/plain")},
            data={"model_name": "Sample G-code"},
        ),
    )
    file_id = payload["file_id"]
    _assert_file_created(db_session, file_id, FileType.GCODE)

    download = client.get(f"/api/v1/files/{file_id}/download")
    assert download.status_code == 200, download.text
    assert b"; generated by OrcaSlicer" in download.content

    thumbnail = client.get(f"/api/v1/files/{file_id}/thumbnail")
    assert thumbnail.status_code == 200, thumbnail.text
    assert thumbnail.content.startswith(PNG_MAGIC)


def test_ingest_stl_creates_db_blob_and_thumbnail(
    tmp_path: Path,
    client: TestClient,
    db_session: Session,
    auth_headers: dict[str, str],
) -> None:
    _configure_storage(tmp_path)

    payload = _completed_job(
        client,
        client.post(
            "/api/v1/ingest/model",
            headers=auth_headers,
            files={"file": ("cube.stl", _cube_stl(), "application/sla")},
            data={"model_name": "Cube"},
        ),
    )
    file_id = payload["file_id"]
    _assert_file_created(db_session, file_id, FileType.STL)

    download = client.get(f"/api/v1/files/{file_id}/download")
    assert download.status_code == 200, download.text
    assert b"solid cube" in download.content

    thumbnail = client.get(f"/api/v1/files/{file_id}/thumbnail")
    assert thumbnail.status_code == 200, thumbnail.text
    assert thumbnail.content.startswith(PNG_MAGIC)
