"""Tests for G-code revision metadata on model files."""

from __future__ import annotations

import io
import zipfile
from pathlib import Path

import pytest
from fastapi.testclient import TestClient
from sqlmodel import Session

from app.core.config import _overlay
from app.core.time import utcnow
from app.db.models import (
    Collection,
    CollectionPermission,
    CollectionRole,
    File,
    FileType,
    Metadata,
    Model,
    Printer,
    PrinterFile,
    PrintJob,
    PrintJobState,
    User,
)
from app.services.auth import create_access_token, hash_password


def _model(db_session: Session, *, slug: str = "bracket") -> Model:
    model = Model(name="Bracket", slug=slug, hash=f"{slug:0<64}"[:64])
    db_session.add(model)
    db_session.commit()
    db_session.refresh(model)
    return model


def _file(
    db_session: Session,
    model: Model,
    *,
    file_type: FileType = FileType.GCODE,
    version: int = 1,
    sha: str = "a",
) -> File:
    file_row = File(
        model_id=model.id,
        path=f"/data/files/{model.slug}/v{version}/file-{version}.gcode",
        original_filename=f"file-{version}.gcode",
        file_type=file_type,
        version=version,
        size_bytes=123,
        sha256=sha * 64,
    )
    db_session.add(file_row)
    db_session.commit()
    db_session.refresh(file_row)
    return file_row


def _configure_storage(tmp_path: Path) -> None:
    _overlay["data_dir"] = tmp_path / "files"
    _overlay["thumb_dir"] = tmp_path / "thumbs"
    _overlay["staging_dir"] = tmp_path / "staging"


def _large_gcode(min_bytes: int = 1_200_000) -> bytes:
    payload = b"; generated by OrcaSlicer\nG90\nG1 X1 Y1 E1\n"
    payload += b"; padding to exceed nginx default body limit\n" * (min_bytes // 45)
    return payload


def test_artifact_outcomes_compare_mixed_files(
    client: TestClient, db_session: Session, auth_headers: dict[str, str]
) -> None:
    model = _model(db_session, slug="outcomes")
    mesh = _file(db_session, model, file_type=FileType.STL, version=1, sha="c")
    gcode = _file(db_session, model, version=2, sha="d")
    db_session.add_all(
        [
            PrintJob(
                model_id=model.id,
                file_id=gcode.id,
                remote_filename=gcode.original_filename,
                state=PrintJobState.COMPLETED,
                source="manual",
                actual_duration_s=100,
                filament_g_effective=12.5,
                cost=1.25,
            ),
            PrintJob(
                model_id=model.id,
                file_id=gcode.id,
                remote_filename=gcode.original_filename,
                state=PrintJobState.FAILED,
                source="manual",
                actual_duration_s=50,
            ),
        ]
    )
    db_session.commit()

    response = client.get(
        f"/api/v1/models/{model.id}/artifact-outcomes?file_id={mesh.id}&file_id={gcode.id}",
        headers=auth_headers,
    )
    assert response.status_code == 200
    by_id = {row["file_id"]: row for row in response.json()}
    assert by_id[mesh.id]["print_count"] == 0
    assert by_id[gcode.id]["completed_count"] == 1
    assert by_id[gcode.id]["failed_count"] == 1
    assert by_id[gcode.id]["success_rate"] == 0.5
    assert by_id[gcode.id]["average_duration_s"] == 75


def test_update_revision_status_notes_and_recommended(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    file_row = _file(db_session, model)

    resp = client.patch(
        f"/api/v1/models/{model.id}/files/{file_row.id}/revision",
        json={
            "revision_status": "known_good",
            "revision_notes": "Printed cleanly in PETG",
            "is_recommended": True,
        },
        headers=auth_headers,
    )

    assert resp.status_code == 200
    body = resp.json()
    revision = body["files"][0]
    assert revision["revision_status"] == "known_good"
    assert revision["revision_notes"] == "Printed cleanly in PETG"
    assert revision["is_recommended"] is True


def test_model_printer_files_lists_printers_for_gcode(
    client: TestClient, db_session: Session, auth_headers: dict[str, str]
) -> None:
    model = _model(db_session)
    file_row = _file(db_session, model)
    printer = Printer(name="Ender", moonraker_url="http://10.0.0.1:7125")
    db_session.add(printer)
    db_session.commit()
    db_session.refresh(printer)
    db_session.add(
        PrinterFile(
            printer_id=printer.id,
            file_id=file_row.id,
            remote_filename="file-1.gcode",
            matched_by="upload_history",
        )
    )
    db_session.commit()

    resp = client.get(f"/api/v1/models/{model.id}/printer-files", headers=auth_headers)
    assert resp.status_code == 200
    assert resp.json() == [
        {
            "file_id": file_row.id,
            "printer_id": printer.id,
            "printer_name": "Ender",
            "remote_filename": "file-1.gcode",
            "matched_by": "upload_history",
            "last_seen_at": resp.json()[0]["last_seen_at"],
            "missing_since": None,
        }
    ]


def test_model_print_jobs_empty_when_none(
    client: TestClient, db_session: Session, auth_headers: dict[str, str]
) -> None:
    model = _model(db_session)

    resp = client.get(f"/api/v1/models/{model.id}/print-jobs", headers=auth_headers)
    assert resp.status_code == 200
    assert resp.json() == []


def test_model_print_jobs_lists_history_enriched(
    client: TestClient, db_session: Session, auth_headers: dict[str, str]
) -> None:
    model = _model(db_session)
    file_row = _file(db_session, model)
    file_row.revision_label = "PETG baseline"
    db_session.add(file_row)
    db_session.add(
        Metadata(file_id=file_row.id, slicer_name="OrcaSlicer", material_type="PETG")
    )
    printer = Printer(name="Ender", moonraker_url="http://10.0.0.1:7125")
    db_session.add(printer)
    db_session.commit()
    db_session.refresh(printer)
    db_session.add(
        PrintJob(
            printer_id=printer.id,
            file_id=file_row.id,
            model_id=model.id,
            remote_filename="file-1.gcode",
            state=PrintJobState.COMPLETED,
        )
    )
    db_session.commit()

    resp = client.get(f"/api/v1/models/{model.id}/print-jobs", headers=auth_headers)
    assert resp.status_code == 200
    rows = resp.json()
    assert len(rows) == 1
    assert rows[0]["printer_name"] == "Ender"
    assert rows[0]["state"] == "completed"
    assert rows[0]["material_type"] == "PETG"
    assert rows[0]["revision_label"] == "PETG baseline"
    assert rows[0]["gcode_revision_number"] == 1


def test_list_models_can_filter_by_printer(
    client: TestClient, db_session: Session, auth_headers: dict[str, str]
) -> None:
    present_model = _model(db_session, slug="present")
    absent_model = _model(db_session, slug="absent")
    present_file = _file(db_session, present_model)
    _file(db_session, absent_model, sha="b")
    printer = Printer(name="Ender", moonraker_url="http://10.0.0.1:7125")
    db_session.add(printer)
    db_session.commit()
    db_session.refresh(printer)
    db_session.add(
        PrinterFile(
            printer_id=printer.id,
            file_id=present_file.id,
            remote_filename="present.gcode",
            matched_by="upload_history",
        )
    )
    db_session.commit()

    resp = client.get(f"/api/v1/models?printer_id={printer.id}", headers=auth_headers)

    assert resp.status_code == 200
    data = resp.json()
    assert [row["id"] for row in data] == [present_model.id]
    assert data[0]["printer_presence"] == [
        {
            "printer_id": printer.id,
            "printer_name": "Ender",
            "file_count": 1,
        }
    ]


def test_list_models_can_filter_by_missing_printer_presence(
    client: TestClient, db_session: Session, auth_headers: dict[str, str]
) -> None:
    present_model = _model(db_session, slug="present-none")
    absent_model = _model(db_session, slug="absent-none")
    present_file = _file(db_session, present_model)
    _file(db_session, absent_model, sha="b")
    printer = Printer(name="Ender", moonraker_url="http://10.0.0.1:7125")
    db_session.add(printer)
    db_session.commit()
    db_session.refresh(printer)
    db_session.add(
        PrinterFile(
            printer_id=printer.id,
            file_id=present_file.id,
            remote_filename="present.gcode",
            matched_by="upload_history",
        )
    )
    db_session.commit()

    resp = client.get("/api/v1/models?printer_presence=none", headers=auth_headers)

    assert resp.status_code == 200
    ids = {row["id"] for row in resp.json()}
    assert absent_model.id in ids
    assert present_model.id not in ids


def test_export_models_json_includes_metadata_only_context(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    file_row = _file(db_session, model)
    file_row.revision_label = "PETG baseline"
    file_row.revision_status = "known_good"
    file_row.is_recommended = True
    db_session.add(file_row)
    db_session.add(
        Metadata(
            file_id=file_row.id,
            slicer_name="OrcaSlicer",
            printer_model="Voron 2.4",
            layer_height_mm=0.2,
            material_type="PETG",
        )
    )
    db_session.commit()

    resp = client.get("/api/v1/models/export", headers=auth_headers)

    assert resp.status_code == 200
    body = resp.json()
    assert body["contents"]["kind"] == "metadata_only"
    assert body["counts"] == {"models": 1, "files": 1}
    exported_file = body["models"][0]["files"][0]
    assert exported_file["revision_label"] == "PETG baseline"
    assert exported_file["revision_status"] == "known_good"
    assert exported_file["is_recommended"] is True
    assert exported_file["metadata"]["slicer_name"] == "OrcaSlicer"
    assert exported_file["metadata"]["printer_model"] == "Voron 2.4"


def test_export_models_csv_flattens_one_row_per_file(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    file_row = _file(db_session, model)
    db_session.add(
        Metadata(
            file_id=file_row.id,
            slicer_name="PrusaSlicer",
            infill_percent=20,
        )
    )
    db_session.commit()

    resp = client.get("/api/v1/models/export?format=csv", headers=auth_headers)

    assert resp.status_code == 200
    assert resp.headers["content-type"].startswith("text/csv")
    assert "model_name" in resp.text
    assert "file_id" in resp.text
    assert "file_type" in resp.text
    assert "Bracket" in resp.text
    assert "PrusaSlicer" in resp.text


def test_add_gcode_revision_to_existing_model(
    tmp_path: Path,
    client: TestClient,
    auth_headers: dict[str, str],
    db_session: Session,
) -> None:
    _configure_storage(tmp_path)
    model = _model(db_session)
    first = _file(db_session, model, version=1)
    first.is_recommended = True
    db_session.add(first)
    db_session.commit()

    resp = client.post(
        f"/api/v1/models/{model.id}/gcode-revisions",
        headers=auth_headers,
        files={
            "file": (
                "tighter-fit.gcode",
                b"; generated by OrcaSlicer\nG28\n",
                "text/plain",
            )
        },
        data={
            "revision_label": "Tighter fit",
            "revision_notes": "Reduced clearance",
            "is_recommended": "true",
        },
    )

    assert resp.status_code == 200, resp.text
    gcode_files = [f for f in resp.json()["files"] if f["file_type"] == "gcode"]
    assert [f["gcode_revision_number"] for f in gcode_files] == [1, 2]
    latest = gcode_files[-1]
    assert latest["revision_label"] == "Tighter fit"
    assert latest["revision_status"] == "needs_test"
    assert latest["revision_notes"] == "Reduced clearance"
    assert latest["is_recommended"] is True
    db_session.refresh(first)
    assert first.is_recommended is False


def test_add_gcode_revision_accepts_payload_over_nginx_default_limit(
    tmp_path: Path,
    client: TestClient,
    auth_headers: dict[str, str],
    db_session: Session,
) -> None:
    _configure_storage(tmp_path)
    model = _model(db_session)

    resp = client.post(
        f"/api/v1/models/{model.id}/gcode-revisions",
        headers=auth_headers,
        files={
            "file": (
                "large-revision.gcode",
                _large_gcode(),
                "text/plain",
            )
        },
        data={"revision_label": "Large revision"},
    )

    assert resp.status_code == 200, resp.text
    gcode_files = [f for f in resp.json()["files"] if f["file_type"] == "gcode"]
    assert len(gcode_files) == 1
    assert gcode_files[0]["size_bytes"] > 1_000_000
    assert gcode_files[0]["revision_label"] == "Large revision"


def test_first_gcode_revision_is_auto_recommended(
    tmp_path: Path,
    client: TestClient,
    auth_headers: dict[str, str],
    db_session: Session,
) -> None:
    _configure_storage(tmp_path)
    model = _model(db_session)

    resp = client.post(
        f"/api/v1/models/{model.id}/gcode-revisions",
        headers=auth_headers,
        files={
            "file": ("first.gcode", b"; generated by OrcaSlicer\nG28\n", "text/plain")
        },
        data={"is_recommended": "false"},
    )

    assert resp.status_code == 200, resp.text
    gcode_files = [f for f in resp.json()["files"] if f["file_type"] == "gcode"]
    assert len(gcode_files) == 1
    assert gcode_files[0]["is_recommended"] is True


def test_second_unmarked_gcode_revision_keeps_existing_recommended(
    tmp_path: Path,
    client: TestClient,
    auth_headers: dict[str, str],
    db_session: Session,
) -> None:
    _configure_storage(tmp_path)
    model = _model(db_session)
    first = _file(db_session, model, version=1)
    first.is_recommended = True
    db_session.add(first)
    db_session.commit()

    resp = client.post(
        f"/api/v1/models/{model.id}/gcode-revisions",
        headers=auth_headers,
        files={
            "file": ("second.gcode", b"; generated by OrcaSlicer\nG28\n", "text/plain")
        },
        data={"is_recommended": "false"},
    )

    assert resp.status_code == 200, resp.text
    files = {f["id"]: f for f in resp.json()["files"]}
    assert files[first.id]["is_recommended"] is True
    recommended = [f for f in files.values() if f["is_recommended"]]
    assert len(recommended) == 1


def test_add_gcode_revision_rejects_non_gcode(
    tmp_path: Path,
    client: TestClient,
    auth_headers: dict[str, str],
    db_session: Session,
) -> None:
    _configure_storage(tmp_path)
    model = _model(db_session)

    resp = client.post(
        f"/api/v1/models/{model.id}/gcode-revisions",
        headers=auth_headers,
        files={"file": ("part.stl", b"solid part\nendsolid part\n", "application/sla")},
    )

    assert resp.status_code == 400
    assert resp.json()["detail"] == "unsupported_file_type"


def test_update_revision_can_clear_status_notes_and_recommended(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    file_row = _file(db_session, model)
    file_row.revision_status = "known_good"
    file_row.revision_notes = "Old note"
    file_row.is_recommended = True
    db_session.add(file_row)
    db_session.commit()

    resp = client.patch(
        f"/api/v1/models/{model.id}/files/{file_row.id}/revision",
        json={
            "revision_label": "PETG baseline",
            "revision_status": None,
            "revision_notes": "   ",
            "is_recommended": False,
        },
        headers=auth_headers,
    )

    assert resp.status_code == 200
    revision = resp.json()["files"][0]
    assert revision["revision_label"] == "PETG baseline"
    assert revision["revision_status"] is None
    assert revision["revision_notes"] is None
    assert revision["is_recommended"] is False


def test_update_revision_requires_auth(client: TestClient, db_session: Session) -> None:
    model = _model(db_session)
    file_row = _file(db_session, model)

    resp = client.patch(
        f"/api/v1/models/{model.id}/files/{file_row.id}/revision",
        json={"revision_status": "failed"},
    )

    assert resp.status_code == 401


def test_delete_revision_soft_deletes_and_hides_it(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    keep = _file(db_session, model, version=1, sha="a")
    drop = _file(db_session, model, version=2, sha="b")
    drop.is_recommended = True
    db_session.add(drop)
    db_session.commit()

    resp = client.delete(
        f"/api/v1/models/{model.id}/files/{drop.id}/revision",
        headers=auth_headers,
    )

    assert resp.status_code == 200
    file_ids = [f["id"] for f in resp.json()["files"]]
    assert file_ids == [keep.id]

    db_session.refresh(drop)
    assert drop.deleted_at is not None
    assert drop.is_recommended is False


def test_delete_recommended_revision_promotes_newest_remaining(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    """Invariant: a model with G-code always keeps exactly one recommended
    revision. Deleting the recommended one must promote the newest survivor —
    not leave the model with G-code and nothing recommended."""
    model = _model(db_session)
    _oldest = _file(db_session, model, version=1, sha="a")
    middle = _file(db_session, model, version=2, sha="b")
    newest = _file(db_session, model, version=3, sha="c")
    middle.is_recommended = True
    db_session.add(middle)
    db_session.commit()

    resp = client.delete(
        f"/api/v1/models/{model.id}/files/{middle.id}/revision",
        headers=auth_headers,
    )
    assert resp.status_code == 200

    files = {f["id"]: f for f in resp.json()["files"]}
    recommended = [fid for fid, f in files.items() if f["is_recommended"]]
    assert recommended == [newest.id], "newest live revision should be promoted"
    # Exactly one recommended, and it is a live file.
    assert len(recommended) == 1


def test_delete_only_recommended_revision_leaves_none_recommended(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    """Deleting the sole G-code revision is allowed and simply leaves the model
    with no recommended revision (no G-code remains to carry the marker)."""
    model = _model(db_session)
    only = _file(db_session, model, version=1, sha="a")
    only.is_recommended = True
    db_session.add(only)
    db_session.commit()

    resp = client.delete(
        f"/api/v1/models/{model.id}/files/{only.id}/revision",
        headers=auth_headers,
    )
    assert resp.status_code == 200
    assert resp.json()["files"] == []
    db_session.refresh(only)
    assert only.deleted_at is not None
    assert only.is_recommended is False


def test_delete_revision_rejects_non_gcode(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    mesh = _file(db_session, model, file_type=FileType.STL)

    resp = client.delete(
        f"/api/v1/models/{model.id}/files/{mesh.id}/revision",
        headers=auth_headers,
    )

    assert resp.status_code == 400
    assert resp.json()["detail"] == "revision_not_supported"


def test_delete_revision_requires_auth(client: TestClient, db_session: Session) -> None:
    model = _model(db_session)
    file_row = _file(db_session, model)

    resp = client.delete(f"/api/v1/models/{model.id}/files/{file_row.id}/revision")

    assert resp.status_code == 401


def test_manual_print_job_accepts_adhoc_printer_name(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    file_row = _file(db_session, model)

    resp = client.post(
        f"/api/v1/models/{model.id}/print-jobs",
        json={
            "printer_name": "Garage Prusa",
            "file_id": file_row.id,
            "state": "completed",
        },
        headers=auth_headers,
    )

    assert resp.status_code == 200
    body = resp.json()
    assert body["printer_id"] is None
    assert body["printer_name"] == "Garage Prusa"

    listed = client.get(
        f"/api/v1/models/{model.id}/print-jobs", headers=auth_headers
    ).json()
    assert listed[0]["printer_name"] == "Garage Prusa"


def test_manual_print_job_requires_a_printer(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    file_row = _file(db_session, model)

    resp = client.post(
        f"/api/v1/models/{model.id}/print-jobs",
        json={"file_id": file_row.id, "printer_name": "   "},
        headers=auth_headers,
    )

    assert resp.status_code == 422
    assert resp.json()["detail"]["code"] == "printer_required"


def test_update_revision_rejects_invalid_status(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    file_row = _file(db_session, model)

    resp = client.patch(
        f"/api/v1/models/{model.id}/files/{file_row.id}/revision",
        json={"revision_status": "perfect_enough"},
        headers=auth_headers,
    )

    assert resp.status_code == 422


def test_update_revision_rejects_non_gcode(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    file_row = _file(db_session, model, file_type=FileType.STL)

    resp = client.patch(
        f"/api/v1/models/{model.id}/files/{file_row.id}/revision",
        json={"revision_status": "known_good"},
        headers=auth_headers,
    )

    assert resp.status_code == 400
    assert resp.json()["detail"] == "revision_not_supported"


def test_update_revision_rejects_soft_deleted_file(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    file_row = _file(db_session, model)
    file_row.deleted_at = utcnow()
    db_session.add(file_row)
    db_session.commit()

    resp = client.patch(
        f"/api/v1/models/{model.id}/files/{file_row.id}/revision",
        json={"revision_status": "failed"},
        headers=auth_headers,
    )

    assert resp.status_code == 404
    assert resp.json()["detail"] == "file_not_found"


def test_recommended_revision_is_unique_per_model(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    first = _file(db_session, model, version=1, sha="a")
    second = _file(db_session, model, version=2, sha="b")

    resp1 = client.patch(
        f"/api/v1/models/{model.id}/files/{first.id}/revision",
        json={"is_recommended": True},
        headers=auth_headers,
    )
    assert resp1.status_code == 200

    resp2 = client.patch(
        f"/api/v1/models/{model.id}/files/{second.id}/revision",
        json={"is_recommended": True},
        headers=auth_headers,
    )
    assert resp2.status_code == 200

    files = {f["id"]: f for f in resp2.json()["files"]}
    assert files[first.id]["is_recommended"] is False
    assert files[second.id]["is_recommended"] is True


def test_recommended_revision_does_not_clear_other_models(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    first_model = _model(db_session, slug="one")
    second_model = _model(db_session, slug="two")
    first_file = _file(db_session, first_model, version=1, sha="a")
    second_file = _file(db_session, second_model, version=1, sha="b")
    first_file.is_recommended = True
    db_session.add(first_file)
    db_session.commit()

    resp = client.patch(
        f"/api/v1/models/{second_model.id}/files/{second_file.id}/revision",
        json={"is_recommended": True},
        headers=auth_headers,
    )

    assert resp.status_code == 200
    db_session.refresh(first_file)
    db_session.refresh(second_file)
    assert first_file.is_recommended is True
    assert second_file.is_recommended is True


def test_revision_file_must_belong_to_model(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    first_model = _model(db_session, slug="one")
    second_model = _model(db_session, slug="two")
    file_row = _file(db_session, second_model)

    resp = client.patch(
        f"/api/v1/models/{first_model.id}/files/{file_row.id}/revision",
        json={"revision_status": "failed"},
        headers=auth_headers,
    )

    assert resp.status_code == 404
    assert resp.json()["detail"] == "file_not_found"


def _regular_user(session: Session, username: str = "regular") -> User:
    user = User(
        username=username,
        hashed_password=hash_password("Password123"),
        is_active=True,
        is_superuser=False,
    )
    session.add(user)
    session.commit()
    session.refresh(user)
    return user


def _headers_for(user: User) -> dict[str, str]:
    scope = "admin" if user.is_superuser else "write"
    token = create_access_token(user.id, user.username, scope=scope)
    return {"Authorization": f"Bearer {token}"}


def test_get_model_returns_detail(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    resp = client.get(f"/api/v1/models/{model.id}", headers=auth_headers)
    assert resp.status_code == 200
    assert resp.json()["id"] == model.id


def test_get_model_unknown_id_returns_404(
    client: TestClient, auth_headers: dict[str, str]
) -> None:
    resp = client.get("/api/v1/models/999999", headers=auth_headers)
    assert resp.status_code == 404
    assert resp.json()["detail"] == "model_not_found"


def test_list_models_requires_superuser_for_printer_filters(
    client: TestClient, db_session: Session
) -> None:
    user = _regular_user(db_session)
    resp = client.get("/api/v1/models?printer_presence=any", headers=_headers_for(user))
    assert resp.status_code == 403
    assert resp.json()["detail"] == "admin_required"


def test_star_and_unstar_model(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    starred = client.put(f"/api/v1/models/{model.id}/star", headers=auth_headers)
    assert starred.status_code == 200
    assert starred.json() == {"model_id": model.id, "starred": True}
    # Idempotent — starring twice does not error or duplicate the row.
    again = client.put(f"/api/v1/models/{model.id}/star", headers=auth_headers)
    assert again.status_code == 200

    unstarred = client.delete(f"/api/v1/models/{model.id}/star", headers=auth_headers)
    assert unstarred.status_code == 200
    assert unstarred.json() == {"model_id": model.id, "starred": False}


def test_artifact_outcomes_missing_file_returns_404(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    real = _file(db_session, model, file_type=FileType.STL, sha="e")
    resp = client.get(
        f"/api/v1/models/{model.id}/artifact-outcomes?file_id={real.id}&file_id=999999",
        headers=auth_headers,
    )
    assert resp.status_code == 404
    assert resp.json()["detail"] == "file_not_found"


def test_add_gcode_revision_rejects_missing_filename(
    tmp_path: Path,
    client: TestClient,
    auth_headers: dict[str, str],
    db_session: Session,
) -> None:
    _configure_storage(tmp_path)
    model = _model(db_session)
    boundary = "revisionboundary"
    body = (
        f"--{boundary}\r\n"
        'Content-Disposition: form-data; name="file"; filename=""\r\n'
        "Content-Type: text/plain\r\n\r\n"
        "hi\r\n"
        f"--{boundary}--\r\n"
    ).encode()
    resp = client.post(
        f"/api/v1/models/{model.id}/gcode-revisions",
        content=body,
        headers={
            **auth_headers,
            "content-type": f"multipart/form-data; boundary={boundary}",
        },
    )
    assert resp.status_code == 400
    assert resp.json()["detail"] == "filename_required"


def test_delete_file_revision_rejects_mismatched_model(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    first_model = _model(db_session, slug="one")
    second_model = _model(db_session, slug="two")
    file_row = _file(db_session, second_model)

    resp = client.delete(
        f"/api/v1/models/{first_model.id}/files/{file_row.id}/revision",
        headers=auth_headers,
    )
    assert resp.status_code == 404
    assert resp.json()["detail"] == "file_not_found"


def test_import_print_jobs_from_printer_requires_moonraker_url(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    printer = Printer(name="No URL")
    db_session.add(printer)
    db_session.commit()
    db_session.refresh(printer)

    resp = client.post(
        f"/api/v1/models/{model.id}/print-jobs/import-printer/{printer.id}",
        headers=auth_headers,
    )
    assert resp.status_code == 400
    assert resp.json()["detail"]["code"] == "printer_no_url"


def test_import_print_jobs_from_printer_unknown_printer_404(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    resp = client.post(
        f"/api/v1/models/{model.id}/print-jobs/import-printer/999999",
        headers=auth_headers,
    )
    assert resp.status_code == 404
    assert resp.json()["detail"]["code"] == "printer_not_found"


def test_import_print_jobs_from_printer_reports_moonraker_error(
    client: TestClient, auth_headers: dict[str, str], db_session: Session, monkeypatch
) -> None:
    model = _model(db_session)
    printer = Printer(name="Ender", moonraker_url="http://10.0.0.1:7125")
    db_session.add(printer)
    db_session.commit()
    db_session.refresh(printer)

    from app.services.moonraker import MoonrakerError

    async def fake_import(*_a, **_k):
        raise MoonrakerError("unreachable")

    monkeypatch.setattr(
        "app.api.v1.models.job_import.import_print_jobs_from_printer", fake_import
    )
    resp = client.post(
        f"/api/v1/models/{model.id}/print-jobs/import-printer/{printer.id}",
        headers=auth_headers,
    )
    assert resp.status_code == 502
    assert resp.json()["detail"]["code"] == "printer_unreachable"


def test_vault_stats_returns_counts(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    _model(db_session)
    resp = client.get("/api/v1/models/stats", headers=auth_headers)
    assert resp.status_code == 200
    assert "model_count" in resp.json() or resp.json() != {}


def test_print_stats_requires_superuser(
    client: TestClient, db_session: Session
) -> None:
    user = _regular_user(db_session)
    resp = client.get("/api/v1/models/stats/prints", headers=_headers_for(user))
    assert resp.status_code == 403


def test_print_stats_returns_window(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    resp = client.get("/api/v1/models/stats/prints?period=7d", headers=auth_headers)
    assert resp.status_code == 200


def test_list_trash_and_purge_expired(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    model.deleted_at = utcnow()
    db_session.add(model)
    db_session.commit()

    trash = client.get("/api/v1/models/trash", headers=auth_headers)
    assert trash.status_code == 200
    assert any(row["id"] == model.id for row in trash.json())

    purged = client.delete("/api/v1/models/trash/expired", headers=auth_headers)
    assert purged.status_code == 200
    assert "purged_count" in purged.json()


def test_update_model_can_move_to_root_as_superuser(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    collection = Collection(name="Brackets", slug="brackets", path="brackets")
    db_session.add(collection)
    db_session.commit()
    db_session.refresh(collection)
    model.collection_id = collection.id
    db_session.add(model)
    db_session.commit()

    resp = client.patch(
        f"/api/v1/models/{model.id}",
        json={"collection": ""},
        headers=auth_headers,
    )
    assert resp.status_code == 200
    assert resp.json()["collection"] is None


def test_update_model_root_move_forbidden_for_non_superuser(
    client: TestClient, db_session: Session
) -> None:
    model = _model(db_session)
    collection = Collection(name="Brackets", slug="brackets", path="brackets")
    db_session.add(collection)
    db_session.commit()
    db_session.refresh(collection)
    model.collection_id = collection.id
    db_session.add(model)
    db_session.commit()
    user = _regular_user(db_session)
    db_session.add(
        CollectionPermission(
            user_id=user.id, collection_id=collection.id, role=CollectionRole.EDIT
        )
    )
    db_session.commit()

    resp = client.patch(
        f"/api/v1/models/{model.id}",
        json={"collection": ""},
        headers=_headers_for(user),
    )
    assert resp.status_code == 403
    assert resp.json()["detail"] == "root_collection_admin_required"


def test_update_model_moves_into_existing_collection(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    collection = Collection(name="Brackets", slug="brackets", path="brackets")
    db_session.add(collection)
    db_session.commit()
    db_session.refresh(collection)

    resp = client.patch(
        f"/api/v1/models/{model.id}",
        json={"collection": "brackets", "name": "Renamed", "description": "desc"},
        headers=auth_headers,
    )
    assert resp.status_code == 200
    body = resp.json()
    assert body["collection_id"] == collection.id
    assert body["name"] == "Renamed"
    assert body["description"] == "desc"


def test_update_model_creates_missing_collection_as_superuser(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    resp = client.patch(
        f"/api/v1/models/{model.id}",
        json={"collection": "brand/new/path"},
        headers=auth_headers,
    )
    assert resp.status_code == 200
    assert resp.json()["collection"] == "brand/new/path"


def test_update_model_denies_missing_collection_for_non_superuser(
    client: TestClient, db_session: Session
) -> None:
    model = _model(db_session)
    collection = Collection(name="Brackets", slug="brackets", path="brackets")
    db_session.add(collection)
    db_session.commit()
    db_session.refresh(collection)
    model.collection_id = collection.id
    db_session.add(model)
    db_session.commit()
    user = _regular_user(db_session)
    db_session.add(
        CollectionPermission(
            user_id=user.id, collection_id=collection.id, role=CollectionRole.EDIT
        )
    )
    db_session.commit()

    resp = client.patch(
        f"/api/v1/models/{model.id}",
        json={"collection": "does/not/exist"},
        headers=_headers_for(user),
    )
    assert resp.status_code == 403
    assert resp.json()["detail"] == "collection_permission_denied"


def test_update_model_replaces_tags(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    resp = client.patch(
        f"/api/v1/models/{model.id}",
        json={"tags": ["functional", "bracket"]},
        headers=auth_headers,
    )
    assert resp.status_code == 200
    assert set(resp.json()["tags"]) == {"functional", "bracket"}

    cleared = client.patch(
        f"/api/v1/models/{model.id}",
        json={"tags": []},
        headers=auth_headers,
    )
    assert cleared.status_code == 200
    assert cleared.json()["tags"] == []


def test_delete_model_soft_deletes(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    resp = client.delete(f"/api/v1/models/{model.id}", headers=auth_headers)
    assert resp.status_code == 204
    db_session.refresh(model)
    assert model.deleted_at is not None


def test_restore_model_and_purge_model(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    model.deleted_at = utcnow()
    db_session.add(model)
    db_session.commit()

    restored = client.post(f"/api/v1/models/{model.id}/restore", headers=auth_headers)
    assert restored.status_code == 200
    db_session.refresh(model)
    assert model.deleted_at is None

    model.deleted_at = utcnow()
    db_session.add(model)
    db_session.commit()
    purged = client.delete(f"/api/v1/models/{model.id}/purge", headers=auth_headers)
    assert purged.status_code == 200
    assert purged.json()["purged_model_ids"] == [model.id]


def test_restore_model_unknown_id_404(
    client: TestClient, auth_headers: dict[str, str]
) -> None:
    resp = client.post("/api/v1/models/999999/restore", headers=auth_headers)
    assert resp.status_code == 404
    assert resp.json()["detail"] == "model_not_found"


def test_purge_model_unknown_id_404(
    client: TestClient, auth_headers: dict[str, str]
) -> None:
    resp = client.delete("/api/v1/models/999999/purge", headers=auth_headers)
    assert resp.status_code == 404
    assert resp.json()["detail"] == "model_not_found"


def test_purge_model_not_in_trash_rejected(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    resp = client.delete(f"/api/v1/models/{model.id}/purge", headers=auth_headers)
    assert resp.status_code == 400
    assert resp.json()["detail"] == "model_not_in_trash"


# --------------------------------------------------------------------------- #
# Batch operations.
# --------------------------------------------------------------------------- #
def test_batch_move_models_to_new_collection(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    a = _model(db_session, slug="batch-a")
    b = _model(db_session, slug="batch-b")

    resp = client.post(
        "/api/v1/models/batch/move",
        json={"model_ids": [a.id, b.id], "collection": "new/spot"},
        headers=auth_headers,
    )
    assert resp.status_code == 200
    body = resp.json()
    assert set(body["succeeded_ids"]) == {a.id, b.id}
    assert body["failed_count"] == 0


def test_batch_move_models_root_requires_superuser(
    client: TestClient, db_session: Session
) -> None:
    user = _regular_user(db_session)
    model = _model(db_session)
    resp = client.post(
        "/api/v1/models/batch/move",
        json={"model_ids": [model.id], "collection": ""},
        headers=_headers_for(user),
    )
    assert resp.status_code == 403
    assert resp.json()["detail"] == "root_collection_admin_required"


def test_batch_move_models_reports_missing_model(
    client: TestClient, auth_headers: dict[str, str]
) -> None:
    resp = client.post(
        "/api/v1/models/batch/move",
        json={"model_ids": [999999], "collection": "somewhere"},
        headers=auth_headers,
    )
    assert resp.status_code == 404


def test_batch_tag_models_adds_and_removes(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    a = _model(db_session, slug="tag-a")
    b = _model(db_session, slug="tag-b")

    added = client.post(
        "/api/v1/models/batch/tags",
        json={"model_ids": [a.id, b.id], "add": ["shiny"], "remove": []},
        headers=auth_headers,
    )
    assert added.status_code == 200
    assert added.json()["succeeded_count"] == 2

    removed = client.post(
        "/api/v1/models/batch/tags",
        json={"model_ids": [a.id], "add": [], "remove": ["shiny"]},
        headers=auth_headers,
    )
    assert removed.status_code == 200
    detail = client.get(f"/api/v1/models/{a.id}", headers=auth_headers).json()
    assert detail["tags"] == []


def test_batch_set_revision_labels(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    file_row = _file(db_session, model)

    resp = client.patch(
        "/api/v1/models/batch/revision-labels",
        json={"file_ids": [file_row.id], "revision_label": "Batch label"},
        headers=auth_headers,
    )
    assert resp.status_code == 200
    assert resp.json()["succeeded_ids"] == [file_row.id]
    db_session.refresh(file_row)
    assert file_row.revision_label == "Batch label"


def test_batch_set_revision_labels_rejects_non_gcode(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    mesh = _file(db_session, model, file_type=FileType.STL)

    resp = client.patch(
        "/api/v1/models/batch/revision-labels",
        json={"file_ids": [mesh.id], "revision_label": "x"},
        headers=auth_headers,
    )
    assert resp.status_code == 400
    assert resp.json()["detail"] == "revision_not_supported"


def test_batch_set_revision_labels_unknown_file_404(
    client: TestClient, auth_headers: dict[str, str]
) -> None:
    resp = client.patch(
        "/api/v1/models/batch/revision-labels",
        json={"file_ids": [999999], "revision_label": "x"},
        headers=auth_headers,
    )
    assert resp.status_code == 404
    assert resp.json()["detail"] == "file_not_found"


def test_batch_delete_models(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    resp = client.post(
        "/api/v1/models/batch/delete",
        json={"model_ids": [model.id]},
        headers=auth_headers,
    )
    assert resp.status_code == 200
    assert resp.json()["succeeded_ids"] == [model.id]
    db_session.refresh(model)
    assert model.deleted_at is not None


# --------------------------------------------------------------------------- #
# Library archive export / import.
# --------------------------------------------------------------------------- #
def test_library_archive_export_and_import_round_trip(
    tmp_path: Path,
    client: TestClient,
    auth_headers: dict[str, str],
    db_session: Session,
) -> None:
    _configure_storage(tmp_path)
    # Real ingest so the exported artifact has an actual on-disk blob (the
    # archive writer stats + reads every file from storage).
    uploaded = client.post(
        "/api/v1/ingest/model",
        headers=auth_headers,
        files={"file": ("cube.stl", b"solid cube\nendsolid cube\n", "application/sla")},
        data={"model_name": "Archive Me"},
    )
    assert uploaded.status_code == 202, uploaded.text
    job = client.get(
        f"/api/v1/ingest/jobs/{uploaded.json()['job_id']}", headers=auth_headers
    )
    assert job.json()["state"] == "completed", job.json()

    export = client.get("/api/v1/models/library-archive", headers=auth_headers)
    assert export.status_code == 200
    assert export.headers["content-type"] == "application/zip"

    import_resp = client.post(
        "/api/v1/models/library-import",
        headers=auth_headers,
        files={
            "file": ("printstash-library-v1.zip", export.content, "application/zip")
        },
    )
    assert import_resp.status_code == 200
    assert "created_models" in import_resp.json() or import_resp.json() != {}


def test_library_import_rejects_non_zip(
    client: TestClient, auth_headers: dict[str, str]
) -> None:
    resp = client.post(
        "/api/v1/models/library-import",
        headers=auth_headers,
        files={"file": ("archive.tar", b"not a zip", "application/x-tar")},
    )
    assert resp.status_code == 400
    assert resp.json()["detail"] == "archive_zip_required"


def test_library_import_rejects_invalid_archive(
    client: TestClient, auth_headers: dict[str, str]
) -> None:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as bundle:
        bundle.writestr("not-a-manifest.txt", "hello")

    resp = client.post(
        "/api/v1/models/library-import",
        headers=auth_headers,
        files={"file": ("bad.zip", buf.getvalue(), "application/zip")},
    )
    assert resp.status_code == 400


def test_star_unknown_model_returns_404(
    client: TestClient, auth_headers: dict[str, str]
) -> None:
    resp = client.put("/api/v1/models/999999/star", headers=auth_headers)
    assert resp.status_code == 404
    assert resp.json()["detail"] == "model_not_found"


def test_add_gcode_revision_cleans_up_staged_file_on_error(
    tmp_path: Path,
    client: TestClient,
    auth_headers: dict[str, str],
    db_session: Session,
    monkeypatch,
) -> None:
    _configure_storage(tmp_path)
    model = _model(db_session)
    staged_paths: list[Path] = []

    def fake_add_gcode_revision_to_model(**kwargs):
        staged_paths.append(kwargs["staged_path"])
        raise RuntimeError("boom")

    monkeypatch.setattr(
        "app.api.v1.models.add_gcode_revision_to_model",
        fake_add_gcode_revision_to_model,
    )

    with pytest.raises(RuntimeError, match="boom"):
        client.post(
            f"/api/v1/models/{model.id}/gcode-revisions",
            headers=auth_headers,
            files={"file": ("rev.gcode", b"G28\n", "text/plain")},
        )
    assert staged_paths and not staged_paths[0].exists()


def test_manual_print_job_unknown_file_404(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    resp = client.post(
        f"/api/v1/models/{model.id}/print-jobs",
        json={"file_id": 999999, "printer_name": "Bench"},
        headers=auth_headers,
    )
    assert resp.status_code == 404
    assert resp.json()["detail"]["code"] == "file_not_found"


def test_manual_print_job_unknown_printer_id_404(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    file_row = _file(db_session, model)
    resp = client.post(
        f"/api/v1/models/{model.id}/print-jobs",
        json={"file_id": file_row.id, "printer_id": 999999},
        headers=auth_headers,
    )
    assert resp.status_code == 404
    assert resp.json()["detail"]["code"] == "printer_not_found"


def test_manual_print_job_with_registered_printer(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    file_row = _file(db_session, model)
    printer = Printer(name="Ender", moonraker_url="http://10.0.0.1:7125")
    db_session.add(printer)
    db_session.commit()
    db_session.refresh(printer)

    resp = client.post(
        f"/api/v1/models/{model.id}/print-jobs",
        json={"file_id": file_row.id, "printer_id": printer.id},
        headers=auth_headers,
    )
    assert resp.status_code == 200
    assert resp.json()["printer_id"] == printer.id
    assert resp.json()["printer_name"] == "Ender"


def test_manual_print_job_invalid_state_falls_back_to_completed(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    file_row = _file(db_session, model)
    resp = client.post(
        f"/api/v1/models/{model.id}/print-jobs",
        json={
            "file_id": file_row.id,
            "printer_name": "Bench",
            "state": "not_a_real_state",
        },
        headers=auth_headers,
    )
    assert resp.status_code == 200
    assert resp.json()["state"] == "completed"


def test_batch_move_root_model_denied_for_non_superuser(
    client: TestClient, db_session: Session
) -> None:
    model = _model(db_session)  # root model, no collection
    dest = Collection(name="Dest", slug="dest", path="dest")
    db_session.add(dest)
    db_session.commit()
    db_session.refresh(dest)
    user = _regular_user(db_session)
    db_session.add(
        CollectionPermission(
            user_id=user.id, collection_id=dest.id, role=CollectionRole.EDIT
        )
    )
    db_session.commit()

    resp = client.post(
        "/api/v1/models/batch/move",
        json={"model_ids": [model.id], "collection": "dest"},
        headers=_headers_for(user),
    )
    assert resp.status_code == 403
    assert resp.json()["detail"] == "root_collection_admin_required"


def test_batch_move_unknown_destination_denied_for_non_superuser(
    client: TestClient, db_session: Session
) -> None:
    user = _regular_user(db_session)
    model = _model(db_session)
    resp = client.post(
        "/api/v1/models/batch/move",
        json={"model_ids": [model.id], "collection": "does/not/exist"},
        headers=_headers_for(user),
    )
    assert resp.status_code == 403
    assert resp.json()["detail"] == "collection_permission_denied"


def test_batch_move_to_root_as_superuser(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    collection = Collection(name="Brackets", slug="brackets", path="brackets")
    db_session.add(collection)
    db_session.commit()
    db_session.refresh(collection)
    model.collection_id = collection.id
    db_session.add(model)
    db_session.commit()

    resp = client.post(
        "/api/v1/models/batch/move",
        json={"model_ids": [model.id], "collection": ""},
        headers=auth_headers,
    )
    assert resp.status_code == 200
    db_session.refresh(model)
    assert model.collection_id is None


def test_batch_move_into_existing_destination_checks_role(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    collection = Collection(name="Brackets", slug="brackets", path="brackets")
    db_session.add(collection)
    db_session.commit()
    db_session.refresh(collection)

    resp = client.post(
        "/api/v1/models/batch/move",
        json={"model_ids": [model.id], "collection": "brackets"},
        headers=auth_headers,
    )
    assert resp.status_code == 200
    db_session.refresh(model)
    assert model.collection_id == collection.id


def test_batch_move_denies_model_in_uneditable_source_collection(
    client: TestClient, db_session: Session
) -> None:
    source = Collection(name="Source", slug="source", path="source")
    dest = Collection(name="Dest", slug="dest", path="dest")
    db_session.add(source)
    db_session.add(dest)
    db_session.commit()
    db_session.refresh(source)
    db_session.refresh(dest)
    model = _model(db_session, slug="stuck")
    model.collection_id = source.id
    db_session.add(model)
    db_session.commit()

    user = _regular_user(db_session)
    db_session.add(
        CollectionPermission(
            user_id=user.id, collection_id=dest.id, role=CollectionRole.EDIT
        )
    )
    db_session.commit()

    resp = client.post(
        "/api/v1/models/batch/move",
        json={"model_ids": [model.id], "collection": "dest"},
        headers=_headers_for(user),
    )
    assert resp.status_code == 403
    assert resp.json()["detail"] == "collection_permission_denied"


def test_batch_tag_models_skips_blank_remove_entries(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    resp = client.post(
        "/api/v1/models/batch/tags",
        json={"model_ids": [model.id], "add": [], "remove": ["   "]},
        headers=auth_headers,
    )
    assert resp.status_code == 200
    assert resp.json()["succeeded_count"] == 1


def test_batch_set_revision_labels_reports_unexpected_error(
    client: TestClient, auth_headers: dict[str, str], db_session: Session, monkeypatch
) -> None:
    model = _model(db_session)
    file_row = _file(db_session, model)

    def fake_set_revision_labels(*_a, **_k):
        raise RuntimeError("boom")

    monkeypatch.setattr(
        "app.api.v1.models.model_views.set_revision_labels", fake_set_revision_labels
    )
    with pytest.raises(RuntimeError, match="boom"):
        client.patch(
            "/api/v1/models/batch/revision-labels",
            json={"file_ids": [file_row.id], "revision_label": "x"},
            headers=auth_headers,
        )


def test_update_model_clears_source_url(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    model.source_url = "https://example.com/original"
    db_session.add(model)
    db_session.commit()

    resp = client.patch(
        f"/api/v1/models/{model.id}",
        json={"source_url": None},
        headers=auth_headers,
    )
    assert resp.status_code == 200
    assert resp.json()["source_url"] is None


def test_delete_file_revision_clears_stale_thumbnail_pointer(
    client: TestClient, auth_headers: dict[str, str], db_session: Session
) -> None:
    model = _model(db_session)
    file_row = _file(db_session, model)
    model.thumbnail_file_id = file_row.id
    model.thumbnail_path = "thumbs/stale.webp"
    db_session.add(model)
    db_session.commit()

    resp = client.delete(
        f"/api/v1/models/{model.id}/files/{file_row.id}/revision",
        headers=auth_headers,
    )
    assert resp.status_code == 200
    db_session.refresh(model)
    assert model.thumbnail_file_id is None
    assert model.thumbnail_path is None
