from __future__ import annotations

import io
import struct
from datetime import timedelta
from pathlib import Path
from typing import Any, Callable

from fastapi.testclient import TestClient
from sqlmodel import Session, select

from app.core.config import _overlay
from app.core.time import utcnow
from app.db.models import (
    BackgroundJob,
    Collection,
    CollectionPermission,
    CollectionRole,
    FilamentProfile,
    File,
    FileType,
    InboxItem,
    InboxItemState,
    Metadata,
    Model,
    PrinterProfile,
    User,
)
from app.services import ingestion as ingestion_service
from app.services.auth import create_access_token, hash_password
from app.services.jobs import registry
from app.services.storage_backend import (
    ObjectIdentity,
    StorageCapabilities,
    get_backend,
)
from app.services.storage_ownership import record_creation

PNG_MAGIC = b"\x89PNG\r\n\x1a\n"
WEBP_MAGIC = b"RIFF"


def _cube_stl() -> bytes:
    return b"""solid cube
facet normal 0 0 -1
outer loop
vertex 0 0 0
vertex 1 1 0
vertex 1 0 0
endloop
endfacet
facet normal 0 0 -1
outer loop
vertex 0 0 0
vertex 0 1 0
vertex 1 1 0
endloop
endfacet
facet normal 0 0 1
outer loop
vertex 0 0 1
vertex 1 0 1
vertex 1 1 1
endloop
endfacet
facet normal 0 0 1
outer loop
vertex 0 0 1
vertex 1 1 1
vertex 0 1 1
endloop
endfacet
facet normal 0 -1 0
outer loop
vertex 0 0 0
vertex 1 0 0
vertex 1 0 1
endloop
endfacet
facet normal 0 -1 0
outer loop
vertex 0 0 0
vertex 1 0 1
vertex 0 0 1
endloop
endfacet
facet normal 1 0 0
outer loop
vertex 1 0 0
vertex 1 1 0
vertex 1 1 1
endloop
endfacet
facet normal 1 0 0
outer loop
vertex 1 0 0
vertex 1 1 1
vertex 1 0 1
endloop
endfacet
facet normal 0 1 0
outer loop
vertex 1 1 0
vertex 0 1 0
vertex 0 1 1
endloop
endfacet
facet normal 0 1 0
outer loop
vertex 1 1 0
vertex 0 1 1
vertex 1 1 1
endloop
endfacet
facet normal -1 0 0
outer loop
vertex 0 1 0
vertex 0 0 0
vertex 0 0 1
endloop
endfacet
facet normal -1 0 0
outer loop
vertex 0 1 0
vertex 0 0 1
vertex 0 1 1
endloop
endfacet
endsolid cube
"""


def _large_gcode(min_bytes: int = 1_200_000) -> bytes:
    payload = b"; generated by OrcaSlicer\nG90\nG1 X1 Y1 E1\n"
    payload += b"; padding to exceed nginx default body limit\n" * (min_bytes // 45)
    return payload


def _large_cube_stl(min_bytes: int = 1_200_000) -> bytes:
    lines = _cube_stl().splitlines()
    body = b"\n".join(lines[1:-1]) + b"\n"
    repeat_count = min_bytes // len(body) + 1
    return b"solid large-cube\n" + body * repeat_count + b"endsolid large-cube\n"


def _over_cap_binary_stl(n_triangles: int = 1_001) -> bytes:
    output = io.BytesIO()
    output.write(b"issue-67".ljust(80, b"\x00"))
    output.write(struct.pack("<I", n_triangles))
    record = struct.Struct("<12fH")
    for index in range(n_triangles):
        x = float(index % 100)
        y = float((index // 100) % 100)
        output.write(
            record.pack(
                0,
                0,
                1,
                x,
                y,
                0,
                x + 0.8,
                y,
                0,
                x,
                y + 0.8,
                0,
                0,
            )
        )
    return output.getvalue()


def _configure_storage(tmp_path: Path) -> None:
    _overlay["data_dir"] = tmp_path / "files"
    _overlay["thumb_dir"] = tmp_path / "thumbs"
    _overlay["staging_dir"] = tmp_path / "staging"


def _completed_job(client: TestClient, response) -> dict:
    assert response.status_code == 202, response.text
    job_id = response.json()["job_id"]
    headers = {}
    auth = response.request.headers.get("authorization")
    if auth:
        headers["Authorization"] = auth
    job = client.get(f"/api/v1/ingest/jobs/{job_id}", headers=headers)
    assert job.status_code == 200, job.text
    payload = job.json()
    assert payload["state"] == "completed", payload
    assert payload["model_id"] is not None
    assert payload["file_id"] is not None
    return payload


def _assert_file_created(session: Session, file_id: int, file_type: FileType) -> File:
    file_row = session.get(File, file_id)
    assert file_row is not None
    assert file_row.file_type == file_type
    assert file_row.size_bytes > 0
    assert get_backend().exists(file_row.path)
    metadata = session.exec(select(Metadata).where(Metadata.file_id == file_id)).one()
    assert metadata.file_id == file_id
    model = session.get(Model, file_row.model_id)
    assert model is not None
    assert model.thumbnail_file_id == file_id
    assert model.thumbnail_path
    assert get_backend().exists(model.thumbnail_path)
    return file_row


def test_ingest_orca_gcode_creates_db_blob_and_thumbnail(
    tmp_path: Path,
    client: TestClient,
    db_session: Session,
    auth_headers: dict[str, str],
) -> None:
    _configure_storage(tmp_path)
    gcode = (Path(__file__).parent / "fixtures" / "sample.gcode").read_bytes()

    payload = _completed_job(
        client,
        client.post(
            "/api/v1/ingest/orca",
            headers=auth_headers,
            files={"file": ("sample.gcode", gcode, "text/plain")},
            data={"model_name": "Sample G-code"},
        ),
    )
    file_id = payload["file_id"]
    _assert_file_created(db_session, file_id, FileType.GCODE)

    download = client.get(f"/api/v1/files/{file_id}/download", headers=auth_headers)
    assert download.status_code == 200, download.text
    assert b"; generated by OrcaSlicer" in download.content

    thumbnail = client.get(f"/api/v1/files/{file_id}/thumbnail", headers=auth_headers)
    assert thumbnail.status_code == 200, thumbnail.text
    assert thumbnail.headers["content-type"] == "image/webp"
    assert thumbnail.content.startswith(WEBP_MAGIC)

    filament_profile = db_session.exec(
        select(FilamentProfile).where(FilamentProfile.name == "Generic PLA")
    ).one()
    assert filament_profile.material_type == "PLA"
    assert filament_profile.cost_per_kg == 28

    printer_profile = db_session.exec(
        select(PrinterProfile).where(PrinterProfile.name == "Ender-3 V3 SE")
    ).one()
    assert printer_profile.slicer_name == "OrcaSlicer"
    assert printer_profile.nozzle_diameter_mm == 0.4


def test_ingest_orca_accepts_payload_over_nginx_default_limit(
    tmp_path: Path,
    client: TestClient,
    db_session: Session,
    auth_headers: dict[str, str],
) -> None:
    _configure_storage(tmp_path)

    payload = _completed_job(
        client,
        client.post(
            "/api/v1/ingest/orca",
            headers=auth_headers,
            files={"file": ("large.gcode", _large_gcode(), "text/plain")},
            data={"model_name": "Large G-code"},
        ),
    )

    file_row = db_session.get(File, payload["file_id"])
    assert file_row is not None
    assert file_row.file_type == FileType.GCODE
    assert file_row.size_bytes > 1_000_000
    assert get_backend().exists(file_row.path)
    metadata = db_session.exec(
        select(Metadata).where(Metadata.file_id == file_row.id)
    ).one()
    assert metadata.file_id == file_row.id


def test_ingest_orca_stages_upload_in_threadpool(
    tmp_path: Path,
    client: TestClient,
    auth_headers: dict[str, str],
    monkeypatch,
) -> None:
    _configure_storage(tmp_path)
    called: dict[str, str] = {}

    async def fake_threadpool(
        func: Callable[..., Any], *args: Any, **kwargs: Any
    ) -> Any:
        called["func"] = func.__name__
        return func(*args, **kwargs)

    monkeypatch.setattr("app.api.v1.ingest.run_in_threadpool", fake_threadpool)

    response = client.post(
        "/api/v1/ingest/orca",
        headers=auth_headers,
        files={"file": ("sample.gcode", b"G28\n", "text/plain")},
        data={"model_name": "Threadpool Check"},
    )

    assert response.status_code == 202
    assert called == {"func": "_stage_upload"}


def test_ingest_stl_creates_db_blob_and_thumbnail(
    tmp_path: Path,
    client: TestClient,
    db_session: Session,
    auth_headers: dict[str, str],
) -> None:
    _configure_storage(tmp_path)

    payload = _completed_job(
        client,
        client.post(
            "/api/v1/ingest/model",
            headers=auth_headers,
            files={"file": ("cube.stl", _cube_stl(), "application/sla")},
            data={"model_name": "Cube"},
        ),
    )
    file_id = payload["file_id"]
    _assert_file_created(db_session, file_id, FileType.STL)

    download = client.get(f"/api/v1/files/{file_id}/download", headers=auth_headers)
    assert download.status_code == 200, download.text
    assert b"solid cube" in download.content

    thumbnail = client.get(f"/api/v1/files/{file_id}/thumbnail", headers=auth_headers)
    assert thumbnail.status_code == 200, thumbnail.text
    assert thumbnail.headers["content-type"] == "image/webp"
    assert thumbnail.content.startswith(WEBP_MAGIC)


def test_ingest_publishes_terminal_only_after_fresh_durability_check(
    tmp_path: Path,
    client: TestClient,
    auth_headers: dict[str, str],
    monkeypatch,
) -> None:
    _configure_storage(tmp_path)
    checkpoints: list[str] = []
    observed_job_ids: list[str] = []
    original_verify = ingestion_service.verify_durable_artifact

    def observe_checkpoint(stage: str, current_job_id: str) -> None:
        if stage == "after_commit":
            observed_job_ids.append(current_job_id)

    def observed_verify(*args, **kwargs) -> None:
        status = ingestion_service.registry.get(observed_job_ids[-1])
        assert status is not None
        assert status.state == "running"
        assert status.progress is None or status.progress < 100
        assert status.committed_at is not None
        checkpoints.append("fresh_session_and_storage")
        original_verify(*args, **kwargs)

    monkeypatch.setattr(
        ingestion_service, "_fault_injection_checkpoint", observe_checkpoint
    )
    monkeypatch.setattr(ingestion_service, "verify_durable_artifact", observed_verify)
    response = client.post(
        "/api/v1/ingest/model",
        headers=auth_headers,
        files={"file": ("durable.stl", _cube_stl(), "application/sla")},
        data={"model_name": "Durable Cube"},
    )
    assert response.status_code == 202
    job_id = response.json()["job_id"]

    status = client.get(f"/api/v1/ingest/jobs/{job_id}", headers=auth_headers).json()
    assert checkpoints == ["fresh_session_and_storage"]
    assert status["state"] == "completed"
    assert status["completion"] == "complete"
    assert status["thumbnail_status"] == "generated"
    assert status["committed_at"] is not None


def test_exception_after_commit_is_a_durable_partial_result(
    tmp_path: Path,
    client: TestClient,
    db_session: Session,
    auth_headers: dict[str, str],
    monkeypatch,
) -> None:
    _configure_storage(tmp_path)

    def inject(stage: str, _job_id: str) -> None:
        if stage == "after_commit":
            raise RuntimeError("injected_after_commit")

    monkeypatch.setattr(ingestion_service, "_fault_injection_checkpoint", inject)
    response = client.post(
        "/api/v1/ingest/model",
        headers=auth_headers,
        files={"file": ("post-commit.stl", _cube_stl(), "application/sla")},
        data={"model_name": "Post Commit Cube"},
    )
    assert response.status_code == 202
    job_id = response.json()["job_id"]
    status = client.get(f"/api/v1/ingest/jobs/{job_id}", headers=auth_headers).json()

    assert status["state"] == "completed"
    assert status["completion"] == "partial"
    assert status["thumbnail_reason"] == "post_commit_exception"
    assert status["retryable"] is True
    assert db_session.get(Model, status["model_id"]) is not None
    assert db_session.get(File, status["file_id"]) is not None


def test_ingest_model_accepts_payload_over_nginx_default_limit(
    tmp_path: Path,
    client: TestClient,
    db_session: Session,
    auth_headers: dict[str, str],
    monkeypatch,
) -> None:
    _configure_storage(tmp_path)
    monkeypatch.setattr(
        "app.services.mesh_processing.analyze_mesh",
        lambda _path, report=None: ({"bbox_x_mm": 1.0}, None),
    )

    payload = _completed_job(
        client,
        client.post(
            "/api/v1/ingest/model",
            headers=auth_headers,
            files={"file": ("large-cube.stl", _large_cube_stl(), "application/sla")},
            data={"model_name": "Large Cube"},
        ),
    )

    file_row = db_session.get(File, payload["file_id"])
    assert file_row is not None
    assert file_row.file_type == FileType.STL
    assert file_row.size_bytes > 1_000_000
    assert get_backend().exists(file_row.path)
    metadata = db_session.exec(
        select(Metadata).where(Metadata.file_id == file_row.id)
    ).one()
    assert metadata.bbox_x_mm == 1.0


def test_issue_67_over_cap_stl_persists_authenticated_webp_fallback(
    tmp_path: Path,
    client: TestClient,
    auth_headers: dict[str, str],
    monkeypatch,
) -> None:
    _configure_storage(tmp_path)
    monkeypatch.setitem(_overlay, "mesh_max_render_triangles", 1_000)

    payload = _completed_job(
        client,
        client.post(
            "/api/v1/ingest/model",
            headers=auth_headers,
            files={
                "file": (
                    "issue-67-over-limit.stl",
                    _over_cap_binary_stl(),
                    "application/sla",
                )
            },
            data={"model_name": "Issue 67 Fallback"},
        ),
    )

    assert payload["completion"] == "complete"
    assert payload["thumbnail_status"] == "fallback_generated"
    thumbnail = client.get(
        f"/api/v1/files/{payload['file_id']}/thumbnail", headers=auth_headers
    )
    assert thumbnail.status_code == 200
    assert thumbnail.headers["content-type"] == "image/webp"
    assert thumbnail.content.startswith(WEBP_MAGIC)


def test_issue_67_upload_survives_pruning_completed_inbox_job(
    tmp_path: Path,
    client: TestClient,
    db_session: Session,
    auth_headers: dict[str, str],
    monkeypatch,
) -> None:
    """A stale terminal inbox link must not turn the next upload into a 500."""
    _configure_storage(tmp_path)
    owner = db_session.exec(select(User).where(User.username == "test-writer")).one()
    old_job = BackgroundJob(
        id="expired-inbox-job",
        owner_user_id=owner.id,
        state="completed",
        status_json='{"state":"completed"}',
        finished_at=utcnow() - timedelta(hours=2),
    )
    db_session.add(old_job)
    db_session.flush()
    db_session.add(
        InboxItem(
            owner_user_id=owner.id,
            state=InboxItemState.COMPLETED,
            background_job_id=old_job.id,
        )
    )
    db_session.commit()
    monkeypatch.setattr(registry, "_last_persisted_prune_at", float("-inf"))

    response = client.post(
        "/api/v1/ingest/model",
        headers=auth_headers,
        files={"file": ("issue-67.stl", _cube_stl(), "application/sla")},
        data={"model_name": "Issue 67 Upload"},
    )

    assert response.status_code == 202, response.text


def test_reuploading_deleted_model_restores_it(
    tmp_path: Path,
    client: TestClient,
    db_session: Session,
    auth_headers: dict[str, str],
) -> None:
    _configure_storage(tmp_path)

    first = _completed_job(
        client,
        client.post(
            "/api/v1/ingest/model",
            headers=auth_headers,
            files={"file": ("cube.stl", _cube_stl(), "application/sla")},
            data={"model_name": "Cube"},
        ),
    )
    model_id = first["model_id"]

    delete = client.delete(f"/api/v1/models/{model_id}", headers=auth_headers)
    assert delete.status_code == 204
    assert (
        client.get(f"/api/v1/models/{model_id}", headers=auth_headers).status_code
        == 404
    )

    second = _completed_job(
        client,
        client.post(
            "/api/v1/ingest/model",
            headers=auth_headers,
            files={"file": ("cube.stl", _cube_stl(), "application/sla")},
            data={"model_name": "Cube"},
        ),
    )

    assert second["model_id"] == model_id
    model = db_session.get(Model, model_id)
    assert model is not None
    assert model.deleted_at is None
    detail = client.get(f"/api/v1/models/{model_id}", headers=auth_headers)
    assert detail.status_code == 200, detail.text
    assert len(detail.json()["files"]) == 2


def test_trash_can_restore_and_purge_model(
    tmp_path: Path,
    client: TestClient,
    db_session: Session,
    auth_headers: dict[str, str],
) -> None:
    _configure_storage(tmp_path)

    payload = _completed_job(
        client,
        client.post(
            "/api/v1/ingest/model",
            headers=auth_headers,
            files={"file": ("cube.stl", _cube_stl(), "application/sla")},
            data={"model_name": "Cube"},
        ),
    )
    model_id = payload["model_id"]
    file_row = db_session.get(File, payload["file_id"])
    assert file_row is not None
    blob_path = file_row.path
    thumb_path = get_backend().thumbnail_key(file_row.id)

    delete = client.delete(f"/api/v1/models/{model_id}", headers=auth_headers)
    assert delete.status_code == 204

    trash = client.get("/api/v1/models/trash", headers=auth_headers)
    assert trash.status_code == 200, trash.text
    assert trash.json()[0]["id"] == model_id
    assert trash.json()[0]["file_count"] == 1
    assert trash.json()[0]["expires_at"] is not None

    restored = client.post(f"/api/v1/models/{model_id}/restore", headers=auth_headers)
    assert restored.status_code == 200, restored.text
    assert restored.json()["id"] == model_id
    assert client.get("/api/v1/models/trash", headers=auth_headers).json() == []

    delete = client.delete(f"/api/v1/models/{model_id}", headers=auth_headers)
    assert delete.status_code == 204
    purged = client.delete(f"/api/v1/models/{model_id}/purge", headers=auth_headers)
    assert purged.status_code == 200, purged.text
    assert purged.json() == {
        "purged_model_ids": [model_id],
        "purged_count": 1,
        "storage_completed": 2,
        "storage_pending": 0,
        "storage_blocked": 0,
        "resources_blocked": 0,
    }
    db_session.expire_all()
    assert db_session.get(Model, model_id) is None
    assert db_session.get(File, payload["file_id"]) is None
    assert not get_backend().exists(blob_path)
    assert not get_backend().exists(thumb_path)


def test_non_verified_purge_requires_one_shot_confirmation(
    tmp_path: Path,
    client: TestClient,
    db_session: Session,
    auth_headers: dict[str, str],
    monkeypatch,
) -> None:
    _configure_storage(tmp_path)
    payload = _completed_job(
        client,
        client.post(
            "/api/v1/ingest/model",
            headers=auth_headers,
            files={"file": ("risk.stl", _cube_stl(), "application/sla")},
            data={"model_name": "Risk confirmation"},
        ),
    )
    model_id = payload["model_id"]
    assert client.delete(
        f"/api/v1/models/{model_id}", headers=auth_headers
    ).status_code == 204
    backend = get_backend()
    monkeypatch.setattr(
        backend,
        "_capabilities",
        StorageCapabilities(
            conditional_create=True,
            object_identity=ObjectIdentity.ETAG,
            verified_delete=False,
            conditional_replace=False,
            namespace_ownership=True,
            direct_path=False,
        ),
    )

    refused = client.delete(
        f"/api/v1/models/{model_id}/purge", headers=auth_headers
    )
    assert refused.status_code == 409
    assert refused.json()["detail"] == {
        "code": "storage_risk_confirmation_required",
        "tier": "guarded",
        "operation": "purge_model",
        "required_confirmation": "confirm_storage_risk=true",
    }
    assert db_session.get(Model, model_id) is not None

    confirmed = client.delete(
        f"/api/v1/models/{model_id}/purge?confirm_storage_risk=true",
        headers=auth_headers,
    )
    assert confirmed.status_code == 200, confirmed.text


def test_purge_expired_trash_uses_retention_setting(
    tmp_path: Path,
    client: TestClient,
    db_session: Session,
    auth_headers: dict[str, str],
) -> None:
    _configure_storage(tmp_path)
    _overlay["trash_retention_days"] = 30
    old_model = Model(
        name="Old Cube",
        slug="old-cube",
        hash="old-cube".ljust(64, "0"),
        deleted_at=utcnow() - timedelta(days=31),
    )
    fresh_model = Model(
        name="Fresh Cube",
        slug="fresh-cube",
        hash="fresh-cube".ljust(64, "0"),
        deleted_at=utcnow() - timedelta(days=3),
    )
    db_session.add(old_model)
    db_session.add(fresh_model)
    db_session.commit()
    db_session.refresh(old_model)
    db_session.refresh(fresh_model)

    old_file = File(
        model_id=old_model.id,
        path=str(tmp_path / "files" / "old-cube.stl"),
        original_filename="old-cube.stl",
        file_type=FileType.STL,
        version=1,
        size_bytes=4,
        sha256="a" * 64,
    )
    fresh_file = File(
        model_id=fresh_model.id,
        path=str(tmp_path / "files" / "fresh-cube.stl"),
        original_filename="fresh-cube.stl",
        file_type=FileType.STL,
        version=1,
        size_bytes=4,
        sha256="b" * 64,
    )
    db_session.add(old_file)
    db_session.add(fresh_file)
    db_session.commit()
    old_model_id = old_model.id
    fresh_model_id = fresh_model.id
    old_file_path = old_file.path
    fresh_file_path = fresh_file.path
    backend = get_backend()
    record_creation(
        db_session,
        backend.create_bytes(b"old", old_file.path),
        object_kind="artifact",
    )
    record_creation(
        db_session,
        backend.create_bytes(b"new", fresh_file.path),
        object_kind="artifact",
    )
    db_session.commit()

    purged = client.delete("/api/v1/models/trash/expired", headers=auth_headers)

    assert purged.status_code == 200, purged.text
    assert purged.json() == {
        "purged_model_ids": [old_model_id],
        "purged_count": 1,
        "storage_completed": 1,
        "storage_pending": 0,
        "storage_blocked": 0,
        "resources_blocked": 0,
    }
    db_session.expire_all()
    assert db_session.get(Model, old_model_id) is None
    assert db_session.get(Model, fresh_model_id) is not None
    assert not Path(old_file_path).exists()
    assert Path(fresh_file_path).exists()


def test_force_rebuild_refreshes_existing_mesh_thumbnail(
    tmp_path: Path,
    client: TestClient,
    auth_headers: dict[str, str],
    monkeypatch,
) -> None:
    from PIL import Image

    _configure_storage(tmp_path)

    payload = _completed_job(
        client,
        client.post(
            "/api/v1/ingest/model",
            headers=auth_headers,
            files={"file": ("cube.stl", _cube_stl(), "application/sla")},
            data={"model_name": "Cube"},
        ),
    )
    file_id = payload["file_id"]
    model_id = payload["model_id"]
    replacement_buffer = io.BytesIO()
    Image.new("RGB", (12, 10), (220, 30, 20)).save(replacement_buffer, format="PNG")
    replacement = replacement_buffer.getvalue()

    monkeypatch.setattr(
        "app.services.mesh_processing.render_thumbnail",
        lambda _path: replacement,
    )

    response = client.post(
        "/api/v1/files/thumbnails/rebuild?force=true",
        headers=auth_headers,
    )

    assert response.status_code == 202, response.text
    job_id = response.json()["job_id"]
    job = client.get(f"/api/v1/ingest/jobs/{job_id}", headers=auth_headers)
    assert job.status_code == 200, job.text
    payload = job.json()
    assert payload["state"] == "completed", payload
    assert payload["completion"] == "complete"
    assert payload["thumbnail_status"] == "generated"
    assert payload["succeeded"] == 1
    assert payload["result"]["rebuilt"] == [model_id]

    thumbnail = client.get(f"/api/v1/files/{file_id}/thumbnail", headers=auth_headers)
    assert thumbnail.status_code == 200, thumbnail.text
    assert thumbnail.content.startswith(WEBP_MAGIC)
    with Image.open(io.BytesIO(thumbnail.content)) as refreshed:
        assert refreshed.convert("RGB").getpixel((0, 0)) == (220, 30, 20)


# --------------------------------------------------------------------------- #
# Validation / error paths (filename, file type, collection permission,
# target library) shared by the orca and mesh upload endpoints.
# --------------------------------------------------------------------------- #
def _regular_user(session: Session, username: str = "regular") -> User:
    user = User(
        username=username,
        hashed_password=hash_password("Password123"),
        is_active=True,
        is_superuser=False,
    )
    session.add(user)
    session.commit()
    session.refresh(user)
    return user


def _headers_for(user: User) -> dict[str, str]:
    scope = "admin" if user.is_superuser else "write"
    token = create_access_token(user.id, user.username, scope=scope)
    return {"Authorization": f"Bearer {token}"}


def _post_empty_filename_multipart(
    client: TestClient, url: str, headers: dict[str, str]
) -> Any:
    """Post a multipart body whose file part has an explicit empty filename.

    ``httpx``'s ``files=`` helper drops the ``filename`` attribute entirely
    when given an empty string (turning the part into a plain form field, not
    an ``UploadFile``), so the empty-filename branch can only be reached by
    building the multipart body by hand.
    """
    boundary = "ingesttestboundary"
    body = (
        f"--{boundary}\r\n"
        'Content-Disposition: form-data; name="file"; filename=""\r\n'
        "Content-Type: text/plain\r\n\r\n"
        "hi\r\n"
        f"--{boundary}--\r\n"
    ).encode()
    return client.post(
        url,
        content=body,
        headers={
            **headers,
            "content-type": f"multipart/form-data; boundary={boundary}",
        },
    )


def test_ingest_orca_rejects_missing_filename(
    client: TestClient, auth_headers: dict[str, str]
) -> None:
    response = _post_empty_filename_multipart(
        client, "/api/v1/ingest/orca", auth_headers
    )
    assert response.status_code == 400, response.text
    assert response.json()["detail"] == "filename_required"


def test_ingest_orca_rejects_unsupported_suffix(
    client: TestClient, auth_headers: dict[str, str]
) -> None:
    response = client.post(
        "/api/v1/ingest/orca",
        headers=auth_headers,
        files={"file": ("notes.txt", b"hello", "text/plain")},
    )
    assert response.status_code == 400, response.text
    assert response.json()["detail"] == "unsupported_file_type"


def test_ingest_model_rejects_missing_filename(
    client: TestClient, auth_headers: dict[str, str]
) -> None:
    response = _post_empty_filename_multipart(
        client, "/api/v1/ingest/model", auth_headers
    )
    assert response.status_code == 400, response.text
    assert response.json()["detail"] == "filename_required"


def test_ingest_model_rejects_unsupported_suffix(
    client: TestClient, auth_headers: dict[str, str]
) -> None:
    response = client.post(
        "/api/v1/ingest/model",
        headers=auth_headers,
        files={"file": ("notes.txt", b"hello", "text/plain")},
    )
    assert response.status_code == 400, response.text
    assert response.json()["detail"] == "unsupported_file_type"


def test_ingest_model_requires_collection_for_non_superuser(
    tmp_path: Path, client: TestClient, db_session: Session
) -> None:
    _configure_storage(tmp_path)
    user = _regular_user(db_session)
    response = client.post(
        "/api/v1/ingest/model",
        headers=_headers_for(user),
        files={"file": ("cube.stl", _cube_stl(), "application/sla")},
    )
    assert response.status_code == 403, response.text
    assert response.json()["detail"] == "collection_required"


def test_ingest_model_unknown_collection_denied_for_non_superuser(
    tmp_path: Path, client: TestClient, db_session: Session
) -> None:
    _configure_storage(tmp_path)
    user = _regular_user(db_session)
    response = client.post(
        "/api/v1/ingest/model",
        headers=_headers_for(user),
        files={"file": ("cube.stl", _cube_stl(), "application/sla")},
        data={"collection": "does-not-exist"},
    )
    assert response.status_code == 403, response.text
    assert response.json()["detail"] == "collection_permission_denied"


def test_ingest_model_requires_role_on_existing_collection(
    tmp_path: Path, client: TestClient, db_session: Session
) -> None:
    _configure_storage(tmp_path)
    user = _regular_user(db_session)
    collection = Collection(name="Brackets", slug="brackets", path="brackets")
    db_session.add(collection)
    db_session.commit()
    db_session.refresh(collection)

    response = client.post(
        "/api/v1/ingest/model",
        headers=_headers_for(user),
        files={"file": ("cube.stl", _cube_stl(), "application/sla")},
        data={"collection": "brackets"},
    )
    assert response.status_code == 403, response.text


def test_ingest_model_succeeds_with_granted_collection_role(
    tmp_path: Path, client: TestClient, db_session: Session
) -> None:
    _configure_storage(tmp_path)
    user = _regular_user(db_session)
    collection = Collection(name="Brackets", slug="brackets", path="brackets")
    db_session.add(collection)
    db_session.commit()
    db_session.refresh(collection)
    db_session.add(
        CollectionPermission(
            user_id=user.id, collection_id=collection.id, role=CollectionRole.EDIT
        )
    )
    db_session.commit()

    payload = _completed_job(
        client,
        client.post(
            "/api/v1/ingest/model",
            headers=_headers_for(user),
            files={"file": ("cube.stl", _cube_stl(), "application/sla")},
            data={"collection": "brackets"},
        ),
    )
    assert payload["model_id"] is not None


def test_ingest_model_rejects_disabled_target_library(
    tmp_path: Path, client: TestClient, auth_headers: dict[str, str]
) -> None:
    _configure_storage(tmp_path)
    response = client.post(
        "/api/v1/ingest/model",
        headers=auth_headers,
        files={"file": ("cube.stl", _cube_stl(), "application/sla")},
        data={"target_library_id": "999"},
    )
    assert response.status_code == 400, response.text
    assert response.json()["detail"] == "external_libraries_disabled"


def test_ingest_jobs_list_and_get_scoped_to_owner(
    tmp_path: Path,
    client: TestClient,
    db_session: Session,
    auth_headers: dict[str, str],
) -> None:
    _configure_storage(tmp_path)
    payload = _completed_job(
        client,
        client.post(
            "/api/v1/ingest/model",
            headers=auth_headers,
            files={"file": ("cube.stl", _cube_stl(), "application/sla")},
            data={"model_name": "Cube"},
        ),
    )
    jobs = client.get("/api/v1/ingest/jobs", headers=auth_headers)
    assert jobs.status_code == 200, jobs.text
    assert any(j["model_id"] == payload["model_id"] for j in jobs.json())

    other = _regular_user(db_session, "other-owner")
    forbidden = client.get(
        f"/api/v1/ingest/jobs/{jobs.json()[0]['job_id']}", headers=_headers_for(other)
    )
    assert forbidden.status_code == 404, forbidden.text


def test_get_job_unknown_id_returns_404(
    client: TestClient, auth_headers: dict[str, str]
) -> None:
    response = client.get("/api/v1/ingest/jobs/does-not-exist", headers=auth_headers)
    assert response.status_code == 404, response.text
    assert response.json()["detail"] == "job_not_found"
