/* Representative backend catalogue for configuration form contracts. */
import type { StorageProvider } from "@/types";

export const storageProviderCatalogue: StorageProvider[] = [
  {
    id: "local",
    label: "This machine",
    category: "this_machine",
    description: "Local filesystem directories.",
    expected_tier: "verified",
    expected_tier_note: "Verified on local filesystems with working hardlinks.",
    consequences: [],
    documentation_url: "/docs/storage-providers.md#local",
    available: true,
    selectable: true,
    support_level: "stable",
    disabled_reason: null,
    fields: [
      {
        name: "root",
        label: "Root",
        help: "Dedicated folder or prefix",
        input_type: "path",
        required: true,
        secret: false,
        default: "vault-data",
        options: [],
      },
      {
        name: "data_dir",
        label: "Models directory",
        help: "Directory for model files",
        input_type: "path",
        required: true,
        secret: false,
        default: null,
        options: [],
      },
      {
        name: "thumb_dir",
        label: "Thumbnail directory",
        help: "Directory for generated images",
        input_type: "path",
        required: true,
        secret: false,
        default: null,
        options: [],
      },
    ],
    fields_by_use: {
      vault: [
        {
          name: "root",
          label: "Root",
          help: "Dedicated folder or prefix",
          input_type: "path",
          required: true,
          secret: false,
          default: "vault-data",
          options: [],
        },
        {
          name: "data_dir",
          label: "Models directory",
          help: "Directory for model files",
          input_type: "path",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "thumb_dir",
          label: "Thumbnail directory",
          help: "Directory for generated images",
          input_type: "path",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
      ],
      library: [
        {
          name: "root",
          label: "Base folder",
          help: "Dedicated folder or prefix",
          input_type: "path",
          required: true,
          secret: false,
          default: "PrintStash",
          options: [],
        },
        {
          name: "data_dir",
          label: "Models directory",
          help: "Directory for model files",
          input_type: "path",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "thumb_dir",
          label: "Thumbnail directory",
          help: "Directory for generated images",
          input_type: "path",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
      ],
      backup: [
        {
          name: "root",
          label: "Base folder",
          help: "Dedicated folder or prefix",
          input_type: "path",
          required: true,
          secret: false,
          default: "PrintStash",
          options: [],
        },
        {
          name: "data_dir",
          label: "Models directory",
          help: "Directory for model files",
          input_type: "path",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "thumb_dir",
          label: "Thumbnail directory",
          help: "Directory for generated images",
          input_type: "path",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
      ],
    },
    requirements: [],
    transport: "local",
    uses: {
      vault: {
        dependency_installed: true,
        service_compiled: true,
        supported: true,
        available: true,
        endpoint_proven: false,
        reason: "storage_endpoint_probe_required",
      },
      library: {
        dependency_installed: true,
        service_compiled: true,
        supported: true,
        available: true,
        endpoint_proven: false,
        reason: "storage_endpoint_probe_required",
      },
      backup: {
        dependency_installed: true,
        service_compiled: true,
        supported: true,
        available: true,
        endpoint_proven: false,
        reason: "storage_endpoint_probe_required",
      },
    },
  },
  {
    id: "s3",
    label: "Amazon S3 or compatible",
    category: "s3_compatible",
    description: "Native S3-compatible object storage.",
    expected_tier: "guarded",
    expected_tier_note: "Verified when bucket versioning is enabled; otherwise Guarded.",
    consequences: ["Automated purge requires a Verified probe."],
    documentation_url: "/docs/storage-providers.md#s3",
    available: true,
    selectable: true,
    support_level: "stable",
    disabled_reason: null,
    fields: [
      {
        name: "root",
        label: "Root",
        help: "Dedicated folder or prefix",
        input_type: "path",
        required: true,
        secret: false,
        default: "vault-data",
        options: [],
      },
      {
        name: "bucket",
        label: "Bucket",
        help: "Existing bucket name",
        input_type: "text",
        required: true,
        secret: false,
        default: null,
        options: [],
      },
      {
        name: "region",
        label: "Region",
        help: "Provider region; required for Backblaze B2 and Wasabi",
        input_type: "text",
        required: false,
        secret: false,
        default: "auto",
        options: [],
      },
      {
        name: "addressing_style",
        label: "Addressing style",
        help: "Auto uses the provider preset",
        input_type: "text",
        required: false,
        secret: false,
        default: "auto",
        options: ["auto", "path", "virtual"],
      },
      {
        name: "endpoint_url",
        label: "Endpoint",
        help: "S3-compatible server URL",
        input_type: "url",
        required: false,
        secret: false,
        default: "",
        options: [],
      },
      {
        name: "access_key",
        label: "Access key",
        help: "Object-storage access key",
        input_type: "password",
        required: true,
        secret: true,
        default: null,
        options: [],
      },
      {
        name: "secret_key",
        label: "Secret key",
        help: "Object-storage secret key",
        input_type: "password",
        required: true,
        secret: true,
        default: null,
        options: [],
      },
    ],
    fields_by_use: {
      vault: [
        {
          name: "root",
          label: "Root",
          help: "Dedicated folder or prefix",
          input_type: "path",
          required: true,
          secret: false,
          default: "vault-data",
          options: [],
        },
        {
          name: "bucket",
          label: "Bucket",
          help: "Existing bucket name",
          input_type: "text",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "region",
          label: "Region",
          help: "Provider region; required for Backblaze B2 and Wasabi",
          input_type: "text",
          required: false,
          secret: false,
          default: "auto",
          options: [],
        },
        {
          name: "addressing_style",
          label: "Addressing style",
          help: "Auto uses the provider preset",
          input_type: "text",
          required: false,
          secret: false,
          default: "auto",
          options: ["auto", "path", "virtual"],
        },
        {
          name: "endpoint_url",
          label: "Endpoint",
          help: "S3-compatible server URL",
          input_type: "url",
          required: false,
          secret: false,
          default: "",
          options: [],
        },
        {
          name: "access_key",
          label: "Access key",
          help: "Object-storage access key",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
        {
          name: "secret_key",
          label: "Secret key",
          help: "Object-storage secret key",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
      ],
      library: [
        {
          name: "root",
          label: "Base folder",
          help: "Dedicated folder or prefix",
          input_type: "path",
          required: true,
          secret: false,
          default: "PrintStash",
          options: [],
        },
        {
          name: "bucket",
          label: "Bucket",
          help: "Existing bucket name",
          input_type: "text",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "region",
          label: "Region",
          help: "Provider region; required for Backblaze B2 and Wasabi",
          input_type: "text",
          required: false,
          secret: false,
          default: "auto",
          options: [],
        },
        {
          name: "addressing_style",
          label: "Addressing style",
          help: "Auto uses the provider preset",
          input_type: "text",
          required: false,
          secret: false,
          default: "auto",
          options: ["auto", "path", "virtual"],
        },
        {
          name: "endpoint_url",
          label: "Endpoint",
          help: "S3-compatible server URL",
          input_type: "url",
          required: false,
          secret: false,
          default: "",
          options: [],
        },
        {
          name: "access_key",
          label: "Access key",
          help: "Object-storage access key",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
        {
          name: "secret_key",
          label: "Secret key",
          help: "Object-storage secret key",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
      ],
      backup: [
        {
          name: "root",
          label: "Base folder",
          help: "Dedicated folder or prefix",
          input_type: "path",
          required: true,
          secret: false,
          default: "PrintStash",
          options: [],
        },
        {
          name: "bucket",
          label: "Bucket",
          help: "Existing bucket name",
          input_type: "text",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "region",
          label: "Region",
          help: "Provider region; required for Backblaze B2 and Wasabi",
          input_type: "text",
          required: false,
          secret: false,
          default: "auto",
          options: [],
        },
        {
          name: "addressing_style",
          label: "Addressing style",
          help: "Auto uses the provider preset",
          input_type: "text",
          required: false,
          secret: false,
          default: "auto",
          options: ["auto", "path", "virtual"],
        },
        {
          name: "endpoint_url",
          label: "Endpoint",
          help: "S3-compatible server URL",
          input_type: "url",
          required: false,
          secret: false,
          default: "",
          options: [],
        },
        {
          name: "access_key",
          label: "Access key",
          help: "Object-storage access key",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
        {
          name: "secret_key",
          label: "Secret key",
          help: "Object-storage secret key",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
      ],
    },
    requirements: [],
    transport: "s3",
    uses: {
      vault: {
        dependency_installed: true,
        service_compiled: true,
        supported: true,
        available: true,
        endpoint_proven: false,
        reason: "storage_endpoint_probe_required",
      },
      library: {
        dependency_installed: true,
        service_compiled: true,
        supported: true,
        available: true,
        endpoint_proven: false,
        reason: "storage_endpoint_probe_required",
      },
      backup: {
        dependency_installed: true,
        service_compiled: true,
        supported: true,
        available: true,
        endpoint_proven: false,
        reason: "storage_endpoint_probe_required",
      },
    },
  },
  {
    id: "cloudflare_r2",
    label: "Cloudflare R2",
    category: "s3_compatible",
    description: "Native S3-compatible object storage.",
    expected_tier: "guarded",
    expected_tier_note: "Verified when bucket versioning is enabled; otherwise Guarded.",
    consequences: ["Automated purge requires a Verified probe."],
    documentation_url: "/docs/storage-providers.md#cloudflare_r2",
    available: true,
    selectable: true,
    support_level: "beta",
    disabled_reason: null,
    fields: [
      {
        name: "root",
        label: "Root",
        help: "Dedicated folder or prefix",
        input_type: "path",
        required: true,
        secret: false,
        default: "vault-data",
        options: [],
      },
      {
        name: "bucket",
        label: "Bucket",
        help: "Existing bucket name",
        input_type: "text",
        required: true,
        secret: false,
        default: null,
        options: [],
      },
      {
        name: "region",
        label: "Region",
        help: "Provider region; required for Backblaze B2 and Wasabi",
        input_type: "text",
        required: false,
        secret: false,
        default: "auto",
        options: [],
      },
      {
        name: "addressing_style",
        label: "Addressing style",
        help: "Auto uses the provider preset",
        input_type: "text",
        required: false,
        secret: false,
        default: "auto",
        options: ["auto", "path", "virtual"],
      },
      {
        name: "account_id",
        label: "Account ID",
        help: "Cloudflare account ID",
        input_type: "text",
        required: true,
        secret: false,
        default: "",
        options: [],
      },
      {
        name: "access_key",
        label: "Access key",
        help: "Object-storage access key",
        input_type: "password",
        required: true,
        secret: true,
        default: null,
        options: [],
      },
      {
        name: "secret_key",
        label: "Secret key",
        help: "Object-storage secret key",
        input_type: "password",
        required: true,
        secret: true,
        default: null,
        options: [],
      },
    ],
    fields_by_use: {
      vault: [
        {
          name: "root",
          label: "Root",
          help: "Dedicated folder or prefix",
          input_type: "path",
          required: true,
          secret: false,
          default: "vault-data",
          options: [],
        },
        {
          name: "bucket",
          label: "Bucket",
          help: "Existing bucket name",
          input_type: "text",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "region",
          label: "Region",
          help: "Provider region; required for Backblaze B2 and Wasabi",
          input_type: "text",
          required: false,
          secret: false,
          default: "auto",
          options: [],
        },
        {
          name: "addressing_style",
          label: "Addressing style",
          help: "Auto uses the provider preset",
          input_type: "text",
          required: false,
          secret: false,
          default: "auto",
          options: ["auto", "path", "virtual"],
        },
        {
          name: "account_id",
          label: "Account ID",
          help: "Cloudflare account ID",
          input_type: "text",
          required: true,
          secret: false,
          default: "",
          options: [],
        },
        {
          name: "access_key",
          label: "Access key",
          help: "Object-storage access key",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
        {
          name: "secret_key",
          label: "Secret key",
          help: "Object-storage secret key",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
      ],
      library: [
        {
          name: "root",
          label: "Base folder",
          help: "Dedicated folder or prefix",
          input_type: "path",
          required: true,
          secret: false,
          default: "PrintStash",
          options: [],
        },
        {
          name: "bucket",
          label: "Bucket",
          help: "Existing bucket name",
          input_type: "text",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "region",
          label: "Region",
          help: "Provider region; required for Backblaze B2 and Wasabi",
          input_type: "text",
          required: false,
          secret: false,
          default: "auto",
          options: [],
        },
        {
          name: "addressing_style",
          label: "Addressing style",
          help: "Auto uses the provider preset",
          input_type: "text",
          required: false,
          secret: false,
          default: "auto",
          options: ["auto", "path", "virtual"],
        },
        {
          name: "account_id",
          label: "Account ID",
          help: "Cloudflare account ID",
          input_type: "text",
          required: true,
          secret: false,
          default: "",
          options: [],
        },
        {
          name: "access_key",
          label: "Access key",
          help: "Object-storage access key",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
        {
          name: "secret_key",
          label: "Secret key",
          help: "Object-storage secret key",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
      ],
      backup: [
        {
          name: "root",
          label: "Base folder",
          help: "Dedicated folder or prefix",
          input_type: "path",
          required: true,
          secret: false,
          default: "PrintStash",
          options: [],
        },
        {
          name: "bucket",
          label: "Bucket",
          help: "Existing bucket name",
          input_type: "text",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "region",
          label: "Region",
          help: "Provider region; required for Backblaze B2 and Wasabi",
          input_type: "text",
          required: false,
          secret: false,
          default: "auto",
          options: [],
        },
        {
          name: "addressing_style",
          label: "Addressing style",
          help: "Auto uses the provider preset",
          input_type: "text",
          required: false,
          secret: false,
          default: "auto",
          options: ["auto", "path", "virtual"],
        },
        {
          name: "account_id",
          label: "Account ID",
          help: "Cloudflare account ID",
          input_type: "text",
          required: true,
          secret: false,
          default: "",
          options: [],
        },
        {
          name: "access_key",
          label: "Access key",
          help: "Object-storage access key",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
        {
          name: "secret_key",
          label: "Secret key",
          help: "Object-storage secret key",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
      ],
    },
    requirements: [],
    transport: "s3",
    uses: {
      vault: {
        dependency_installed: true,
        service_compiled: true,
        supported: true,
        available: true,
        endpoint_proven: false,
        reason: "storage_endpoint_probe_required",
      },
      library: {
        dependency_installed: true,
        service_compiled: true,
        supported: true,
        available: true,
        endpoint_proven: false,
        reason: "storage_endpoint_probe_required",
      },
      backup: {
        dependency_installed: true,
        service_compiled: true,
        supported: true,
        available: true,
        endpoint_proven: false,
        reason: "storage_endpoint_probe_required",
      },
    },
  },
  {
    id: "backblaze_b2",
    label: "Backblaze B2",
    category: "s3_compatible",
    description: "Native S3-compatible object storage.",
    expected_tier: "guarded",
    expected_tier_note: "Verified when bucket versioning is enabled; otherwise Guarded.",
    consequences: ["Automated purge requires a Verified probe."],
    documentation_url: "/docs/storage-providers.md#backblaze_b2",
    available: true,
    selectable: true,
    support_level: "beta",
    disabled_reason: null,
    fields: [
      {
        name: "root",
        label: "Root",
        help: "Dedicated folder or prefix",
        input_type: "path",
        required: true,
        secret: false,
        default: "vault-data",
        options: [],
      },
      {
        name: "bucket",
        label: "Bucket",
        help: "Existing bucket name",
        input_type: "text",
        required: true,
        secret: false,
        default: null,
        options: [],
      },
      {
        name: "region",
        label: "Region",
        help: "Provider region; required for Backblaze B2 and Wasabi",
        input_type: "text",
        required: false,
        secret: false,
        default: "auto",
        options: [],
      },
      {
        name: "addressing_style",
        label: "Addressing style",
        help: "Auto uses the provider preset",
        input_type: "text",
        required: false,
        secret: false,
        default: "auto",
        options: ["auto", "path", "virtual"],
      },
      {
        name: "access_key",
        label: "Access key",
        help: "Object-storage access key",
        input_type: "password",
        required: true,
        secret: true,
        default: null,
        options: [],
      },
      {
        name: "secret_key",
        label: "Secret key",
        help: "Object-storage secret key",
        input_type: "password",
        required: true,
        secret: true,
        default: null,
        options: [],
      },
    ],
    fields_by_use: {
      vault: [
        {
          name: "root",
          label: "Root",
          help: "Dedicated folder or prefix",
          input_type: "path",
          required: true,
          secret: false,
          default: "vault-data",
          options: [],
        },
        {
          name: "bucket",
          label: "Bucket",
          help: "Existing bucket name",
          input_type: "text",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "region",
          label: "Region",
          help: "Provider region; required for Backblaze B2 and Wasabi",
          input_type: "text",
          required: false,
          secret: false,
          default: "auto",
          options: [],
        },
        {
          name: "addressing_style",
          label: "Addressing style",
          help: "Auto uses the provider preset",
          input_type: "text",
          required: false,
          secret: false,
          default: "auto",
          options: ["auto", "path", "virtual"],
        },
        {
          name: "access_key",
          label: "Access key",
          help: "Object-storage access key",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
        {
          name: "secret_key",
          label: "Secret key",
          help: "Object-storage secret key",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
      ],
      library: [
        {
          name: "root",
          label: "Base folder",
          help: "Dedicated folder or prefix",
          input_type: "path",
          required: true,
          secret: false,
          default: "PrintStash",
          options: [],
        },
        {
          name: "bucket",
          label: "Bucket",
          help: "Existing bucket name",
          input_type: "text",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "region",
          label: "Region",
          help: "Provider region; required for Backblaze B2 and Wasabi",
          input_type: "text",
          required: false,
          secret: false,
          default: "auto",
          options: [],
        },
        {
          name: "addressing_style",
          label: "Addressing style",
          help: "Auto uses the provider preset",
          input_type: "text",
          required: false,
          secret: false,
          default: "auto",
          options: ["auto", "path", "virtual"],
        },
        {
          name: "access_key",
          label: "Access key",
          help: "Object-storage access key",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
        {
          name: "secret_key",
          label: "Secret key",
          help: "Object-storage secret key",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
      ],
      backup: [
        {
          name: "root",
          label: "Base folder",
          help: "Dedicated folder or prefix",
          input_type: "path",
          required: true,
          secret: false,
          default: "PrintStash",
          options: [],
        },
        {
          name: "bucket",
          label: "Bucket",
          help: "Existing bucket name",
          input_type: "text",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "region",
          label: "Region",
          help: "Provider region; required for Backblaze B2 and Wasabi",
          input_type: "text",
          required: false,
          secret: false,
          default: "auto",
          options: [],
        },
        {
          name: "addressing_style",
          label: "Addressing style",
          help: "Auto uses the provider preset",
          input_type: "text",
          required: false,
          secret: false,
          default: "auto",
          options: ["auto", "path", "virtual"],
        },
        {
          name: "access_key",
          label: "Access key",
          help: "Object-storage access key",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
        {
          name: "secret_key",
          label: "Secret key",
          help: "Object-storage secret key",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
      ],
    },
    requirements: [
      {
        kind: "not_value",
        fields: ["region"],
        value: "auto",
        message: "Enter the provider region.",
      },
    ],
    transport: "s3",
    uses: {
      vault: {
        dependency_installed: true,
        service_compiled: true,
        supported: true,
        available: true,
        endpoint_proven: false,
        reason: "storage_endpoint_probe_required",
      },
      library: {
        dependency_installed: true,
        service_compiled: true,
        supported: true,
        available: true,
        endpoint_proven: false,
        reason: "storage_endpoint_probe_required",
      },
      backup: {
        dependency_installed: true,
        service_compiled: true,
        supported: true,
        available: true,
        endpoint_proven: false,
        reason: "storage_endpoint_probe_required",
      },
    },
  },
  {
    id: "wasabi",
    label: "Wasabi",
    category: "s3_compatible",
    description: "Native S3-compatible object storage.",
    expected_tier: "guarded",
    expected_tier_note: "Verified when bucket versioning is enabled; otherwise Guarded.",
    consequences: ["Automated purge requires a Verified probe."],
    documentation_url: "/docs/storage-providers.md#wasabi",
    available: true,
    selectable: true,
    support_level: "beta",
    disabled_reason: null,
    fields: [
      {
        name: "root",
        label: "Root",
        help: "Dedicated folder or prefix",
        input_type: "path",
        required: true,
        secret: false,
        default: "vault-data",
        options: [],
      },
      {
        name: "bucket",
        label: "Bucket",
        help: "Existing bucket name",
        input_type: "text",
        required: true,
        secret: false,
        default: null,
        options: [],
      },
      {
        name: "region",
        label: "Region",
        help: "Provider region; required for Backblaze B2 and Wasabi",
        input_type: "text",
        required: false,
        secret: false,
        default: "auto",
        options: [],
      },
      {
        name: "addressing_style",
        label: "Addressing style",
        help: "Auto uses the provider preset",
        input_type: "text",
        required: false,
        secret: false,
        default: "auto",
        options: ["auto", "path", "virtual"],
      },
      {
        name: "access_key",
        label: "Access key",
        help: "Object-storage access key",
        input_type: "password",
        required: true,
        secret: true,
        default: null,
        options: [],
      },
      {
        name: "secret_key",
        label: "Secret key",
        help: "Object-storage secret key",
        input_type: "password",
        required: true,
        secret: true,
        default: null,
        options: [],
      },
    ],
    fields_by_use: {
      vault: [
        {
          name: "root",
          label: "Root",
          help: "Dedicated folder or prefix",
          input_type: "path",
          required: true,
          secret: false,
          default: "vault-data",
          options: [],
        },
        {
          name: "bucket",
          label: "Bucket",
          help: "Existing bucket name",
          input_type: "text",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "region",
          label: "Region",
          help: "Provider region; required for Backblaze B2 and Wasabi",
          input_type: "text",
          required: false,
          secret: false,
          default: "auto",
          options: [],
        },
        {
          name: "addressing_style",
          label: "Addressing style",
          help: "Auto uses the provider preset",
          input_type: "text",
          required: false,
          secret: false,
          default: "auto",
          options: ["auto", "path", "virtual"],
        },
        {
          name: "access_key",
          label: "Access key",
          help: "Object-storage access key",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
        {
          name: "secret_key",
          label: "Secret key",
          help: "Object-storage secret key",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
      ],
      library: [
        {
          name: "root",
          label: "Base folder",
          help: "Dedicated folder or prefix",
          input_type: "path",
          required: true,
          secret: false,
          default: "PrintStash",
          options: [],
        },
        {
          name: "bucket",
          label: "Bucket",
          help: "Existing bucket name",
          input_type: "text",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "region",
          label: "Region",
          help: "Provider region; required for Backblaze B2 and Wasabi",
          input_type: "text",
          required: false,
          secret: false,
          default: "auto",
          options: [],
        },
        {
          name: "addressing_style",
          label: "Addressing style",
          help: "Auto uses the provider preset",
          input_type: "text",
          required: false,
          secret: false,
          default: "auto",
          options: ["auto", "path", "virtual"],
        },
        {
          name: "access_key",
          label: "Access key",
          help: "Object-storage access key",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
        {
          name: "secret_key",
          label: "Secret key",
          help: "Object-storage secret key",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
      ],
      backup: [
        {
          name: "root",
          label: "Base folder",
          help: "Dedicated folder or prefix",
          input_type: "path",
          required: true,
          secret: false,
          default: "PrintStash",
          options: [],
        },
        {
          name: "bucket",
          label: "Bucket",
          help: "Existing bucket name",
          input_type: "text",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "region",
          label: "Region",
          help: "Provider region; required for Backblaze B2 and Wasabi",
          input_type: "text",
          required: false,
          secret: false,
          default: "auto",
          options: [],
        },
        {
          name: "addressing_style",
          label: "Addressing style",
          help: "Auto uses the provider preset",
          input_type: "text",
          required: false,
          secret: false,
          default: "auto",
          options: ["auto", "path", "virtual"],
        },
        {
          name: "access_key",
          label: "Access key",
          help: "Object-storage access key",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
        {
          name: "secret_key",
          label: "Secret key",
          help: "Object-storage secret key",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
      ],
    },
    requirements: [
      {
        kind: "not_value",
        fields: ["region"],
        value: "auto",
        message: "Enter the provider region.",
      },
    ],
    transport: "s3",
    uses: {
      vault: {
        dependency_installed: true,
        service_compiled: true,
        supported: true,
        available: true,
        endpoint_proven: false,
        reason: "storage_endpoint_probe_required",
      },
      library: {
        dependency_installed: true,
        service_compiled: true,
        supported: true,
        available: true,
        endpoint_proven: false,
        reason: "storage_endpoint_probe_required",
      },
      backup: {
        dependency_installed: true,
        service_compiled: true,
        supported: true,
        available: true,
        endpoint_proven: false,
        reason: "storage_endpoint_probe_required",
      },
    },
  },
  {
    id: "s3_self_hosted",
    label: "Self-hosted S3",
    category: "s3_compatible",
    description: "Native S3-compatible object storage.",
    expected_tier: "guarded",
    expected_tier_note: "Verified when bucket versioning is enabled; otherwise Guarded.",
    consequences: ["Automated purge requires a Verified probe."],
    documentation_url: "/docs/storage-providers.md#s3_self_hosted",
    available: true,
    selectable: true,
    support_level: "beta",
    disabled_reason: null,
    fields: [
      {
        name: "root",
        label: "Root",
        help: "Dedicated folder or prefix",
        input_type: "path",
        required: true,
        secret: false,
        default: "vault-data",
        options: [],
      },
      {
        name: "bucket",
        label: "Bucket",
        help: "Existing bucket name",
        input_type: "text",
        required: true,
        secret: false,
        default: null,
        options: [],
      },
      {
        name: "region",
        label: "Region",
        help: "Provider region; required for Backblaze B2 and Wasabi",
        input_type: "text",
        required: false,
        secret: false,
        default: "auto",
        options: [],
      },
      {
        name: "addressing_style",
        label: "Addressing style",
        help: "Auto uses the provider preset",
        input_type: "text",
        required: false,
        secret: false,
        default: "auto",
        options: ["auto", "path", "virtual"],
      },
      {
        name: "endpoint_url",
        label: "Endpoint",
        help: "S3-compatible server URL",
        input_type: "url",
        required: true,
        secret: false,
        default: "",
        options: [],
      },
      {
        name: "access_key",
        label: "Access key",
        help: "Object-storage access key",
        input_type: "password",
        required: true,
        secret: true,
        default: null,
        options: [],
      },
      {
        name: "secret_key",
        label: "Secret key",
        help: "Object-storage secret key",
        input_type: "password",
        required: true,
        secret: true,
        default: null,
        options: [],
      },
    ],
    fields_by_use: {
      vault: [
        {
          name: "root",
          label: "Root",
          help: "Dedicated folder or prefix",
          input_type: "path",
          required: true,
          secret: false,
          default: "vault-data",
          options: [],
        },
        {
          name: "bucket",
          label: "Bucket",
          help: "Existing bucket name",
          input_type: "text",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "region",
          label: "Region",
          help: "Provider region; required for Backblaze B2 and Wasabi",
          input_type: "text",
          required: false,
          secret: false,
          default: "auto",
          options: [],
        },
        {
          name: "addressing_style",
          label: "Addressing style",
          help: "Auto uses the provider preset",
          input_type: "text",
          required: false,
          secret: false,
          default: "auto",
          options: ["auto", "path", "virtual"],
        },
        {
          name: "endpoint_url",
          label: "Endpoint",
          help: "S3-compatible server URL",
          input_type: "url",
          required: true,
          secret: false,
          default: "",
          options: [],
        },
        {
          name: "access_key",
          label: "Access key",
          help: "Object-storage access key",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
        {
          name: "secret_key",
          label: "Secret key",
          help: "Object-storage secret key",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
      ],
      library: [
        {
          name: "root",
          label: "Base folder",
          help: "Dedicated folder or prefix",
          input_type: "path",
          required: true,
          secret: false,
          default: "PrintStash",
          options: [],
        },
        {
          name: "bucket",
          label: "Bucket",
          help: "Existing bucket name",
          input_type: "text",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "region",
          label: "Region",
          help: "Provider region; required for Backblaze B2 and Wasabi",
          input_type: "text",
          required: false,
          secret: false,
          default: "auto",
          options: [],
        },
        {
          name: "addressing_style",
          label: "Addressing style",
          help: "Auto uses the provider preset",
          input_type: "text",
          required: false,
          secret: false,
          default: "auto",
          options: ["auto", "path", "virtual"],
        },
        {
          name: "endpoint_url",
          label: "Endpoint",
          help: "S3-compatible server URL",
          input_type: "url",
          required: true,
          secret: false,
          default: "",
          options: [],
        },
        {
          name: "access_key",
          label: "Access key",
          help: "Object-storage access key",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
        {
          name: "secret_key",
          label: "Secret key",
          help: "Object-storage secret key",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
      ],
      backup: [
        {
          name: "root",
          label: "Base folder",
          help: "Dedicated folder or prefix",
          input_type: "path",
          required: true,
          secret: false,
          default: "PrintStash",
          options: [],
        },
        {
          name: "bucket",
          label: "Bucket",
          help: "Existing bucket name",
          input_type: "text",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "region",
          label: "Region",
          help: "Provider region; required for Backblaze B2 and Wasabi",
          input_type: "text",
          required: false,
          secret: false,
          default: "auto",
          options: [],
        },
        {
          name: "addressing_style",
          label: "Addressing style",
          help: "Auto uses the provider preset",
          input_type: "text",
          required: false,
          secret: false,
          default: "auto",
          options: ["auto", "path", "virtual"],
        },
        {
          name: "endpoint_url",
          label: "Endpoint",
          help: "S3-compatible server URL",
          input_type: "url",
          required: true,
          secret: false,
          default: "",
          options: [],
        },
        {
          name: "access_key",
          label: "Access key",
          help: "Object-storage access key",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
        {
          name: "secret_key",
          label: "Secret key",
          help: "Object-storage secret key",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
      ],
    },
    requirements: [],
    transport: "s3",
    uses: {
      vault: {
        dependency_installed: true,
        service_compiled: true,
        supported: true,
        available: true,
        endpoint_proven: false,
        reason: "storage_endpoint_probe_required",
      },
      library: {
        dependency_installed: true,
        service_compiled: true,
        supported: true,
        available: true,
        endpoint_proven: false,
        reason: "storage_endpoint_probe_required",
      },
      backup: {
        dependency_installed: true,
        service_compiled: true,
        supported: true,
        available: true,
        endpoint_proven: false,
        reason: "storage_endpoint_probe_required",
      },
    },
  },
  {
    id: "nextcloud",
    label: "Nextcloud",
    category: "nextcloud_webdav",
    description: "Remote storage over WebDAV.",
    expected_tier: "guarded",
    expected_tier_note:
      "Confirmed catalog removal retains stored bytes; exact physical deletion is unavailable.",
    consequences: [
      "Confirmed catalog removal retains stored bytes.",
      "Automatic physical deletion is unavailable.",
    ],
    documentation_url: "/docs/storage-providers.md#nextcloud",
    available: true,
    selectable: true,
    support_level: "beta",
    disabled_reason: null,
    fields: [
      {
        name: "root",
        label: "Root",
        help: "Dedicated folder or prefix",
        input_type: "path",
        required: true,
        secret: false,
        default: "vault-data",
        options: [],
      },
      {
        name: "endpoint_url",
        label: "Server URL",
        help: "Nextcloud base URL or full WebDAV endpoint",
        input_type: "url",
        required: true,
        secret: false,
        default: null,
        options: [],
      },
      {
        name: "username",
        label: "Username",
        help: "Remote account username",
        input_type: "text",
        required: true,
        secret: false,
        default: null,
        options: [],
      },
      {
        name: "password",
        label: "Password",
        help: "Remote account password",
        input_type: "password",
        required: true,
        secret: true,
        default: null,
        options: [],
      },
    ],
    fields_by_use: {
      vault: [
        {
          name: "root",
          label: "Root",
          help: "Dedicated folder or prefix",
          input_type: "path",
          required: true,
          secret: false,
          default: "vault-data",
          options: [],
        },
        {
          name: "endpoint_url",
          label: "Server URL",
          help: "Nextcloud base URL or full WebDAV endpoint",
          input_type: "url",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "username",
          label: "Username",
          help: "Remote account username",
          input_type: "text",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "password",
          label: "Password",
          help: "Remote account password",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
      ],
      library: [
        {
          name: "root",
          label: "Base folder",
          help: "Dedicated folder or prefix",
          input_type: "path",
          required: true,
          secret: false,
          default: "PrintStash",
          options: [],
        },
        {
          name: "endpoint_url",
          label: "Server URL",
          help: "Nextcloud base URL or full WebDAV endpoint",
          input_type: "url",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "username",
          label: "Username",
          help: "Remote account username",
          input_type: "text",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "password",
          label: "Password",
          help: "Remote account password",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
      ],
      backup: [
        {
          name: "root",
          label: "Base folder",
          help: "Dedicated folder or prefix",
          input_type: "path",
          required: true,
          secret: false,
          default: "PrintStash",
          options: [],
        },
        {
          name: "endpoint_url",
          label: "Server URL",
          help: "Nextcloud base URL or full WebDAV endpoint",
          input_type: "url",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "username",
          label: "Username",
          help: "Remote account username",
          input_type: "text",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "password",
          label: "Password",
          help: "Remote account password",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
      ],
    },
    requirements: [],
    transport: "webdav",
    uses: {
      vault: {
        dependency_installed: true,
        service_compiled: true,
        supported: true,
        available: true,
        endpoint_proven: false,
        reason: "storage_endpoint_probe_required",
      },
      library: {
        dependency_installed: true,
        service_compiled: true,
        supported: true,
        available: true,
        endpoint_proven: false,
        reason: "storage_endpoint_probe_required",
      },
      backup: {
        dependency_installed: true,
        service_compiled: true,
        supported: true,
        available: true,
        endpoint_proven: false,
        reason: "storage_endpoint_probe_required",
      },
    },
  },
  {
    id: "webdav",
    label: "WebDAV",
    category: "nextcloud_webdav",
    description: "Remote storage over WebDAV.",
    expected_tier: "guarded",
    expected_tier_note:
      "Confirmed catalog removal retains stored bytes; exact physical deletion is unavailable.",
    consequences: [
      "Confirmed catalog removal retains stored bytes.",
      "Automatic physical deletion is unavailable.",
    ],
    documentation_url: "/docs/storage-providers.md#webdav",
    available: true,
    selectable: true,
    support_level: "beta",
    disabled_reason: null,
    fields: [
      {
        name: "root",
        label: "Root",
        help: "Dedicated folder or prefix",
        input_type: "path",
        required: true,
        secret: false,
        default: "vault-data",
        options: [],
      },
      {
        name: "endpoint_url",
        label: "Server URL",
        help: "Nextcloud base URL or full WebDAV endpoint",
        input_type: "url",
        required: true,
        secret: false,
        default: null,
        options: [],
      },
      {
        name: "username",
        label: "Username",
        help: "Remote account username",
        input_type: "text",
        required: true,
        secret: false,
        default: null,
        options: [],
      },
      {
        name: "password",
        label: "Password",
        help: "Remote account password",
        input_type: "password",
        required: true,
        secret: true,
        default: null,
        options: [],
      },
    ],
    fields_by_use: {
      vault: [
        {
          name: "root",
          label: "Root",
          help: "Dedicated folder or prefix",
          input_type: "path",
          required: true,
          secret: false,
          default: "vault-data",
          options: [],
        },
        {
          name: "endpoint_url",
          label: "Server URL",
          help: "Nextcloud base URL or full WebDAV endpoint",
          input_type: "url",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "username",
          label: "Username",
          help: "Remote account username",
          input_type: "text",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "password",
          label: "Password",
          help: "Remote account password",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
      ],
      library: [
        {
          name: "root",
          label: "Base folder",
          help: "Dedicated folder or prefix",
          input_type: "path",
          required: true,
          secret: false,
          default: "PrintStash",
          options: [],
        },
        {
          name: "endpoint_url",
          label: "Server URL",
          help: "Nextcloud base URL or full WebDAV endpoint",
          input_type: "url",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "username",
          label: "Username",
          help: "Remote account username",
          input_type: "text",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "password",
          label: "Password",
          help: "Remote account password",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
      ],
      backup: [
        {
          name: "root",
          label: "Base folder",
          help: "Dedicated folder or prefix",
          input_type: "path",
          required: true,
          secret: false,
          default: "PrintStash",
          options: [],
        },
        {
          name: "endpoint_url",
          label: "Server URL",
          help: "Nextcloud base URL or full WebDAV endpoint",
          input_type: "url",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "username",
          label: "Username",
          help: "Remote account username",
          input_type: "text",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "password",
          label: "Password",
          help: "Remote account password",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
      ],
    },
    requirements: [],
    transport: "webdav",
    uses: {
      vault: {
        dependency_installed: true,
        service_compiled: true,
        supported: true,
        available: true,
        endpoint_proven: false,
        reason: "storage_endpoint_probe_required",
      },
      library: {
        dependency_installed: true,
        service_compiled: true,
        supported: true,
        available: true,
        endpoint_proven: false,
        reason: "storage_endpoint_probe_required",
      },
      backup: {
        dependency_installed: true,
        service_compiled: true,
        supported: true,
        available: true,
        endpoint_proven: false,
        reason: "storage_endpoint_probe_required",
      },
    },
  },
  {
    id: "sftp",
    label: "SFTP",
    category: "nas_sftp",
    description: "NAS storage over SSH File Transfer Protocol.",
    expected_tier: "guarded",
    expected_tier_note:
      "Publish uses SSH exclusive create (`x` mode); `host_key` is required and purge is manual and confirmed only.",
    consequences: [
      "Confirmed catalog removal retains stored bytes.",
      "Automatic physical deletion is unavailable.",
    ],
    documentation_url: "/docs/storage-providers.md#sftp",
    available: true,
    selectable: true,
    support_level: "beta",
    disabled_reason: null,
    fields: [
      {
        name: "root",
        label: "Root",
        help: "Dedicated folder or prefix",
        input_type: "path",
        required: true,
        secret: false,
        default: "vault-data",
        options: [],
      },
      {
        name: "host",
        label: "Host",
        help: "SFTP hostname",
        input_type: "text",
        required: true,
        secret: false,
        default: null,
        options: [],
      },
      {
        name: "port",
        label: "Port",
        help: "SFTP port",
        input_type: "number",
        required: false,
        secret: false,
        default: 22,
        options: [],
      },
      {
        name: "username",
        label: "Username",
        help: "SFTP account username",
        input_type: "text",
        required: true,
        secret: false,
        default: null,
        options: [],
      },
      {
        name: "host_key",
        label: "Host key",
        help: "OpenSSH known-hosts path or entry",
        input_type: "path",
        required: true,
        secret: false,
        default: "",
        options: [],
      },
      {
        name: "password",
        label: "Password",
        help: "Use either a password or a mounted private-key path",
        input_type: "password",
        required: false,
        secret: true,
        default: "",
        options: [],
      },
      {
        name: "private_key_path",
        label: "Private key path",
        help: "Mounted service-key path; inline key material is forbidden",
        input_type: "path",
        required: false,
        secret: false,
        default: "",
        options: [],
      },
      {
        name: "passphrase",
        label: "Key passphrase",
        help: "Optional passphrase for the mounted private key",
        input_type: "password",
        required: false,
        secret: true,
        default: "",
        options: [],
      },
    ],
    fields_by_use: {
      vault: [
        {
          name: "root",
          label: "Root",
          help: "Dedicated folder or prefix",
          input_type: "path",
          required: true,
          secret: false,
          default: "vault-data",
          options: [],
        },
        {
          name: "host",
          label: "Host",
          help: "SFTP hostname",
          input_type: "text",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "port",
          label: "Port",
          help: "SFTP port",
          input_type: "number",
          required: false,
          secret: false,
          default: 22,
          options: [],
        },
        {
          name: "username",
          label: "Username",
          help: "SFTP account username",
          input_type: "text",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "host_key",
          label: "Host key",
          help: "OpenSSH known-hosts path or entry",
          input_type: "path",
          required: true,
          secret: false,
          default: "",
          options: [],
        },
        {
          name: "password",
          label: "Password",
          help: "Use either a password or a mounted private-key path",
          input_type: "password",
          required: false,
          secret: true,
          default: "",
          options: [],
        },
        {
          name: "private_key_path",
          label: "Private key path",
          help: "Mounted service-key path; inline key material is forbidden",
          input_type: "path",
          required: false,
          secret: false,
          default: "",
          options: [],
        },
        {
          name: "passphrase",
          label: "Key passphrase",
          help: "Optional passphrase for the mounted private key",
          input_type: "password",
          required: false,
          secret: true,
          default: "",
          options: [],
        },
      ],
      library: [
        {
          name: "root",
          label: "Base folder",
          help: "Dedicated folder or prefix",
          input_type: "path",
          required: true,
          secret: false,
          default: "PrintStash",
          options: [],
        },
        {
          name: "host",
          label: "Host",
          help: "SFTP hostname",
          input_type: "text",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "port",
          label: "Port",
          help: "SFTP port",
          input_type: "number",
          required: false,
          secret: false,
          default: 22,
          options: [],
        },
        {
          name: "username",
          label: "Username",
          help: "SFTP account username",
          input_type: "text",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "host_key",
          label: "Host key",
          help: "OpenSSH known-hosts path or entry",
          input_type: "path",
          required: true,
          secret: false,
          default: "",
          options: [],
        },
        {
          name: "password",
          label: "Password",
          help: "Use either a password or a mounted private-key path",
          input_type: "password",
          required: false,
          secret: true,
          default: "",
          options: [],
        },
        {
          name: "private_key_path",
          label: "Private key path",
          help: "Mounted service-key path; inline key material is forbidden",
          input_type: "path",
          required: false,
          secret: false,
          default: "",
          options: [],
        },
        {
          name: "passphrase",
          label: "Key passphrase",
          help: "Optional passphrase for the mounted private key",
          input_type: "password",
          required: false,
          secret: true,
          default: "",
          options: [],
        },
      ],
      backup: [
        {
          name: "root",
          label: "Base folder",
          help: "Dedicated folder or prefix",
          input_type: "path",
          required: true,
          secret: false,
          default: "PrintStash",
          options: [],
        },
        {
          name: "host",
          label: "Host",
          help: "SFTP hostname",
          input_type: "text",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "port",
          label: "Port",
          help: "SFTP port",
          input_type: "number",
          required: false,
          secret: false,
          default: 22,
          options: [],
        },
        {
          name: "username",
          label: "Username",
          help: "SFTP account username",
          input_type: "text",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "host_key",
          label: "Host key",
          help: "OpenSSH known-hosts path or entry",
          input_type: "path",
          required: true,
          secret: false,
          default: "",
          options: [],
        },
        {
          name: "password",
          label: "Password",
          help: "Use either a password or a mounted private-key path",
          input_type: "password",
          required: false,
          secret: true,
          default: "",
          options: [],
        },
        {
          name: "private_key_path",
          label: "Private key path",
          help: "Mounted service-key path; inline key material is forbidden",
          input_type: "path",
          required: false,
          secret: false,
          default: "",
          options: [],
        },
        {
          name: "passphrase",
          label: "Key passphrase",
          help: "Optional passphrase for the mounted private key",
          input_type: "password",
          required: false,
          secret: true,
          default: "",
          options: [],
        },
      ],
    },
    requirements: [
      {
        kind: "exactly_one",
        fields: ["password", "private_key_path"],
        message: "Use either a password or a private key path.",
      },
      {
        kind: "requires",
        fields: ["passphrase", "private_key_path"],
        message: "A key passphrase requires a private key path.",
      },
    ],
    transport: "sftp",
    uses: {
      vault: {
        dependency_installed: true,
        service_compiled: true,
        supported: true,
        available: true,
        endpoint_proven: false,
        reason: "storage_endpoint_probe_required",
      },
      library: {
        dependency_installed: true,
        service_compiled: true,
        supported: true,
        available: true,
        endpoint_proven: false,
        reason: "storage_endpoint_probe_required",
      },
      backup: {
        dependency_installed: true,
        service_compiled: true,
        supported: true,
        available: true,
        endpoint_proven: false,
        reason: "storage_endpoint_probe_required",
      },
    },
  },
  {
    id: "gdrive",
    label: "Google Drive",
    category: "consumer_cloud",
    description: "Consumer cloud storage through Apache OpenDAL.",
    expected_tier: "unguarded",
    expected_tier_note:
      "Available for read-only Library sources and off-site backup replicas; not selectable as managed Vault storage.",
    consequences: [
      "Remote backup retention is manual because conditional delete is unavailable.",
      "Google Drive replicas do not authorize automatic Vault garbage collection.",
    ],
    documentation_url: "/docs/storage-providers.md#gdrive",
    available: true,
    selectable: false,
    support_level: "beta",
    disabled_reason: "storage_use_unsupported",
    fields: [
      {
        name: "root",
        label: "Folder",
        help: "Dedicated folder or prefix",
        input_type: "path",
        required: true,
        secret: false,
        default: "PrintStash",
        options: [],
      },
      {
        name: "client_id",
        label: "OAuth client ID",
        help: "Google OAuth application client ID",
        input_type: "text",
        required: true,
        secret: false,
        default: null,
        options: [],
      },
      {
        name: "client_secret",
        label: "OAuth client secret",
        help: "Google OAuth application client secret",
        input_type: "password",
        required: true,
        secret: true,
        default: null,
        options: [],
      },
      {
        name: "refresh_token",
        label: "Refresh token",
        help: "OAuth refresh token",
        input_type: "password",
        required: true,
        secret: true,
        default: null,
        options: [],
      },
    ],
    fields_by_use: {
      vault: [
        {
          name: "root",
          label: "Folder",
          help: "Dedicated folder or prefix",
          input_type: "path",
          required: true,
          secret: false,
          default: "PrintStash",
          options: [],
        },
        {
          name: "client_id",
          label: "OAuth client ID",
          help: "Google OAuth application client ID",
          input_type: "text",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "client_secret",
          label: "OAuth client secret",
          help: "Google OAuth application client secret",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
        {
          name: "refresh_token",
          label: "Refresh token",
          help: "OAuth refresh token",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
      ],
      library: [
        {
          name: "root",
          label: "Base folder",
          help: "Dedicated folder or prefix",
          input_type: "path",
          required: true,
          secret: false,
          default: "PrintStash",
          options: [],
        },
        {
          name: "client_id",
          label: "OAuth client ID",
          help: "Google OAuth application client ID",
          input_type: "text",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "client_secret",
          label: "OAuth client secret",
          help: "Google OAuth application client secret",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
        {
          name: "refresh_token",
          label: "Refresh token",
          help: "OAuth refresh token",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
      ],
      backup: [
        {
          name: "root",
          label: "Base folder",
          help: "Dedicated folder or prefix",
          input_type: "path",
          required: true,
          secret: false,
          default: "PrintStash",
          options: [],
        },
        {
          name: "client_id",
          label: "OAuth client ID",
          help: "Google OAuth application client ID",
          input_type: "text",
          required: true,
          secret: false,
          default: null,
          options: [],
        },
        {
          name: "client_secret",
          label: "OAuth client secret",
          help: "Google OAuth application client secret",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
        {
          name: "refresh_token",
          label: "Refresh token",
          help: "OAuth refresh token",
          input_type: "password",
          required: true,
          secret: true,
          default: null,
          options: [],
        },
      ],
    },
    requirements: [],
    transport: "gdrive",
    uses: {
      vault: {
        dependency_installed: true,
        service_compiled: true,
        supported: false,
        available: false,
        endpoint_proven: false,
        reason: "storage_use_unsupported",
      },
      library: {
        dependency_installed: true,
        service_compiled: true,
        supported: true,
        available: true,
        endpoint_proven: false,
        reason: "storage_endpoint_probe_required",
      },
      backup: {
        dependency_installed: true,
        service_compiled: true,
        supported: true,
        available: true,
        endpoint_proven: false,
        reason: "storage_endpoint_probe_required",
      },
    },
  },
];
