"""Checks `alembic/env.py` runs over what autogenerate is about to write.

Here rather than inside `env.py` because `env.py` is executed by Alembic with a
`context` in scope and cannot be imported, so nothing in it can be tested directly.
These are pure functions over the operations Alembic produced; `env.py` extracts the
operations and calls them.
"""

from __future__ import annotations

from typing import Any

# table -> (columns this migration drops, columns it adds)
ColumnChanges = dict[str, tuple[list[str], list[str]]]


def dropped_and_added_columns(upgrade_ops: Any) -> ColumnChanges:
    """Per table, which columns an autogenerated migration drops and adds."""
    per_table: ColumnChanges = {}
    for diff in upgrade_ops.as_diffs():
        # Nested lists are `alter_column` groups; only the flat tuples matter here.
        if not isinstance(diff, tuple) or len(diff) < 4:
            continue
        kind, _schema, table, column = diff[0], diff[1], diff[2], diff[3]
        if kind not in {"add_column", "remove_column"}:
            continue
        dropped, added = per_table.setdefault(str(table), ([], []))
        (dropped if kind == "remove_column" else added).append(column.name)
    return per_table


def acknowledged_drops(changes: ColumnChanges, *, allowed: set[str]) -> list[str]:
    """The `table.column` drops in *changes* that the author explicitly acknowledged.

    Returned so the acknowledgement can be written into the migration's docstring.
    Without that it lives only in the shell history of whoever ran the command, and a
    reviewer meeting `add_column` next to `remove_column` has no way to tell a vetted
    drop from the rename this guard exists to catch — which is the same failure one step
    later.
    """
    return sorted(
        f"{table}.{column}"
        for table, (dropped, added) in changes.items()
        for column in dropped
        if added and f"{table}.{column}" in allowed
    )


def refuse_possible_renames(changes: ColumnChanges, *, allowed: set[str]) -> None:
    """Raise when a migration drops and adds columns in the same table.

    Autogenerate compares two *states* — the database's schema and the models'
    metadata — and a rename is invisible to a state comparison. Renaming `old_name` to
    `new_name` and dropping `old_name` while adding an unrelated `new_name` produce
    byte-identical diffs, so no setting can separate them: the distinguishing fact is
    what the author meant, and that was never written anywhere Alembic can read. Django
    resolves the same ambiguity by asking interactively; Alembic is non-interactive by
    design.

    What is left is refusing to write the file quietly. The drop reads as an ordinary
    migration in review, and shipping it empties the column on every installation.

    *allowed* holds `table.column` entries the author has explicitly acknowledged as
    real drops, passed as `-x allow_column_drop=things.old_name`.
    """
    for table, (dropped, added) in sorted(changes.items()):
        unacknowledged = [
            column for column in dropped if f"{table}.{column}" not in allowed
        ]
        if not (unacknowledged and added):
            continue
        raise RuntimeError(
            f"this migration would drop {table}.{unacknowledged[0]} and add "
            f"{table}.{added[0]} — which is what a *rename* looks like to a schema "
            "differ, and shipping it as a drop destroys the column's data.\n"
            "  If it is a rename: replace both operations with "
            f'`batch_op.alter_column("{unacknowledged[0]}", '
            f'new_column_name="{added[0]}")`.\n'
            "  If it really is a drop: re-run with "
            f"`-x allow_column_drop={table}.{unacknowledged[0]}`."
        )
