"""Add variation relationships without changing Model or Revision ownership.

Autogenerated from the four Family tables; the canonical FK is applied after
both ends exist, using frozen batch snapshots for SQLite offline migration.

Revision ID: 0118bda3e719
Revises: f3736257acd2
Create Date: 2026-09-11 07:33:57.974044

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0118bda3e719"
down_revision: Union[str, Sequence[str], None] = "f3736257acd2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _family_columns():
    """Frozen autogenerated columns and constraints for SQLite offline batches."""
    return [
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("export_id", sa.String(length=36), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("collection_id", sa.Integer(), nullable=True),
        sa.Column("cover_model_id", sa.Integer(), nullable=True),
        sa.Column("cover_image_url", sa.String(length=2083), nullable=True),
        sa.Column("cover_filename", sa.String(length=255), nullable=True),
        sa.Column("cover_content_type", sa.String(length=64), nullable=True),
        sa.Column("cover_size_bytes", sa.Integer(), nullable=True),
        sa.Column("canonical_member_id", sa.Integer(), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "version > 0", name=op.f("ck_model_families_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
            name=op.f("fk_model_families_collection_id_collections"),
        ),
        sa.ForeignKeyConstraint(
            ["cover_model_id"],
            ["models.id"],
            name=op.f("fk_model_families_cover_model_id_models"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_model_families_created_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["users.id"],
            name=op.f("fk_model_families_deleted_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_model_families_updated_by_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_families")),
    ]


def _family_snapshot(*, with_canonical=False):
    columns = _family_columns()
    if with_canonical:
        columns.append(
            sa.ForeignKeyConstraint(
                ["canonical_member_id"],
                ["model_family_members.id"],
                name="fk_model_families_canonical_member_id_model_family_members",
                ondelete="SET NULL",
                use_alter=False,
            )
        )
    return sa.Table("model_families", sa.MetaData(), *columns)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("model_families", *_family_columns())
    op.create_table(
        "model_family_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("family_id", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=True),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("transformation_note", sa.Text(), nullable=True),
        sa.Column("scale_factor", sa.Float(), nullable=True),
        sa.Column("mirrored", sa.Boolean(), nullable=False),
        sa.Column("relative_to_member_id", sa.Integer(), nullable=True),
        sa.Column("mirror_reference_member_id", sa.Integer(), nullable=True),
        sa.Column("mirror_verified", sa.Boolean(), nullable=False),
        sa.Column("relative_review_required", sa.Boolean(), nullable=False),
        sa.Column("joined_via", sa.String(length=32), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("detached_at", sa.DateTime(), nullable=True),
        sa.Column("detached_by", sa.Integer(), nullable=True),
        sa.Column("detach_reason", sa.String(length=32), nullable=True),
        sa.CheckConstraint(
            "(detached_at IS NULL AND detach_reason IS NULL) OR (detached_at IS NOT NULL AND detach_reason IS NOT NULL AND detach_reason IN ('removed', 'moved', 'family_trashed', 'model_purged'))",
            name=op.f("ck_model_family_members_detach_state_valid"),
        ),
        sa.CheckConstraint(
            "model_id IS NOT NULL OR (detached_at IS NOT NULL AND detach_reason = 'model_purged')",
            name=op.f("ck_model_family_members_missing_model_is_purged"),
        ),
        sa.CheckConstraint(
            "role IN ('canonical', 'identical', 'rescaled', 'mirrored', 'repaired', 'print_variant')",
            name=op.f("ck_model_family_members_role_valid"),
        ),
        sa.CheckConstraint(
            "scale_factor IS NULL OR (scale_factor > 0 AND scale_factor <= 1.7976931348623157e308)",
            name=op.f("ck_model_family_members_scale_positive_finite"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_model_family_members_created_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["detached_by"],
            ["users.id"],
            name=op.f("fk_model_family_members_detached_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["model_families.id"],
            name=op.f("fk_model_family_members_family_id_model_families"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["mirror_reference_member_id"],
            ["model_family_members.id"],
            name=op.f(
                "fk_model_family_members_mirror_reference_member_id_model_family_members"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["models.id"],
            name=op.f("fk_model_family_members_model_id_models"),
        ),
        sa.ForeignKeyConstraint(
            ["relative_to_member_id"],
            ["model_family_members.id"],
            name=op.f(
                "fk_model_family_members_relative_to_member_id_model_family_members"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_model_family_members_updated_by_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_family_members")),
    )
    with op.batch_alter_table("model_family_members", schema=None) as batch_op:
        batch_op.create_index(
            "ix_model_family_members_family_detached_order",
            ["family_id", "detached_at", "sort_order", "id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_model_family_members_model_id"), ["model_id"], unique=False
        )
        batch_op.create_index(
            "uq_model_family_members_active_canonical",
            ["family_id"],
            unique=True,
            sqlite_where=sa.text("detached_at IS NULL AND role = 'canonical'"),
            postgresql_where=sa.text("detached_at IS NULL AND role = 'canonical'"),
        )
        batch_op.create_index(
            "uq_model_family_members_active_model",
            ["model_id"],
            unique=True,
            sqlite_where=sa.text("detached_at IS NULL"),
            postgresql_where=sa.text("detached_at IS NULL"),
        )

    op.create_table(
        "model_family_stars",
        sa.Column("family_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["model_families.id"],
            name=op.f("fk_model_family_stars_family_id_model_families"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_model_family_stars_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "family_id", "user_id", name=op.f("pk_model_family_stars")
        ),
    )
    op.create_table(
        "model_family_tags",
        sa.Column("family_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["model_families.id"],
            name=op.f("fk_model_family_tags_family_id_model_families"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
            name=op.f("fk_model_family_tags_tag_id_tags"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "family_id", "tag_id", name=op.f("pk_model_family_tags")
        ),
    )
    # Autogenerate placed use_alter on the inline FK, which PostgreSQL omits.
    # Add it after both tables exist; batch mode also emits real SQLite DDL.
    with op.batch_alter_table(
        "model_families", copy_from=_family_snapshot()
    ) as batch_op:
        batch_op.create_foreign_key(
            "fk_model_families_canonical_member_id_model_family_members",
            "model_family_members",
            ["canonical_member_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("model_families", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_model_families_collection_id"),
            ["collection_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_model_families_cover_model_id"),
            ["cover_model_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_model_families_deleted_at"), ["deleted_at"], unique=False
        )
        batch_op.create_index(
            "ix_model_families_deleted_updated_id",
            ["deleted_at", "updated_at", "id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_model_families_export_id"), ["export_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_model_families_name"), ["name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_model_families_slug"), ["slug"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_model_families_updated_at"), ["updated_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("model_family_tags")
    op.drop_table("model_family_stars")
    with op.batch_alter_table("model_families", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_model_families_updated_at"))
        batch_op.drop_index(batch_op.f("ix_model_families_slug"))
        batch_op.drop_index(batch_op.f("ix_model_families_name"))
        batch_op.drop_index(batch_op.f("ix_model_families_export_id"))
        batch_op.drop_index("ix_model_families_deleted_updated_id")
        batch_op.drop_index(batch_op.f("ix_model_families_deleted_at"))
        batch_op.drop_index(batch_op.f("ix_model_families_cover_model_id"))
        batch_op.drop_index(batch_op.f("ix_model_families_collection_id"))

    with op.batch_alter_table(
        "model_families", copy_from=_family_snapshot(with_canonical=True)
    ) as batch_op:
        batch_op.drop_constraint(
            "fk_model_families_canonical_member_id_model_family_members",
            type_="foreignkey",
        )

    with op.batch_alter_table("model_family_members", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_model_family_members_active_model",
            sqlite_where=sa.text("detached_at IS NULL"),
            postgresql_where=sa.text("detached_at IS NULL"),
        )
        batch_op.drop_index(
            "uq_model_family_members_active_canonical",
            sqlite_where=sa.text("detached_at IS NULL AND role = 'canonical'"),
            postgresql_where=sa.text("detached_at IS NULL AND role = 'canonical'"),
        )
        batch_op.drop_index(batch_op.f("ix_model_family_members_model_id"))
        batch_op.drop_index("ix_model_family_members_family_detached_order")

    op.drop_table("model_family_members")
    op.drop_table("model_families")
    # ### end Alembic commands ###
