"""Retain verified remote change markers without inventing historical evidence.

Revision ID: 046685afd7ea
Revises: 0aece77e15cf
Create Date: 2026-09-05 12:50:40.493854

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "046685afd7ea"
down_revision: Union[str, Sequence[str], None] = "0aece77e15cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.add_column(sa.Column("source_etag", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("source_version_id", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.drop_column("source_version_id")
        batch_op.drop_column("source_etag")

    # ### end Alembic commands ###
