"""Protect preset drafts across competing edits, restores and reused row IDs.

Revision ID: 09232f601ed9
Revises: f92f1ea1dfe2
Create Date: 2026-10-07 12:24:52.398630

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from app.db import profile_edit_contracts_v1

# revision identifiers, used by Alembic.
revision: str = "09232f601ed9"
down_revision: Union[str, Sequence[str], None] = "f92f1ea1dfe2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Frozen post-addition shapes allow SQLite's default-removal rebuild to render
# offline. The shared historical identity is safe because the public token also
# binds kind, integer ID and database history; every future row supplies a UUID.
_FILAMENTS = sa.Table(
    "filament_profiles",
    sa.MetaData(),
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("name", sa.String(128), nullable=False),
    sa.Column("material_type", sa.String(64)),
    sa.Column("material_brand", sa.String(128)),
    sa.Column("cost_per_kg", sa.Float()),
    sa.Column("notes", sa.String()),
    sa.Column("spoolman_filament_id", sa.Integer()),
    sa.Column("density_g_cm3", sa.Float()),
    sa.Column("diameter_mm", sa.Float()),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.Column("edit_version", sa.BigInteger(), server_default="1", nullable=False),
    sa.Column(
        "edit_identity",
        sa.String(32),
        server_default="00000000000000000000000000000000",
        nullable=False,
    ),
    sa.PrimaryKeyConstraint("id", name="pk_filament_profiles"),
    sa.Index("ix_filament_profiles_name", "name", unique=True),
    sa.Index("ix_filament_profiles_material_type", "material_type"),
    sa.Index("ix_filament_profiles_material_brand", "material_brand"),
    sa.Index("ix_filament_profiles_spoolman_filament_id", "spoolman_filament_id"),
)
_PRINTERS = sa.Table(
    "printer_profiles",
    sa.MetaData(),
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("name", sa.String(128), nullable=False),
    sa.Column("printer_model", sa.String(128)),
    sa.Column("slicer_name", sa.String(64)),
    sa.Column("nozzle_diameter_mm", sa.Float()),
    sa.Column("notes", sa.String()),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.Column("edit_version", sa.BigInteger(), server_default="1", nullable=False),
    sa.Column(
        "edit_identity",
        sa.String(32),
        server_default="00000000000000000000000000000000",
        nullable=False,
    ),
    sa.PrimaryKeyConstraint("id", name="pk_printer_profiles"),
    sa.Index("ix_printer_profiles_name", "name", unique=True),
    sa.Index("ix_printer_profiles_printer_model", "printer_model"),
    sa.Index("ix_printer_profiles_slicer_name", "slicer_name"),
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("filament_profiles", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "edit_version", sa.BigInteger(), server_default="1", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "edit_identity",
                sa.String(length=32),
                server_default="00000000000000000000000000000000",
                nullable=False,
            )
        )

    with op.batch_alter_table("printer_profiles", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "edit_version", sa.BigInteger(), server_default="1", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "edit_identity",
                sa.String(length=32),
                server_default="00000000000000000000000000000000",
                nullable=False,
            )
        )

    # Remove the backfill-only default: new rows must provide a fresh identity.
    for table in (_FILAMENTS, _PRINTERS):
        with op.batch_alter_table(table.name, copy_from=table) as batch_op:
            batch_op.alter_column(
                "edit_identity",
                existing_type=sa.String(32),
                existing_nullable=False,
                server_default=None,
            )
    profile_edit_contracts_v1.install(op.get_bind())


def downgrade() -> None:
    """Downgrade schema."""
    profile_edit_contracts_v1.uninstall(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "printer_profiles", schema=None, recreate="never"
    ) as batch_op:
        batch_op.drop_column("edit_identity")
        batch_op.drop_column("edit_version")

    with op.batch_alter_table(
        "filament_profiles", schema=None, recreate="never"
    ) as batch_op:
        batch_op.drop_column("edit_identity")
        batch_op.drop_column("edit_version")

    # ### end Alembic commands ###
