"""Version Search settings independently from background progress

Revision ID: 0a76fbca8438
Revises: 09232f601ed9
Create Date: 2026-10-07 13:04:24.944174

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from app.db import search_edit_contracts_v1

# revision identifiers, used by Alembic.
revision: str = "0a76fbca8438"
down_revision: Union[str, Sequence[str], None] = "09232f601ed9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "system_config", schema=None, recreate="never"
    ) as batch_op:
        batch_op.add_column(
            sa.Column(
                "search_edit_version",
                sa.BigInteger(),
                server_default="1",
                nullable=False,
            )
        )

    # Schema autogenerate cannot emit this trigger; fresh installs share it.
    search_edit_contracts_v1.install(op.get_bind())


def downgrade() -> None:
    """Downgrade schema without rebuilding away existing singleton triggers."""
    search_edit_contracts_v1.uninstall(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "system_config", schema=None, recreate="never"
    ) as batch_op:
        batch_op.drop_column("search_edit_version")

    # ### end Alembic commands ###
