"""Keep passage retries while adding hash-scoped Artifact quarantine.

Revision ID: 10104316c059
Revises: 7fec0b53bb5c
Create Date: 2026-09-12 00:31:25.312857

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "10104316c059"
down_revision: Union[str, Sequence[str], None] = "7fec0b53bb5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("search_index_failures", schema=None) as batch_op:
        batch_op.add_column(sa.Column("file_id", sa.Integer(), nullable=True))
        batch_op.alter_column("passage_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.create_index(
            batch_op.f("ix_search_index_failures_file_id"), ["file_id"], unique=False
        )
        batch_op.create_unique_constraint(
            "uq_search_index_failure_file", ["generation_id", "file_id", "input_hash"]
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_search_index_failures_file_id_files"),
            "files",
            ["file_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_search_index_failures_source_identity"),
            "(passage_id IS NOT NULL AND file_id IS NULL) OR (passage_id IS NULL AND file_id IS NOT NULL)",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Visual retries are derived work and cannot be represented by the older
    # passage-only schema. Preserve every existing passage retry verbatim.
    op.execute("DELETE FROM search_index_failures WHERE file_id IS NOT NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("search_index_failures", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("ck_search_index_failures_source_identity"), type_="check"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_search_index_failures_file_id_files"), type_="foreignkey"
        )
        batch_op.drop_constraint("uq_search_index_failure_file", type_="unique")
        batch_op.drop_index(batch_op.f("ix_search_index_failures_file_id"))
        batch_op.alter_column("passage_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column("file_id")

    # ### end Alembic commands ###
