"""persist first run storage preparation

Revision ID: 199d0382f2d1
Revises: 5f0f887bdd0b
Create Date: 2026-09-05 18:23:31.429994

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '199d0382f2d1'
down_revision: Union[str, Sequence[str], None] = '5f0f887bdd0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setup_storage_pending', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.drop_column('setup_storage_pending')

    # ### end Alembic commands ###
