"""add multipart covers and favorites

Revision ID: 23bdc08ade8b
Revises: 270a39e42dea
Create Date: 2026-09-02 16:53:32.016657

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "23bdc08ade8b"
down_revision: Union[str, Sequence[str], None] = "270a39e42dea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "multipart_model_stars",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("multipart_model_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["multipart_model_id"],
            ["multipart_models.id"],
            name=op.f("fk_multipart_model_stars_multipart_model_id_multipart_models"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_multipart_model_stars_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_multipart_model_stars")),
        sa.UniqueConstraint(
            "user_id", "multipart_model_id", name="uq_multipart_model_stars_user_model"
        ),
    )
    with op.batch_alter_table("multipart_model_stars", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_multipart_model_stars_multipart_model_id"),
            ["multipart_model_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_multipart_model_stars_user_id"), ["user_id"], unique=False
        )

    with op.batch_alter_table("multipart_models", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("cover_image_url", sa.String(length=2083), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("multipart_models", schema=None) as batch_op:
        batch_op.drop_column("cover_image_url")

    with op.batch_alter_table("multipart_model_stars", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_multipart_model_stars_user_id"))
        batch_op.drop_index(batch_op.f("ix_multipart_model_stars_multipart_model_id"))

    op.drop_table("multipart_model_stars")
    # ### end Alembic commands ###
