"""Store personal natural-language search consent and timezone

Revision ID: 2d8bebe0f959
Revises: 5e261c89ef07
Create Date: 2026-09-12 03:34:51.184725

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2d8bebe0f959'
down_revision: Union[str, Sequence[str], None] = '5e261c89ef07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_search_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nl_filters_enabled', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_search_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_search_preferences'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_search_preferences')
    # ### end Alembic commands ###
