"""add standalone multipart models

Revision ID: 30c1c4a321a5
Revises: 54b21089d3af
Create Date: 2026-09-01 16:39:21.872754

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "30c1c4a321a5"
down_revision: Union[str, Sequence[str], None] = "54b21089d3af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "multipart_models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("collection_id", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
            name=op.f("fk_multipart_models_collection_id_collections"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_multipart_models_created_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_multipart_models_updated_by_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_multipart_models")),
        sa.UniqueConstraint("slug", name="uq_multipart_models_slug"),
    )
    with op.batch_alter_table("multipart_models", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_multipart_models_collection_id"),
            ["collection_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_multipart_models_name"), ["name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_multipart_models_slug"), ["slug"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_multipart_models_updated_at"), ["updated_at"], unique=False
        )

    op.create_table(
        "multipart_parts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("multipart_model_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("name_key", sa.String(length=128), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["multipart_model_id"],
            ["multipart_models.id"],
            name=op.f("fk_multipart_parts_multipart_model_id_multipart_models"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_multipart_parts")),
        sa.UniqueConstraint(
            "multipart_model_id", "name_key", name="uq_multipart_parts_model_name_key"
        ),
        sa.UniqueConstraint(
            "multipart_model_id",
            "sort_order",
            name="uq_multipart_parts_model_sort_order",
        ),
    )
    with op.batch_alter_table("multipart_parts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_multipart_parts_multipart_model_id"),
            ["multipart_model_id"],
            unique=False,
        )

    op.create_table(
        "multipart_model_choices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("multipart_model_id", sa.Integer(), nullable=False),
        sa.Column("multipart_part_id", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.Column("source_file_id", sa.Integer(), nullable=True),
        sa.Column("label", sa.String(length=128), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["models.id"],
            name=op.f("fk_multipart_model_choices_model_id_models"),
        ),
        sa.ForeignKeyConstraint(
            ["source_file_id"],
            ["files.id"],
            name=op.f("fk_multipart_model_choices_source_file_id_files"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["multipart_model_id"],
            ["multipart_models.id"],
            name=op.f("fk_multipart_model_choices_multipart_model_id_multipart_models"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["multipart_part_id"],
            ["multipart_parts.id"],
            name=op.f("fk_multipart_model_choices_multipart_part_id_multipart_parts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_multipart_model_choices")),
        sa.UniqueConstraint(
            "multipart_part_id",
            "sort_order",
            name="uq_multipart_choices_part_sort_order",
        ),
    )
    with op.batch_alter_table("multipart_model_choices", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_multipart_model_choices_model_id"),
            ["model_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_multipart_model_choices_source_file_id"),
            ["source_file_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_multipart_model_choices_multipart_model_id"),
            ["multipart_model_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_multipart_model_choices_multipart_part_id"),
            ["multipart_part_id"],
            unique=False,
        )

    _backfill_legacy_part_options()
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("multipart_model_choices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_multipart_model_choices_multipart_part_id"))
        batch_op.drop_index(batch_op.f("ix_multipart_model_choices_multipart_model_id"))
        batch_op.drop_index(batch_op.f("ix_multipart_model_choices_source_file_id"))
        batch_op.drop_index(batch_op.f("ix_multipart_model_choices_model_id"))

    op.drop_table("multipart_model_choices")
    with op.batch_alter_table("multipart_parts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_multipart_parts_multipart_model_id"))

    op.drop_table("multipart_parts")
    with op.batch_alter_table("multipart_models", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_multipart_models_updated_at"))
        batch_op.drop_index(batch_op.f("ix_multipart_models_slug"))
        batch_op.drop_index(batch_op.f("ix_multipart_models_name"))
        batch_op.drop_index(batch_op.f("ix_multipart_models_collection_id"))

    op.drop_table("multipart_models")
    # ### end Alembic commands ###


def _backfill_legacy_part_options() -> None:
    """Copy nested assembly rows without changing or deleting legacy tables.

    This is intentionally set based.  Besides being faster for a large library,
    using only INSERT...SELECT means the exact same statements are emitted by
    ``alembic upgrade --sql`` and executed during an online upgrade.
    """
    # New tables are empty at this revision.  The parent model id makes the slug
    # deterministic across imports and gives all subsequent INSERT...SELECT
    # statements a stable join key without relying on dialect-specific
    # RETURNING syntax.  Model hashes are unique and survive ID changes.
    op.execute(
        sa.text(
            """
            INSERT INTO multipart_models
              (name, slug, description, collection_id, created_by, updated_by,
               created_at, updated_at)
            SELECT m.name,
                   'legacy-parts-' || m.hash,
                   m.description, m.collection_id, m.created_by, m.updated_by,
                   m.created_at, m.updated_at
            FROM models m
            WHERE EXISTS (
                SELECT 1 FROM part_groups pg WHERE pg.model_id = m.id
            )
            """
        )
    )

    # Only groups with at least one resolvable target become visible parts.
    # Compacting their order with ROW_NUMBER avoids collisions after malformed
    # empty groups are omitted.  There is deliberately no synthetic parent
    # part: the legacy parent is only the grouping container, and a self-target
    # option is represented by its original PartOption below.
    op.execute(
        sa.text(
            """
            INSERT INTO multipart_parts
              (multipart_model_id, name, name_key, sort_order, created_at, updated_at)
            SELECT mm.id, pg.name, pg.name_key,
                   ROW_NUMBER() OVER (
                       PARTITION BY pg.model_id
                       ORDER BY pg.sort_order, pg.id
                   ) - 1,
                   pg.created_at, pg.created_at
            FROM part_groups pg
            JOIN multipart_models mm
              ON mm.slug = 'legacy-parts-' || (
                  SELECT parent.hash FROM models parent WHERE parent.id = pg.model_id
              )
            WHERE EXISTS (
                SELECT 1
                FROM part_options po
                LEFT JOIN files f ON f.id = po.file_id
                WHERE po.part_group_id = pg.id
                  AND COALESCE(po.model_id, f.model_id) IS NOT NULL
            )
            """
        )
    )

    # Preserve every valid option.  In particular, do not de-duplicate by
    # model_id: two legacy file options can refer to different files of one
    # Model and their labels/source files are part of the user-visible data.
    op.execute(
        sa.text(
            """
            INSERT INTO multipart_model_choices
              (multipart_model_id, multipart_part_id, model_id, source_file_id,
               label, sort_order, created_at)
            SELECT mm.id, mp.id, COALESCE(po.model_id, f.model_id), po.file_id,
                   po.name,
                   ROW_NUMBER() OVER (
                       PARTITION BY po.part_group_id
                       ORDER BY po.is_default DESC, po.sort_order, po.id
                   ) - 1,
                   po.created_at
            FROM part_options po
            JOIN part_groups pg ON pg.id = po.part_group_id
            JOIN multipart_models mm
              ON mm.slug = 'legacy-parts-' || (
                  SELECT parent.hash FROM models parent WHERE parent.id = pg.model_id
              )
            JOIN multipart_parts mp
              ON mp.multipart_model_id = mm.id
             AND mp.name_key = pg.name_key
            LEFT JOIN files f ON f.id = po.file_id
            WHERE COALESCE(po.model_id, f.model_id) IS NOT NULL
            """
        )
    )
