"""persist bounded mesh fingerprint continuations

Revision ID: 3bcdfeec6c4f
Revises: 8fd749bf52a1
Create Date: 2026-10-04 23:51:42.770902

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3bcdfeec6c4f"
down_revision: Union[str, Sequence[str], None] = "8fd749bf52a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mesh_fingerprint_continuations",
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=True),
        sa.Column("execution_epoch", sa.String(length=64), nullable=True),
        sa.Column("job_attempt", sa.Integer(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("metadata_recipe", sa.Integer(), nullable=False),
        sa.Column("algorithm_version", sa.String(length=128), nullable=False),
        sa.Column("triangle_cap", sa.Integer(), nullable=False),
        sa.Column("source_identity_json", sa.Text(), nullable=False),
        sa.Column("regenerated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "(job_id IS NULL AND execution_epoch IS NULL AND job_attempt IS NULL) OR (job_id IS NOT NULL AND execution_epoch IS NOT NULL AND job_attempt IS NOT NULL AND length(execution_epoch) > 0 AND job_attempt > 0)",
            name=op.f("ck_mesh_fingerprint_continuations_execution_identity"),
        ),
        sa.CheckConstraint(
            "attempts > 0",
            name=op.f("ck_mesh_fingerprint_continuations_attempts_positive"),
        ),
        sa.CheckConstraint(
            "length(algorithm_version) BETWEEN 1 AND 128",
            name=op.f("ck_mesh_fingerprint_continuations_continuation_algorithm"),
        ),
        sa.CheckConstraint(
            "length(source_identity_json) > 0",
            name=op.f("ck_mesh_fingerprint_continuations_continuation_source_identity"),
        ),
        sa.CheckConstraint(
            "length(source_sha256) = 64",
            name=op.f("ck_mesh_fingerprint_continuations_continuation_source_hash"),
        ),
        sa.CheckConstraint(
            "length(token) = 36",
            name=op.f("ck_mesh_fingerprint_continuations_continuation_token_length"),
        ),
        sa.CheckConstraint(
            "metadata_recipe > 0",
            name=op.f("ck_mesh_fingerprint_continuations_continuation_recipe_positive"),
        ),
        sa.CheckConstraint(
            "triangle_cap BETWEEN 100 AND 2000000",
            name=op.f("ck_mesh_fingerprint_continuations_continuation_face_cap"),
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
            name=op.f("fk_mesh_fingerprint_continuations_file_id_files"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "file_id", name=op.f("pk_mesh_fingerprint_continuations")
        ),
    )
    with op.batch_alter_table(
        "mesh_fingerprint_continuations", schema=None
    ) as batch_op:
        batch_op.create_index(
            "ix_mesh_fingerprint_continuations_available",
            ["available_at"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "mesh_fingerprint_continuations", schema=None
    ) as batch_op:
        batch_op.drop_index("ix_mesh_fingerprint_continuations_available")

    op.drop_table("mesh_fingerprint_continuations")
    # ### end Alembic commands ###
