"""add collection and artifact tags

Revision ID: 3e7ab53ac43d
Revises: f3a4f173d948
Create Date: 2026-08-31 21:45:19.792109

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3e7ab53ac43d"
down_revision: Union[str, Sequence[str], None] = "f3a4f173d948"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection_tags",
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
            name=op.f("fk_collection_tags_collection_id_collections"),
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name=op.f("fk_collection_tags_tag_id_tags")
        ),
        sa.PrimaryKeyConstraint(
            "collection_id", "tag_id", name=op.f("pk_collection_tags")
        ),
    )
    with op.batch_alter_table("collection_tags", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_collection_tags_tag_id"), ["tag_id"], unique=False
        )

    op.create_table(
        "file_tags",
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"], ["files.id"], name=op.f("fk_file_tags_file_id_files")
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name=op.f("fk_file_tags_tag_id_tags")
        ),
        sa.PrimaryKeyConstraint("file_id", "tag_id", name=op.f("pk_file_tags")),
    )
    with op.batch_alter_table("file_tags", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_file_tags_tag_id"), ["tag_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("file_tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_file_tags_tag_id"))

    op.drop_table("file_tags")
    with op.batch_alter_table("collection_tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_collection_tags_tag_id"))

    op.drop_table("collection_tags")
    # ### end Alembic commands ###
