"""add remote connection purposes

Revision ID: 4608a3ae9e23
Revises: 23bdc08ade8b
Create Date: 2026-09-02 20:17:02.652385

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4608a3ae9e23"
down_revision: Union[str, Sequence[str], None] = "23bdc08ade8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Both storage_connections.kind and external_libraries.source_kind use this
    # native enum on Postgres. SQLite persists the same labels as VARCHAR.
    if op.get_bind().dialect.name == "postgresql":
        op.execute("ALTER TYPE librarysourcekind ADD VALUE IF NOT EXISTS 'GDRIVE'")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("storage_connections", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "purpose",
                sa.Enum(
                    "LIBRARY",
                    "BACKUP",
                    name="storageconnectionpurpose",
                    native_enum=False,
                    length=16,
                ),
                server_default="LIBRARY",
                nullable=False,
            )
        )
        batch_op.create_index(
            batch_op.f("ix_storage_connections_purpose"), ["purpose"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("storage_connections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_storage_connections_purpose"))
        batch_op.drop_column("purpose")

    # ### end Alembic commands ###
    # GDRIVE remains in the Postgres enum: Postgres cannot remove an enum label
    # safely in place, and the extra accepted value is harmless after rollback.
