"""version reusable storage connection edits

Revision ID: 46d9d9f875bc
Revises: c9852ff533ee
Create Date: 2026-10-07 16:02:42.615343

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from app.db import connection_edit_contracts_v1

# revision identifiers, used by Alembic.
revision: str = "46d9d9f875bc"
down_revision: Union[str, Sequence[str], None] = "c9852ff533ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Frozen post-addition table for the SQLite default-removal rebuild and offline SQL.
_CONNECTIONS = sa.Table(
    "storage_connections",
    sa.MetaData(),
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("name", sa.String(128), nullable=False),
    sa.Column("kind", sa.String(7), nullable=False),
    sa.Column("config_json", sa.Text(), nullable=False),
    sa.Column("secret_json", sa.Text(), nullable=False),
    sa.Column("enabled", sa.Boolean(), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.Column("purpose", sa.String(16), server_default="LIBRARY", nullable=False),
    sa.Column(
        "manual_backup_enabled", sa.Boolean(), server_default="1", nullable=False
    ),
    sa.Column(
        "automatic_backup_enabled", sa.Boolean(), server_default="1", nullable=False
    ),
    sa.Column("edit_version", sa.BigInteger(), server_default="1", nullable=False),
    sa.Column(
        "edit_identity",
        sa.String(32),
        server_default="00000000000000000000000000000000",
        nullable=False,
    ),
    sa.PrimaryKeyConstraint("id", name="pk_storage_connections"),
    sa.Index("ix_storage_connections_name", "name", unique=True),
    sa.Index("ix_storage_connections_kind", "kind"),
    sa.Index("ix_storage_connections_enabled", "enabled"),
    sa.Index("ix_storage_connections_purpose", "purpose"),
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "storage_connections", schema=None, recreate="never"
    ) as batch_op:
        batch_op.add_column(
            sa.Column(
                "edit_version", sa.BigInteger(), server_default="1", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "edit_identity",
                sa.String(length=32),
                server_default="00000000000000000000000000000000",
                nullable=False,
            )
        )

    with op.batch_alter_table(
        "storage_connections", copy_from=_CONNECTIONS
    ) as batch_op:
        batch_op.alter_column(
            "edit_identity",
            existing_type=sa.String(32),
            existing_nullable=False,
            server_default=None,
        )
    connection_edit_contracts_v1.install(op.get_bind())

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    connection_edit_contracts_v1.uninstall(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "storage_connections", schema=None, recreate="never"
    ) as batch_op:
        batch_op.drop_column("edit_identity")
        batch_op.drop_column("edit_version")

    # ### end Alembic commands ###
