"""track search extraction dependencies and repair checkpoints

Revision ID: 4c5217a2a36f
Revises: bf435683b126
Create Date: 2026-09-11 18:20:22.964432

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c5217a2a36f"
down_revision: Union[str, Sequence[str], None] = "bf435683b126"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "search_dependencies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subject_type", sa.String(length=32), nullable=False),
        sa.Column("subject_id", sa.Integer(), nullable=False),
        sa.Column("source_kind", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_dependencies")),
        sa.UniqueConstraint(
            "subject_type",
            "subject_id",
            "source_kind",
            "source_id",
            name="uq_search_dependency_identity",
        ),
    )
    with op.batch_alter_table("search_dependencies", schema=None) as batch_op:
        batch_op.create_index(
            "ix_search_dependency_source", ["source_kind", "source_id"], unique=False
        )

    op.create_table(
        "search_reconciliation_states",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subject_type", sa.String(length=32), nullable=False),
        sa.Column("watermark_at", sa.DateTime(), nullable=False),
        sa.Column("watermark_id", sa.Integer(), nullable=False),
        sa.Column("partition_after_id", sa.Integer(), nullable=False),
        sa.Column("orphan_after_id", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_reconciliation_states")),
        sa.UniqueConstraint(
            "subject_type", name=op.f("uq_search_reconciliation_states_subject_type")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("search_reconciliation_states")
    with op.batch_alter_table("search_dependencies", schema=None) as batch_op:
        batch_op.drop_index("ix_search_dependency_source")

    op.drop_table("search_dependencies")
    # ### end Alembic commands ###
