"""add remote library sources

Revision ID: 51102a1c411e
Revises: 6dc6d8698ceb
Create Date: 2026-08-31 01:26:16.518790

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "51102a1c411e"
down_revision: Union[str, Sequence[str], None] = "6dc6d8698ceb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "storage_connections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("MOUNTED", "S3", "WEBDAV", "SFTP", name="librarysourcekind"),
            nullable=False,
        ),
        sa.Column("config_json", sa.Text(), nullable=False),
        # EncryptedText persists ciphertext in a regular TEXT column. Migrations
        # must not depend on the mutable ORM decorator implementation.
        sa.Column("secret_json", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_storage_connections")),
    )
    with op.batch_alter_table("storage_connections", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_storage_connections_enabled"), ["enabled"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_storage_connections_kind"), ["kind"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_storage_connections_name"), ["name"], unique=True
        )

    op.create_table(
        "external_library_checkpoints",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("epoch", sa.String(length=64), nullable=False),
        sa.Column("cursor", sa.String(length=2048), nullable=True),
        sa.Column("complete", sa.Boolean(), nullable=False),
        sa.Column("observed_keys_json", sa.Text(), nullable=False),
        sa.Column("metadata_ops", sa.Integer(), nullable=False),
        sa.Column("bytes_read", sa.BigInteger(), nullable=False),
        sa.Column("backoff_until", sa.DateTime(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["external_libraries.id"],
            name=op.f("fk_external_library_checkpoints_library_id_external_libraries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_library_checkpoints")),
        sa.UniqueConstraint("library_id", name="uq_external_library_checkpoint"),
    )
    with op.batch_alter_table("external_library_checkpoints", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_external_library_checkpoints_backoff_until"),
            ["backoff_until"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_external_library_checkpoints_complete"),
            ["complete"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_external_library_checkpoints_epoch"), ["epoch"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_external_library_checkpoints_library_id"),
            ["library_id"],
            unique=False,
        )

    op.create_table(
        "external_library_tombstones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("source_key", sa.String(length=2048), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("reason", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("cleared_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["external_libraries.id"],
            name=op.f("fk_external_library_tombstones_library_id_external_libraries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_library_tombstones")),
        sa.UniqueConstraint(
            "library_id", "source_key", name="uq_external_tombstone_source_key"
        ),
    )
    with op.batch_alter_table("external_library_tombstones", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_external_library_tombstones_cleared_at"),
            ["cleared_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_external_library_tombstones_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_external_library_tombstones_library_id"),
            ["library_id"],
            unique=False,
        )

    with op.batch_alter_table("external_libraries", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "source_kind",
                sa.Enum("MOUNTED", "S3", "WEBDAV", "SFTP", name="librarysourcekind"),
                server_default="MOUNTED",
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("connection_id", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "source_prefix",
                sa.String(length=1024),
                server_default="",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "writeback_enabled",
                sa.Boolean(),
                server_default=sa.false(),
                nullable=False,
            )
        )
        batch_op.create_index(
            batch_op.f("ix_external_libraries_connection_id"),
            ["connection_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_external_libraries_source_kind"),
            ["source_kind"],
            unique=False,
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_external_libraries_connection_id_storage_connections"),
            "storage_connections",
            ["connection_id"],
            ["id"],
        )

    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("source_key", sa.String(length=2048), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_files_source_key"), ["source_key"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_files_source_key"))
        batch_op.drop_column("source_key")

    with op.batch_alter_table("external_libraries", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_external_libraries_connection_id_storage_connections"),
            type_="foreignkey",
        )
        batch_op.drop_index(batch_op.f("ix_external_libraries_source_kind"))
        batch_op.drop_index(batch_op.f("ix_external_libraries_connection_id"))
        batch_op.drop_column("writeback_enabled")
        batch_op.drop_column("source_prefix")
        batch_op.drop_column("connection_id")
        batch_op.drop_column("source_kind")

    with op.batch_alter_table("external_library_tombstones", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_external_library_tombstones_library_id"))
        batch_op.drop_index(batch_op.f("ix_external_library_tombstones_created_at"))
        batch_op.drop_index(batch_op.f("ix_external_library_tombstones_cleared_at"))

    op.drop_table("external_library_tombstones")
    with op.batch_alter_table("external_library_checkpoints", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_external_library_checkpoints_library_id"))
        batch_op.drop_index(batch_op.f("ix_external_library_checkpoints_epoch"))
        batch_op.drop_index(batch_op.f("ix_external_library_checkpoints_complete"))
        batch_op.drop_index(batch_op.f("ix_external_library_checkpoints_backoff_until"))

    op.drop_table("external_library_checkpoints")
    with op.batch_alter_table("storage_connections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_storage_connections_name"))
        batch_op.drop_index(batch_op.f("ix_storage_connections_kind"))
        batch_op.drop_index(batch_op.f("ix_storage_connections_enabled"))

    op.drop_table("storage_connections")
    # ### end Alembic commands ###
