"""version external library source edits

Revision ID: 5291a5f0231c
Revises: 46d9d9f875bc
Create Date: 2026-10-07 16:30:45.300488

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from app.db import source_edit_contracts_v1

# revision identifiers, used by Alembic.
revision: str = "5291a5f0231c"
down_revision: Union[str, Sequence[str], None] = "46d9d9f875bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Frozen post-addition table for SQLite batch/offline default removal.
_SOURCES = sa.Table(
    "external_libraries",
    sa.MetaData(),
    sa.Column("id", sa.INTEGER(), nullable=False),
    sa.Column("name", sa.VARCHAR(length=128), nullable=False),
    sa.Column("root_path", sa.VARCHAR(length=1024), nullable=False),
    sa.Column("enabled", sa.BOOLEAN(), nullable=False),
    sa.Column("scan_interval_minutes", sa.INTEGER(), nullable=False),
    sa.Column("collection_mode", sa.VARCHAR(length=6), nullable=False),
    sa.Column("target_collection_id", sa.INTEGER(), nullable=True),
    sa.Column("last_scanned_at", sa.DATETIME(), nullable=True),
    sa.Column("last_scan_status", sa.VARCHAR(length=7), nullable=True),
    sa.Column("last_scan_summary", sa.TEXT(), nullable=True),
    sa.Column("created_at", sa.DATETIME(), nullable=False),
    sa.Column("updated_at", sa.DATETIME(), nullable=False),
    sa.Column("scan_schedule", sa.VARCHAR(length=128), nullable=False),
    sa.Column("watch_mode", sa.VARCHAR(length=6), nullable=False),
    sa.Column("fs_kind", sa.VARCHAR(length=16), nullable=True),
    sa.Column("scan_claim_token", sa.VARCHAR(length=64), nullable=True),
    sa.Column("scan_claim_expires_at", sa.DATETIME(), nullable=True),
    sa.Column("scan_job_id", sa.VARCHAR(length=64), nullable=True),
    sa.Column("root_identity", sa.VARCHAR(length=64), nullable=True),
    sa.Column("source_kind", sa.VARCHAR(length=7), nullable=False),
    sa.Column("connection_id", sa.INTEGER(), nullable=True),
    sa.Column("source_prefix", sa.VARCHAR(length=1024), nullable=False),
    sa.Column("writeback_enabled", sa.BOOLEAN(), nullable=False),
    sa.Column("scan_requested_at", sa.DATETIME(), nullable=True),
    sa.Column("scan_requested_path", sa.VARCHAR(length=2048), nullable=True),
    sa.Column("edit_version", sa.BigInteger(), server_default="1", nullable=False),
    sa.Column(
        "edit_identity",
        sa.String(32),
        server_default="00000000000000000000000000000000",
        nullable=False,
    ),
    sa.PrimaryKeyConstraint(*["id"], name="pk_external_libraries"),
    sa.ForeignKeyConstraint(
        ["connection_id"],
        ["storage_connections.id"],
        name="fk_external_libraries_connection_id_storage_connections",
    ),
    sa.ForeignKeyConstraint(
        ["target_collection_id"],
        ["collections.id"],
        name="fk_external_libraries_target_collection_id_collections",
    ),
    sa.Index("ix_external_libraries_connection_id", *["connection_id"], unique=False),
    sa.Index("ix_external_libraries_enabled", *["enabled"], unique=False),
    sa.Index("ix_external_libraries_root_identity", *["root_identity"], unique=False),
    sa.Index(
        "ix_external_libraries_scan_claim_expires_at",
        *["scan_claim_expires_at"],
        unique=False,
    ),
    sa.Index(
        "ix_external_libraries_scan_claim_token", *["scan_claim_token"], unique=False
    ),
    sa.Index("ix_external_libraries_scan_job_id", *["scan_job_id"], unique=False),
    sa.Index(
        "ix_external_libraries_scan_requested_at", *["scan_requested_at"], unique=False
    ),
    sa.Index("ix_external_libraries_source_kind", *["source_kind"], unique=False),
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "external_libraries", schema=None, recreate="never"
    ) as batch_op:
        batch_op.add_column(
            sa.Column(
                "edit_version", sa.BigInteger(), server_default="1", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "edit_identity",
                sa.String(length=32),
                server_default="00000000000000000000000000000000",
                nullable=False,
            )
        )

    with op.batch_alter_table("external_libraries", copy_from=_SOURCES) as batch_op:
        batch_op.alter_column(
            "edit_identity",
            existing_type=sa.String(32),
            existing_nullable=False,
            server_default=None,
        )
    source_edit_contracts_v1.install(op.get_bind())

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    source_edit_contracts_v1.uninstall(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "external_libraries", schema=None, recreate="never"
    ) as batch_op:
        batch_op.drop_column("edit_identity")
        batch_op.drop_column("edit_version")

    # ### end Alembic commands ###
