"""add model part options

Revision ID: 547387477ce4
Revises: 3e7ab53ac43d
Create Date: 2026-08-31 23:32:57.275750

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "547387477ce4"
down_revision: Union[str, Sequence[str], None] = "3e7ab53ac43d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "part_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("name_key", sa.String(length=128), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["models.id"],
            name=op.f("fk_part_groups_model_id_models"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_part_groups")),
        sa.UniqueConstraint(
            "model_id", "name_key", name="uq_part_groups_model_name_key"
        ),
        sa.UniqueConstraint(
            "model_id", "sort_order", name="uq_part_groups_model_sort_order"
        ),
    )
    with op.batch_alter_table("part_groups", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_part_groups_model_id"), ["model_id"], unique=False
        )

    op.create_table(
        "part_options",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("part_group_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("name_key", sa.String(length=128), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
            name=op.f("fk_part_options_file_id_files"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["part_group_id"],
            ["part_groups.id"],
            name=op.f("fk_part_options_part_group_id_part_groups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_part_options")),
        sa.UniqueConstraint("file_id", name="uq_part_options_file_id"),
        sa.UniqueConstraint(
            "part_group_id", "name_key", name="uq_part_options_group_name_key"
        ),
        sa.UniqueConstraint(
            "part_group_id", "sort_order", name="uq_part_options_group_sort_order"
        ),
    )
    with op.batch_alter_table("part_options", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_part_options_file_id"), ["file_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_part_options_part_group_id"), ["part_group_id"], unique=False
        )
        batch_op.create_index(
            "uq_part_options_one_default",
            ["part_group_id"],
            unique=True,
            sqlite_where=sa.text("is_default = 1"),
            postgresql_where=sa.text("is_default IS TRUE"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("part_options", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_part_options_one_default",
            sqlite_where=sa.text("is_default = 1"),
            postgresql_where=sa.text("is_default IS TRUE"),
        )
        batch_op.drop_index(batch_op.f("ix_part_options_part_group_id"))
        batch_op.drop_index(batch_op.f("ix_part_options_file_id"))

    op.drop_table("part_options")
    with op.batch_alter_table("part_groups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_part_groups_model_id"))

    op.drop_table("part_groups")
    # ### end Alembic commands ###
