"""point part options at models

Revision ID: 54b21089d3af
Revises: 547387477ce4
Create Date: 2026-09-01 14:37:23.043091

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "54b21089d3af"
down_revision: Union[str, Sequence[str], None] = "547387477ce4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("part_options", schema=None) as batch_op:
        batch_op.add_column(sa.Column("model_id", sa.Integer(), nullable=True))
        batch_op.alter_column("file_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.create_index(
            batch_op.f("ix_part_options_model_id"), ["model_id"], unique=False
        )
        batch_op.create_unique_constraint("uq_part_options_model_id", ["model_id"])
        batch_op.create_foreign_key(
            batch_op.f("fk_part_options_model_id_models"),
            "models",
            ["model_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_part_options_part_option_exactly_one_target"),
            "(file_id IS NULL) != (model_id IS NULL)",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Defensive cleanup for rows inserted outside the API without a source
    # Artifact: keeping a malformed group would violate the old NOT NULL shape.
    op.execute(
        sa.text(
            """
            DELETE FROM part_groups
            WHERE id IN (
                SELECT part_group_id
                FROM part_options
                WHERE model_id IS NOT NULL
                  AND NOT EXISTS (
                      SELECT 1
                      FROM files
                      WHERE files.model_id = part_options.model_id
                        AND files.deleted_at IS NULL
                        AND files.file_type != 'GCODE'
                  )
            )
            """
        )
    )
    # The old schema can only point at an Artifact. Preserve the member identity
    # by selecting its first source Artifact before dropping ``model_id``.
    op.execute(
        sa.text(
            """
            UPDATE part_options
            SET file_id = (
                SELECT MIN(files.id)
                FROM files
                WHERE files.model_id = part_options.model_id
                  AND files.deleted_at IS NULL
                  AND files.file_type != 'GCODE'
            ), model_id = NULL
            WHERE model_id IS NOT NULL
            """
        )
    )
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("part_options", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("ck_part_options_part_option_exactly_one_target"),
            type_="check",
        )
        batch_op.drop_constraint(
            batch_op.f("fk_part_options_model_id_models"), type_="foreignkey"
        )
        batch_op.drop_constraint("uq_part_options_model_id", type_="unique")
        batch_op.drop_index(batch_op.f("ix_part_options_model_id"))
        batch_op.alter_column("file_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column("model_id")

    # ### end Alembic commands ###
