"""add durable gc safety plans

Revision ID: 6dc6d8698ceb
Revises: c3ec006ced6a
Create Date: 2026-08-31 01:12:43.153940

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6dc6d8698ceb"
down_revision: Union[str, Sequence[str], None] = "c3ec006ced6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gc_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "preview",
                "quarantined",
                "finalizing",
                "completed",
                "aborted",
                "blocked",
                name="gcrunstate",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("retention_days", sa.Integer(), nullable=False),
        sa.Column("cutoff_at", sa.DateTime(), nullable=False),
        sa.Column("resource_count", sa.Integer(), nullable=False),
        sa.Column("candidate_pool_count", sa.Integer(), nullable=False),
        sa.Column("key_count", sa.Integer(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("scheduled", sa.Boolean(), nullable=False),
        sa.Column("requested_by", sa.Integer(), nullable=True),
        sa.Column("approved_by", sa.Integer(), nullable=True),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("quarantine_until", sa.DateTime(), nullable=True),
        sa.Column("backup_id", sa.String(length=255), nullable=True),
        sa.Column("backup_source_ref", sa.String(length=64), nullable=True),
        sa.Column("backup_provider_ref", sa.String(length=64), nullable=True),
        sa.Column("backup_archive_sha256", sa.String(length=64), nullable=True),
        sa.Column("backup_verified_at", sa.DateTime(), nullable=True),
        sa.Column("active_provider_ref", sa.String(length=64), nullable=True),
        sa.Column("restore_generation", sa.String(length=64), nullable=False),
        sa.Column("last_error", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["approved_by"], ["users.id"], name=op.f("fk_gc_runs_approved_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"], ["users.id"], name=op.f("fk_gc_runs_requested_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gc_runs")),
    )
    with op.batch_alter_table("gc_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_gc_runs_approved_at"), ["approved_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_gc_runs_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_gc_runs_cutoff_at"), ["cutoff_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_gc_runs_digest"), ["digest"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_gc_runs_quarantine_until"),
            ["quarantine_until"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_gc_runs_state"), ["state"], unique=False)

    op.create_table(
        "gc_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("resource_kind", sa.String(length=32), nullable=False),
        sa.Column("resource_id", sa.Integer(), nullable=False),
        sa.Column("deleted_at_snapshot", sa.DateTime(), nullable=False),
        sa.Column("key_count", sa.Integer(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["gc_runs.id"],
            name=op.f("fk_gc_items_run_id_gc_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gc_items")),
        sa.UniqueConstraint(
            "run_id", "resource_kind", "resource_id", name="uq_gc_item_resource"
        ),
    )
    with op.batch_alter_table("gc_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_gc_items_resource_id"), ["resource_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_gc_items_resource_kind"), ["resource_kind"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_gc_items_run_id"), ["run_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gc_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_gc_items_run_id"))
        batch_op.drop_index(batch_op.f("ix_gc_items_resource_kind"))
        batch_op.drop_index(batch_op.f("ix_gc_items_resource_id"))

    op.drop_table("gc_items")
    with op.batch_alter_table("gc_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_gc_runs_state"))
        batch_op.drop_index(batch_op.f("ix_gc_runs_quarantine_until"))
        batch_op.drop_index(batch_op.f("ix_gc_runs_digest"))
        batch_op.drop_index(batch_op.f("ix_gc_runs_cutoff_at"))
        batch_op.drop_index(batch_op.f("ix_gc_runs_created_at"))
        batch_op.drop_index(batch_op.f("ix_gc_runs_approved_at"))

    op.drop_table("gc_runs")
    # ### end Alembic commands ###
