"""add durable backup runs and replica retry attempts

Revision ID: 73644b08645c
Revises: 046685afd7ea
Create Date: 2026-09-05 16:55:20.863198

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '73644b08645c'
down_revision: Union[str, Sequence[str], None] = '046685afd7ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('backup_id', sa.String(length=64), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('archive_name', sa.String(length=255), nullable=False),
    sa.Column('archive_sha256', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=True),
    sa.Column('storage_backend', sa.String(length=64), nullable=False),
    sa.Column('app_version', sa.String(length=64), nullable=False),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup_runs'))
    )
    with op.batch_alter_table('backup_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup_runs_backup_id'), ['backup_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_runs_outcome'), ['outcome'], unique=False)

    op.create_table('backup_destination_results',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('configuration_json', sa.Text(), nullable=False),
    sa.Column('target_identity_json', sa.Text(), nullable=True),
    sa.Column('provider_ref', sa.String(length=64), nullable=True),
    sa.Column('namespace', sa.Text(), nullable=True),
    sa.Column('key', sa.Text(), nullable=True),
    sa.Column('source_ref', sa.String(length=64), nullable=True),
    sa.Column('ownership_id', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ownership_id'], ['owned_storage_objects.id'], name=op.f('fk_backup_destination_results_ownership_id_owned_storage_objects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['backup_runs.id'], name=op.f('fk_backup_destination_results_run_id_backup_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup_destination_results'))
    )
    with op.batch_alter_table('backup_destination_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup_destination_results_connection_id'), ['connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_destination_results_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_destination_results_run_id'), ['run_id'], unique=False)

    op.create_table('backup_retry_attempts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('destination_result_id', sa.String(), nullable=False),
    sa.Column('source_result_id', sa.String(length=64), nullable=True),
    sa.Column('archive_sha256', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destination_result_id'], ['backup_destination_results.id'], name=op.f('fk_backup_retry_attempts_destination_result_id_backup_destination_results'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup_retry_attempts'))
    )
    with op.batch_alter_table('backup_retry_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup_retry_attempts_destination_result_id'), ['destination_result_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backup_retry_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup_retry_attempts_destination_result_id'))

    op.drop_table('backup_retry_attempts')
    with op.batch_alter_table('backup_destination_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup_destination_results_run_id'))
        batch_op.drop_index(batch_op.f('ix_backup_destination_results_outcome'))
        batch_op.drop_index(batch_op.f('ix_backup_destination_results_connection_id'))

    op.drop_table('backup_destination_results')
    with op.batch_alter_table('backup_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup_runs_outcome'))
        batch_op.drop_index(batch_op.f('ix_backup_runs_created_at'))
        batch_op.drop_index(batch_op.f('ix_backup_runs_backup_id'))

    op.drop_table('backup_runs')
    # ### end Alembic commands ###
