"""version browser name edits independently from activity

Revision ID: 7af8bb13c174
Revises: 0a76fbca8438
Create Date: 2026-10-07 13:59:14.084944

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from app.db import browser_edit_contracts_v1

# revision identifiers, used by Alembic.
revision: str = "7af8bb13c174"
down_revision: Union[str, Sequence[str], None] = "0a76fbca8438"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "browser_devices", schema=None, recreate="never"
    ) as batch_op:
        batch_op.add_column(
            sa.Column(
                "edit_version", sa.BigInteger(), server_default="1", nullable=False
            )
        )

    browser_edit_contracts_v1.install(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove the additive contract without rebuilding away other triggers."""
    browser_edit_contracts_v1.uninstall(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "browser_devices", schema=None, recreate="never"
    ) as batch_op:
        batch_op.drop_column("edit_version")

    # ### end Alembic commands ###
