"""add resumable artifact uploads

Revision ID: 7d07ebda70ef
Revises: 00cb0e8975d1
Create Date: 2026-09-09 05:48:06.659148

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d07ebda70ef"
down_revision: Union[str, Sequence[str], None] = "00cb0e8975d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifact_upload_sessions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("owner_user_id", sa.Integer(), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("target_role", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.String(length=128), nullable=True),
        sa.Column("request_json", sa.Text(), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("media_type", sa.String(length=128), nullable=False),
        sa.Column("declared_size", sa.BigInteger(), nullable=False),
        sa.Column("client_sha256", sa.String(length=64), nullable=True),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("adapter_id", sa.String(length=32), nullable=False),
        sa.Column("destination_ref", sa.String(length=512), nullable=True),
        sa.Column("protected_native_id", sa.Text(), nullable=True),
        sa.Column("staging_identity_json", sa.Text(), nullable=True),
        sa.Column("received_bytes", sa.BigInteger(), nullable=False),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("retryable", sa.Boolean(), nullable=False),
        sa.Column("verified_size", sa.BigInteger(), nullable=True),
        sa.Column("verified_sha256", sa.String(length=64), nullable=True),
        sa.Column("background_job_id", sa.String(length=64), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "state IN ('created', 'uploading', 'verifying', 'ingesting', 'completed', 'failed', 'aborted', 'expired')",
            name=op.f("ck_artifact_upload_sessions_ck_artifact_upload_state"),
        ),
        sa.CheckConstraint(
            "declared_size >= 0",
            name=op.f("ck_artifact_upload_sessions_ck_artifact_upload_declared_size"),
        ),
        sa.CheckConstraint(
            "received_bytes >= 0",
            name=op.f("ck_artifact_upload_sessions_ck_artifact_upload_received_bytes"),
        ),
        sa.CheckConstraint(
            "verified_size IS NULL OR verified_size >= 0",
            name=op.f("ck_artifact_upload_sessions_ck_artifact_upload_verified_size"),
        ),
        sa.CheckConstraint(
            "version >= 0",
            name=op.f("ck_artifact_upload_sessions_ck_artifact_upload_version"),
        ),
        sa.ForeignKeyConstraint(
            ["background_job_id"],
            ["background_jobs.id"],
            name=op.f("fk_artifact_upload_sessions_background_job_id_background_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_artifact_upload_sessions_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifact_upload_sessions")),
    )
    with op.batch_alter_table("artifact_upload_sessions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_artifact_upload_owner_state_updated",
            ["owner_user_id", "state", "updated_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_artifact_upload_sessions_background_job_id"),
            ["background_job_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_artifact_upload_sessions_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_artifact_upload_sessions_expires_at"),
            ["expires_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_artifact_upload_sessions_owner_user_id"),
            ["owner_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_artifact_upload_sessions_purpose"), ["purpose"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_artifact_upload_sessions_retryable"),
            ["retryable"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_artifact_upload_sessions_state"), ["state"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_artifact_upload_sessions_target_id"),
            ["target_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_artifact_upload_sessions_target_role"),
            ["target_role"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_artifact_upload_sessions_updated_at"),
            ["updated_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_artifact_upload_sessions_verified_sha256"),
            ["verified_sha256"],
            unique=False,
        )

    op.create_table(
        "artifact_upload_parts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("part_number", sa.Integer(), nullable=False),
        sa.Column("byte_offset", sa.BigInteger(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("provider_receipt_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "byte_offset >= 0",
            name=op.f("ck_artifact_upload_parts_ck_artifact_upload_part_offset"),
        ),
        sa.CheckConstraint(
            "part_number >= 1",
            name=op.f("ck_artifact_upload_parts_ck_artifact_upload_part_number"),
        ),
        sa.CheckConstraint(
            "size_bytes > 0",
            name=op.f("ck_artifact_upload_parts_ck_artifact_upload_part_size"),
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["artifact_upload_sessions.id"],
            name=op.f("fk_artifact_upload_parts_session_id_artifact_upload_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifact_upload_parts")),
        sa.UniqueConstraint(
            "session_id", "part_number", name="uq_artifact_upload_part_number"
        ),
    )
    with op.batch_alter_table("artifact_upload_parts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_artifact_upload_parts_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_artifact_upload_parts_session_id"),
            ["session_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("artifact_upload_parts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_artifact_upload_parts_session_id"))
        batch_op.drop_index(batch_op.f("ix_artifact_upload_parts_created_at"))

    op.drop_table("artifact_upload_parts")
    with op.batch_alter_table("artifact_upload_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_artifact_upload_sessions_verified_sha256"))
        batch_op.drop_index(batch_op.f("ix_artifact_upload_sessions_updated_at"))
        batch_op.drop_index(batch_op.f("ix_artifact_upload_sessions_target_role"))
        batch_op.drop_index(batch_op.f("ix_artifact_upload_sessions_target_id"))
        batch_op.drop_index(batch_op.f("ix_artifact_upload_sessions_state"))
        batch_op.drop_index(batch_op.f("ix_artifact_upload_sessions_retryable"))
        batch_op.drop_index(batch_op.f("ix_artifact_upload_sessions_purpose"))
        batch_op.drop_index(batch_op.f("ix_artifact_upload_sessions_owner_user_id"))
        batch_op.drop_index(batch_op.f("ix_artifact_upload_sessions_expires_at"))
        batch_op.drop_index(batch_op.f("ix_artifact_upload_sessions_created_at"))
        batch_op.drop_index(batch_op.f("ix_artifact_upload_sessions_background_job_id"))
        batch_op.drop_index("ix_artifact_upload_owner_state_updated")

    op.drop_table("artifact_upload_sessions")
    # ### end Alembic commands ###
