"""link documents to multipart models

Revision ID: 7f460c4cf1f3
Revises: 30c1c4a321a5
Create Date: 2026-09-02 09:19:04.580314

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f460c4cf1f3"
down_revision: Union[str, Sequence[str], None] = "30c1c4a321a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("multipart_model_id", sa.Integer(), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_documents_multipart_model_id"),
            ["multipart_model_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_documents_multipart_model_id_multipart_models"),
            "multipart_models",
            ["multipart_model_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_documents_multipart_model_id_multipart_models"),
            type_="foreignkey",
        )
        batch_op.drop_index(batch_op.f("ix_documents_multipart_model_id"))
        batch_op.drop_column("multipart_model_id")

    # ### end Alembic commands ###
