"""add durable search generation lifecycle and reader leases

Revision ID: 7fec0b53bb5c
Revises: bf6dfc561eca
Create Date: 2026-09-11 20:33:25.810868

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7fec0b53bb5c"
down_revision: Union[str, Sequence[str], None] = "bf6dfc561eca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "search_generation_leases",
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("generation_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["generation_id"],
            ["index_generations.id"],
            name=op.f("fk_search_generation_leases_generation_id_index_generations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("token", name=op.f("pk_search_generation_leases")),
    )
    with op.batch_alter_table("search_generation_leases", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_search_generation_leases_expires_at"),
            ["expires_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_search_generation_leases_generation_id"),
            ["generation_id"],
            unique=False,
        )

    op.create_table(
        "search_index_failures",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("generation_id", sa.Integer(), nullable=False),
        sa.Column("passage_id", sa.Integer(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("retry_after", sa.DateTime(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["generation_id"],
            ["index_generations.id"],
            name=op.f("fk_search_index_failures_generation_id_index_generations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["passage_id"],
            ["search_passages.id"],
            name=op.f("fk_search_index_failures_passage_id_search_passages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_index_failures")),
        sa.UniqueConstraint(
            "generation_id",
            "passage_id",
            "input_hash",
            name="uq_search_index_failure_unit",
        ),
    )
    with op.batch_alter_table("search_index_failures", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_search_index_failures_generation_id"),
            ["generation_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_search_index_failures_passage_id"),
            ["passage_id"],
            unique=False,
        )

    with op.batch_alter_table("index_generations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("version_token", sa.String(length=32), nullable=True)
        )
        batch_op.add_column(sa.Column("actor_id", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("replaces_generation_id", sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("lease_token", sa.String(length=64), nullable=True)
        )
        batch_op.add_column(sa.Column("lease_expires_at", sa.DateTime(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "cancel_requested", sa.Boolean(), server_default="0", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column("auto_activate", sa.Boolean(), server_default="0", nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "passage_after_id", sa.Integer(), server_default="0", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "reconcile_kind", sa.Integer(), server_default="0", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column("processed", sa.Integer(), server_default="0", nullable=False)
        )
        batch_op.add_column(
            sa.Column("copied", sa.Integer(), server_default="0", nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "truncated_count", sa.Integer(), server_default="0", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "verified_count", sa.Integer(), server_default="0", nullable=False
            )
        )
        batch_op.add_column(sa.Column("verified_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("last_activity_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("activated_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("retired_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("retain_until", sa.DateTime(), nullable=True))
        batch_op.add_column(
            sa.Column("error_code", sa.String(length=64), nullable=True)
        )
        batch_op.add_column(sa.Column("job_id", sa.String(length=64), nullable=True))
        batch_op.add_column(
            sa.Column("reservation_id", sa.String(length=128), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "estimated_bytes", sa.Integer(), server_default="0", nullable=False
            )
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_index_generations_actor_id_users"),
            "users",
            ["actor_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("passage_vectors", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("truncated", sa.Boolean(), server_default="0", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("passage_vectors", schema=None) as batch_op:
        batch_op.drop_column("truncated")

    with op.batch_alter_table("index_generations", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_index_generations_actor_id_users"), type_="foreignkey"
        )
        batch_op.drop_column("estimated_bytes")
        batch_op.drop_column("reservation_id")
        batch_op.drop_column("job_id")
        batch_op.drop_column("error_code")
        batch_op.drop_column("retain_until")
        batch_op.drop_column("retired_at")
        batch_op.drop_column("activated_at")
        batch_op.drop_column("last_activity_at")
        batch_op.drop_column("verified_at")
        batch_op.drop_column("verified_count")
        batch_op.drop_column("truncated_count")
        batch_op.drop_column("copied")
        batch_op.drop_column("processed")
        batch_op.drop_column("reconcile_kind")
        batch_op.drop_column("passage_after_id")
        batch_op.drop_column("auto_activate")
        batch_op.drop_column("cancel_requested")
        batch_op.drop_column("lease_expires_at")
        batch_op.drop_column("lease_token")
        batch_op.drop_column("replaces_generation_id")
        batch_op.drop_column("actor_id")
        batch_op.drop_column("version_token")

    with op.batch_alter_table("search_index_failures", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_search_index_failures_passage_id"))
        batch_op.drop_index(batch_op.f("ix_search_index_failures_generation_id"))

    op.drop_table("search_index_failures")
    with op.batch_alter_table("search_generation_leases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_search_generation_leases_generation_id"))
        batch_op.drop_index(batch_op.f("ix_search_generation_leases_expires_at"))

    op.drop_table("search_generation_leases")
    # ### end Alembic commands ###
