"""Preserve frozen batch units and incremental outcomes across interrupted imports.

Revision ID: 809afb73e776
Revises: 85a30cfcf7ba
Create Date: 2026-10-05 07:40:32.339720

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "809afb73e776"
down_revision: Union[str, Sequence[str], None] = "85a30cfcf7ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingestion_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=True),
        sa.Column("inbox_item_id", sa.Integer(), nullable=True),
        sa.Column("entry_key", sa.String(length=64), nullable=False),
        sa.Column("identity", sa.Text(), nullable=False),
        sa.Column("display_name", sa.String(length=512), nullable=False),
        sa.Column("descriptor_json", sa.Text(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=True),
        sa.Column("file_id", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("retryable", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "(state IN ('failed', 'skipped') AND error_code IS NOT NULL AND length(error_code) > 0) OR (state NOT IN ('failed', 'skipped') AND error_code IS NULL)",
            name=op.f("ck_ingestion_entries_entry_diagnostic"),
        ),
        sa.CheckConstraint(
            "NOT retryable OR state = 'failed'",
            name=op.f("ck_ingestion_entries_entry_retryable"),
        ),
        sa.CheckConstraint(
            "state IN ('pending', 'imported', 'deduplicated', 'failed', 'skipped')",
            name=op.f("ck_ingestion_entries_state_values"),
        ),
        sa.CheckConstraint(
            "(job_id IS NULL) <> (inbox_item_id IS NULL)",
            name=op.f("ck_ingestion_entries_entry_owner"),
        ),
        sa.CheckConstraint(
            "length(entry_key) = 64",
            name=op.f("ck_ingestion_entries_entry_key_present"),
        ),
        sa.CheckConstraint(
            "ordinal >= 0", name=op.f("ck_ingestion_entries_entry_ordinal_nonnegative")
        ),
        sa.CheckConstraint(
            "size_bytes IS NULL OR size_bytes >= 0",
            name=op.f("ck_ingestion_entries_entry_size_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
            name=op.f("fk_ingestion_entries_file_id_files"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["inbox_item_id"],
            ["inbox_items.id"],
            name=op.f("fk_ingestion_entries_inbox_item_id_inbox_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_ingestion_entries_job_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["models.id"],
            name=op.f("fk_ingestion_entries_model_id_models"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_entries")),
        sa.UniqueConstraint(
            "inbox_item_id", "entry_key", name="uq_ingestion_entry_inbox_key"
        ),
        sa.UniqueConstraint("job_id", "entry_key", name="uq_ingestion_entry_job_key"),
    )
    with op.batch_alter_table("ingestion_entries", schema=None) as batch_op:
        batch_op.create_index(
            "ix_ingestion_entries_inbox_page", ["inbox_item_id", "id"], unique=False
        )
        batch_op.create_index(
            "ix_ingestion_entries_inbox_state_order",
            ["inbox_item_id", "state", "ordinal", "id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_ingestion_entries_job_page", ["job_id", "id"], unique=False
        )
        batch_op.create_index(
            "ix_ingestion_entries_job_state_order",
            ["job_id", "state", "ordinal", "id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ingestion_entries", schema=None) as batch_op:
        batch_op.drop_index("ix_ingestion_entries_job_state_order")
        batch_op.drop_index("ix_ingestion_entries_job_page")
        batch_op.drop_index("ix_ingestion_entries_inbox_state_order")
        batch_op.drop_index("ix_ingestion_entries_inbox_page")

    op.drop_table("ingestion_entries")
    # ### end Alembic commands ###
