"""Pin the historical root for legacy S3 configurations.

Revision ID: 8c44c3bfef74
Revises: 92525c540994
Create Date: 2026-08-30 06:00:10.122969

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c44c3bfef74"
down_revision: Union[str, Sequence[str], None] = "92525c540994"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add the compatibility root and preserve v0.12 object locations."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("system_config", schema=None) as batch_op:
        batch_op.add_column(sa.Column("s3_root", sa.String(length=1024), nullable=True))

    # v0.12's untyped S3 backend always used this literal prefix.  Do not use
    # the current environment here: that could strand objects when an operator
    # upgraded with a different VAULT_S3_ROOT.  Typed-provider rows are left
    # untouched because their root is stored in provider JSON.
    op.execute(
        sa.text(
            "UPDATE system_config SET s3_root = 'vault-data' "
            "WHERE storage_backend = 's3' "
            "AND (storage_provider IS NULL OR storage_provider = '') "
            "AND s3_root IS NULL"
        )
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("system_config", schema=None) as batch_op:
        batch_op.drop_column("s3_root")

    # ### end Alembic commands ###
