"""serialize storage publication retirement

Revision ID: 8ce8989462c0
Revises: 809afb73e776
Create Date: 2026-10-05 14:19:02.481674

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ce8989462c0"
down_revision: Union[str, Sequence[str], None] = "809afb73e776"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "storage_publication_locators",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("backend", sa.String(length=32), nullable=False),
        sa.Column("namespace", sa.String(length=1024), nullable=False),
        sa.Column("key", sa.String(length=2048), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_storage_publication_locators")),
    )
    with op.batch_alter_table("owned_storage_objects", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("publication_generation", sa.String(length=64), nullable=True)
        )
        batch_op.add_column(sa.Column("next_recovery_at", sa.DateTime(), nullable=True))
        batch_op.alter_column(
            "state",
            existing_type=sa.VARCHAR(length=16),
            type_=sa.Text(),
            existing_nullable=False,
        )
    # Preserve populated historical receipts before requiring generation identity.
    op.execute(
        sa.text(
            "UPDATE owned_storage_objects SET publication_generation = 'legacy-' || CAST(id AS TEXT)"
        )
    )
    with op.batch_alter_table("owned_storage_objects", schema=None) as batch_op:
        batch_op.alter_column(
            "publication_generation", existing_type=sa.String(length=64), nullable=False
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_owned_storage_objects_publication_generation_present"),
            "length(publication_generation) > 0",
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_owned_storage_objects_state_values"),
            "state IN ('pending', 'committed', 'blocked', 'retiring')",
        )
        batch_op.drop_index(
            batch_op.f("uq_owned_storage_legacy_locator"),
            sqlite_where=sa.text("provider_ref IS NULL"),
        )
        batch_op.drop_constraint(
            batch_op.f("uq_owned_storage_provider_locator"), type_="unique"
        )
        batch_op.create_index(
            batch_op.f("ix_owned_storage_objects_next_recovery_at"),
            ["next_recovery_at"],
            unique=False,
        )
        batch_op.create_index(
            "uq_owned_storage_active_legacy_locator",
            ["backend", "namespace", "key"],
            unique=True,
            sqlite_where=sa.text("provider_ref IS NULL AND state != 'retiring'"),
            postgresql_where=sa.text("provider_ref IS NULL AND state != 'retiring'"),
        )
        batch_op.create_index(
            "uq_owned_storage_active_provider_locator",
            ["backend", "provider_ref", "namespace", "key"],
            unique=True,
            sqlite_where=sa.text("provider_ref IS NOT NULL AND state != 'retiring'"),
            postgresql_where=sa.text(
                "provider_ref IS NOT NULL AND state != 'retiring'"
            ),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Refuse to erase the authority of a retired generation."""
    if op.get_context().as_sql:
        raise RuntimeError("storage_retirement_downgrade_requires_online_validation")
    retired = (
        op.get_bind()
        .execute(
            sa.text(
                "SELECT id FROM owned_storage_objects WHERE state = 'retiring' LIMIT 1"
            )
        )
        .first()
    )
    if retired is not None:
        raise RuntimeError("storage_retirement_history_prevents_downgrade")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("owned_storage_objects", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_owned_storage_active_provider_locator",
            sqlite_where=sa.text("provider_ref IS NOT NULL AND state != 'retiring'"),
            postgresql_where=sa.text(
                "provider_ref IS NOT NULL AND state != 'retiring'"
            ),
        )
        batch_op.drop_index(
            "uq_owned_storage_active_legacy_locator",
            sqlite_where=sa.text("provider_ref IS NULL AND state != 'retiring'"),
            postgresql_where=sa.text("provider_ref IS NULL AND state != 'retiring'"),
        )
        batch_op.drop_index(batch_op.f("ix_owned_storage_objects_next_recovery_at"))
        batch_op.create_unique_constraint(
            batch_op.f("uq_owned_storage_provider_locator"),
            ["backend", "provider_ref", "namespace", "key"],
        )
        batch_op.create_index(
            batch_op.f("uq_owned_storage_legacy_locator"),
            ["backend", "namespace", "key"],
            unique=1,
            sqlite_where=sa.text("provider_ref IS NULL"),
        )
        batch_op.drop_constraint(
            batch_op.f("ck_owned_storage_objects_state_values"), type_="check"
        )
        batch_op.drop_constraint(
            batch_op.f("ck_owned_storage_objects_publication_generation_present"),
            type_="check",
        )
        batch_op.alter_column(
            "state",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(length=16),
            existing_nullable=False,
        )
        batch_op.drop_column("next_recovery_at")
        batch_op.drop_column("publication_generation")

    op.drop_table("storage_publication_locators")
    # ### end Alembic commands ###
