"""Add durable identities for external-library root enrollment.

Legacy rows remain NULL and are intentionally handled as unbound by the
runtime until an administrator explicitly enrolls the existing directory.

Revision ID: 92525c540994
Revises: beab532a9998
Create Date: 2026-08-30 04:20:48.401387

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "92525c540994"
down_revision: Union[str, Sequence[str], None] = "beab532a9998"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("external_libraries", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("root_identity", sa.String(length=64), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_external_libraries_root_identity"),
            ["root_identity"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("external_libraries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_external_libraries_root_identity"))
        batch_op.drop_column("root_identity")

    # ### end Alembic commands ###
