"""add durable restore marker

Revision ID: 9a7a42dcf8e5
Revises: 02b4f9e2f6f1
Create Date: 2026-08-29 19:10:24.947840

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9a7a42dcf8e5'
down_revision: Union[str, Sequence[str], None] = '02b4f9e2f6f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restore_markers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backup_id', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_restore_markers')),
    sa.UniqueConstraint('backup_id', name='uq_restore_marker_backup')
    )
    with op.batch_alter_table('restore_markers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restore_markers_backup_id'), ['backup_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_restore_markers_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_restore_markers_state'), ['state'], unique=False)

    with op.batch_alter_table('storage_delete_intents', schema=None) as batch_op:
        batch_op.alter_column('authorization_mode',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('authorized_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('quarantine_state',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storage_delete_intents', schema=None) as batch_op:
        batch_op.alter_column('quarantine_state',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'none'"),
               existing_nullable=False)
        batch_op.alter_column('authorized_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
        batch_op.alter_column('authorization_mode',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'verified'"),
               existing_nullable=False)

    with op.batch_alter_table('restore_markers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restore_markers_state'))
        batch_op.drop_index(batch_op.f('ix_restore_markers_created_at'))
        batch_op.drop_index(batch_op.f('ix_restore_markers_backup_id'))

    op.drop_table('restore_markers')
    # ### end Alembic commands ###
