"""add live derivative processing controls

Revision ID: a1d9da54fb03
Revises: 489225f7b46b
Create Date: 2026-09-30 23:08:19.286224

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1d9da54fb03"
down_revision: Union[str, Sequence[str], None] = "489225f7b46b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "derivative_group_regenerations",
        sa.Column("definition", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("requested_at", sa.DateTime(), nullable=False),
        sa.Column("requested_by", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "definition IN ('administration.audit', 'backups.automatic', 'backups.create', 'backups.retry_destination', 'backups.trash_gc', 'derivatives.gcode', 'derivatives.mesh', 'derivatives.toolpath', 'identity.retention', 'inference.model_download', 'ingestion.archive_inspect', 'ingestion.archive_selection', 'ingestion.artifact_upload', 'ingestion.collection', 'ingestion.inbox_import', 'ingestion.inbox_resolve', 'ingestion.inbox_retention', 'ingestion.library_import', 'ingestion.upload', 'ingestion.upload_recovery', 'ingestion.url', 'ingestion.url_selection', 'notifications.deliver', 'notifications.retention', 'printing.dispatch', 'search.caption', 'search.caption_queue', 'search.expand', 'search.generation', 'search.index', 'search.project', 'search.repair', 'similarity.analyze', 'sources.scan', 'storage.inventory', 'storage.migrate', 'work.housekeeping')",
            name=op.f("ck_derivative_group_regenerations_definition_values"),
        ),
        sa.CheckConstraint(
            "kind IN ('metadata', 'thumbnail', 'toolpath')",
            name=op.f("ck_derivative_group_regenerations_kind_values"),
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
            name=op.f("fk_derivative_group_regenerations_requested_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint(
            "definition", "kind", name=op.f("pk_derivative_group_regenerations")
        ),
    )
    with op.batch_alter_table("system_config", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("derivatives_mesh_enabled", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("derivatives_gcode_enabled", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("derivatives_toolpath_enabled", sa.Boolean(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("system_config", schema=None) as batch_op:
        batch_op.drop_column("derivatives_toolpath_enabled")
        batch_op.drop_column("derivatives_gcode_enabled")
        batch_op.drop_column("derivatives_mesh_enabled")

    op.drop_table("derivative_group_regenerations")
    # ### end Alembic commands ###
