"""Version the vault configuration aggregate without counting operational progress.

Revision ID: ae086ab363c8
Revises: ed85e4d73965
Create Date: 2026-10-07 09:01:55.577756

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from app.db import config_edit_contracts_v1

# revision identifiers, used by Alembic.
revision: str = "ae086ab363c8"
down_revision: Union[str, Sequence[str], None] = "ed85e4d73965"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("system_config", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "vault_edit_version",
                sa.BigInteger(),
                server_default="1",
                nullable=False,
            )
        )

    # The schema differ does not emit triggers; fresh bootstrap installs this same contract.
    config_edit_contracts_v1.install(op.get_bind())


def downgrade() -> None:
    """Downgrade schema."""
    config_edit_contracts_v1.uninstall(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("system_config", schema=None) as batch_op:
        batch_op.drop_column("vault_edit_version")

    # ### end Alembic commands ###
