"""add separate sparse expansion postings

Revision ID: b49f72e927c9
Revises: 2d8bebe0f959
Create Date: 2026-09-12 04:21:28.203328

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b49f72e927c9"
down_revision: Union[str, Sequence[str], None] = "2d8bebe0f959"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "search_expansions",
        sa.Column("passage_id", sa.Integer(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("recipe", sa.String(length=64), nullable=False),
        sa.Column("phase", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=True),
        sa.Column("lease_until", sa.DateTime(), nullable=True),
        sa.Column("retry_at", sa.DateTime(), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("truncated", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "phase IN ('running', 'ready', 'failed')",
            name=op.f("ck_search_expansions_phase"),
        ),
        sa.CheckConstraint(
            "attempts >= 0 AND attempts <= 3",
            name=op.f("ck_search_expansions_attempts"),
        ),
        sa.ForeignKeyConstraint(
            ["passage_id"],
            ["search_passages.id"],
            name=op.f("fk_search_expansions_passage_id_search_passages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("passage_id", name=op.f("pk_search_expansions")),
    )
    with op.batch_alter_table("search_expansions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_search_expansions_work",
            ["phase", "retry_at", "lease_until"],
            unique=False,
        )

    op.create_table(
        "search_expansion_terms",
        sa.Column("passage_id", sa.Integer(), nullable=False),
        sa.Column("term", sa.String(length=128), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "weight > 0 AND weight <= 10", name=op.f("ck_search_expansion_terms_weight")
        ),
        sa.ForeignKeyConstraint(
            ["passage_id"],
            ["search_expansions.passage_id"],
            name=op.f("fk_search_expansion_terms_passage_id_search_expansions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "passage_id", "term", name=op.f("pk_search_expansion_terms")
        ),
    )
    with op.batch_alter_table("search_expansion_terms", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_search_expansion_terms_term"), ["term"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("search_expansion_terms", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_search_expansion_terms_term"))

    op.drop_table("search_expansion_terms")
    with op.batch_alter_table("search_expansions", schema=None) as batch_op:
        batch_op.drop_index("ix_search_expansions_work")

    op.drop_table("search_expansions")
    # ### end Alembic commands ###
