"""add spoolman editing version

Revision ID: bcb8ec58819b
Revises: 5291a5f0231c
Create Date: 2026-10-07 17:45:45.408616

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from app.db import spoolman_edit_contracts_v1

# revision identifiers, used by Alembic.
revision: str = "bcb8ec58819b"
down_revision: Union[str, Sequence[str], None] = "5291a5f0231c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "system_config", schema=None, recreate="never"
    ) as batch_op:
        batch_op.add_column(
            sa.Column(
                "spoolman_edit_version",
                sa.BigInteger(),
                server_default="1",
                nullable=False,
            )
        )

    spoolman_edit_contracts_v1.install(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Native DROP COLUMN preserves the independent vault/search/notification triggers.
    spoolman_edit_contracts_v1.uninstall(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "system_config", schema=None, recreate="never"
    ) as batch_op:
        batch_op.drop_column("spoolman_edit_version")

    # ### end Alembic commands ###
