"""add restore marker operation identity

Revision ID: beab532a9998
Revises: 9a7a42dcf8e5
Create Date: 2026-08-29 20:03:29.775050

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "beab532a9998"
down_revision: Union[str, Sequence[str], None] = "9a7a42dcf8e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("restore_markers", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("operation_nonce", sa.String(length=64), nullable=True)
        )
        batch_op.add_column(
            sa.Column("archive_sha256", sa.String(length=64), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_restore_markers_archive_sha256"),
            ["archive_sha256"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_restore_markers_operation_nonce"),
            ["operation_nonce"],
            unique=False,
        )
        batch_op.create_unique_constraint(
            "uq_restore_marker_nonce", ["operation_nonce"]
        )

    # Existing markers are recovery evidence from the previous schema and do
    # not identify a current operation. Give them deterministic placeholders;
    # restore retries require a matching v2 journal nonce/hash and therefore
    # cannot mistake these rows for active proof. CAST is understood by both
    # SQLite and PostgreSQL, unlike SQLite's printf(), and also renders safely
    # in Alembic's offline SQL mode.
    op.execute(
        sa.text(
            "UPDATE restore_markers "
            "SET operation_nonce = CAST(id AS VARCHAR(64)), "
            "archive_sha256 = CAST(id AS VARCHAR(64)) "
            "WHERE operation_nonce IS NULL OR archive_sha256 IS NULL"
        )
    )
    with op.batch_alter_table("restore_markers", schema=None) as batch_op:
        batch_op.alter_column(
            "operation_nonce", existing_type=sa.String(length=64), nullable=False
        )
        batch_op.alter_column(
            "archive_sha256", existing_type=sa.String(length=64), nullable=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("restore_markers", schema=None) as batch_op:
        batch_op.drop_constraint("uq_restore_marker_nonce", type_="unique")
        batch_op.drop_index(batch_op.f("ix_restore_markers_operation_nonce"))
        batch_op.drop_index(batch_op.f("ix_restore_markers_archive_sha256"))
        batch_op.drop_column("archive_sha256")
        batch_op.drop_column("operation_nonce")

    # ### end Alembic commands ###
