"""Add durable search passages without modifying existing library rows.

The table is an internal W1 foundation. Source projection and future inference
indexes are populated by application operations, never during an upgrade.

Revision ID: bf435683b126
Revises: 0118bda3e719
Create Date: 2026-09-11 16:26:27.868029

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bf435683b126"
down_revision: Union[str, Sequence[str], None] = "0118bda3e719"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "search_passages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subject_type", sa.String(length=32), nullable=False),
        sa.Column("subject_id", sa.Integer(), nullable=False),
        sa.Column("visibility_segment_key", sa.String(length=64), nullable=False),
        sa.Column("access_dependencies_json", sa.Text(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("recipe_version", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("truncated", sa.Boolean(), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "subject_type IN ('model', 'collection', 'multipart_model', 'document')",
            name=op.f("ck_search_passages_subject_type"),
        ),
        sa.CheckConstraint(
            "chunk_index >= 0 AND chunk_index < 16",
            name=op.f("ck_search_passages_chunk_index"),
        ),
        sa.CheckConstraint(
            "length(text) <= 16384", name=op.f("ck_search_passages_text_length")
        ),
        sa.CheckConstraint(
            "recipe_version > 0", name=op.f("ck_search_passages_recipe_version")
        ),
        sa.CheckConstraint(
            "subject_id > 0", name=op.f("ck_search_passages_subject_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_passages")),
        sa.UniqueConstraint(
            "subject_type",
            "subject_id",
            "visibility_segment_key",
            "chunk_index",
            "recipe_version",
            name="uq_search_passage_identity",
        ),
    )
    with op.batch_alter_table("search_passages", schema=None) as batch_op:
        batch_op.create_index(
            "ix_search_passages_watermark", ["updated_at", "id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("search_passages", schema=None) as batch_op:
        batch_op.drop_index("ix_search_passages_watermark")

    op.drop_table("search_passages")
    # ### end Alembic commands ###
