"""Store immutable, encrypted inference endpoint versions and independent opt-ins.

Revision ID: bf6dfc561eca
Revises: c3707090f459
Create Date: 2026-09-11 19:59:30.568101

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bf6dfc561eca"
down_revision: Union[str, Sequence[str], None] = "c3707090f459"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inference_endpoints",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("config_hash", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("config_json", sa.Text(), nullable=False),
        sa.Column("api_key", sa.Text(), nullable=False),
        sa.Column("headers_json", sa.Text(), nullable=False),
        sa.Column("native_dimension", sa.Integer(), nullable=True),
        sa.Column("supports_images", sa.Boolean(), nullable=False),
        sa.Column("dialect", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inference_endpoints")),
        sa.UniqueConstraint(
            "config_hash", name=op.f("uq_inference_endpoints_config_hash")
        ),
    )
    with op.batch_alter_table("system_config", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("ai_search_settings_json", sa.Text(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("system_config", schema=None) as batch_op:
        batch_op.drop_column("ai_search_settings_json")

    op.drop_table("inference_endpoints")
    # ### end Alembic commands ###
