"""adopt shared native vectors for typed search subjects

Revision ID: c3707090f459
Revises: 68d8257ee80a
Create Date: 2026-09-11 19:06:50.192042

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c3707090f459'
down_revision: Union[str, Sequence[str], None] = '68d8257ee80a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('index_generations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('building_profile_key', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('phase', sa.String(length=32), server_default='ready', nullable=False))
        batch_op.add_column(sa.Column('transform_json', sa.Text(), server_default='{}', nullable=False))
        batch_op.add_column(sa.Column('vector_table_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('index_state', sa.String(length=16), server_default='absent', nullable=False))
        batch_op.add_column(sa.Column('index_error', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('indexed_after_id', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_unique_constraint('uq_index_generation_building_profile', ['building_profile_key'])

    with op.batch_alter_table('passage_vectors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_type', sa.String(length=32), server_default='model', nullable=False))
        batch_op.add_column(sa.Column('subject_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('passage_id', sa.Integer(), nullable=True))
        batch_op.alter_column('model_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('file_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index('ix_passage_vector_subject', ['subject_type', 'subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_passage_vectors_passage_id'), ['passage_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_passage_vectors_passage_id_search_passages'), 'search_passages', ['passage_id'], ['id'], ondelete='CASCADE')

    # Adopt existing #154 units without changing IDs, keys, hashes or BLOBs.
    op.execute("UPDATE passage_vectors SET subject_id = model_id WHERE subject_id IS NULL")
    with op.batch_alter_table('passage_vectors', schema=None) as batch_op:
        batch_op.alter_column('subject_id', existing_type=sa.Integer(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # These are rebuildable units for new Subject types; their source content
    # survives downgrade. The old schema requires a Model and Artifact for each.
    op.execute("DELETE FROM passage_vectors WHERE model_id IS NULL OR file_id IS NULL")

    with op.batch_alter_table('passage_vectors', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_passage_vectors_passage_id_search_passages'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_passage_vectors_passage_id'))
        batch_op.drop_index('ix_passage_vector_subject')
        batch_op.alter_column('file_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('model_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('passage_id')
        batch_op.drop_column('subject_id')
        batch_op.drop_column('subject_type')

    with op.batch_alter_table('index_generations', schema=None) as batch_op:
        batch_op.drop_constraint('uq_index_generation_building_profile', type_='unique')
        batch_op.drop_column('indexed_after_id')
        batch_op.drop_column('index_error')
        batch_op.drop_column('index_state')
        batch_op.drop_column('vector_table_name')
        batch_op.drop_column('transform_json')
        batch_op.drop_column('phase')
        batch_op.drop_column('building_profile_key')

    # ### end Alembic commands ###
