"""version notification channels and global switch independently

Revision ID: c9852ff533ee
Revises: 7af8bb13c174
Create Date: 2026-10-07 14:45:35.743494

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from app.db import notification_edit_contracts_v1

# revision identifiers, used by Alembic.
revision: str = "c9852ff533ee"
down_revision: Union[str, Sequence[str], None] = "7af8bb13c174"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Frozen post-addition shape for offline SQLite default-removal rebuilds.
# Existing identities bind the database epoch and integer ID; new rows supply UUIDs.
_CHANNELS = sa.Table(
    "notification_channels",
    sa.MetaData(),
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("name", sa.String(128), nullable=False),
    sa.Column("target", sa.String(8), nullable=False),
    sa.Column("enabled", sa.Boolean(), nullable=False),
    sa.Column("config_json", sa.Text(), nullable=False),
    sa.Column("events_json", sa.Text()),
    sa.Column("printer_ids_json", sa.Text()),
    sa.Column("last_status", sa.String(16)),
    sa.Column("last_error", sa.String(1024)),
    sa.Column("last_delivered_at", sa.DateTime()),
    sa.Column("consecutive_failures", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.Column("edit_version", sa.BigInteger(), server_default="1", nullable=False),
    sa.Column(
        "edit_identity",
        sa.String(32),
        server_default="00000000000000000000000000000000",
        nullable=False,
    ),
    sa.PrimaryKeyConstraint("id", name="pk_notification_channels"),
    sa.Index("ix_notification_channels_enabled", "enabled"),
    sa.Index("ix_notification_channels_target", "target"),
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "notification_channels", schema=None, recreate="never"
    ) as batch_op:
        batch_op.add_column(
            sa.Column(
                "edit_version", sa.BigInteger(), server_default="1", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "edit_identity",
                sa.String(length=32),
                server_default="00000000000000000000000000000000",
                nullable=False,
            )
        )

    with op.batch_alter_table(
        "system_config", schema=None, recreate="never"
    ) as batch_op:
        batch_op.add_column(
            sa.Column(
                "notification_edit_version",
                sa.BigInteger(),
                server_default="1",
                nullable=False,
            )
        )

    with op.batch_alter_table("notification_channels", copy_from=_CHANNELS) as batch_op:
        batch_op.alter_column(
            "edit_identity",
            existing_type=sa.String(32),
            existing_nullable=False,
            server_default=None,
        )
    notification_edit_contracts_v1.install(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    notification_edit_contracts_v1.uninstall(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "system_config", schema=None, recreate="never"
    ) as batch_op:
        batch_op.drop_column("notification_edit_version")

    with op.batch_alter_table(
        "notification_channels", schema=None, recreate="never"
    ) as batch_op:
        batch_op.drop_column("edit_identity")
        batch_op.drop_column("edit_version")

    # ### end Alembic commands ###
