"""Persist private ingestion review manifests

Revision ID: e21ed0a3d7d7
Revises: 6af74a0d6909
Create Date: 2026-09-15 17:00:14.851372

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e21ed0a3d7d7'
down_revision: Union[str, Sequence[str], None] = '6af74a0d6909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_reviews',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('source_job_id', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('claim_expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_ingestion_reviews_owner_user_id_users')),
    sa.ForeignKeyConstraint(['source_job_id'], ['background_jobs.id'], name=op.f('fk_ingestion_reviews_source_job_id_background_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_reviews')),
    info={'audit_exclude': True}
    )
    with op.batch_alter_table('ingestion_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestion_reviews_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_reviews_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_reviews_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_reviews_source_job_id'), ['source_job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingestion_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestion_reviews_source_job_id'))
        batch_op.drop_index(batch_op.f('ix_ingestion_reviews_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_ingestion_reviews_kind'))
        batch_op.drop_index(batch_op.f('ix_ingestion_reviews_expires_at'))

    op.drop_table('ingestion_reviews')
    # ### end Alembic commands ###
