"""add source verification and gc lease

Revision ID: f0bde833e466
Revises: 51102a1c411e
Create Date: 2026-08-31 01:41:46.874535

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f0bde833e466"
down_revision: Union[str, Sequence[str], None] = "51102a1c411e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("external_libraries", schema=None) as batch_op:
        batch_op.alter_column(
            "source_kind",
            existing_type=sa.VARCHAR(length=7),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "source_prefix",
            existing_type=sa.VARCHAR(length=1024),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "writeback_enabled",
            existing_type=sa.BOOLEAN(),
            server_default=None,
            existing_nullable=False,
        )

    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("source_verified_at", sa.DateTime(), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_files_source_verified_at"),
            ["source_verified_at"],
            unique=False,
        )

    with op.batch_alter_table("gc_runs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("active_slot", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_gc_runs_active_slot"), ["active_slot"], unique=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gc_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_gc_runs_active_slot"))
        batch_op.drop_column("active_slot")

    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_files_source_verified_at"))
        batch_op.drop_column("source_verified_at")

    with op.batch_alter_table("external_libraries", schema=None) as batch_op:
        batch_op.alter_column(
            "writeback_enabled",
            existing_type=sa.BOOLEAN(),
            server_default=sa.false(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "source_prefix",
            existing_type=sa.VARCHAR(length=1024),
            server_default=sa.text("('')"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "source_kind",
            existing_type=sa.VARCHAR(length=7),
            server_default=sa.text("'MOUNTED'"),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
