"""add independent similarity evidence and local vectors

Revision ID: f3736257acd2
Revises: 18c4551a00dc
Create Date: 2026-09-10 21:16:24.499610

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3736257acd2"
down_revision: Union[str, Sequence[str], None] = "18c4551a00dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "embedding_spaces",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("config_hash", sa.String(length=64), nullable=False),
        sa.Column("modality", sa.String(length=32), nullable=False),
        sa.Column("profile", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model_key", sa.String(length=128), nullable=False),
        sa.Column("model_revision", sa.String(length=128), nullable=False),
        sa.Column("native_dimension", sa.Integer(), nullable=False),
        sa.Column("normalization", sa.String(length=16), nullable=False),
        sa.Column("prefixes_json", sa.Text(), nullable=False),
        sa.Column("recipe_json", sa.Text(), nullable=False),
        sa.Column("config_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "native_dimension >= 1 AND native_dimension <= 4096",
            name=op.f("ck_embedding_spaces_dimension_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_embedding_spaces")),
        sa.UniqueConstraint(
            "config_hash", name=op.f("uq_embedding_spaces_config_hash")
        ),
    )
    op.create_table(
        "geometry_fingerprints",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("component_index", sa.Integer(), nullable=False),
        sa.Column("algorithm_version", sa.String(length=64), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("physical_hash_0", sa.String(length=64), nullable=True),
        sa.Column("physical_hash_1", sa.String(length=64), nullable=True),
        sa.Column("physical_hash_2", sa.String(length=64), nullable=True),
        sa.Column("physical_hash_3", sa.String(length=64), nullable=True),
        sa.Column("normalized_hash_0", sa.String(length=64), nullable=True),
        sa.Column("normalized_hash_1", sa.String(length=64), nullable=True),
        sa.Column("normalized_hash_2", sa.String(length=64), nullable=True),
        sa.Column("normalized_hash_3", sa.String(length=64), nullable=True),
        sa.Column("vertex_count", sa.Integer(), nullable=True),
        sa.Column("face_count", sa.Integer(), nullable=True),
        sa.Column("component_count", sa.Integer(), nullable=True),
        sa.Column("euler_characteristic", sa.Integer(), nullable=True),
        sa.Column("watertight", sa.Boolean(), nullable=True),
        sa.Column("surface_area", sa.Float(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("area_volume_ratio", sa.Float(), nullable=True),
        sa.Column("normalized_area", sa.Float(), nullable=True),
        sa.Column("hull_ratio", sa.Float(), nullable=True),
        sa.Column("fill_ratio", sa.Float(), nullable=True),
        sa.Column("eigen_ratio_0", sa.Float(), nullable=True),
        sa.Column("inertia_ratio_0", sa.Float(), nullable=True),
        sa.Column("inertia_ratio_1", sa.Float(), nullable=True),
        sa.Column("radius", sa.Float(), nullable=True),
        sa.Column("d2_blob", sa.LargeBinary(), nullable=True),
        sa.Column("sh_blob", sa.LargeBinary(), nullable=True),
        sa.Column("view_blob", sa.LargeBinary(), nullable=True),
        sa.Column("instance_count", sa.Integer(), nullable=False),
        sa.Column("recipe_json", sa.Text(), nullable=False),
        sa.Column("metrics_json", sa.Text(), nullable=False),
        sa.Column("unavailable_json", sa.Text(), nullable=False),
        sa.Column("instances_json", sa.Text(), nullable=False),
        sa.Column("failure_code", sa.String(length=64), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("lease_token", sa.String(length=64), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("peak_rss_bytes", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "state IN ('pending','ready','partial','unsupported','failed')",
            name=op.f("ck_geometry_fingerprints_state_values"),
        ),
        sa.CheckConstraint(
            "component_index >= 0 AND instance_count >= 1",
            name=op.f("ck_geometry_fingerprints_component_values"),
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
            name=op.f("fk_geometry_fingerprints_file_id_files"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_geometry_fingerprints")),
        sa.UniqueConstraint(
            "file_id",
            "component_index",
            "algorithm_version",
            "source_sha256",
            name="uq_geometry_fingerprint_input",
        ),
    )
    with op.batch_alter_table("geometry_fingerprints", schema=None) as batch_op:
        batch_op.create_index(
            "ix_geometry_fingerprint_claim", ["state", "lease_expires_at"], unique=False
        )
        batch_op.create_index(
            "ix_geometry_fingerprint_repair",
            ["algorithm_version", "state", "normalized_area"],
            unique=False,
        )
        batch_op.create_index(
            "ix_geometry_fingerprint_strict",
            ["algorithm_version", "state", "area_volume_ratio"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_geometry_fingerprints_eigen_ratio_0"),
            ["eigen_ratio_0"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_geometry_fingerprints_file_id"), ["file_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_geometry_fingerprints_normalized_hash_0"),
            ["normalized_hash_0"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_geometry_fingerprints_normalized_hash_1"),
            ["normalized_hash_1"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_geometry_fingerprints_normalized_hash_2"),
            ["normalized_hash_2"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_geometry_fingerprints_normalized_hash_3"),
            ["normalized_hash_3"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_geometry_fingerprints_physical_hash_0"),
            ["physical_hash_0"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_geometry_fingerprints_physical_hash_1"),
            ["physical_hash_1"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_geometry_fingerprints_physical_hash_2"),
            ["physical_hash_2"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_geometry_fingerprints_physical_hash_3"),
            ["physical_hash_3"],
            unique=False,
        )

    op.create_table(
        "index_generations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("space_id", sa.Integer(), nullable=False),
        sa.Column("active_profile_key", sa.String(length=128), nullable=True),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("index_dimension", sa.Integer(), nullable=False),
        sa.Column("quantization", sa.String(length=16), nullable=False),
        sa.Column("index_backend", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "index_dimension >= 1 AND index_dimension <= 4096",
            name=op.f("ck_index_generations_dimension_range"),
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["embedding_spaces.id"],
            name=op.f("fk_index_generations_space_id_embedding_spaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_index_generations")),
        sa.UniqueConstraint(
            "active_profile_key", name="uq_index_generation_active_profile"
        ),
    )
    with op.batch_alter_table("index_generations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_index_generations_space_id"), ["space_id"], unique=False
        )

    op.create_table(
        "similarity_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("scope_ids_json", sa.Text(), nullable=False),
        sa.Column("active_scope_key", sa.String(length=64), nullable=True),
        sa.Column("algorithm_version", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("phase", sa.String(length=16), nullable=False),
        sa.Column("checkpoint_json", sa.Text(), nullable=False),
        sa.Column("settings_json", sa.Text(), nullable=False),
        sa.Column("counters_json", sa.Text(), nullable=False),
        sa.Column("cutoff", sa.DateTime(), nullable=False),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("lease_token", sa.String(length=64), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(), nullable=True),
        sa.Column("failure_code", sa.String(length=64), nullable=True),
        sa.Column("trigger", sa.String(length=16), nullable=False),
        sa.Column("peak_rss_bytes", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("last_activity_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "state IN ('queued','running','cancelling','cancelled','completed','failed')",
            name=op.f("ck_similarity_runs_state_values"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_similarity_runs_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_similarity_runs")),
        sa.UniqueConstraint("active_scope_key", name="uq_similarity_run_active_scope"),
    )
    with op.batch_alter_table("similarity_runs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_similarity_run_claim", ["state", "lease_expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_similarity_runs_actor_id"), ["actor_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_similarity_runs_created_at"), ["created_at"], unique=False
        )

    op.create_table(
        "passage_vectors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("generation_id", sa.Integer(), nullable=False),
        sa.Column("unit_kind", sa.String(length=32), nullable=False),
        sa.Column("unit_key", sa.String(length=128), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("native_dimension", sa.Integer(), nullable=False),
        sa.Column("vector_blob", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "native_dimension >= 1 AND native_dimension <= 4096",
            name=op.f("ck_passage_vectors_dimension_range"),
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
            name=op.f("fk_passage_vectors_file_id_files"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["generation_id"],
            ["index_generations.id"],
            name=op.f("fk_passage_vectors_generation_id_index_generations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["models.id"],
            name=op.f("fk_passage_vectors_model_id_models"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_passage_vectors")),
        sa.UniqueConstraint(
            "generation_id", "unit_kind", "unit_key", name="uq_passage_vector_unit"
        ),
    )
    with op.batch_alter_table("passage_vectors", schema=None) as batch_op:
        batch_op.create_index(
            "ix_passage_vector_scan", ["generation_id", "id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_passage_vectors_file_id"), ["file_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_passage_vectors_model_id"), ["model_id"], unique=False
        )

    op.create_table(
        "similarity_candidates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model_a_id", sa.Integer(), nullable=False),
        sa.Column("model_b_id", sa.Integer(), nullable=False),
        sa.Column("algorithm_version", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.Column("evidence_class", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("exact_equivalence", sa.Boolean(), nullable=False),
        sa.Column("primary_lineage_key", sa.String(length=64), nullable=True),
        sa.Column("summary_json", sa.Text(), nullable=False),
        sa.Column("review_state", sa.String(length=16), nullable=False),
        sa.Column("resolution_kind", sa.String(length=32), nullable=True),
        sa.Column("freshness", sa.String(length=16), nullable=False),
        sa.Column("stale_reason", sa.String(length=64), nullable=True),
        sa.Column("reviewer_id", sa.Integer(), nullable=True),
        sa.Column("reconsidered_candidate_id", sa.Integer(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "freshness IN ('current','stale')",
            name=op.f("ck_similarity_candidates_freshness_values"),
        ),
        sa.CheckConstraint(
            "review_state IN ('open','confirmed','rejected','later')",
            name=op.f("ck_similarity_candidates_review_state_values"),
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_similarity_candidates_confidence_range"),
        ),
        sa.CheckConstraint(
            "model_a_id < model_b_id",
            name=op.f("ck_similarity_candidates_ordered_pair"),
        ),
        sa.ForeignKeyConstraint(
            ["model_a_id"],
            ["models.id"],
            name=op.f("fk_similarity_candidates_model_a_id_models"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["model_b_id"],
            ["models.id"],
            name=op.f("fk_similarity_candidates_model_b_id_models"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reconsidered_candidate_id"],
            ["similarity_candidates.id"],
            name=op.f(
                "fk_similarity_candidates_reconsidered_candidate_id_similarity_candidates"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
            name=op.f("fk_similarity_candidates_reviewer_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["similarity_runs.id"],
            name=op.f("fk_similarity_candidates_run_id_similarity_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_similarity_candidates")),
        sa.UniqueConstraint(
            "model_a_id",
            "model_b_id",
            "algorithm_version",
            name="uq_similarity_candidate_pair",
        ),
    )
    with op.batch_alter_table("similarity_candidates", schema=None) as batch_op:
        batch_op.create_index(
            "ix_similarity_candidate_review",
            ["review_state", "freshness", "confidence", "id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_similarity_candidates_evidence_class"),
            ["evidence_class"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_similarity_candidates_model_a_id"),
            ["model_a_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_similarity_candidates_model_b_id"),
            ["model_b_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_similarity_candidates_run_id"), ["run_id"], unique=False
        )

    op.create_table(
        "similarity_candidate_observations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("candidate_id", sa.Integer(), nullable=False),
        sa.Column("fingerprint_a_id", sa.Integer(), nullable=True),
        sa.Column("fingerprint_b_id", sa.Integer(), nullable=True),
        sa.Column("lineage_key", sa.String(length=64), nullable=False),
        sa.Column("input_hash_a", sa.String(length=64), nullable=False),
        sa.Column("input_hash_b", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("contained_side", sa.String(length=1), nullable=True),
        sa.Column("multiplicity_a", sa.Integer(), nullable=False),
        sa.Column("multiplicity_b", sa.Integer(), nullable=False),
        sa.Column("evidence_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "multiplicity_a >= 1 AND multiplicity_b >= 1",
            name=op.f("ck_similarity_candidate_observations_multiplicity_values"),
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["similarity_candidates.id"],
            name=op.f(
                "fk_similarity_candidate_observations_candidate_id_similarity_candidates"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["fingerprint_a_id"],
            ["geometry_fingerprints.id"],
            name=op.f(
                "fk_similarity_candidate_observations_fingerprint_a_id_geometry_fingerprints"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["fingerprint_b_id"],
            ["geometry_fingerprints.id"],
            name=op.f(
                "fk_similarity_candidate_observations_fingerprint_b_id_geometry_fingerprints"
            ),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_similarity_candidate_observations")
        ),
        sa.UniqueConstraint(
            "candidate_id", "lineage_key", name="uq_similarity_observation_lineage"
        ),
    )
    with op.batch_alter_table(
        "similarity_candidate_observations", schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_similarity_candidate_observations_candidate_id"),
            ["candidate_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_similarity_candidate_observations_fingerprint_a_id"),
            ["fingerprint_a_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_similarity_candidate_observations_fingerprint_b_id"),
            ["fingerprint_b_id"],
            unique=False,
        )

    op.create_table(
        "similarity_review_decisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("candidate_id", sa.Integer(), nullable=True),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("resolution_kind", sa.String(length=32), nullable=True),
        sa.Column("target_id", sa.Integer(), nullable=True),
        sa.Column("before_state", sa.String(length=16), nullable=False),
        sa.Column("after_state", sa.String(length=16), nullable=False),
        sa.Column("candidate_version", sa.Integer(), nullable=False),
        sa.Column("snapshot_json", sa.Text(), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_similarity_review_decisions_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["similarity_candidates.id"],
            name=op.f(
                "fk_similarity_review_decisions_candidate_id_similarity_candidates"
            ),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_similarity_review_decisions")),
        sa.UniqueConstraint(
            "actor_id", "request_id", name="uq_similarity_decision_request"
        ),
    )
    with op.batch_alter_table("similarity_review_decisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_similarity_review_decisions_actor_id"),
            ["actor_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_similarity_review_decisions_candidate_id"),
            ["candidate_id"],
            unique=False,
        )

    with op.batch_alter_table("system_config", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("similarity_settings_json", sa.Text(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("system_config", schema=None) as batch_op:
        batch_op.drop_column("similarity_settings_json")

    with op.batch_alter_table("similarity_review_decisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_similarity_review_decisions_candidate_id"))
        batch_op.drop_index(batch_op.f("ix_similarity_review_decisions_actor_id"))

    op.drop_table("similarity_review_decisions")
    with op.batch_alter_table(
        "similarity_candidate_observations", schema=None
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_similarity_candidate_observations_fingerprint_b_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_similarity_candidate_observations_fingerprint_a_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_similarity_candidate_observations_candidate_id")
        )

    op.drop_table("similarity_candidate_observations")
    with op.batch_alter_table("similarity_candidates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_similarity_candidates_run_id"))
        batch_op.drop_index(batch_op.f("ix_similarity_candidates_model_b_id"))
        batch_op.drop_index(batch_op.f("ix_similarity_candidates_model_a_id"))
        batch_op.drop_index(batch_op.f("ix_similarity_candidates_evidence_class"))
        batch_op.drop_index("ix_similarity_candidate_review")

    op.drop_table("similarity_candidates")
    with op.batch_alter_table("passage_vectors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_passage_vectors_model_id"))
        batch_op.drop_index(batch_op.f("ix_passage_vectors_file_id"))
        batch_op.drop_index("ix_passage_vector_scan")

    op.drop_table("passage_vectors")
    with op.batch_alter_table("similarity_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_similarity_runs_created_at"))
        batch_op.drop_index(batch_op.f("ix_similarity_runs_actor_id"))
        batch_op.drop_index("ix_similarity_run_claim")

    op.drop_table("similarity_runs")
    with op.batch_alter_table("index_generations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_index_generations_space_id"))

    op.drop_table("index_generations")
    with op.batch_alter_table("geometry_fingerprints", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_geometry_fingerprints_physical_hash_3"))
        batch_op.drop_index(batch_op.f("ix_geometry_fingerprints_physical_hash_2"))
        batch_op.drop_index(batch_op.f("ix_geometry_fingerprints_physical_hash_1"))
        batch_op.drop_index(batch_op.f("ix_geometry_fingerprints_physical_hash_0"))
        batch_op.drop_index(batch_op.f("ix_geometry_fingerprints_normalized_hash_3"))
        batch_op.drop_index(batch_op.f("ix_geometry_fingerprints_normalized_hash_2"))
        batch_op.drop_index(batch_op.f("ix_geometry_fingerprints_normalized_hash_1"))
        batch_op.drop_index(batch_op.f("ix_geometry_fingerprints_normalized_hash_0"))
        batch_op.drop_index(batch_op.f("ix_geometry_fingerprints_file_id"))
        batch_op.drop_index(batch_op.f("ix_geometry_fingerprints_eigen_ratio_0"))
        batch_op.drop_index("ix_geometry_fingerprint_strict")
        batch_op.drop_index("ix_geometry_fingerprint_repair")
        batch_op.drop_index("ix_geometry_fingerprint_claim")

    op.drop_table("geometry_fingerprints")
    op.drop_table("embedding_spaces")
    # ### end Alembic commands ###
