"""add durable thumbnail generations

Revision ID: f3a4f173d948
Revises: f0bde833e466
Create Date: 2026-08-31 11:39:22.532569

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3a4f173d948"
down_revision: Union[str, Sequence[str], None] = "f0bde833e466"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "thumbnail_generations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("recipe_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("storage_key", sa.String(length=2048), nullable=True),
        sa.Column("output_sha256", sa.String(length=64), nullable=True),
        sa.Column("output_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("output_etag", sa.String(length=256), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("strategy", sa.String(length=32), nullable=True),
        sa.Column("complete", sa.Boolean(), nullable=False),
        sa.Column("failure_reason", sa.String(length=64), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("lease_token", sa.String(length=64), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("peak_rss_bytes", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
            name=op.f("fk_thumbnail_generations_file_id_files"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_thumbnail_generations")),
        sa.UniqueConstraint(
            "file_id",
            "source_sha256",
            "recipe_fingerprint",
            name="uq_thumbnail_generation_recipe",
        ),
    )
    with op.batch_alter_table("thumbnail_generations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_thumbnail_generation_state_lease",
            ["state", "lease_expires_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_thumbnail_generations_file_id"), ["file_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_thumbnail_generations_lease_expires_at"),
            ["lease_expires_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_thumbnail_generations_lease_token"),
            ["lease_token"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_thumbnail_generations_state"), ["state"], unique=False
        )

    op.create_table(
        "thumbnail_render_slots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slot_number", sa.Integer(), nullable=False),
        sa.Column("generation_id", sa.Integer(), nullable=True),
        sa.Column("lease_token", sa.String(length=64), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["generation_id"],
            ["thumbnail_generations.id"],
            name=op.f("fk_thumbnail_render_slots_generation_id_thumbnail_generations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_thumbnail_render_slots")),
    )
    with op.batch_alter_table("thumbnail_render_slots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_thumbnail_render_slots_generation_id"),
            ["generation_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_thumbnail_render_slots_lease_expires_at"),
            ["lease_expires_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_thumbnail_render_slots_lease_token"),
            ["lease_token"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_thumbnail_render_slots_slot_number"),
            ["slot_number"],
            unique=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("thumbnail_render_slots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_thumbnail_render_slots_slot_number"))
        batch_op.drop_index(batch_op.f("ix_thumbnail_render_slots_lease_token"))
        batch_op.drop_index(batch_op.f("ix_thumbnail_render_slots_lease_expires_at"))
        batch_op.drop_index(batch_op.f("ix_thumbnail_render_slots_generation_id"))

    op.drop_table("thumbnail_render_slots")
    with op.batch_alter_table("thumbnail_generations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_thumbnail_generations_state"))
        batch_op.drop_index(batch_op.f("ix_thumbnail_generations_lease_token"))
        batch_op.drop_index(batch_op.f("ix_thumbnail_generations_lease_expires_at"))
        batch_op.drop_index(batch_op.f("ix_thumbnail_generations_file_id"))
        batch_op.drop_index("ix_thumbnail_generation_state_lease")

    op.drop_table("thumbnail_generations")
    # ### end Alembic commands ###
