"""Version printer settings without invalidating drafts for live telemetry.

Revision ID: f92f1ea1dfe2
Revises: ae086ab363c8
Create Date: 2026-10-07 11:32:23.416424

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from app.db import printer_edit_contracts_v1

# revision identifiers, used by Alembic.
revision: str = "f92f1ea1dfe2"
down_revision: Union[str, Sequence[str], None] = "ae086ab363c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("printers", schema=None, recreate="never") as batch_op:
        batch_op.add_column(
            sa.Column(
                "edit_version", sa.BigInteger(), server_default="1", nullable=False
            )
        )

    # Triggers are not emitted by the schema differ; fresh installs share this contract.
    printer_edit_contracts_v1.install(op.get_bind())


def downgrade() -> None:
    """Downgrade schema."""
    printer_edit_contracts_v1.uninstall(op.get_bind())
    # Native DROP COLUMN preserves existing browse triggers. Supported SQLite
    # versions already require RETURNING (the same 3.35 minimum).
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("printers", schema=None, recreate="never") as batch_op:
        batch_op.drop_column("edit_version")

    # ### end Alembic commands ###
