//! Framework-neutral, bounded slicer metadata extraction.
#![forbid(unsafe_code)]

use regex::Regex;
use std::fs::File;
use std::io::{self, Read, Seek, SeekFrom};
use std::path::Path;
use std::sync::LazyLock;

pub const HEAD_BYTES: u64 = 64 * 1024;
pub const TAIL_BYTES: u64 = 64 * 1024;

#[derive(Clone, Debug, PartialEq)]
pub struct MaterialRequirement {
    pub tool_index: usize,
    pub material_type: String,
    pub color_hex: Option<String>,
}

#[derive(Clone, Debug, Default, PartialEq)]
pub struct Metadata {
    pub slicer_name: Option<String>,
    pub slicer_version: Option<String>,
    pub printer_model: Option<String>,
    pub nozzle_diameter_mm: Option<f64>,
    pub layer_height_mm: Option<f64>,
    pub first_layer_height_mm: Option<f64>,
    pub infill_percent: Option<f64>,
    pub wall_loops: Option<i64>,
    pub top_shell_layers: Option<i64>,
    pub bottom_shell_layers: Option<i64>,
    pub support_material: Option<bool>,
    pub nozzle_temperature_c: Option<f64>,
    pub bed_temperature_c: Option<f64>,
    pub estimated_time_s: Option<u64>,
    pub filament_weight_g: Option<f64>,
    pub filament_length_mm: Option<f64>,
    pub filament_cost: Option<f64>,
    pub material_type: Option<String>,
    pub material_brand: Option<String>,
    pub material_requirements: Option<Vec<MaterialRequirement>>,
    pub printer_preset_name: Option<String>,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ThumbnailFormat {
    Png,
    Jpeg,
    Qoi,
}

impl ThumbnailFormat {
    pub fn code(self) -> u16 {
        match self {
            Self::Png => 0,
            Self::Jpeg => 1,
            Self::Qoi => 2,
        }
    }

    pub fn extension(self) -> &'static str {
        match self {
            Self::Png => "png",
            Self::Jpeg => "jpg",
            Self::Qoi => "qoi",
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Thumbnail {
    pub format: ThumbnailFormat,
    pub width: u16,
    pub height: u16,
    pub data: Vec<u8>,
}

struct Pattern {
    key: &'static str,
    expressions: Vec<Regex>,
}

fn expression(value: &str) -> Regex {
    Regex::new(&format!("(?i){value}")).expect("static G-code regex")
}

static PATTERNS: LazyLock<Vec<Pattern>> = LazyLock::new(|| {
    [
        (
            "slicer_version",
            &[
                r";\s*generated by\s+(.+?)(?:\s+on\b|[\r\n])",
                r";\s*generated with\s+([^\r\n]+)",
            ][..],
        ),
        (
            "printer_model",
            &[
                r";\s*printer_model\s*=\s*(.+)",
                r";\s*printer_settings_id\s*=\s*(.+)",
                r";\s*machine_name\s*=\s*(.+)",
            ],
        ),
        (
            "printer_preset_name",
            &[r";\s*printer_settings_id\s*=\s*(.+)"],
        ),
        (
            "nozzle_diameter_mm",
            &[
                r";\s*nozzle_diameter\s*=\s*([\d.]+)",
                r";\s*nozzle diameter\s*[:=]\s*([\d.]+)",
            ],
        ),
        (
            "layer_height_mm",
            &[
                r";\s*layer_height\s*=\s*([\d.]+)",
                r";\s*layer height\s*[:=]\s*([\d.]+)",
            ],
        ),
        (
            "first_layer_height_mm",
            &[
                r";\s*first_layer_height\s*=\s*([\d.]+)",
                r";\s*first layer height\s*[:=]\s*([\d.]+)",
                r";\s*initial_layer_print_height\s*=\s*([\d.]+)",
            ],
        ),
        (
            "infill_percent",
            &[
                r";\s*sparse_infill_density\s*=\s*([\d.]+)\s*%?",
                r";\s*infill_density\s*=\s*([\d.]+)\s*%?",
                r";\s*fill_density\s*=\s*([\d.]+)\s*%?",
                r";\s*fill density\s*[:=]\s*([\d.]+)\s*%?",
            ],
        ),
        (
            "wall_loops",
            &[
                r";\s*wall_loops\s*=\s*(\d+)",
                r";\s*wall loops\s*[:=]\s*(\d+)",
                r";\s*perimeters\s*=\s*(\d+)",
                r";\s*wall_line_count\s*=\s*(\d+)",
            ],
        ),
        (
            "top_shell_layers",
            &[
                r";\s*top_shell_layers\s*=\s*(\d+)",
                r";\s*top shell layers\s*[:=]\s*(\d+)",
                r";\s*top_solid_layers\s*=\s*(\d+)",
                r";\s*top_layers\s*=\s*(\d+)",
            ],
        ),
        (
            "bottom_shell_layers",
            &[
                r";\s*bottom_shell_layers\s*=\s*(\d+)",
                r";\s*bottom shell layers\s*[:=]\s*(\d+)",
                r";\s*bottom_solid_layers\s*=\s*(\d+)",
                r";\s*bottom_layers\s*=\s*(\d+)",
            ],
        ),
        (
            "support_material_raw",
            &[
                r";\s*enable_support\s*=\s*([^\r\n;]+)",
                r";\s*support_material\s*=\s*([^\r\n;]+)",
                r";\s*support_enable\s*=\s*([^\r\n;]+)",
                r";\s*support\s*[:=]\s*([^\r\n;]+)",
            ],
        ),
        (
            "nozzle_temperature_c",
            &[
                r";\s*nozzle_temperature\s*=\s*([\d.]+)",
                r";\s*filament_temperature\s*=\s*([\d.]+)",
                r";\s*temperature\s*[:=]\s*([\d.]+)",
                r";\s*print_temperature\s*=\s*([\d.]+)",
            ],
        ),
        (
            "bed_temperature_c",
            &[
                r";\s*bed_temperature\s*=\s*([\d.]+)",
                r";\s*hot_plate_temp\s*=\s*([\d.]+)",
                r";\s*filament_bed_temperature\s*=\s*([\d.]+)",
                r";\s*bed temperature\s*[:=]\s*([\d.]+)",
                r";\s*print_bed_temperature\s*=\s*([\d.]+)",
            ],
        ),
        (
            "estimated_time_raw",
            &[
                r";\s*estimated printing time.*?=\s*(.+)",
                r";\s*estimated_printing_time\s*=\s*(.+)",
                r";\s*time\s*:\s*(\d+)",
            ],
        ),
        (
            "filament_weight_g",
            &[
                r";\s*total filament used \[g\]\s*=\s*([\d.]+)",
                r";\s*filament used \[g\]\s*=\s*([\d.]+)",
            ],
        ),
        (
            "filament_length_mm",
            &[
                r";\s*total filament length \[mm\]\s*=\s*([\d.]+)",
                r";\s*filament used \[mm\]\s*=\s*([\d.]+)",
                r";\s*filament used\s*:\s*([\d.]+)\s*m",
            ],
        ),
        (
            "filament_cost",
            &[
                r";\s*total filament cost\s*=\s*([\d.]+)",
                r";\s*filament cost\s*=\s*([\d.]+)",
            ],
        ),
        (
            "material_type",
            &[
                r";\s*filament_type\s*=\s*([^\r\n]+)",
                r";\s*filament type\s*[:=]\s*([^\r\n]+)",
            ],
        ),
        (
            "material_brand",
            &[
                r";\s*filament_brand\s*=\s*([^\n;]+)",
                r";\s*filament_vendor\s*=\s*([^\n;]+)",
                r";\s*filament_settings_id\s*=\s*([^\n;]+)",
            ],
        ),
    ]
    .into_iter()
    .map(|(key, values)| Pattern {
        key,
        expressions: values.iter().map(|value| expression(value)).collect(),
    })
    .collect()
});

static FILAMENT_COLOR_PATTERNS: LazyLock<Vec<Regex>> = LazyLock::new(|| {
    [
        r";\s*filament_colou?r\s*=\s*([^\r\n]+)",
        r";\s*filament colou?r\s*[:=]\s*([^\r\n]+)",
    ]
    .into_iter()
    .map(expression)
    .collect()
});
static DURATION: LazyLock<Regex> = LazyLock::new(|| expression(r"(\d+(?:\.\d+)?)\s*([dhms])"));
static NUMBER: LazyLock<Regex> = LazyLock::new(|| Regex::new(r"[-+]?\d+(?:\.\d+)?").unwrap());
static CURA_METERS: LazyLock<Regex> =
    LazyLock::new(|| expression(r"filament used\s*:\s*[\d.]+\s*m"));
static MM_LENGTH: LazyLock<Regex> = LazyLock::new(|| expression(r"filament[^\r\n]*\[mm\]"));
static COLOR: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"(?i)^#?([0-9A-F]{6})(?:[0-9A-F]{2})?$").unwrap());

pub fn read_text_window(path: &Path) -> io::Result<Vec<u8>> {
    let mut file = File::open(path)?;
    let size = file.metadata()?.len();
    let mut bytes = Vec::with_capacity((HEAD_BYTES + TAIL_BYTES + 1).min(size + 1) as usize);
    file.by_ref()
        .take(HEAD_BYTES.min(size))
        .read_to_end(&mut bytes)?;
    bytes.push(b'\n');
    if size > HEAD_BYTES + TAIL_BYTES {
        file.seek(SeekFrom::End(-(TAIL_BYTES as i64)))?;
        file.take(TAIL_BYTES).read_to_end(&mut bytes)?;
    }
    Ok(bytes)
}

pub fn parse_text_path(path: &Path) -> io::Result<Metadata> {
    Ok(parse_text(&String::from_utf8_lossy(&read_text_window(
        path,
    )?)))
}

pub fn is_bgcode(path: &Path) -> bool {
    let mut magic = [0_u8; 4];
    File::open(path)
        .and_then(|mut file| file.read_exact(&mut magic))
        .is_ok_and(|()| magic == *b"GCDE")
}

/// Extract metadata without letting a missing or malformed file abort an import.
pub fn parse(path: &Path) -> Metadata {
    if !is_bgcode(path) {
        return parse_text_path(path).unwrap_or_default();
    }
    printstash_libbgcode::inspect(path, false, false)
        .map(|inspection| parse_text(&inspection.metadata_text))
        .unwrap_or_default()
}

/// Validate binary framing and every checksum while keeping G-code bodies bounded.
pub fn is_valid_bgcode(path: &Path) -> bool {
    if !is_bgcode(path) {
        return false;
    }
    printstash_libbgcode::inspect(path, false, true)
        .is_ok_and(|inspection| inspection.valid && inspection.saw_block && inspection.saw_gcode)
}

pub fn bgcode_metadata_text(path: &Path) -> Option<String> {
    if !is_bgcode(path) {
        return None;
    }
    printstash_libbgcode::inspect(path, false, false)
        .ok()
        .map(|inspection| inspection.metadata_text)
        .filter(|text| !text.is_empty())
}

/// Return only successfully decoded, bounded binary previews.
pub fn thumbnails(path: &Path) -> Vec<Thumbnail> {
    if !is_bgcode(path) {
        return Vec::new();
    }
    printstash_libbgcode::inspect(path, true, false)
        .map(|inspection| {
            inspection
                .thumbnails
                .into_iter()
                .filter_map(|thumbnail| {
                    let format = match thumbnail.format {
                        0 => ThumbnailFormat::Png,
                        1 => ThumbnailFormat::Jpeg,
                        2 => ThumbnailFormat::Qoi,
                        _ => return None,
                    };
                    Some(Thumbnail {
                        format,
                        width: thumbnail.width,
                        height: thumbnail.height,
                        data: thumbnail.data,
                    })
                })
                .collect()
        })
        .unwrap_or_default()
}

fn first_match(text: &str, expressions: &[Regex]) -> Option<String> {
    expressions.iter().find_map(|expression| {
        expression
            .captures(text)
            .and_then(|capture| capture.get(1))
            .map(|value| value.as_str().trim().to_owned())
    })
}

fn value(text: &str, key: &str) -> Option<String> {
    PATTERNS
        .iter()
        .find(|pattern| pattern.key == key)
        .and_then(|pattern| first_match(text, &pattern.expressions))
}

fn float(value: Option<&str>) -> Option<f64> {
    let capture = NUMBER.find(value?)?;
    capture.as_str().parse().ok()
}

fn integer(value: Option<&str>) -> Option<i64> {
    let number = value?.split(',').next()?.trim().parse::<f64>().ok()?;
    (number.is_finite() && number >= i64::MIN as f64 && number < i64::MAX as f64)
        .then_some(number as i64)
}

fn flag(value: Option<&str>) -> Option<bool> {
    match value?
        .split(',')
        .next()?
        .trim()
        .to_ascii_lowercase()
        .as_str()
    {
        "1" | "true" | "yes" | "on" | "enabled" | "generated" => Some(true),
        "0" | "false" | "no" | "off" | "disabled" | "none" | "not generated" => Some(false),
        _ => None,
    }
}

fn first_list_value(value: Option<&str>) -> Option<String> {
    value?
        .split([';', ','])
        .next()
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .map(str::to_owned)
}

fn list(value: Option<&str>) -> Vec<String> {
    value
        .into_iter()
        .flat_map(|value| value.split([';', ',']))
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .map(str::to_owned)
        .collect()
}

fn color(value: &str) -> Option<String> {
    let value = value.trim().to_ascii_uppercase();
    COLOR
        .captures(&value)
        .and_then(|capture| capture.get(1))
        .map(|digits| format!("#{}", digits.as_str()))
}

fn slicer_name(version: Option<&str>) -> Option<String> {
    let lower = version?.to_ascii_lowercase();
    [
        ("orca", "OrcaSlicer"),
        ("prusa", "PrusaSlicer"),
        ("bambu", "BambuStudio"),
        ("super", "SuperSlicer"),
        ("cura", "Cura"),
    ]
    .into_iter()
    .find(|(needle, _)| lower.contains(needle))
    .map(|(_, name)| name.to_owned())
}

pub fn parse_duration(value: &str) -> Option<u64> {
    let matches: Vec<_> = DURATION.captures_iter(value).collect();
    if matches.is_empty() {
        let seconds = value.trim().parse::<f64>().ok()?;
        return whole_seconds(seconds);
    }
    let total = matches
        .into_iter()
        .map(|capture| {
            let amount = capture[1].parse::<f64>().unwrap_or(0.0);
            let multiplier = match capture[2].to_ascii_lowercase().as_str() {
                "d" => 86_400.0,
                "h" => 3_600.0,
                "m" => 60.0,
                _ => 1.0,
            };
            amount * multiplier
        })
        .sum::<f64>();
    whole_seconds(total)
}

fn whole_seconds(value: f64) -> Option<u64> {
    (value.is_finite() && value >= 0.0 && value < u64::MAX as f64).then_some(value as u64)
}

pub fn parse_text(text: &str) -> Metadata {
    let slicer_version = value(text, "slicer_version");
    let material_text = value(text, "material_type");
    let materials = list(material_text.as_deref());
    let colors = list(first_match(text, &FILAMENT_COLOR_PATTERNS).as_deref());
    let material_requirements = (!materials.is_empty()).then(|| {
        materials
            .into_iter()
            .enumerate()
            .map(|(tool_index, material_type)| MaterialRequirement {
                tool_index,
                color_hex: colors.get(tool_index).and_then(|value| color(value)),
                material_type,
            })
            .collect()
    });
    let mut filament_length_mm = float(value(text, "filament_length_mm").as_deref());
    if filament_length_mm.is_some() && !MM_LENGTH.is_match(text) && CURA_METERS.is_match(text) {
        filament_length_mm = filament_length_mm.map(|value| value * 1000.0);
    }
    let estimated_time = value(text, "estimated_time_raw");
    Metadata {
        slicer_name: slicer_name(slicer_version.as_deref()),
        slicer_version,
        printer_model: value(text, "printer_model"),
        nozzle_diameter_mm: float(value(text, "nozzle_diameter_mm").as_deref()),
        layer_height_mm: float(value(text, "layer_height_mm").as_deref()),
        first_layer_height_mm: float(value(text, "first_layer_height_mm").as_deref()),
        infill_percent: float(value(text, "infill_percent").as_deref()),
        wall_loops: integer(value(text, "wall_loops").as_deref()),
        top_shell_layers: integer(value(text, "top_shell_layers").as_deref()),
        bottom_shell_layers: integer(value(text, "bottom_shell_layers").as_deref()),
        support_material: flag(value(text, "support_material_raw").as_deref()),
        nozzle_temperature_c: float(value(text, "nozzle_temperature_c").as_deref()),
        bed_temperature_c: float(value(text, "bed_temperature_c").as_deref()),
        estimated_time_s: estimated_time.as_deref().and_then(parse_duration),
        filament_weight_g: float(value(text, "filament_weight_g").as_deref()),
        filament_length_mm,
        filament_cost: float(value(text, "filament_cost").as_deref()),
        material_type: first_list_value(material_text.as_deref()),
        material_brand: first_list_value(value(text, "material_brand").as_deref()),
        material_requirements,
        printer_preset_name: value(text, "printer_preset_name"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    #[test]
    fn keeps_materials_in_tool_order() {
        let metadata = parse_text("; generated by BambuStudio 2.0\n; filament_type = PLA;PETG\n; filament_colour = FF0000FF;#00FF00\n; estimated printing time = 1h 2m 3s\n");
        assert_eq!(metadata.slicer_name.as_deref(), Some("BambuStudio"));
        assert_eq!(metadata.estimated_time_s, Some(3723));
        assert_eq!(
            metadata.material_requirements.unwrap(),
            vec![
                MaterialRequirement {
                    tool_index: 0,
                    material_type: "PLA".into(),
                    color_hex: Some("#FF0000".into())
                },
                MaterialRequirement {
                    tool_index: 1,
                    material_type: "PETG".into(),
                    color_hex: Some("#00FF00".into())
                },
            ]
        );
    }

    #[test]
    fn parses_supported_duration_forms_and_rejects_invalid_values() {
        for (input, expected) in [
            ("1h 23m 45s", Some(5_025)),
            ("2d 4h", Some(187_200)),
            ("123.5", Some(123)),
            ("1.5h", Some(5_400)),
            ("0.5m", Some(30)),
            ("0h 0m 0s", Some(0)),
            ("-5", None),
            ("1e100", None),
            ("999999999999999999999999h", None),
            ("", None),
            ("not a duration", None),
        ] {
            assert_eq!(parse_duration(input), expected, "{input}");
        }
    }

    #[test]
    fn rejects_out_of_range_integer_metadata() {
        let metadata = parse_text(
            "; wall_loops = 999999999999999999999999\n\
             ; top_shell_layers = 4\n",
        );

        assert_eq!(metadata.wall_loops, None);
        assert_eq!(metadata.top_shell_layers, Some(4));
    }

    #[test]
    fn parses_prusa_metadata_without_scaling_millimetres() {
        let metadata = parse_text(
            "; generated by PrusaSlicer 2.7.0\n\
             ; printer_settings_id = MK4 Input Shaper 0.4 nozzle\n\
             ; fill_density = 15%\n\
             ; filament used [mm] = 3350.2\n\
             ; filament_type = PETG\n",
        );

        assert_eq!(metadata.slicer_name.as_deref(), Some("PrusaSlicer"));
        assert_eq!(
            metadata.printer_model.as_deref(),
            Some("MK4 Input Shaper 0.4 nozzle")
        );
        assert_eq!(metadata.printer_preset_name, metadata.printer_model);
        assert_eq!(metadata.infill_percent, Some(15.0));
        assert_eq!(metadata.filament_length_mm, Some(3350.2));
        assert_eq!(metadata.material_type.as_deref(), Some("PETG"));
    }

    #[test]
    fn converts_cura_metres_but_prefers_an_explicit_millimetre_length() {
        let metres = parse_text(
            "; generated by Cura_SteamEngine 5.6.0\n\
             ;Filament used : 1.5m\n",
        );
        assert_eq!(metres.slicer_name.as_deref(), Some("Cura"));
        assert_eq!(metres.filament_length_mm, Some(1_500.0));

        let explicit_mm = parse_text(
            "; generated by OrcaSlicer 2.3.2\n\
             ;Filament used:4.20m\n\
             ; filament used [mm] = 4201.91\n",
        );
        assert_eq!(explicit_mm.filament_length_mm, Some(4201.91));
    }

    #[test]
    fn keeps_bed_temperature_out_of_the_nozzle_field() {
        let metadata = parse_text(
            "; generated by PrusaSlicer 2.7.0\n\
             ; bed_temperature = 60\n",
        );

        assert_eq!(metadata.bed_temperature_c, Some(60.0));
        assert_eq!(metadata.nozzle_temperature_c, None);
    }

    #[test]
    fn parses_flags_and_ignores_unrecognised_spellings() {
        for (input, expected) in [
            ("1", Some(true)),
            ("TRUE", Some(true)),
            ("generated", Some(true)),
            ("0", Some(false)),
            ("not generated", Some(false)),
            ("maybe", None),
        ] {
            let metadata = parse_text(&format!("; support_material = {input}\n"));
            assert_eq!(metadata.support_material, expected, "{input}");
        }
    }

    #[test]
    fn drops_invalid_tool_colours_without_dropping_materials() {
        let metadata = parse_text(
            "; generated by BambuStudio 2.0\n\
             ; filament_type = PLA;PETG;ABS\n\
             ; filament_colour = FF0000FF;not-a-colour;00FF00\n",
        );
        let requirements = metadata.material_requirements.unwrap();

        assert_eq!(requirements.len(), 3);
        assert_eq!(requirements[0].color_hex.as_deref(), Some("#FF0000"));
        assert_eq!(requirements[1].color_hex, None);
        assert_eq!(requirements[2].color_hex.as_deref(), Some("#00FF00"));
    }

    #[test]
    fn accepts_crlf_and_lossy_utf8_text() {
        let bytes =
            b"; generated by OrcaSlicer 1.9.0\r\n; profile = \xff\xfe\r\n; layer_height = 0.2\r\n";
        let metadata = parse_text(&String::from_utf8_lossy(bytes));

        assert_eq!(metadata.slicer_name.as_deref(), Some("OrcaSlicer"));
        assert_eq!(metadata.layer_height_mm, Some(0.2));
    }

    #[test]
    fn reads_only_file_ends() {
        let path =
            std::env::temp_dir().join(format!("printstash-gcode-core-{}", std::process::id()));
        let mut file = File::create(&path).unwrap();
        file.write_all(b"; generated by OrcaSlicer 2.1\n").unwrap();
        file.write_all(&vec![b'x'; HEAD_BYTES as usize]).unwrap();
        file.write_all(b"; layer_height = 0.9\n").unwrap();
        file.write_all(&vec![b'y'; TAIL_BYTES as usize]).unwrap();
        file.write_all(b"; nozzle_diameter = 0.4\n").unwrap();
        drop(file);
        let metadata = parse_text_path(&path).unwrap();
        std::fs::remove_file(path).unwrap();
        assert_eq!(metadata.slicer_name.as_deref(), Some("OrcaSlicer"));
        assert_eq!(metadata.layer_height_mm, None);
        assert_eq!(metadata.nozzle_diameter_mm, Some(0.4));
    }
}
