"""Slicer ("Open in slicer") download-token flow — issue #27.

An external slicer process can't send the user's bearer token, so the file
download must be reachable via a short-lived, file-scoped capability token
instead. The frontend mints one through `/slicer-url` and appends it to the
download URL as `?slicer_token=`.
"""

from __future__ import annotations

from pathlib import Path

from fastapi.testclient import TestClient
from sqlmodel import Session

from app.db.models import FileType
from app.services import auth
from tests._env import use_local_storage
from tests.integration.api.v1._ingest_assertions import (
    assert_file_created,
    completed_job,
)
from tests.paths import FIXTURES_DIR


def _ingest_gcode(client: TestClient, auth_headers: dict[str, str]) -> int:
    gcode = (FIXTURES_DIR / "sample.gcode").read_bytes()
    payload = completed_job(
        client,
        client.post(
            "/api/v1/ingest/orca",
            headers=auth_headers,
            files={"file": ("sample.gcode", gcode, "text/plain")},
            data={"model_name": "Slicer Sample"},
        ),
    )
    return payload["file_id"]


class TestVerifyDownloadToken:
    def test_token_for_wrong_file_is_rejected(
        self,
        tmp_path: Path,
        client: TestClient,
        auth_headers: dict[str, str],
    ) -> None:
        use_local_storage(tmp_path)
        file_id = _ingest_gcode(client, auth_headers)

        # A token minted for a different file id must not unlock this one.
        other_token = auth.create_file_download_token(file_id + 999)
        resp = client.get(f"/api/v1/files/{file_id}/slicer/{other_token}/sample.gcode")
        assert resp.status_code == 401, resp.text

    def test_garbage_token_is_rejected(
        self,
        tmp_path: Path,
        client: TestClient,
        auth_headers: dict[str, str],
    ) -> None:
        use_local_storage(tmp_path)
        file_id = _ingest_gcode(client, auth_headers)

        resp = client.get(f"/api/v1/files/{file_id}/slicer/not-a-jwt/sample.gcode")
        assert resp.status_code == 401, resp.text

    def test_verify_download_token_unit(self) -> None:
        token = auth.create_file_download_token(42)
        assert auth.verify_file_download_token(token, 42) is True
        assert auth.verify_file_download_token(token, 43) is False
        # A normal access token isn't a download token (wrong scope).
        access = auth.create_access_token(1, "alice", "write")
        assert auth.verify_file_download_token(access, 42) is False


class TestAuth:
    def test_a_slicer_url_token_downloads_without_a_session(
        self,
        tmp_path: Path,
        client: TestClient,
        db_session: Session,
        auth_headers: dict[str, str],
    ) -> None:
        use_local_storage(tmp_path)
        file_id = _ingest_gcode(client, auth_headers)
        assert_file_created(db_session, file_id, FileType.GCODE)

        # Minting the URL requires auth + VIEW access.
        resp = client.get(f"/api/v1/files/{file_id}/slicer-url", headers=auth_headers)
        assert resp.status_code == 200, resp.text
        url = resp.json()["url"]
        # The URL must END with the original filename (token earlier in the path), so
        # the slicer detects the format. A trailing ?token=… query made OrcaSlicer
        # save the blob as "sample.gcode?slicer_token=…" and never open it (#27).
        assert url.startswith(f"/api/v1/files/{file_id}/slicer/")
        assert url.endswith("/sample.gcode")

        # The slicer fetches that URL with NO Authorization header.
        download = client.get(url)
        assert download.status_code == 200, download.text
        assert b"; generated by OrcaSlicer" in download.content

    def test_download_without_auth_or_token_is_rejected(
        self,
        tmp_path: Path,
        client: TestClient,
        auth_headers: dict[str, str],
    ) -> None:
        use_local_storage(tmp_path)
        file_id = _ingest_gcode(client, auth_headers)

        resp = client.get(f"/api/v1/files/{file_id}/download")
        assert resp.status_code == 401, resp.text

    def test_slicer_url_requires_auth(
        self,
        tmp_path: Path,
        client: TestClient,
        auth_headers: dict[str, str],
    ) -> None:
        use_local_storage(tmp_path)
        file_id = _ingest_gcode(client, auth_headers)

        resp = client.get(f"/api/v1/files/{file_id}/slicer-url")
        assert resp.status_code == 401, resp.text
