/**
 * Putting two G-code revisions side by side.
 *
 * Comparing revisions is how somebody decides which one to print, so the view has to
 * surface what actually *differs* — a comparison that renders both columns identically
 * when the layer heights differ is worse than no comparison, because it answers the
 * question wrongly rather than not at all.
 */
import { test, expect } from "./helpers";
import { modelCard } from "./util";

// Compare Artifacts (0.10.0): with two G-code revisions on a model, the compare
// panel appears and shows a field-level diff — matching values render plain,
// differing values are highlighted.

test.describe("revision comparison", () => {
  test("comparing two revisions surfaces differing metadata", async ({ page }) => {
    const name = `e2e-compare-${Date.now()}`;

    await page.goto("/");
    await page.getByRole("button", { name: "Upload", exact: true }).click();
    const dialog = page.getByRole("dialog", { name: "Upload model" });
    await expect(dialog).toBeVisible();
    await page.locator('input[accept=".gcode,.g,.gco"]').setInputFiles({
      name: "rev1.gcode",
      mimeType: "text/plain",
      buffer: Buffer.from(
        ["; generated by e2e", "; estimated printing time (normal mode) = 30m 12s", "G28"].join(
          "\n",
        ),
      ),
    });
    await page.getByPlaceholder("e.g. Bracket v2").fill(name);
    await page.getByRole("button", { name: /upload to vault/i }).click();
    await expect(dialog).toHaveCount(0);

    await expect(async () => {
      await page.goto("/");
      await expect(modelCard(page, name)).toBeVisible({ timeout: 2_000 });
    }).toPass({ timeout: 30_000 });

    await modelCard(page, name).click();
    await expect(page.getByRole("heading", { name })).toBeVisible();
    await page.getByRole("tab", { name: /Revisions/ }).click();
    await expect(page.getByText("Rev 1", { exact: true }).first()).toBeVisible();

    // A second revision with a very different estimated print time — that field
    // should show up as a highlighted diff once compared.
    await page.getByRole("button", { name: "Add", exact: true }).click();
    await expect(page.getByRole("heading", { name: "Add G-code revision" })).toBeVisible();
    await page.locator('input[accept=".gcode,.g,.gco"]').setInputFiles({
      name: "rev2.gcode",
      mimeType: "text/plain",
      buffer: Buffer.from(
        ["; second revision", "; estimated printing time (normal mode) = 2h 5m", "G28"].join("\n"),
      ),
    });
    await page.getByRole("button", { name: "Add revision" }).click();
    await expect(page.getByText("Rev 2", { exact: true }).first()).toBeVisible();

    const compare = page.getByRole("heading", { name: /Compare Artifacts/ }).locator("..");
    await expect(compare).toBeVisible();

    // The two selects default to the most recent revisions, but which side gets
    // which is an implementation detail — pin them explicitly to rev1 vs rev2 so
    // the diff assertion below is deterministic.
    const selects = compare.locator("select");
    const rev1Value = await selects
      .nth(0)
      .locator("option", { hasText: "rev1.gcode" })
      .getAttribute("value");
    const rev2Value = await selects
      .nth(1)
      .locator("option", { hasText: "rev2.gcode" })
      .getAttribute("value");
    await selects.nth(0).selectOption(rev1Value!);
    await selects.nth(1).selectOption(rev2Value!);

    // Est. time differs between the two revisions — its right-hand value is
    // rendered in the diff-highlight style, distinct from a matching field.
    const estTimeRow = compare
      .locator("div")
      .filter({ hasText: /^Est\. time/ })
      .first();
    const [, leftValue, rightValue] = await estTimeRow.locator("span").allTextContents();
    expect(leftValue).not.toBe(rightValue);
  });
});
