import { expect, type Page } from "@playwright/test";

// The backend dedupes files by content hash, so the bytes must be unique per
// model — embed the name so each upload creates a distinct model.
function gcodeFor(name: string): string {
  return [
    `; generated by e2e for ${name}`,
    "; estimated printing time (normal mode) = 30m 12s",
    "; filament used [g] = 6.8",
    "G28",
    "G1 Z0.2 F300",
  ].join("\n");
}

// A minimal single-triangle ASCII STL; the solid name keeps the bytes unique.
function stlFor(name: string): string {
  return [
    `solid ${name}`,
    "facet normal 0 0 1",
    " outer loop",
    "  vertex 0 0 0",
    "  vertex 1 0 0",
    "  vertex 0 1 0",
    " endloop",
    "endfacet",
    `endsolid ${name}`,
  ].join("\n");
}

export function modelCard(page: Page, name: string) {
  return page.locator('a[href^="/models/"]').filter({ hasText: name });
}

type UploadOpts = { mesh?: boolean; gcode?: boolean; collection?: string; tag?: string };

// Upload a model through the real upload flow and wait for async ingestion to
// surface it. With a collection it lands inside that collection, not at root.
export async function uploadModel(page: Page, name: string, opts: UploadOpts = {}): Promise<void> {
  const { mesh = false, gcode = true, collection, tag } = opts;
  await page.goto("/");
  await page.getByRole("button", { name: "Upload" }).click();
  const dialog = page.getByRole("dialog", { name: "Upload model" });
  await expect(dialog).toBeVisible();

  if (gcode) {
    await page.locator('input[accept=".gcode,.g,.gco"]').setInputFiles({
      name: `${name}.gcode`,
      mimeType: "text/plain",
      buffer: Buffer.from(gcodeFor(name)),
    });
  }
  if (mesh) {
    await page.locator('input[accept=".stl,.3mf,.obj,.step,.stp"]').setInputFiles({
      name: `${name}.stl`,
      mimeType: "model/stl",
      buffer: Buffer.from(stlFor(name)),
    });
  }
  await page.getByPlaceholder("e.g. Bracket v2").fill(name);

  if (collection) {
    await dialog.getByRole("button", { name: "None" }).click();
    await dialog.getByRole("option", { name: new RegExp(collection) }).click();
  }
  if (tag) {
    const tagInput = page.getByPlaceholder("Search or create — press Enter");
    await tagInput.fill(tag);
    await tagInput.press("Enter");
  }

  await page.getByRole("button", { name: /upload to vault/i }).click();
  await expect(dialog).toHaveCount(0);

  const view = collection ? `/?c=${encodeURIComponent(collection)}` : "/";
  await expect(async () => {
    await page.goto(view);
    await expect(modelCard(page, name)).toBeVisible({ timeout: 2_000 });
  }).toPass({ timeout: 60_000 });
}

export function uploadGcodeModel(page: Page, name: string): Promise<void> {
  return uploadModel(page, name, { gcode: true });
}
