"""Headline E2E for Bambu external-job evidence recovery (#70)."""

from __future__ import annotations

import zipfile
from pathlib import Path

import pytest
from sqlmodel import select

from app.db.models import File, FileType, PrinterProvider, PrintJob
from app.services.printer_hub import PrinterHub
from tests.factories import build_printer


class TestExternalCapture:
    @pytest.mark.asyncio
    async def test_external_bambu_job_archives_available_gcode_through_real_storage(
        self, api, superuser_headers, e2e_db, tmp_path: Path
    ):
        printer = build_printer(
            e2e_db,
            name="Bambu X1C",
            provider=PrinterProvider.BAMBU_LAN,
            bambu_host="192.0.2.10",
            bambu_serial="01P00A123456",
            bambu_access_code="12345678",
        )
        hub = PrinterHub()

        capture = hub._sync_active_job_db(
            int(printer.id),
            "printing",
            "benchy.gcode",
            0.25,
            {
                "state": "printing",
                "filename": "benchy.gcode",
                "external_display_name": "Benchy",
                "external_task_id": "task-42",
                "external_project_id": "project-7",
                "external_plate_index": 2,
                "external_gcode_file": "/cache/benchy.gcode",
                "_capture_available": True,
            },
        )
        assert capture is not None
        job_id, remote_path = capture
        assert remote_path == "/cache/benchy.gcode"

        staged = tmp_path / "benchy.3mf"
        with zipfile.ZipFile(staged, "w", compression=zipfile.ZIP_DEFLATED) as archive:
            archive.writestr(
                "Metadata/plate_2.gcode", b"; generated by Bambu Studio\nG28\n"
            )
        hub._persist_external_artifact(job_id, staged, "benchy.3mf")

        e2e_db.expire_all()
        job = e2e_db.exec(
            select(PrintJob).where(PrintJob.provider_job_id == "task-42")
        ).one()
        artifact = e2e_db.get(File, job.file_id)
        assert job.source == "external"
        assert job.external_project_id == "project-7"
        assert job.artifact_evidence == "project_archived"
        assert artifact is not None
        assert artifact.original_filename == "benchy.3mf"
        assert artifact.file_type == FileType.THREE_MF
        assert artifact.sha256 != "0" * 64
        e2e_db.close()

        # The API read contract distinguishes exact artifact evidence from the
        # printer-reported identity/metadata that cannot reconstruct slicer input.
        from app.services.printer_jobs import reproducibility_payload

        contract = reproducibility_payload(
            job,
            file_type=artifact.file_type,
            download_url=f"/api/v1/files/{job.file_id}/download",
        )
        assert contract["reproducibility_level"] == "exact"
        assert contract["identity"]["task_id"] == "task-42"
        assert contract["identity"]["project_id"] == "project-7"
        assert contract["download_url"].endswith("/download")
        assert contract["toolpath_preview_url"] == (
            f"/api/v1/files/{job.file_id}/embedded-gcode?plate_index=2"
        )

        response = await api.get(
            f"/api/v1/files/{job.file_id}/embedded-gcode?plate_index=2",
            headers=superuser_headers,
        )
        assert response.status_code == 200, response.text
        assert response.content == b"; generated by Bambu Studio\nG28\n"
