"""Headline E2E for Bambu external-job evidence recovery (#70)."""

from __future__ import annotations

from pathlib import Path

from sqlmodel import select

from app.db.models import File, Printer, PrinterProvider, PrintJob
from app.services.printer_hub import PrinterHub


def test_external_bambu_job_archives_available_gcode_through_real_storage(
    e2e_db, tmp_path: Path
):
    printer = Printer(
        name="Bambu X1C",
        provider=PrinterProvider.BAMBU_LAN,
        bambu_host="192.0.2.10",
        bambu_serial="01P00A123456",
        bambu_access_code="12345678",
    )
    e2e_db.add(printer)
    e2e_db.commit()
    e2e_db.refresh(printer)
    hub = PrinterHub()

    capture = hub._sync_active_job_db(
        int(printer.id),
        "printing",
        "benchy.gcode",
        0.25,
        {
            "state": "printing",
            "filename": "benchy.gcode",
            "external_display_name": "Benchy",
            "external_task_id": "task-42",
            "external_project_id": "project-7",
            "external_gcode_file": "/cache/benchy.gcode",
            "_capture_available": True,
        },
    )
    assert capture is not None
    job_id, remote_path = capture
    assert remote_path == "/cache/benchy.gcode"

    staged = tmp_path / "benchy.gcode"
    staged.write_bytes(b"; generated by Bambu Studio\nG28\n")
    hub._persist_external_artifact(job_id, staged, "benchy.gcode")

    e2e_db.expire_all()
    job = e2e_db.exec(
        select(PrintJob).where(PrintJob.provider_job_id == "task-42")
    ).one()
    artifact = e2e_db.get(File, job.file_id)
    assert job.source == "external"
    assert job.external_project_id == "project-7"
    assert job.artifact_evidence == "gcode_archived"
    assert artifact is not None
    assert artifact.original_filename == "benchy.gcode"
    assert artifact.sha256 != "0" * 64
