"""A migration changes the schema the same way on every dialect, or it is not done.

SQLite's `ALTER TABLE` supports four things: rename table, rename column, add
column, drop column. There is no `ADD CONSTRAINT` and there never has been, so
`op.create_foreign_key` — which compiles to exactly that — fails with
`OperationalError: near "FOREIGN": syntax error`.

Alembic's answer is `op.batch_alter_table`, which on SQLite rebuilds the table:
create a new one with the full target definition, copy the rows, drop the old,
rename. `alembic/env.py` already passes `render_as_batch=True` for SQLite, so
**autogenerated** migrations get those blocks for free.

`render_as_batch` is a *rendering* flag, though. It shapes what `alembic revision
--autogenerate` writes into a file; it does nothing for a migration written by hand.
A hand-written `op.create_foreign_key` is a plain `ALTER TABLE ... ADD CONSTRAINT`
whatever `env.py` says.

That is how this happened. `69b6a6d8a1d1` was written by hand — no autogenerate
marker, a round `Create Date`, a hand-rolled loop over table names — hit the SQLite
error, and resolved it with `if not is_sqlite:` around the constraint. The column
landed on every dialect and the constraint landed on none of the SQLite ones, which
is the default database of this product. Eighteen foreign keys the models declare do
not exist on any installation that upgraded through the chain, and
`tests/integration/db/migrations/test_models_versus_chain.py` measures what that
grew into.

Nothing caught it for three months because nothing compared the two schemas, and
because the test suite had foreign keys switched off, so the constraint's absence
changed no test's outcome.

Goes red when: a migration skips a constraint operation on a dialect instead of
using batch mode.
"""

from __future__ import annotations

import ast
from pathlib import Path

import pytest

VERSIONS = Path(__file__).resolve().parents[2] / "alembic" / "versions"

# Operations SQLite cannot express as an `ALTER TABLE`, and which therefore have to
# go through `op.batch_alter_table` rather than behind a dialect check.
CONSTRAINT_OPERATIONS = {
    "create_foreign_key",
    "drop_constraint",
    "create_unique_constraint",
    "create_check_constraint",
}

# The one migration that predates this rule, kept so the count can only fall.
# Its `upgrade()` is why an upgraded SQLite installation is missing eighteen foreign
# keys; its `downgrade()` skips the matching drops. Fixing it means a *new* migration
# with batch mode, never editing this one — self-hosters have already run it.
RECORDED_EXCEPTIONS = {"69b6a6d8a1d1_phase_4c_4d_lifecycle_audit.py"}


def _migrations() -> list[Path]:
    return sorted(p for p in VERSIONS.glob("*.py") if not p.name.startswith("__"))


def _dialect_guarded_constraint_ops(tree: ast.Module) -> list[str]:
    """Constraint operations a dialect check makes conditional.

    Structural rather than a grep for `is_sqlite`, and it turns on *who the call is
    made on*, which is what separates the two shapes:

        if is_sqlite:                            # correct
            with op.batch_alter_table("x") as b:
                b.drop_constraint(...)

        if not is_sqlite:                        # the bug
            op.drop_constraint(...)

    Branching per dialect is normal and often unavoidable. Calling `op.<constraint>`
    directly inside that branch is the smell, because the other dialect then gets no
    constraint at all; `batch.<constraint>` inside a `batch_alter_table` block is the
    supported way to do the same thing on SQLite.
    """
    found: list[str] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.If):
            continue
        test = ast.unparse(node.test)
        if "sqlite" not in test.lower() and "dialect" not in test.lower():
            continue
        for inner in ast.walk(node):
            if not (
                isinstance(inner, ast.Call)
                and isinstance(inner.func, ast.Attribute)
                and inner.func.attr in CONSTRAINT_OPERATIONS
            ):
                continue
            receiver = inner.func.value
            if isinstance(receiver, ast.Name) and receiver.id == "op":
                found.append(f"op.{inner.func.attr} under `if {test}`")
    return found


class TestMigrations:
    @pytest.mark.parametrize("migration", _migrations(), ids=lambda p: p.name)
    def test_no_constraint_operation_is_skipped_for_a_dialect(
        self, migration: Path
    ) -> None:
        offenders = _dialect_guarded_constraint_ops(
            ast.parse(migration.read_text(encoding="utf-8"))
        )

        if migration.name in RECORDED_EXCEPTIONS:
            assert offenders, (
                f"{migration.name} is listed in RECORDED_EXCEPTIONS but no longer "
                "guards a constraint operation. Remove it from the list."
            )
            return

        assert not offenders, (
            f"{migration.name} skips {', '.join(offenders)}. A constraint the "
            "models declare and a migration does not create is a schema that "
            "differs between a fresh installation and an upgraded one, silently. "
            "Use `with op.batch_alter_table(...) as batch:` — SQLite cannot "
            "`ALTER TABLE ... ADD CONSTRAINT`, and batch mode rebuilds the table "
            "instead. `alembic/env.py` already renders it for autogenerated "
            "migrations; hand-written ones have to ask for it."
        )

    def test_the_exception_list_only_names_migrations_that_exist(self) -> None:
        names = {path.name for path in _migrations()}

        stale = sorted(RECORDED_EXCEPTIONS - names)

        assert not stale, (
            "RECORDED_EXCEPTIONS names migrations that are not there: "
            + ", ".join(stale)
        )
