; generated by BambuStudio 1.9.3.50 on 2025-02-14
; printer_model = Bambu Lab P1S 0.4 nozzle
; nozzle_diameter = 0.4
; layer_height = 0.16
; sparse_infill_density = 15%
; total filament used [g] = 18.25
; total filament length [mm] = 6120.4
; total filament cost = 0.52
; filament_type = PLA;PLA
; estimated printing time (normal mode) = 2h 4m 5s
G28
M84
