; generated by OrcaSlicer 2.0.0 on 2025-03-01
; printer_model = Voron 2.4 350 Klipper
; nozzle_diameter = 0.4,0.4
; layer_height = 0.24
; sparse_infill_density = 10%
; total filament used [g] = 31.4
; total filament length [mm] = 10500
; filament_type = ASA
; estimated printing time (normal mode) = 3h 12m
START_PRINT BED_TEMP=110 EXTRUDER_TEMP=250
END_PRINT
