; generated by PrusaSlicer 2.7.4+linux-x64 on 2025-01-08 at 12:34:56 UTC
; printer_settings_id = MK4 Input Shaper 0.4 nozzle
; nozzle_diameter = 0.4
; layer_height = 0.2
; fill density = 20%
; filament used [mm] = 3350.2
; filament used [g] = 9.7
; filament_type = PETG
; estimated printing time (normal mode) = 56m 12s
G28
M84
