; generated by OrcaSlicer 1.9.0 on 2024-03-15
; printer_model = Ender-3 V3 SE
; nozzle_diameter = 0.4
; layer_height = 0.2
; first_layer_height = 0.24
; sparse_infill_density = 15%
; wall_loops = 3
; top_shell_layers = 4
; bottom_shell_layers = 3
; enable_support = 0
; nozzle_temperature = 215
; bed_temperature = 60
; total filament used [g] = 12.5
; total filament length [mm] = 4200.0
; total filament cost = 0.35
; filament_type = PLA
; filament_brand = Generic PLA
; estimated printing time (normal mode) = 1h 23m 45s
;
; thumbnail begin 32x32 128
; iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR
; 42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==
; thumbnail end
;
G28 ; home all axes
G1 Z5 F5000 ; lift nozzle
M107
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
G1 Z0.200 F1800.000
G1 X10.000 Y10.000 E0.50000 F1800.000
G1 X20.000 Y10.000 E0.05000 F1800.000
G1 X20.000 Y20.000 E0.05000 F1800.000
G1 X10.000 Y20.000 E0.05000 F1800.000
G1 X10.000 Y10.000 E0.05000 F1800.000
M107
G28 X0 ; home X axis
M84 ; disable motors
