"""Unit tests for embedded thumbnail extraction."""

from __future__ import annotations

import base64
import io
from pathlib import Path

import pytest

from app.core.config import _overlay
from app.services.thumbnail import _MAX_BLOCK_LINES, extract, to_webp
from tests.paths import FIXTURES_DIR


def _block(width: int, height: int, payload: bytes) -> str:
    b64 = base64.b64encode(payload).decode()
    return f"; thumbnail begin {width}x{height} {len(b64)}\n; {b64}\n; thumbnail end\n"


class TestExtract:
    def test_extract_sample_gcode(self) -> None:
        fixture = FIXTURES_DIR / "sample.gcode"
        result = extract(fixture)
        assert result is not None
        assert len(result) > 0
        assert result[:4] == b"\x89PNG"  # PNG magic bytes

    def test_extract_missing_file(self, tmp_path: Path) -> None:
        result = extract(tmp_path / "nonexistent.gcode")
        assert result is None

    def test_extract_no_thumbnail(self, tmp_path: Path) -> None:
        f = tmp_path / "no_thumb.gcode"
        f.write_text("G28\nG1 X10 Y10\nM84\n")
        result = extract(f)
        assert result is None

    def test_picks_largest_block_by_area(self, tmp_path: Path) -> None:
        small = b"small-preview"
        large = b"large-preview-data" * 4
        f = tmp_path / "multi.gcode"
        f.write_text(
            "; generated by PrusaSlicer\n"
            + _block(16, 16, small)
            + _block(640, 480, large)
            + "G1 X0 Y0\n"
        )
        assert extract(f) == large

    def test_an_unterminated_block_is_bounded_before_giving_up(
        self, tmp_path: Path
    ) -> None:
        # Regression: a "thumbnail begin" with no "thumbnail end" must not buffer
        # the whole file; it is abandoned past the cap and yields nothing.
        f = tmp_path / "runaway.gcode"
        f.write_text(
            "; thumbnail begin 16x16 100\n" + "; AAAA\n" * (_MAX_BLOCK_LINES + 5000)
        )
        assert extract(f) is None

    def test_recovers_valid_block_after_runaway(self, tmp_path: Path) -> None:
        real = b"the-real-thumbnail"
        f = tmp_path / "recover.gcode"
        f.write_text(
            "; thumbnail begin 8x8 10\n"
            + "; ZZZZ\n" * (_MAX_BLOCK_LINES + 50)  # unterminated, abandoned
            + _block(64, 64, real)
            + "G1 X0\n"
        )
        assert extract(f) == real


class TestWebpNormalization:
    def test_embedded_preview_is_centered_on_the_canonical_canvas(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        from PIL import Image

        source = io.BytesIO()
        Image.new("RGB", (100, 200), "white").save(source, format="PNG")
        monkeypatch.setitem(_overlay, "model_thumbnail_width", 320)

        encoded = to_webp(source.getvalue())

        with Image.open(io.BytesIO(encoded)) as result:
            assert result.size == (320, 240)
            assert result.mode == "RGBA"
            alpha = result.getchannel("A")
            bounds = alpha.getbbox()
            assert bounds is not None
            assert bounds[0] > 0
            assert bounds[1] > 0
            assert bounds[2] < result.width
            assert bounds[3] < result.height

    def test_empty_transparent_preview_is_rejected(self) -> None:
        from PIL import Image

        source = io.BytesIO()
        Image.new("RGBA", (64, 64), (0, 0, 0, 0)).save(source, format="PNG")

        with pytest.raises(ValueError, match="thumbnail_empty"):
            to_webp(source.getvalue())

    def test_canonical_renderer_webp_is_validated_without_reencoding(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        from PIL import Image, ImageDraw

        monkeypatch.setitem(_overlay, "model_thumbnail_width", 320)
        source = io.BytesIO()
        image = Image.new("RGBA", (320, 240), (0, 0, 0, 0))
        ImageDraw.Draw(image).rectangle((32, 24, 287, 215), fill=(90, 130, 210, 255))
        image.save(source, format="WEBP", lossless=True, exact=True, method=6)
        encoded = source.getvalue()

        assert to_webp(encoded) == encoded
