"""Unit tests for the PrusaSlicer binary G-code (.bgcode) reader.

Most cases build a synthetic bgcode container in-memory so the tests don't
depend on the large repo fixture; one guarded case parses the real testdata
file when present.
"""

from __future__ import annotations

import io
import struct
import zlib
from pathlib import Path

from app.services import bgcode, thumbnail
from app.services.gcode_parser import parse
from tests.paths import TESTDATA_DIR, require_fixtures

_REAL_FIXTURE = TESTDATA_DIR / "benchy" / "BenchyRules_PLA_14m.bgcode"

# Block types.
_FILE_META, _GCODE, _SLICER_META, _PRINTER_META, _PRINT_META, _THUMBNAIL = (
    0,
    1,
    2,
    3,
    4,
    5,
)


def _block(
    btype: int, params: bytes, data: bytes, *, compression: int, checksum_type: int
) -> bytes:
    """Assemble one bgcode block. compression: 0=none, 1=deflate, 3='heatshrink'."""
    if compression == 1:
        body = zlib.compress(data)
    elif compression == 0:
        body = data
    else:
        # Heatshrink etc. — the reader must never try to decode these; the body
        # bytes are opaque, so any payload stands in for a real one.
        body = data
    header = struct.pack("<HHI", btype, compression, len(data))
    if compression != 0:
        header += struct.pack("<I", len(body))
    blk = header + params + body
    if checksum_type != 0:
        # The reader skips the checksum without validating it; any 4 bytes work.
        blk += struct.pack("<I", zlib.crc32(blk) & 0xFFFFFFFF)
    return blk


def _meta_params() -> bytes:
    return struct.pack("<H", 0)  # encoding = INI


def _thumb_params(fmt: int, w: int, h: int) -> bytes:
    return struct.pack("<HHH", fmt, w, h)


def _build(blocks: list[bytes], *, checksum_type: int = 1) -> bytes:
    return b"GCDE" + struct.pack("<IH", 1, checksum_type) + b"".join(blocks)


def _png_bytes(w: int, h: int) -> bytes:
    from PIL import Image

    buf = io.BytesIO()
    Image.new("RGB", (w, h), (10, 20, 30)).save(buf, format="PNG")
    return buf.getvalue()


def _sample_container(*, checksum_type: int = 1) -> bytes:
    file_meta = _block(
        _FILE_META,
        _meta_params(),
        b"Producer=PrusaSlicer 2.8.0+win64\n",
        compression=0,
        checksum_type=checksum_type,
    )
    printer_meta = _block(
        _PRINTER_META,
        _meta_params(),
        (
            b"printer_model=MK4S\nnozzle_diameter=0.4\nbed_temperature=60\n"
            b"fill_density=15%\nlayer_height=0.2\ntemperature=215\n"
            b"support_material=0\nfilament_type=PETG\n"
        ),
        compression=0,
        checksum_type=checksum_type,
    )
    # Deflate-compressed, to exercise the zlib path.
    print_meta = _block(
        _PRINT_META,
        _meta_params(),
        (
            b"filament used [mm]=1234.5\ntotal filament used [g]=7.5\n"
            b"total filament cost=0.25\nestimated printing time (normal mode)=1h 5m 3s\n"
        ),
        compression=1,
        checksum_type=checksum_type,
    )
    thumb = _block(
        _THUMBNAIL,
        _thumb_params(0, 16, 16),
        _png_bytes(16, 16),
        compression=0,
        checksum_type=checksum_type,
    )
    # A "heatshrink" g-code block the reader must skip without decoding.
    gcode = _block(
        _GCODE,
        struct.pack("<H", 2),
        b"\x00\x01\x02opaque-heatshrink-bytes",
        compression=3,
        checksum_type=checksum_type,
    )
    return _build(
        [file_meta, printer_meta, thumb, print_meta, gcode], checksum_type=checksum_type
    )


class TestSyntheticBgcode:
    def _parse(self, tmp_path: Path, *, checksum_type: int = 1) -> dict:
        p = tmp_path / "sample.bgcode"
        p.write_bytes(_sample_container(checksum_type=checksum_type))
        return parse(p)

    def test_is_bgcode_detects_magic(self, tmp_path: Path) -> None:
        p = tmp_path / "sample.bgcode"
        p.write_bytes(_sample_container())
        assert bgcode.is_bgcode(p) is True

        plain = tmp_path / "plain.gcode"
        plain.write_text("; generated by PrusaSlicer\nG1 X0\n")
        assert bgcode.is_bgcode(plain) is False

    def test_metadata_fields(self, tmp_path: Path) -> None:
        result = self._parse(tmp_path)
        assert result["slicer_name"] == "PrusaSlicer"
        assert result["slicer_version"] == "PrusaSlicer 2.8.0+win64"
        assert result["printer_model"] == "MK4S"
        assert result["nozzle_diameter_mm"] == 0.4
        assert result["layer_height_mm"] == 0.2
        assert result["infill_percent"] == 15.0
        assert result["nozzle_temperature_c"] == 215.0
        assert result["bed_temperature_c"] == 60.0
        assert result["support_material"] is False
        assert result["material_type"] == "PETG"

    def test_metadata_from_deflate_block(self, tmp_path: Path) -> None:
        result = self._parse(tmp_path)
        # These live in the deflate-compressed PrintMeta block.
        assert result["filament_length_mm"] == 1234.5
        assert result["filament_weight_g"] == 7.5
        assert result["filament_cost"] == 0.25
        assert result["estimated_time_s"] == 3903  # 1h 5m 3s

    def test_mm_length_not_treated_as_metres(self, tmp_path: Path) -> None:
        # An explicit "[mm]" length must not be multiplied by 1000.
        assert self._parse(tmp_path)["filament_length_mm"] == 1234.5

    def test_works_without_per_block_checksum(self, tmp_path: Path) -> None:
        assert self._parse(tmp_path, checksum_type=0)["printer_model"] == "MK4S"

    def test_thumbnail_extracted(self, tmp_path: Path) -> None:
        p = tmp_path / "sample.bgcode"
        p.write_bytes(_sample_container())
        thumb = thumbnail.extract(p)
        assert thumb is not None
        assert thumb[:8] == b"\x89PNG\r\n\x1a\n"
        # And it survives the WebP conversion seam used on ingest.
        assert thumbnail.to_webp(thumb)[:4] == b"RIFF"

    def test_malformed_returns_empty_not_raises(self, tmp_path: Path) -> None:
        # Truncated mid-block: every field stays None, no exception.
        p = tmp_path / "truncated.bgcode"
        p.write_bytes(_sample_container()[:40])
        result = parse(p)
        assert all(v is None for v in result.values())

    def test_not_bgcode_falls_through_to_text_parser(self, tmp_path: Path) -> None:
        p = tmp_path / "plain.gcode"
        p.write_text("; printer_model = Ender 3\nG1 X0 Y0\n")
        assert parse(p)["printer_model"] == "Ender 3"


class TestMalformedEdges:
    """Targeted edge cases for the low-level block walker and helpers."""

    def test_header_too_short_yields_nothing(self, tmp_path: Path) -> None:
        # Only the magic, no version/checksum_type: _parse_file_header bails
        # (line 71) and _walk returns immediately (line 92).
        p = tmp_path / "short.bgcode"
        p.write_bytes(b"GCDE")
        assert bgcode.read_metadata_text(p) is None
        assert list(bgcode.iter_thumbnails(p)) == []

    def test_an_unknown_block_type_is_skipped(self, tmp_path: Path) -> None:
        # _block_param_len falls through to 0 for block types it doesn't
        # recognize (line 81), and the walker still parses what follows.
        assert bgcode._block_param_len(99) == 0

        unknown = _block(
            99, b"", b"unknown-block-payload", compression=0, checksum_type=1
        )
        file_meta = _block(
            _FILE_META,
            _meta_params(),
            b"Producer=PrusaSlicer 2.8.0+win64\n",
            compression=0,
            checksum_type=1,
        )
        p = tmp_path / "unknown.bgcode"
        p.write_bytes(_build([unknown, file_meta], checksum_type=1))
        assert (
            bgcode.read_metadata_text(p)
            == "; Producer=PrusaSlicer 2.8.0+win64\n; generated by PrusaSlicer 2.8.0+win64\n"
        )

    def test_truncated_compressed_size_field(self, tmp_path: Path) -> None:
        # Block header declares compression, but the file ends before the
        # 4-byte compressed-size field (line 103).
        header = struct.pack("<HHI", _FILE_META, 1, 100)
        p = tmp_path / "trunc_csize.bgcode"
        p.write_bytes(b"GCDE" + struct.pack("<IH", 1, 1) + header)
        assert bgcode.read_metadata_text(p) is None

    def test_truncated_params_field(self, tmp_path: Path) -> None:
        # Block header is intact but the file ends before the 2-byte
        # metadata params are fully readable (line 111).
        header = struct.pack("<HHI", _FILE_META, 0, 10)
        p = tmp_path / "trunc_params.bgcode"
        p.write_bytes(b"GCDE" + struct.pack("<IH", 1, 0) + header + b"\x00")
        assert bgcode.read_metadata_text(p) is None

    def test_oversized_block_data_is_rejected(self, tmp_path: Path) -> None:
        # An (uncompressed) declared size beyond the safety cap aborts the
        # walk rather than trying to read it (line 114).
        header = struct.pack("<HHI", _FILE_META, 0, bgcode._MAX_BLOCK_DATA + 1)
        params = _meta_params()
        p = tmp_path / "oversized.bgcode"
        p.write_bytes(b"GCDE" + struct.pack("<IH", 1, 0) + header + params)
        assert bgcode.read_metadata_text(p) is None

    def test_decompress_bad_deflate_returns_none(self) -> None:
        # Corrupt zlib stream: caught and turned into None (lines 134-135).
        assert bgcode._decompress(1, b"not-a-valid-zlib-stream") is None

    def test_decompress_rejects_output_over_limit_without_materializing_it(
        self,
    ) -> None:
        compressed = zlib.compress(b"x" * 8192)
        assert bgcode._decompress(1, compressed, max_output=1024) is None

    def test_decompress_rejects_trailing_or_truncated_streams(self) -> None:
        compressed = zlib.compress(b"metadata")
        assert bgcode._decompress(1, compressed[:-1], max_output=1024) is None
        assert bgcode._decompress(1, compressed + b"trailing", max_output=1024) is None

    def test_decompress_heatshrink_is_never_decoded(self) -> None:
        # Any non-none, non-deflate compression code (e.g. heatshrink) is
        # left alone entirely (line 137).
        assert bgcode._decompress(3, b"\x00\x01opaque") is None

    @staticmethod
    def _corrupt_deflate_block(
        btype: int, params: bytes, checksum_type: int = 1
    ) -> bytes:
        # _block() would happily re-compress our "corrupt" payload into
        # something valid, so build a genuinely undecodable deflate block by
        # hand: header + compressed_size + params + garbage bytes.
        garbage = b"not-a-valid-zlib-stream"
        header = struct.pack("<HHI", btype, 1, 1000) + struct.pack("<I", len(garbage))
        blk = header + params + garbage
        if checksum_type != 0:
            blk += struct.pack("<I", zlib.crc32(blk) & 0xFFFFFFFF)
        return blk

    def test_corrupt_metadata_block_is_skipped_not_fatal(self, tmp_path: Path) -> None:
        # A metadata block that fails to decompress is skipped (line 155),
        # but a later, valid metadata block still comes through.
        corrupt = self._corrupt_deflate_block(_PRINT_META, _meta_params())
        good = _block(
            _FILE_META,
            _meta_params(),
            b"Producer=PrusaSlicer 2.8.0+win64\n",
            compression=0,
            checksum_type=1,
        )
        p = tmp_path / "corrupt_meta.bgcode"
        p.write_bytes(_build([corrupt, good], checksum_type=1))
        result = bgcode.read_metadata_text(p)
        assert (
            result
            == "; Producer=PrusaSlicer 2.8.0+win64\n; generated by PrusaSlicer 2.8.0+win64\n"
        )

    def test_metadata_over_size_cap_breaks_early(self, tmp_path: Path) -> None:
        # A single decompressed metadata block bigger than the total cap
        # stops accumulation (line 158) instead of reading it all in.
        huge = ("key=" + "x" * (bgcode._MAX_METADATA_BYTES + 1024) + "\n").encode()
        block = _block(
            _PRINT_META, _meta_params(), huge, compression=1, checksum_type=1
        )
        p = tmp_path / "huge_meta.bgcode"
        p.write_bytes(_build([block], checksum_type=1))
        result = bgcode.read_metadata_text(p)
        # Nothing is appended before the break, so no lines survive.
        assert result is None

    def test_blank_metadata_lines_are_skipped(self, tmp_path: Path) -> None:
        # Blank lines within a metadata block are dropped (line 163).
        block = _block(
            _FILE_META,
            _meta_params(),
            b"Producer=PrusaSlicer 2.8.0+win64\n\n\n",
            compression=0,
            checksum_type=1,
        )
        p = tmp_path / "blank_lines.bgcode"
        p.write_bytes(_build([block], checksum_type=1))
        result = bgcode.read_metadata_text(p)
        assert (
            result
            == "; Producer=PrusaSlicer 2.8.0+win64\n; generated by PrusaSlicer 2.8.0+win64\n"
        )

    def test_read_metadata_text_oserror_on_directory(self, tmp_path: Path) -> None:
        # Passing a directory makes path.open() raise OSError, caught and
        # turned into a clean None (lines 170-172).
        assert bgcode.read_metadata_text(tmp_path) is None

    def test_iter_thumbnails_oserror_on_directory(self, tmp_path: Path) -> None:
        # Same OSError handling on the thumbnail-reading path (lines 189-191).
        assert list(bgcode.iter_thumbnails(tmp_path)) == []

    def test_corrupt_thumbnail_block_is_skipped(self, tmp_path: Path) -> None:
        # A thumbnail block that fails to decompress is skipped (line 186),
        # exercising the same decompress-error path as metadata but on the
        # thumbnail walk.
        corrupt_thumb = self._corrupt_deflate_block(
            _THUMBNAIL, _thumb_params(0, 16, 16)
        )
        p = tmp_path / "corrupt_thumb.bgcode"
        p.write_bytes(_build([corrupt_thumb], checksum_type=1))
        assert list(bgcode.iter_thumbnails(p)) == []


require_fixtures(_REAL_FIXTURE)


class TestRealFixture:
    def test_parse_real_prusaslicer_bgcode(self) -> None:
        result = parse(_REAL_FIXTURE)
        assert result["slicer_name"] == "PrusaSlicer"
        assert result["printer_model"] == "MK4S"
        assert result["material_type"] == "PLA"
        assert result["nozzle_diameter_mm"] == 0.4
        assert result["filament_weight_g"] == 10.35
        assert result["filament_length_mm"] == 3471.06
        assert result["estimated_time_s"] and result["estimated_time_s"] > 0

    def test_thumbnail_from_real_bgcode(self) -> None:
        thumb = thumbnail.extract(_REAL_FIXTURE)
        assert thumb is not None
        assert thumb[:8] == b"\x89PNG\r\n\x1a\n"
