"""Unit tests for embedded thumbnail extraction."""

from __future__ import annotations

import base64
from pathlib import Path

from app.services.thumbnail import _MAX_BLOCK_LINES, extract
from tests.paths import FIXTURES_DIR


def _block(width: int, height: int, payload: bytes) -> str:
    b64 = base64.b64encode(payload).decode()
    return f"; thumbnail begin {width}x{height} {len(b64)}\n; {b64}\n; thumbnail end\n"


class TestExtract:
    def test_extract_sample_gcode(self) -> None:
        fixture = FIXTURES_DIR / "sample.gcode"
        result = extract(fixture)
        assert result is not None
        assert len(result) > 0
        assert result[:4] == b"\x89PNG"  # PNG magic bytes

    def test_extract_missing_file(self, tmp_path: Path) -> None:
        result = extract(tmp_path / "nonexistent.gcode")
        assert result is None

    def test_extract_no_thumbnail(self, tmp_path: Path) -> None:
        f = tmp_path / "no_thumb.gcode"
        f.write_text("G28\nG1 X10 Y10\nM84\n")
        result = extract(f)
        assert result is None

    def test_picks_largest_block_by_area(self, tmp_path: Path) -> None:
        small = b"small-preview"
        large = b"large-preview-data" * 4
        f = tmp_path / "multi.gcode"
        f.write_text(
            "; generated by PrusaSlicer\n"
            + _block(16, 16, small)
            + _block(640, 480, large)
            + "G1 X0 Y0\n"
        )
        assert extract(f) == large

    def test_an_unterminated_block_is_bounded_before_giving_up(
        self, tmp_path: Path
    ) -> None:
        # Regression: a "thumbnail begin" with no "thumbnail end" must not buffer
        # the whole file; it is abandoned past the cap and yields nothing.
        f = tmp_path / "runaway.gcode"
        f.write_text(
            "; thumbnail begin 16x16 100\n" + "; AAAA\n" * (_MAX_BLOCK_LINES + 5000)
        )
        assert extract(f) is None

    def test_recovers_valid_block_after_runaway(self, tmp_path: Path) -> None:
        real = b"the-real-thumbnail"
        f = tmp_path / "recover.gcode"
        f.write_text(
            "; thumbnail begin 8x8 10\n"
            + "; ZZZZ\n" * (_MAX_BLOCK_LINES + 50)  # unterminated, abandoned
            + _block(64, 64, real)
            + "G1 X0\n"
        )
        assert extract(f) == real
