"""Thumbnail ingestion accepts bounded slicer previews and stores only WebP.

Failures here can persist hostile image bytes or make otherwise valid Artifacts
lose their derivative preview.
"""

from __future__ import annotations

import base64
import io
from pathlib import Path

import pytest

from app.core.config import _overlay
from app.services import thumbnail
from app.services.thumbnail import _MAX_BLOCK_LINES, extract, to_webp
from tests.paths import TEST_DATA_DIR


def _block(width: int, height: int, payload: bytes) -> str:
    b64 = base64.b64encode(payload).decode()
    return f"; thumbnail begin {width}x{height} {len(b64)}\n; {b64}\n; thumbnail end\n"


def _png(mode: str = "RGBA", size: tuple[int, int] = (4, 3)) -> bytes:
    from PIL import Image

    output = io.BytesIO()
    color: int | tuple[int, ...] = 128 if mode == "L" else (12, 120, 220, 180)
    Image.new(mode, size, color).save(output, format="PNG")
    return output.getvalue()


class TestToWebp:
    @pytest.mark.parametrize("mode", ["RGB", "RGBA"], ids=["rgb", "rgba"])
    def test_converts_a_valid_image_to_lossless_webp(self, mode: str) -> None:
        from PIL import Image

        source = _png(mode)

        encoded = to_webp(source)

        with Image.open(io.BytesIO(source)) as expected:
            expected_pixels = list(expected.convert("RGBA").get_flattened_data())
        with Image.open(io.BytesIO(encoded)) as result:
            assert result.format == "WEBP"
            assert result.size == (4, 3)
            assert list(result.convert("RGBA").get_flattened_data()) == expected_pixels

    def test_normalises_a_grayscale_image_before_encoding(self) -> None:
        from PIL import Image

        encoded = to_webp(_png("L"))

        with Image.open(io.BytesIO(encoded)) as result:
            assert result.convert("RGB").getpixel((0, 0)) == (128, 128, 128)

    def test_honours_the_configured_model_preview_size(self, monkeypatch) -> None:
        from PIL import Image

        source = _png("RGB", (800, 600))
        monkeypatch.setitem(_overlay, "model_thumbnail_width", 320)

        encoded = to_webp(source)

        with Image.open(io.BytesIO(encoded)) as result:
            assert result.size == (320, 240)

    def test_rejects_invalid_image_bytes_with_a_stable_error(self) -> None:
        with pytest.raises(ValueError, match="thumbnail_too_large"):
            to_webp(b"not-an-image")

    def test_rejects_an_image_above_the_pixel_budget(self, monkeypatch) -> None:
        monkeypatch.setattr(thumbnail, "_MAX_IMAGE_PIXELS", 3)

        with pytest.raises(ValueError, match="thumbnail_too_large"):
            to_webp(_png(size=(2, 2)))


class TestExtract:
    def test_extract_sample_gcode(self) -> None:
        fixture = TEST_DATA_DIR / "sample.gcode"
        result = extract(fixture)
        assert result is not None
        assert len(result) > 0
        assert result[:4] == b"\x89PNG"  # PNG magic bytes

    def test_extract_missing_file(self, tmp_path: Path) -> None:
        result = extract(tmp_path / "nonexistent.gcode")
        assert result is None

    def test_extract_no_thumbnail(self, tmp_path: Path) -> None:
        f = tmp_path / "no_thumb.gcode"
        f.write_text("G28\nG1 X10 Y10\nM84\n")
        result = extract(f)
        assert result is None

    def test_picks_largest_block_by_area(self, tmp_path: Path) -> None:
        small = b"small-preview"
        large = b"large-preview-data" * 4
        f = tmp_path / "multi.gcode"
        f.write_text(
            "; generated by PrusaSlicer\n"
            + _block(16, 16, small)
            + _block(640, 480, large)
            + "G1 X0 Y0\n"
        )
        assert extract(f) == large

    def test_picks_the_largest_supported_binary_gcode_thumbnail(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        path = tmp_path / "preview.bgcode"
        path.write_bytes(b"GCDE")
        monkeypatch.setattr(thumbnail.bgcode, "is_bgcode", lambda _path: True)
        monkeypatch.setattr(
            thumbnail.bgcode,
            "iter_thumbnails",
            lambda _path: iter(
                [
                    (2, 640, 480, b"qoi"),
                    (0, 16, 16, b"small-png"),
                    (1, 64, 64, b"large-jpg"),
                ]
            ),
        )

        result = extract(path)

        assert result == b"large-jpg"

    def test_rejects_malformed_base64(self, tmp_path: Path) -> None:
        path = tmp_path / "malformed.gcode"
        path.write_text(
            "; thumbnail begin 16x16 4\n; !!!!\n; thumbnail end\n",
            encoding="utf-8",
        )

        result = extract(path)

        assert result is None

    def test_unterminated_block_is_bounded_and_returns_none(
        self, tmp_path: Path
    ) -> None:
        # Regression: a "thumbnail begin" with no "thumbnail end" must not buffer
        # the whole file; it is abandoned past the cap and yields nothing.
        f = tmp_path / "runaway.gcode"
        f.write_text(
            "; thumbnail begin 16x16 100\n" + "; AAAA\n" * (_MAX_BLOCK_LINES + 5000)
        )
        assert extract(f) is None

    def test_recovers_valid_block_after_runaway(self, tmp_path: Path) -> None:
        real = b"the-real-thumbnail"
        f = tmp_path / "recover.gcode"
        f.write_text(
            "; thumbnail begin 8x8 10\n"
            + "; ZZZZ\n" * (_MAX_BLOCK_LINES + 50)  # unterminated, abandoned
            + _block(64, 64, real)
            + "G1 X0\n"
        )
        assert extract(f) == real
