/* eslint-disable react-refresh/only-export-components */
import { Children, cloneElement, isValidElement, useEffect, useRef, type ReactElement, type ReactNode } from "react";

import { useI18n, useOptionalI18n, type Locale } from "@/lib/i18n";

const ES_PHRASES: ReadonlyArray<readonly [string, string]> = [
  ["Vault configuration and display preferences", "Configuración de la bóveda y preferencias de visualización"],
  ["Portable archive with models, metadata, print history, and original artifacts", "Archivo portátil con modelos, metadatos, historial de impresión y artefactos originales"],
  ["Export a versioned archive for migration to another PrintStash installation. Accounts, credentials, settings, and trash are excluded.", "Exporta un archivo versionado para migrar a otra instalación de PrintStash. Se excluyen cuentas, credenciales, ajustes y papelera."],
  ["Download your searchable library context for spreadsheets, audits, migrations, or local AI prompts.", "Descarga el contexto consultable de tu biblioteca para hojas de cálculo, auditorías, migraciones o IA local."],
  ["Metadata only — no raw STL/3MF/G-code files", "Solo metadatos, sin archivos STL/3MF/G-code originales"],
  ["Server status and vault configuration", "Estado del servidor y configuración de la bóveda"],
  ["API server status and version", "Estado y versión del servidor API"],
  ["SQLite by default, Postgres optional", "SQLite por defecto; Postgres opcional"],
  ["Configured vault storage", "Almacenamiento configurado de la bóveda"],
  ["Tracked in the database", "Registrados en la base de datos"],
  ["Hierarchical tree entries", "Entradas del árbol jerárquico"],
  ["Flat tag vocabulary size", "Tamaño del vocabulario de etiquetas"],
  ["Live library entries", "Entradas activas de la biblioteca"],
  ["Configured devices", "Dispositivos configurados"],
  ["File storage backend, S3 credentials, and backup retention", "Backend de archivos, credenciales S3 y retención de copias"],
  ["Changes to the storage backend require an application restart.", "Cambiar el backend de almacenamiento requiere reiniciar la aplicación."],
  ["Leave empty for AWS S3. Required for Cloudflare R2, MinIO, etc.", "Déjalo vacío para AWS S3. Es obligatorio para Cloudflare R2, MinIO, etc."],
  ["Keys are stored in the vault database. Set via environment for production.", "Las claves se guardan en la base de datos. En producción, configúralas mediante variables de entorno."],
  ["Set to 0 to keep backups forever. Old backups are purged after each new backup.", "Usa 0 para conservar las copias siempre. Las antiguas se eliminan después de cada copia nueva."],
  ["Backups are always stored locally first. If configured here, they are also uploaded to cloud storage for off-site durability.", "Las copias siempre se guardan primero en local. Si lo configuras aquí, también se suben a la nube."],
  ["Connect Authentik, Authelia, Keycloak, or another standards-compatible identity provider. Local login stays available.", "Conecta Authentik, Authelia, Keycloak u otro proveedor de identidad compatible. El acceso local seguirá disponible."],
  ["Issuer URL and client ID are required before enabling SSO.", "La URL del emisor y el ID de cliente son obligatorios para activar SSO."],
  ["Shows provider button on login page.", "Muestra el botón del proveedor en la página de acceso."],
  ["Clear stored client secret when saving", "Borrar el secreto de cliente guardado al guardar"],
  ["Comma-separated group names granted superuser access.", "Grupos separados por comas que reciben acceso de superusuario."],
  ["Leave blank unless reverse-proxy URL detection is incorrect.", "Déjalo vacío salvo que la detección de URL del proxy inverso sea incorrecta."],
  ["Allow HTTP issuer on trusted LAN", "Permitir emisor HTTP en una LAN de confianza"],
  ["Permanently delete?", "¿Eliminar permanentemente?"],
  ["This will delete the model and all its files immediately. This cannot be undone.", "Esto eliminará inmediatamente el modelo y todos sus archivos. No se puede deshacer."],
  ["This replaces the current database and stored files with the selected backup.", "Esto sustituirá la base de datos y los archivos actuales por la copia seleccionada."],
  ["Download third-party printer images?", "¿Descargar imágenes de impresoras de terceros?"],
  ["Export full library", "Exportar biblioteca completa"],
  ["Import archive", "Importar archivo"],
  ["Library migration", "Migración de biblioteca"],
  ["Data export", "Exportación de datos"],
  ["Storage configuration", "Configuración de almacenamiento"],
  ["Storage backend", "Backend de almacenamiento"],
  ["Storage used", "Almacenamiento usado"],
  ["Local paths", "Rutas locales"],
  ["Local disk", "Disco local"],
  ["Data directory", "Directorio de datos"],
  ["Thumbnail directory", "Directorio de miniaturas"],
  ["S3 connection", "Conexión S3"],
  ["Endpoint URL", "URL del endpoint"],
  ["Access key", "Clave de acceso"],
  ["Secret key", "Clave secreta"],
  ["Backup destination (optional)", "Destino de copias (opcional)"],
  ["Retention (days)", "Retención (días)"],
  ["Save configuration", "Guardar configuración"],
  ["Sign in to modify configuration.", "Inicia sesión para modificar la configuración."],
  ["OpenID Connect", "OpenID Connect"],
  ["Enable SSO login", "Activar acceso SSO"],
  ["Issuer URL", "URL del emisor"],
  ["Client ID", "ID de cliente"],
  ["Client secret", "Secreto de cliente"],
  ["Login button label", "Texto del botón de acceso"],
  ["Configured — enter to replace", "Configurado; escribe para sustituirlo"],
  ["Optional for public clients", "Opcional para clientes públicos"],
  ["Advanced mapping", "Mapeo avanzado"],
  ["Admin groups", "Grupos administradores"],
  ["Username claim", "Atributo de usuario"],
  ["Groups claim", "Atributo de grupos"],
  ["Public callback URL override", "URL pública de retorno personalizada"],
  ["Allow insecure HTTP issuer", "Permitir emisor HTTP no seguro"],
  ["Save SSO settings", "Guardar ajustes SSO"],
  ["Single sign-on settings saved.", "Ajustes de inicio de sesión único guardados."],
  ["Settings sections", "Secciones de ajustes"],
  ["Vault version", "Versión de la bóveda"],
  ["Indexed files", "Archivos indexados"],
  ["All Models", "Todos los modelos"],
  ["New collection", "Nueva colección"],
  ["Saved views", "Vistas guardadas"],
  ["Select Models and folders (S)", "Seleccionar modelos y carpetas (S)"],
  ["Update with current filters", "Actualizar con filtros actuales"],
  ["Select all matching models", "Seleccionar todos los modelos coincidentes"],
  ["Select all on screen", "Seleccionar todo en pantalla"],
  ["Connect folder or NAS", "Conectar carpeta o NAS"],
  ["Clear recent folders", "Borrar carpetas recientes"],
  ["Clear all filters", "Borrar todos los filtros"],
  ["Find a saved view...", "Buscar una vista guardada..."],
  ["Find a saved view", "Buscar una vista guardada"],
  ["Delete saved view?", "¿Eliminar vista guardada?"],
  ["Rename saved view", "Renombrar vista guardada"],
  ["Save current view", "Guardar vista actual"],
  ["Modified saved view", "Vista guardada modificada"],
  ["Create Collection", "Crear colección"],
  ["Delete collection", "Eliminar colección"],
  ["New collection", "Nueva colección"],
  ["Recent folders", "Carpetas recientes"],
  ["No printers configured", "No hay impresoras configuradas"],
  ["No matching tags.", "No hay etiquetas coincidentes."],
  ["No models found", "No se encontraron modelos"],
  ["No results.", "Sin resultados."],
  ["Drop to upload", "Suelta para subir"],
  ["Import from URL", "Importar desde URL"],
  ["Upload files", "Subir archivos"],
  ["Filter outliner...", "Filtrar árbol..."],
  ["Filter tags...", "Filtrar etiquetas..."],
  ["View name", "Nombre de vista"],
  ["Ready to print", "Listo para imprimir"],
  ["Sort models", "Ordenar modelos"],
  ["Newest", "Más recientes"],
  ["Oldest", "Más antiguos"],
  ["Name A–Z", "Nombre A–Z"],
  ["Name Z–A", "Nombre Z–A"],
  ["Best success rate", "Mejor tasa de éxito"],
  ["Recently printed", "Impresos recientemente"],
  ["Shortest print", "Impresión más corta"],
  ["Least filament", "Menos filamento"],
  ["Lowest cost", "Menor coste"],
  ["Load more", "Cargar más"],
  ["Search", "Buscar"],
  ["Tag", "Etiqueta"],
  ["Uploaded after", "Subido después de"],
  ["Uploaded before", "Subido antes de"],
  ["Try clearing some filters.", "Prueba a borrar algunos filtros."],
  ["Upload a model when you're ready, or skim the wiki first if this is a new install.", "Sube un modelo cuando quieras o consulta primero la wiki si es una instalación nueva."],
  ["Drag to reorder", "Arrastra para reordenar"],
  ["On a printer", "En una impresora"],
  ["On printer", "En impresora"],
  ["Recent", "Recientes"],
  ["Filters", "Filtros"],
  ["Layout", "Diseño"],
  ["Density", "Densidad"],
  ["Folder", "Carpeta"],
  ["Duplicate", "Duplicar"],
  ["Rename", "Renombrar"],
  ["Clear all", "Borrar todo"],
  ["Clear", "Borrar"],
  ["Save view", "Guardar vista"],
  ["Updated", "Actualizado"],
  ["Updating...", "Actualizando..."],
  ["Save view", "Guardar vista"],
  ["Display", "Vista"],
  ["Thumb", "Miniatura"],
  ["Name", "Nombre"],
  ["Collection", "Colección"],
  ["Files", "Archivos"],
  ["Delete model?", "¿Eliminar modelo?"],
  ["Delete tag?", "¿Eliminar etiqueta?"],
  ["Model name", "Nombre del modelo"],
  ["Created", "Creado"],
  ["Resize details panel", "Cambiar el tamaño del panel de detalles"],
  ["Delete revision?", "¿Eliminar revisión?"],
  ["Label (blank clears)", "Etiqueta (vacío elimina)"],
  ["Unmarked", "Sin marcar"],
  ["Known good", "Conocida como buena"],
  ["Needs test", "Necesita pruebas"],
  ["Archived", "Archivada"],
  ["Notes about print outcome, fit, filament, or what to try next", "Notas sobre el resultado, ajuste, filamento o qué probar después"],
  ["Result", "Resultado"],
  ["Started (opt.)", "Inicio (opcional)"],
  ["Finished (opt.)", "Fin (opcional)"],
  ["Error (opt.)", "Error (opcional)"],
  ["Printer", "Impresora"],
  ["Printer name", "Nombre de la impresora"],
  ["e.g. Garage Prusa MK4", "p. ej., Prusa MK4 del taller"],
  ["G-code Revision", "Revisión G-code"],
  ["Spool (opt.)", "Carrete (opcional)"],
  ["Measured", "Medido"],
  ["measured", "medido"],
  ["Stored in a linked shared volume; synced both ways", "Guardado en un volumen compartido vinculado; sincronizado en ambos sentidos"],
  ["Model filters", "Filtros de modelos"],
  ["Filter values could not be loaded.", "No se pudieron cargar los valores de los filtros."],
  ["Loading filter values…", "Cargando valores de filtros…"],
  ["After", "Después de"],
  ["Before", "Antes de"],
  ["Known Good", "Conocida como buena"],
  ["Needs Test", "Necesita pruebas"],
  ["Archived", "Archivada"],
  ["On printer", "En impresora"],
  ["File", "Archivo"],
  ["Files", "Archivos"],
  ["selected", "seleccionados"],
  ["subcollection", "subcolección"],
  ["more", "más"],
  ["Any location", "Cualquier ubicación"],
  ["On a printer", "En una impresora"],
  ["Vault only", "Solo en la bóveda"],
  ["Filter outline...", "Filtrar árbol..."],
  ["Show printer image", "Mostrar imagen de impresora"],
  ["Model card metrics", "Métricas de tarjetas de modelo"],
  ["Model metadata", "Metadatos del modelo"],
  ["Print tracking", "Seguimiento de impresión"],
  ["Trash retention", "Retención de papelera"],
  ["Deleted models", "Modelos eliminados"],
  ["Latest changes", "Últimos cambios"],
  ["Check for updates", "Buscar actualizaciones"],
  ["Create users, assign vault admins, disable accounts, and reset passwords.", "Crea usuarios, asigna administradores, desactiva cuentas y restablece contraseñas."],
  ["Assign view, edit, or admin access per user. Child collections inherit parent grants.", "Asigna acceso de lectura, edición o administración por usuario. Las colecciones hijas heredan los permisos."],
  ["Create credentials for scripts and integrations, then exchange them for a JWT at login.", "Crea credenciales para scripts e integraciones y canjéalas por un JWT al iniciar sesión."],
  ["Copy this key now. It will only be shown once.", "Copia esta clave ahora. Solo se mostrará una vez."],
  ["Create a full backup of the database and all stored files right now.", "Crea ahora una copia completa de la base de datos y los archivos guardados."],
  ["Recover the vault database and stored files from a previous backup.", "Recupera la base de datos y los archivos desde una copia anterior."],
  ["Mirror a folder — on the server or a NAS — in place: files are indexed where they live, never copied. Local folders can be watched in real time; all folders support scheduled and manual scans. Off by default.", "Refleja una carpeta del servidor o NAS sin copiarla: los archivos se indexan donde están. Las carpetas locales admiten vigilancia en tiempo real y todas admiten análisis programados o manuales. Desactivado por defecto."],
  ["Watching gives near-real-time updates on local folders. Network folders (NAS over NFS/SMB) don't deliver file events, so they fall back to the schedule above.", "La vigilancia actualiza casi en tiempo real las carpetas locales. Las carpetas de red no emiten eventos y usan la programación indicada."],
  ["Add a folder below to start mirroring it into your vault.", "Añade una carpeta para empezar a reflejarla en tu bóveda."],
  ["Add a channel to start receiving print and printer alerts.", "Añade un canal para recibir alertas de impresiones e impresoras."],
  ["Send webhook, Discord, Telegram, or ntfy alerts on print and printer events.", "Envía alertas por webhook, Discord, Telegram o ntfy sobre impresiones e impresoras."],
  ["Only an administrator can manage notification channels.", "Solo un administrador puede gestionar canales de notificación."],
  ["Track filament inventory and per-print consumption with a self-hosted Spoolman instance. Off by default.", "Controla inventario y consumo de filamento con una instancia propia de Spoolman. Desactivado por defecto."],
  ["Only an administrator can configure Spoolman.", "Solo un administrador puede configurar Spoolman."],
  ["Decrements the selected spool by measured filament when a print completes (Moonraker-measured prints only).", "Descuenta del carrete seleccionado el filamento medido al terminar una impresión (solo mediciones de Moonraker)."],
  ["Connect a MakerWorld (Bambu) account so model &amp; collection imports can download files", "Conecta una cuenta de MakerWorld (Bambu) para descargar archivos al importar modelos y colecciones"],
  ["Only an administrator can connect MakerWorld.", "Solo un administrador puede conectar MakerWorld."],
  ["Your password is sent once to Bambu to obtain a session token and is never stored. MakerWorld usually emails a verification code next.", "La contraseña se envía una vez a Bambu para obtener un token de sesión y nunca se guarda. MakerWorld suele enviar después un código por correo."],
  ["Sessions expire periodically — if imports start failing with a login error, disconnect and connect again.", "Las sesiones caducan periódicamente. Si las importaciones fallan por acceso, desconecta y vuelve a conectar."],
  ["Choose whether printer cards include a visual. Plain cards remain more compact and information-dense.", "Elige si las tarjetas de impresora incluyen imagen. Sin imagen son más compactas."],
  ["Adds a brand-neutral printer visual above each card.", "Añade una imagen neutral sobre cada tarjeta."],
  ["Automatically promote a revision to known-good after its first successful print. A manual failed/archived verdict is never overridden.", "Marca automáticamente una revisión como válida tras su primera impresión correcta. Nunca sustituye un estado manual fallido o archivado."],
  ["Currency used to display cost figures in statistics and filament pricing.", "Moneda usada para costes en estadísticas y precios de filamento."],
  ["Choose which 3 stats appear on each model card in the grid.", "Elige las 3 estadísticas visibles en cada tarjeta de modelo."],
  ["Choose which metadata fields appear on model detail pages.", "Elige los metadatos visibles en las páginas de modelo."],
  ["Soft-deleted models stay restorable until the retention window expires.", "Los modelos eliminados se pueden restaurar hasta que venza la retención."],
  ["Restore models or remove them permanently from storage.", "Restaura modelos o elimínalos permanentemente del almacenamiento."],
  ["Self-hosted asset management for 3D printing workflows.", "Gestión autohospedada de recursos para impresión 3D."],
  ["What changed in the current release", "Cambios de la versión actual"],
  ["Select a user to review collection grants.", "Selecciona un usuario para revisar permisos de colecciones."],
  ["Initial password: at least 8 characters.", "Contraseña inicial: mínimo 8 caracteres."],
  ["Sign in to create API keys.", "Inicia sesión para crear claves API."],
  ["Sign in to manage the trash.", "Inicia sesión para gestionar la papelera."],
  ["No active API keys.", "No hay claves API activas."],
  ["No backups found.", "No se encontraron copias."],
  ["No notification channels yet", "Aún no hay canales de notificación"],
  ["No printers configured.", "No hay impresoras configuradas."],
  ["No shared volumes yet", "Aún no hay volúmenes compartidos"],
  ["No users.", "No hay usuarios."],
  ["Trash is empty.", "La papelera está vacía."],
  ["Collection access", "Acceso a colecciones"],
  ["API keys", "Claves API"],
  ["API key", "Clave API"],
  ["Initial password", "Contraseña inicial"],
  ["New password", "Nueva contraseña"],
  ["Reset password", "Restablecer contraseña"],
  ["Revoke API key", "Revocar clave API"],
  ["Copy API key", "Copiar clave API"],
  ["Copy OrcaSlicer post-processing command", "Copiar comando de posprocesado de OrcaSlicer"],
  ["Collection access", "Acceso a colecciones"],
  ["Select collection", "Seleccionar colección"],
  ["Select user", "Seleccionar usuario"],
  ["Remove collection access", "Quitar acceso a colección"],
  ["Refresh collection access", "Actualizar acceso a colecciones"],
  ["Superuser access is required.", "Se requiere acceso de superusuario."],
  ["Manual backup", "Copia manual"],
  ["Backup now", "Crear copia ahora"],
  ["Refresh backups", "Actualizar copias"],
  ["Restore backup", "Restaurar copia"],
  ["Restore backup?", "¿Restaurar copia?"],
  ["Shared volumes", "Volúmenes compartidos"],
  ["Add a folder", "Añadir carpeta"],
  ["Remove external library?", "¿Quitar biblioteca externa?"],
  ["Remove library", "Quitar biblioteca"],
  ["Mirror subfolders as collections", "Reflejar subcarpetas como colecciones"],
  ["Real-time watching", "Vigilancia en tiempo real"],
  ["Scan schedule", "Programación de análisis"],
  ["Auto-scan enabled", "Análisis automático activado"],
  ["Single collection (flat)", "Una colección (plana)"],
  ["Some files could not be indexed", "Algunos archivos no pudieron indexarse"],
  ["Recent deliveries", "Entregas recientes"],
  ["Send a test notification", "Enviar notificación de prueba"],
  ["Create channel", "Crear canal"],
  ["Save changes", "Guardar cambios"],
  ["Delete channel", "Eliminar canal"],
  ["Edit channel", "Editar canal"],
  ["All printers", "Todas las impresoras"],
  ["MakerWorld account", "Cuenta de MakerWorld"],
  ["MakerWorld is connected.", "MakerWorld está conectado."],
  ["MakerWorld password", "Contraseña de MakerWorld"],
  ["Verification code", "Código de verificación"],
  ["Use password instead", "Usar contraseña"],
  ["Google account? Paste token", "¿Cuenta de Google? Pega el token"],
  ["Session token", "Token de sesión"],
  ["Session stored", "Sesión guardada"],
  ["Disconnect", "Desconectar"],
  ["Test connection", "Probar conexión"],
  ["Enable Spoolman integration", "Activar integración con Spoolman"],
  ["Write consumption back to Spoolman", "Registrar consumo en Spoolman"],
  ["Only if Spoolman sits behind an authenticating proxy", "Solo si Spoolman está detrás de un proxy con autenticación"],
  ["Printer cards", "Tarjetas de impresora"],
  ["Display currency", "Moneda mostrada"],
  ["Auto-mark known good on successful print", "Marcar como válida tras una impresión correcta"],
  ["Show printer image on printer cards", "Mostrar imagen en tarjetas de impresora"],
  ["Refresh trash", "Actualizar papelera"],
  ["View release", "Ver versión"],
  ["View", "Ver"],
  ["Edit", "Editar"],
  ["Admin", "Administrador"],
  ["User", "Usuario"],
  ["Role", "Rol"],
  ["Name", "Nombre"],
  ["Email", "Correo"],
  ["Password", "Contraseña"],
  ["Username", "Usuario"],
  ["Create", "Crear"],
  ["Generate", "Generar"],
  ["Grant", "Conceder"],
  ["Remove", "Quitar"],
  ["Cancel", "Cancelar"],
  ["Enabled", "Activado"],
  ["Disabled", "Desactivado"],
  ["Events", "Eventos"],
  ["Type", "Tipo"],
  ["Authorization", "Autorización"],
  ["Inventory", "Inventario"],
  ["Base URL", "URL base"],
  ["Key name", "Nombre de clave"],
  ["Collection", "Colección"],
  ["Download", "Descargar"],
  ["Printer artwork will load from OrcaSlicer's GitHub repository. Images may be copyrighted or trademarked by their creators or printer manufacturers and remain subject to their original licenses. PrintStash does not own or redistribute them. Continue only if this use is permitted where you live.", "Las imágenes de impresoras se cargarán desde el repositorio de OrcaSlicer. Pueden tener derechos de autor o marcas de sus creadores o fabricantes y conservan sus licencias originales. PrintStash no las posee ni redistribuye. Continúa solo si este uso está permitido donde vives."],
  ["Leave empty for AWS S3.", "Déjalo vacío para AWS S3."],
  ["Review release notes before updating your self-hosted installation.", "Revisa las notas de versión antes de actualizar tu instalación."],
  ["Add channel", "Añadir canal"],
  ["Auto-disabled", "Desactivado automáticamente"],
  ["Backing up…", "Creando copia…"],
  ["Custom cron…", "Cron personalizado…"],
  ["Orca command", "Comando de Orca"],
  ["Notifications", "Notificaciones"],
  ["Scopes", "Ámbitos"],
  ["Slot", "Posición"],
  ["This vault is running v", "Esta bóveda usa v"],
  ["Update available: v", "Actualización disponible: v"],
  ["has no direct collection access.", "no tiene acceso directo a colecciones."],
  ["added ·", "añadido ·"],
  ["updated ·", "actualizado ·"],
  ["removed", "eliminado"],
  ["disabled", "desactivado"],
  ["paused", "pausado"],
  ["shown", "visibles"],
  ["models", "modelos"],
  ["files", "archivos"],
  ["left", "restantes"],
  ["of", "de"],
  ["· Expires", "· Caduca"],
  ["· last scan", "· último análisis"],
  ["Storage", "Almacenamiento"],
  ["System", "Sistema"],
  ["Database", "Base de datos"],
  ["Connected", "Conectada"],
  ["Unknown", "Desconocido"],
  ["Models", "Modelos"],
  ["Documents", "Documentos"],
  ["Files", "Archivos"],
  ["Printers", "Impresoras"],
  ["Collections", "Colecciones"],
  ["Tags", "Etiquetas"],
  ["Users", "Usuarios"],
  ["Upload", "Subir"],
  ["Favorites", "Favoritos"],
  ["Select", "Seleccionar"],
  ["Newest", "Más recientes"],
  ["Display", "Vista"],
  ["Loading...", "Cargando..."],
  ["Loading", "Cargando"],
  ["Exporting", "Exportando"],
  ["Importing", "Importando"],
  ["Saving...", "Guardando..."],
  ["Saving", "Guardando"],
  ["Saved", "Guardado"],
  ["Save", "Guardar"],
  ["Refresh", "Actualizar"],
  ["Restore", "Restaurar"],
  ["Delete forever", "Eliminar definitivamente"],
  ["Delete", "Eliminar"],
  ["Download & enable", "Descargar y activar"],
  ["Backup", "Copia de seguridad"],
  ["Bucket", "Bucket"],
  ["Region", "Región"],
  ["Credentials", "Credenciales"],
  ["Local", "Local"],
  ["Never", "Nunca"],
  ["Days", "Días"],
  ["Reset", "Restablecer"],
  ["Show all", "Mostrar todo"],
  ["Hide all", "Ocultar todo"],
  ["Currency", "Moneda"],
  ["Overview", "Resumen"],
  ["Your prints, organized", "Tus impresiones, organizadas"],
  ["Vault", "Bóveda"],
  ["Pending Imports", "Importaciones pendientes"],
  ["Profiles", "Perfiles"],
  ["Filament and printer presets for cost tracking and slicer defaults", "Perfiles de filamento e impresora para controlar costes y valores predeterminados del laminador"],
  ["Settings", "Ajustes"],
  ["Wiki", "Wiki"],
  ["Sign in", "Iniciar sesión"],
  ["Statistics", "Estadísticas"],
  ["Fleet", "Parque"],
  ["Queue", "Cola"],
  ["Admin required", "Se requiere administrador"],
  ["Active jobs", "Trabajos activos"],
  ["Needs attention", "Requieren atención"],
  ["Ready", "Lista"],
  ["Ungrouped", "Sin grupo"],
  ["Restricted", "Restringido"],
  ["Open", "Abrir"],
  ["Activity", "Actividad"],
  ["Never connected", "Nunca conectada"],
  ["Endpoint", "Endpoint"],
  ["importable", "importable"],
  ["Image: OrcaSlicer", "Imagen: OrcaSlicer"],
  ["New filament", "Nuevo filamento"],
  ["New printer", "Nueva impresora"],
  ["Sync Spoolman", "Sincronizar Spoolman"],
  ["Printers page", "Página de impresoras"],
  ["Add printer", "Añadir impresora"],
  ["Remove printer?", "¿Quitar impresora?"],
  ["Set model", "Establecer modelo"],
  ["Model unknown", "Modelo desconocido"],
  ["Integration", "Integración"],
  ["Printer URL", "URL de la impresora"],
  ["Printer host or IP", "Host o IP de la impresora"],
  ["Leave blank if auth is disabled", "Déjalo vacío si la autenticación está desactivada"],
  ["From printer discovery or diagnostics", "Desde el descubrimiento o diagnóstico de la impresora"],
  ["Enable LAN Only in printer network settings before connecting.", "Activa LAN Only en los ajustes de red de la impresora antes de conectarla."],
  ["Could not add printer", "No se pudo añadir la impresora"],
  ["Needed for reliable printer commands while idle, paused, or errored.", "Necesario para enviar comandos a la impresora de forma fiable cuando está inactiva, pausada o en error."],
  ["Ranked by", "Ordenado por"],
  ["No data for this period", "No hay datos para este periodo"],
  ["Completed jobs in selected period", "Trabajos completados en el periodo seleccionado"],
  ["No completed prints in this period.", "No hay impresiones completadas en este periodo."],
  ["7-day forecast uses selected period’s daily filament average.", "La previsión de 7 días usa la media diaria de filamento del periodo seleccionado."],
  ["Print hours", "Horas de impresión"],
  ["Filament weight", "Peso del filamento"],
  ["Visible ranking charts", "Gráficos de clasificación visibles"],
  ["Customize", "Personalizar"],
  ["Loading statistics…", "Cargando estadísticas…"],
  ["Failed to load statistics.", "No se pudieron cargar las estadísticas."],
  ["Unknown", "Desconocido"],
  ["Name", "Nombre"],
  ["Material", "Material"],
  ["Brand", "Marca"],
  ["Notes", "Notas"],
  ["Optional", "Opcional"],
  ["Nozzle", "Boquilla"],
  ["Printer model", "Modelo de impresora"],
  ["Printer name", "Nombre de la impresora"],
  ["Printer type", "Tipo de impresora"],
  ["Create filament preset", "Crear perfil de filamento"],
  ["Create printer preset", "Crear perfil de impresora"],
  ["Filament preset name", "Nombre del perfil de filamento"],
  ["Filament type", "Tipo de filamento"],
  ["Filament brand", "Marca del filamento"],
  ["Filament cost per kg", "Coste del filamento por kg"],
  ["Filament notes", "Notas del filamento"],
  ["Printer preset name", "Nombre del perfil de impresora"],
  ["Printer nozzle diameter", "Diámetro de boquilla de la impresora"],
  ["Printer notes", "Notas de la impresora"],
  ["Changes save automatically when leaving a row.", "Los cambios se guardan automáticamente al salir de una fila."],
  ["Detected from", "Detectado desde"],
  ["used by", "usado por"],
  ["file", "archivo"],
  ["files", "archivos"],
  ["Sign out", "Cerrar sesión"],
  ["Navigation", "Navegación"],
  ["Search models", "Buscar modelos"],
  ["Toggle theme", "Cambiar tema"],
  ["Dismiss", "Descartar"],
  ["Model filters", "Filtros de modelos"],
  ["Artifact", "Artefacto"],
  ["Slicer", "Laminador"],
  ["Printer model", "Modelo de impresora"],
  ["Revision", "Revisión"],
  ["Printed", "Impreso"],
  ["Print outcome", "Resultado de impresión"],
  ["Collections", "Colecciones"],
  ["All Models", "Todos los modelos"],
  ["Any location", "Cualquier ubicación"],
  ["On a printer", "En una impresora"],
  ["Vault only", "Solo en la bóveda"],
  ["Tags", "Etiquetas"],
  ["Filter tags...", "Filtrar etiquetas..."],
  ["Filter outliner...", "Filtrar árbol..."],
  ["No results.", "Sin resultados."],
  ["No printers configured", "No hay impresoras configuradas"],
  ["No matching tags.", "No hay etiquetas coincidentes."],
  ["Show fewer", "Mostrar menos"],
  ["Drag to reorder", "Arrastra para reordenar"],
  ["Delete collection", "Eliminar colección"],
  ["Create Collection", "Crear colección"],
  ["Collapse", "Contraer"],
  ["Expand", "Expandir"],
  ["Printing", "Imprimiendo"],
  ["Paused", "Pausada"],
  ["Offline", "Desconectada"],
  ["Error", "Error"],
  ["Clear selection", "Borrar selección"],
  ["Filter values could not be loaded.", "No se pudieron cargar los valores de los filtros."],
  ["Loading filter values…", "Cargando valores de filtros…"],
  ["Uploaded", "Subido"],
  ["After", "Después de"],
  ["Before", "Antes de"],
  ["Collapse", "Contraer"],
  ["Expand", "Expandir"],
  ["All groups", "Todos los grupos"],
  ["Fleet summary", "Resumen del parque"],
  ["Filter printers by group", "Filtrar impresoras por grupo"],
  ["Connected printer endpoints", "Endpoints de impresoras conectadas"],
  ["No printers configured yet.", "Aún no hay impresoras configuradas."],
  ["No printer models match your search.", "Ningún modelo de impresora coincide con la búsqueda."],
  ["Search printer models", "Buscar modelos de impresora"],
  ["Printer brands", "Marcas de impresoras"],
  ["Custom model", "Modelo personalizado"],
  ["Enter model name", "Introduce el nombre del modelo"],
  ["Save model", "Guardar modelo"],
  ["Connection issue: ", "Problema de conexión: "],
  ["Printer serial", "Número de serie de la impresora"],
  ["LAN access code", "Código de acceso LAN"],
  ["Authentication", "Autenticación"],
  ["Username and password (recommended)", "Usuario y contraseña (recomendado)"],
  ["Legacy API key", "Clave API heredada"],
  ["Printer access code", "Código de acceso de la impresora"],
  ["Failed to load 3D preview", "No se pudo cargar la vista previa 3D"],
  ["G-code toolpath preview", "Vista previa de la trayectoria G-code"],
  ["Fit to view", "Ajustar a la vista"],
  ["Screenshot", "Captura de pantalla"],
  ["Build plate grid", "Cuadrícula de la base de impresión"],
  ["Could not render this PDF.", "No se pudo mostrar este PDF."],
  ["Previous page", "Página anterior"],
  ["Next page", "Página siguiente"],
  ["Zoom out", "Alejar"],
  ["Zoom in", "Acercar"],
  ["Printer status", "Estado de la impresora"],
  ["Checking…", "Comprobando…"],
  ["No printers", "Sin impresoras"],
  ["Configure printer", "Configurar impresora"],
  ["Manage printers", "Gestionar impresoras"],
  ["Send to printer", "Enviar a impresora"],
  ["Sign in to send", "Inicia sesión para enviar"],
  ["Action", "Acción"],
  ["Send now", "Enviar ahora"],
  ["Add to queue", "Añadir a la cola"],
  ["Least busy eligible printer", "Impresora elegible menos ocupada"],
  ["Default printer", "Impresora predeterminada"],
  ["Choose printer", "Elegir impresora"],
  ["Start print immediately", "Iniciar impresión inmediatamente"],
  ["Filaments", "Filamentos"],
  ["Filament presets", "Perfiles de filamento"],
  ["Printer presets", "Perfiles de impresora"],
  ["Changes save automatically when leaving a row.", "Los cambios se guardan automáticamente al salir de una fila."],
  ["Add preset", "Añadir perfil"],
  ["No filament presets", "No hay perfiles de filamento"],
  ["No printer presets", "No hay perfiles de impresora"],
  ["Create one to track materials, brands, and costs.", "Crea uno para controlar materiales, marcas y costes."],
  ["Create one to reuse machine and nozzle settings.", "Crea uno para reutilizar ajustes de máquina y boquilla."],
  ["Manufacturer", "Fabricante"],
  ["Cost per kg", "Coste por kg"],
  ["Nozzle diameter", "Diámetro de boquilla"],
  ["Machine model", "Modelo de máquina"],
  ["Synced", "Sincronizado"],
  ["Used by", "Usado por"],
  ["Detected from", "Detectado desde"],
  ["Printer workload", "Carga de impresoras"],
  ["Most printed models", "Modelos más impresos"],
  ["Filament usage", "Uso de filamento"],
  ["Top collections", "Colecciones principales"],
  ["7 days", "7 días"],
  ["30 days", "30 días"],
  ["90 days", "90 días"],
  ["1 year", "1 año"],
  ["All time", "Todo el periodo"],
  ["Cost", "Coste"],
  ["Prints", "Impresiones"],
  ["Area", "Área"],
  ["Line", "Línea"],
  ["Bar", "Barras"],
  ["Total cost", "Coste total"],
  ["Filament used", "Filamento usado"],
  ["Avg / print", "Media / impresión"],
  ["Print time", "Tiempo de impresión"],
  ["7-day forecast", "Previsión de 7 días"],
  ["Cost, filament and print activity from completed jobs", "Coste, filamento y actividad de impresión de trabajos completados"],
  ["Capture now, organize later", "Captura ahora, organiza después"],
  ["Model URL", "URL del modelo"],
  ["Display title", "Título mostrado"],
  ["Target Collection", "Colección de destino"],
  ["Import tags", "Etiquetas de importación"],
  ["Tags to add", "Etiquetas que añadir"],
  ["Optional title", "Título opcional"],
  ["No documents here yet.", "Aún no hay documentos aquí."],
  ["Create a markdown doc or upload a PDF.", "Crea un documento Markdown o sube un PDF."],
  ["Delete document?", "¿Eliminar documento?"],
  ["This document will be moved to trash.", "Este documento se moverá a la papelera."],
  ["This page doesn’t exist.", "Esta página no existe."],
  ["Back to vault", "Volver a la bóveda"],
  ["Secure vault access", "Acceso seguro a la bóveda"],
  ["Choose where files live", "Elige dónde se guardan los archivos"],
  ["Setup progress", "Progreso de configuración"],
  ["Confirm password", "Confirmar contraseña"],
  ["Object storage", "Almacenamiento de objetos"],
  ["Recommended", "Recomendado"],
  ["Retention days", "Días de retención"],
  ["Printer settings", "Ajustes de impresora"],
  ["Connection and display details", "Detalles de conexión y visualización"],
  ["No active print", "No hay ninguna impresión activa"],
  ["Remote file", "Archivo remoto"],
  ["Vault match", "Coincidencia en la bóveda"],
  ["Last seen", "Visto por última vez"],
  ["When", "Cuándo"],
  ["State", "Estado"],
  ["Progress", "Progreso"],
  ["Started", "Iniciada"],
  ["Finished", "Finalizada"],
  ["Pause", "Pausar"],
  ["Resume", "Reanudar"],
  ["No access", "Sin acceso"],
  ["Homed", "Referenciada"],
  ["Idle", "Inactiva"],
  ["No queued print jobs", "No hay trabajos de impresión en cola"],
  ["No printers to maintain", "No hay impresoras que mantener"],
  ["Accepting scheduled work", "Acepta trabajos programados"],
  ["Soft drain active", "Drenaje suave activo"],
  ["Draining", "Drenando"],
  ["Unset default", "Quitar como predeterminada"],
  ["Set default", "Establecer como predeterminada"],
  ["Resume routing", "Reanudar enrutamiento"],
  ["Soft drain", "Drenaje suave"],
  ["Schedule", "Programar"],
  ["Log", "Registro"],
  ["No maintenance activity recorded.", "No hay actividad de mantenimiento registrada."],
  ["Queue summary", "Resumen de la cola"],
  ["Queued", "En cola"],
  ["Active", "Activos"],
  ["Retry", "Reintentar"],
  ["No active tasks", "No hay tareas activas"],
  ["active", "activas"],
  ["3D Model", "Modelo 3D"],
  ["ZIP archive", "Archivo ZIP"],
  ["G-code", "G-code"],
  ["Vault storage", "Almacenamiento de la bóveda"],
  ["Close", "Cerrar"],
  ["Remove selected file", "Quitar archivo seleccionado"],
  ["Remove", "Quitar"],
  ["Delete", "Eliminar"],
  ["Rename", "Renombrar"],
  ["Duplicate", "Duplicar"],
  ["Update with current filters", "Actualizar con filtros actuales"],
  ["Modified saved view", "Vista guardada modificada"],
  ["G-code render failed", "No se pudo mostrar el G-code"],
  ["Parsing G-code…", "Analizando G-code…"],
  ["No toolpath found in file", "No se encontró ninguna trayectoria en el archivo"],
  ["Optional description", "Descripción opcional"],
  ["Model actions", "Acciones del modelo"],
  ["Resize details panel", "Cambiar el tamaño del panel de detalles"],
  ["Find destination...", "Buscar destino..."],
  ["No valid destinations", "No hay destinos válidos"],
  ["Add tags", "Añadir etiquetas"],
  ["Remove tags", "Quitar etiquetas"],
  ["OpenID Connect", "OpenID Connect"],
  ["Spool (opt.)", "Carrete (opcional)"],
  ["No spool", "Sin carrete"],
  ["G-code Revision", "Revisión G-code"],
  ["Select revision…", "Seleccionar revisión…"],
  ["Select printer…", "Seleccionar impresora…"],
  ["Other (not listed)…", "Otra (no listada)…"],
  ["Completed", "Completada"],
  ["Failed", "Fallida"],
  ["Cancelled", "Cancelada"],
  ["No matching jobs found on this printer.", "No se encontraron trabajos coincidentes en esta impresora."],
  ["Describe what went wrong…", "Describe qué salió mal…"],
  ["Source Files", "Archivos fuente"],
  ["No source files (STL / 3MF / OBJ) for this model.", "No hay archivos fuente (STL / 3MF / OBJ) para este modelo."],
  ["Recommended Print", "Impresión recomendada"],
  ["Print History", "Historial de impresión"],
  ["No print settings recorded yet. Add a sliced G-code revision to capture them.", "Aún no hay ajustes de impresión registrados. Añade una revisión G-code laminada para capturarlos."],
  ["No active print", "No hay ninguna impresión activa"],
  ["Printer is offline. Print details will appear after it reconnects.", "La impresora está desconectada. Los detalles aparecerán cuando vuelva a conectarse."],
  ["Start a file from the Files tab to see live progress and controls here.", "Inicia un archivo desde la pestaña Archivos para ver aquí el progreso y los controles en directo."],
  ["Browse files", "Explorar archivos"],
  ["Temperatures", "Temperaturas"],
  ["Preheat", "Precalentar"],
  ["Cooldown", "Enfriar"],
  ["Home all", "Referenciar todos"],
  ["E-stop", "Parada de emergencia"],
  ["Printer files", "Archivos de la impresora"],
  ["Syncing", "Sincronizando"],
  ["Sync", "Sincronizar"],
  ["No printer files synced yet.", "Aún no se han sincronizado archivos de la impresora."],
  ["Printer file inventory is not supported by this provider.", "Este proveedor no admite el inventario de archivos de la impresora."],
  ["Print history", "Historial de impresión"],
  ["No print jobs yet.", "Aún no hay trabajos de impresión."],
  ["Moonraker and Klipper config", "Configuración de Moonraker y Klipper"],
  ["Loading config…", "Cargando configuración…"],
  ["Config not loaded.", "No se ha cargado la configuración."],
  ["Provider diagnostics", "Diagnóstico del proveedor"],
  ["Checking", "Comprobando"],
  ["Diagnostics have not loaded yet.", "El diagnóstico aún no se ha cargado."],
  ["Unsupported in this provider", "No compatible con este proveedor"],
  ["Controls permitted by your printer role.", "Controles permitidos por tu rol en la impresora."],
  ["Control role required.", "Se requiere el rol de control."],
  ["Actual filament", "Filamento real"],
  ["Actual cost", "Coste real"],
  ["Field", "Campo"],
  ["Add G-code revision", "Añadir revisión G-code"],
  ["G-code file", "Archivo G-code"],
  ["Choose G-code or drop it here", "Elige un G-code o suéltalo aquí"],
  ["Revision label", "Etiqueta de revisión"],
  ["What changed in this slice?", "¿Qué cambió en este laminado?"],
  ["Mark as recommended", "Marcar como recomendada"],
  ["Allow file download", "Permitir descargar archivos"],
  ["No share links yet.", "Aún no hay enlaces compartidos."],
  ["Model actions", "Acciones del modelo"],
  ["Drag to resize · Double-click to reset", "Arrastra para cambiar el tamaño · Haz doble clic para restablecer"],
  ["3D model view", "Vista del modelo 3D"],
  ["Reset view", "Restablecer vista"],
  ["Zoom in", "Acercar"],
  ["Zoom out", "Alejar"],
  ["Upload-only printers", "Impresoras solo de subida"],
  ["Print hours", "Horas de impresión"],
  ["Account", "Cuenta"],
  ["Active links", "Enlaces activos"],
  ["Add", "Añadir"],
  ["Add Record", "Añadir registro"],
  ["Add your first printer", "Añade tu primera impresora"],
  ["Already uploaded to", "Ya subido a"],
  ["Apply", "Aplicar"],
  ["Apply label", "Aplicar etiqueta"],
  ["At least 8 characters", "Al menos 8 caracteres"],
  ["Back", "Volver"],
  ["Backup access key", "Clave de acceso de copia"],
  ["Backup bucket", "Bucket de copia"],
  ["Backup endpoint", "Endpoint de copia"],
  ["Backup region", "Región de copia"],
  ["Backup retention", "Retención de copias"],
  ["Backup secret key", "Clave secreta de copia"],
  ["Backup Verification", "Verificación de copia"],
  ["Bed", "Cama"],
  ["Bed target", "Objetivo de cama"],
  ["Beta", "Beta"],
  ["Cancel job", "Cancelar trabajo"],
  ["Cancel queued print?", "¿Cancelar impresión en cola?"],
  ["Cannot reach the vault", "No se puede acceder a la bóveda"],
  ["Capabilities", "Capacidades"],
  ["Capture", "Capturar"],
  ["Category", "Categoría"],
  ["Checking vault setup…", "Comprobando la configuración de la bóveda…"],
  ["Checks", "Comprobaciones"],
  ["Choose during review", "Elegir durante la revisión"],
  ["Choose your storage", "Elige tu almacenamiento"],
  ["Clear done", "Borrar completadas"],
  ["Clear stored client secret", "Borrar secreto de cliente guardado"],
  ["Compare", "Comparar"],
  ["Compare Artifacts", "Comparar artefactos"],
  ["Complete setup", "Completar configuración"],
  ["Connect a supported printer to send files directly from the Vault.", "Conecta una impresora compatible para enviar archivos directamente desde la bóveda."],
  ["Connection", "Conexión"],
  ["Connection issue:", "Problema de conexión:"],
  ["Control", "Control"],
  ["Cost / kg", "Coste / kg"],
  ["Create link", "Crear enlace"],
  ["Create the first administrator account. You can add more users later.", "Crea la primera cuenta de administrador. Podrás añadir más usuarios después."],
  ["Create your admin account", "Crea tu cuenta de administrador"],
  ["Credentials can stay empty when your runtime provides them.", "Las credenciales pueden quedar vacías si el entorno de ejecución las proporciona."],
  ["Current print", "Impresión actual"],
  ["Default", "Predeterminado"],
  ["Delete document", "Eliminar documento"],
  ["Delete maintenance log", "Eliminar registro de mantenimiento"],
  ["Delete maintenance window", "Eliminar ventana de mantenimiento"],
  ["Delete model", "Eliminar modelo"],
  ["Delete printer file?", "¿Eliminar archivo de impresora?"],
  ["Deleted", "Eliminado"],
  ["Description", "Descripción"],
  ["Discovering total… Safe to close this view.", "Calculando el total… Puedes cerrar esta vista sin problema."],
  ["Downloads are disabled for this link — view only.", "Las descargas están desactivadas para este enlace; solo permite ver."],
  ["Drop 3D models or a folder here", "Suelta aquí modelos 3D o una carpeta"],
  ["Drop a 3D model, a G-code, or both together", "Suelta un modelo 3D, un G-code o ambos"],
  ["e.g. Bracket v2", "p. ej., Soporte v2"],
  ["e.g. Stronger walls", "p. ej., Paredes más resistentes"],
  ["Edit details", "Editar detalles"],
  ["ELAPSED", "TRANSCURRIDO"],
  ["Emergency stop", "Parada de emergencia"],
  ["Emergency stop printer?", "¿Parar la impresora de emergencia?"],
  ["Ends", "Finaliza"],
  ["Every revision", "Todas las revisiones"],
  ["Everyday PLA", "PLA diario"],
  ["Expires (days)", "Caduca (días)"],
  ["External", "Externo"],
  ["Failed item details", "Detalles del elemento fallido"],
  ["Fetch & Import", "Obtener e importar"],
  ["Fetch recent print history from a Moonraker printer and import jobs matching this model's G-code files.", "Obtén el historial reciente de una impresora Moonraker e importa los trabajos que coincidan con los archivos G-code de este modelo."],
  ["Filament", "Filamento"],
  ["FILE", "ARCHIVO"],
  ["Find destination", "Buscar destino"],
  ["Fit", "Ajustar"],
  ["Full Audit", "Auditoría completa"],
  ["G-code preview", "Vista previa de G-code"],
  ["G-code revision", "Revisión G-code"],
  ["G-code Revisions", "Revisiones G-code"],
  ["G-code toolpath", "Trayectoria G-code"],
  ["Grant access per printer. Roles build from view to print, machine control, and administration.", "Concede acceso por impresora. Los roles abarcan consulta, impresión, control de máquina y administración."],
  ["Grid", "Cuadrícula"],
  ["Group", "Grupo"],
  ["Hotend", "Hotend"],
  ["Hotend target", "Objetivo del hotend"],
  ["Ignore", "Ignorar"],
  ["Import", "Importar"],
  ["Import ready", "Importar listos"],
  ["Keep the recommended local paths, or connect S3-compatible object storage.", "Mantén las rutas locales recomendadas o conecta almacenamiento de objetos compatible con S3."],
  ["Klipper config", "Configuración de Klipper"],
  ["Layer", "Capa"],
  ["Leave blank to keep current value", "Déjalo vacío para conservar el valor actual"],
  ["Leave empty for AWS S3", "Déjalo vacío para AWS S3"],
  ["Linked", "Vinculado"],
  ["Live", "En directo"],
  ["Load older jobs", "Cargar trabajos anteriores"],
  ["Loading Pending Imports…", "Cargando importaciones pendientes…"],
  ["Loading…", "Cargando…"],
  ["Local backups are kept for this many days.", "Las copias locales se conservan este número de días."],
  ["Mainboard ID", "ID de la placa principal"],
  ["Makes this default revision for downloads and printer sends. Current recommendation will be replaced.", "Hace que esta sea la revisión predeterminada para descargas y envíos a impresora. Se sustituirá la recomendación actual."],
  ["Mark as recommended G-code for this model", "Marcar como G-code recomendado para este modelo"],
  ["Mark failed", "Marcar como fallida"],
  ["Markdown · paste or drop images", "Markdown · pega o suelta imágenes"],
  ["Mesh Geometry", "Geometría de malla"],
  ["Model", "Modelo"],
  ["Model page, collection, or direct .stl/.zip link", "Página de modelo, colección o enlace directo .stl/.zip"],
  ["Moonraker config", "Configuración de Moonraker"],
  ["Move", "Mover"],
  ["Move here", "Mover aquí"],
  ["New document", "Nuevo documento"],
  ["New link (copy it now)", "Nuevo enlace (cópialo ahora)"],
  ["Next", "Siguiente"],
  ["No audit has run yet.", "Aún no se ha ejecutado ninguna auditoría."],
  ["No backups available.", "No hay copias disponibles."],
  ["No collection selected", "No hay ninguna colección seleccionada"],
  ["No configured printer supports Vault upload/send.", "Ninguna impresora configurada admite subir o enviar desde la bóveda."],
  ["No editable collections.", "No hay colecciones editables."],
  ["No findings in this category.", "No hay hallazgos en esta categoría."],
  ["No G-code file", "No hay archivo G-code"],
  ["No importable 3D files in this archive.", "No hay archivos 3D importables en este archivo."],
  ["No previewable mesh or G-code in this share.", "No hay malla ni G-code que se pueda previsualizar en este enlace."],
  ["No print history yet. Add a record manually or import from a printer.", "Aún no hay historial de impresión. Añade un registro manualmente o impórtalo desde una impresora."],
  ["No selected printer online", "No hay ninguna impresora seleccionada conectada"],
  ["No sliced G-code revisions yet.", "Aún no hay revisiones G-code laminadas."],
  ["None", "Ninguno"],
  ["None (root)", "Ninguna (raíz)"],
  ["Note", "Nota"],
  ["Off by default. When enabled, selected printers begin printing after upload.", "Desactivado de forma predeterminada. Al activarlo, las impresoras seleccionadas empiezan a imprimir tras la subida."],
  ["Off-site backup", "Copia externa"],
  ["Open in slicer", "Abrir en el laminador"],
  ["Open login", "Abrir inicio de sesión"],
  ["Open Model", "Abrir modelo"],
  ["Optional farm grouping", "Agrupación opcional de granja"],
  ["Or select a folder", "O selecciona una carpeta"],
  ["Paste a supported model page or direct file URL. PrintStash will resolve it safely and keep review choices across restarts.", "Pega una página de modelo compatible o la URL directa de un archivo. PrintStash la resolverá de forma segura y conservará las opciones de revisión tras reiniciar."],
  ["Paste the value of the makerworld.com 'token' cookie", "Pega el valor de la cookie 'token' de makerworld.com"],
  ["Preview", "Vista previa"],
  ["Print", "Imprimir"],
  ["Print Settings", "Ajustes de impresión"],
  ["Printer access", "Acceso a impresoras"],
  ["Public, expiring, read-only links. Anyone with the link can view this model only.", "Enlaces públicos, temporales y de solo lectura. Cualquiera con el enlace solo puede ver este modelo."],
  ["Quick Audit", "Auditoría rápida"],
  ["Read-only checks for owned Artifacts, thumbnails, Metadata, external links, and storage ownership.", "Comprobaciones de solo lectura para artefactos propios, miniaturas, metadatos, enlaces externos y propiedad del almacenamiento."],
  ["Reason", "Motivo"],
  ["Recommend", "Recomendar"],
  ["Recommended Rev", "Rev. recomendada"],
  ["Reconnecting…", "Reconectando…"],
  ["Refresh printer access", "Actualizar acceso a impresoras"],
  ["Remember me", "Recordarme"],
  ["Remove printer access", "Quitar acceso a impresora"],
  ["Remove upload-only printers to enable this option.", "Elimina las impresoras solo de subida para activar esta opción."],
  ["Repair", "Reparar"],
  ["Repair this finding?", "¿Reparar este hallazgo?"],
  ["Replace", "Sustituir"],
  ["Retry eligible", "Reintentar elegibles"],
  ["Rev", "Rev."],
  ["Review and retry", "Revisar y reintentar"],
  ["Review collection items before importing", "Revisar los elementos de la colección antes de importar"],
  ["Revisions", "Revisiones"],
  ["Revoke", "Revocar"],
  ["Routing", "Enrutamiento"],
  ["S3 / R2", "S3 / R2"],
  ["Select printer", "Seleccionar impresora"],
  ["Select printer model", "Seleccionar modelo de impresora"],
  ["Selected revisions", "Revisiones seleccionadas"],
  ["Set", "Establecer"],
  ["Set collection", "Establecer colección"],
  ["Setup token", "Token de configuración"],
  ["Share", "Compartir"],
  ["Share model", "Compartir modelo"],
  ["Shared model · PrintStash", "Modelo compartido · PrintStash"],
  ["Shared revision", "Revisión compartida"],
  ["Sign in before uploading.", "Inicia sesión antes de subir archivos."],
  ["Sign in to edit printer settings.", "Inicia sesión para editar los ajustes de la impresora."],
  ["Size", "Tamaño"],
  ["Sliced with", "Laminado con"],
  ["Source model", "Modelo fuente"],
  ["Source URL", "URL de origen"],
  ["Spool", "Carrete"],
  ["Start", "Iniciar"],
  ["Starts", "Empieza"],
  ["STATE", "ESTADO"],
  ["Status", "Estado"],
  ["Store in", "Guardar en"],
  ["Sync status", "Estado de sincronización"],
  ["Tasks", "Tareas"],
  ["This document is empty.", "Este documento está vacío."],
  ["This halts the printer immediately and requires a firmware restart.", "Esto detiene la impresora de inmediato y requiere reiniciar el firmware."],
  ["This removes work from scheduling. It does not cancel an active printer.", "Esto elimina el trabajo de la planificación. No cancela una impresora activa."],
  ["This will move the model to trash. Files will be permanently removed after the retention period.", "Esto moverá el modelo a la papelera. Los archivos se eliminarán permanentemente después del período de retención."],
  ["TOTAL", "TOTAL"],
  ["Travel", "Desplazamiento"],
  ["TRIANGLES", "TRIÁNGULOS"],
  ["Two quick steps to prepare your self-hosted vault.", "Dos pasos rápidos para preparar tu bóveda autohospedada."],
  ["Unchanged", "Sin cambios"],
  ["Upload another slice while keeping earlier settings and print history available.", "Sube otro laminado conservando los ajustes e historial de impresión anteriores."],
  ["Upload model", "Subir modelo"],
  ["Upload PDF / file", "Subir PDF / archivo"],
  ["Uploading image…", "Subiendo imagen…"],
  ["Use 0 to keep forever", "Usa 0 para conservar siempre"],
  ["Use this account to manage your library and invite other administrators later.", "Usa esta cuenta para gestionar tu biblioteca e invitar a otros administradores más adelante."],
  ["Vault Audit", "Auditoría de bóveda"],
  ["Verify", "Verificar"],
  ["Viewing:", "Viendo:"],
  ["views", "vistas"],
  ["VOLUME", "VOLUMEN"],
  ["Welcome to PrintStash", "Te damos la bienvenida a PrintStash"],
  ["Workshop", "Taller"],
  ["G-code", "G-code"],
  ["Beta", "Beta"],
  ["TOTAL", "TOTAL"],
  ["Hotend", "Hotend"],
  ["OpenID Connect", "OpenID Connect"],
  ["S3 / R2", "S3 / R2"],
  ["Bucket", "Bucket"],
  ["Control", "Control"],
  ["Material", "Material"],
  ["· G-code", "· G-code"],
  ["Endpoint", "Endpoint"],
  ["— use Download to open it.", "— usa Descargar para abrirlo."],
  [". Review release notes before updating your self-hosted installation.", ". Revisa las notas de la versión antes de actualizar tu instalación autohospedada."],
  [". The hook exchanges it for a JWT Bearer token, then uploads with the normal", ". El hook lo intercambia por un token JWT Bearer y después sube con la cabecera habitual"],
  ["· Created", "· Creado"],
  ["· G-code", "· G-code"],
  ["· Last updated", "· Última actualización"],
  ["· Source", "· Origen"],
  ["· subfolders become nested collections", "· las subcarpetas se convierten en colecciones anidadas"],
  ["(optional)", "(opcional)"],
  ["(recommended)", "(recomendado)"],
  ["(shared volume)", "(volumen compartido)"],
  ["A model page, a", "Una página de modelo, una"],
  ["A short description of this collection. Markdown — paste or drop images.", "Una breve descripción de esta colección. Markdown: pega o suelta imágenes."],
  ["Absolute folder path (e.g. /mnt/nas/3d)", "Ruta absoluta de carpeta (p. ej., /mnt/nas/3d)"],
  ["Add a description for this collection", "Añade una descripción para esta colección"],
  ["Add G-code from a model’s Send dialog to start building the fleet queue.", "Añade G-code desde el diálogo Enviar de un modelo para empezar a formar la cola de la granja."],
  ["collection", "colección"],
  ["configuration", "configuración"],
  ["cookie from DevTools → Application → Cookies. This is the way to connect a Google-linked account.", "cookie desde Herramientas de desarrollo → Aplicación → Cookies. Así puedes conectar una cuenta vinculada a Google."],
  ["Copy it from the API container logs", "Cópialo de los registros del contenedor de API"],
  ["expires", "caduca"],
  ["Fetch & Import", "Obtener e importar"],
  ["Fetch recent print history from a Moonraker printer and import jobs matching this model's G-code files.", "Obtén el historial reciente de una impresora Moonraker e importa trabajos que coincidan con los archivos G-code de este modelo."],
  ["files ·", "archivos ·"],
  ["Files (", "Archivos ("],
  ["has no direct printer access.", "no tiene acceso directo a la impresora."],
  ["header.", "cabecera."],
  ["importable", "importable"],
  ["is available", "está disponible"],
  ["is marked", "está marcado"],
  ["Living-room printer alerts", "Alertas de impresora del salón"],
  ["Log in to makerworld.com in your browser (Google sign-in is fine), then copy the", "Inicia sesión en makerworld.com desde tu navegador (puedes usar Google) y luego copia la"],
  ["model", "modelo"],
  ["Moonraker's native Spoolman integration is already decrementing the active spool, so PrintStash automatically skips its own write-back to avoid double-counting. Only override this if you have disabled Moonraker's hook and want PrintStash to count consumption.", "La integración nativa de Spoolman de Moonraker ya descuenta el carrete activo, por lo que PrintStash omite automáticamente su propia escritura para evitar el doble recuento. Anula este comportamiento solo si has desactivado el hook de Moonraker y quieres que PrintStash contabilice el consumo."],
  ["Name (e.g. NAS models)", "Nombre (p. ej., modelos NAS)"],
  ["NAS libraries write the file into the folder; revisions to a linked model always follow that model automatically.", "Las bibliotecas NAS escriben el archivo en la carpeta; las revisiones de un modelo vinculado siempre siguen automáticamente ese modelo."],
  ["online", "conectada"],
  ["Pick a known model or type your own", "Elige un modelo conocido o escribe uno propio"],
  ["printer", "impresora"],
  ["PrintStash will apply the targeted repair and record the action in the audit log. Original Artifact bytes are never replaced by thumbnail or metadata repairs.", "PrintStash aplicará la reparación seleccionada y registrará la acción en la auditoría. Los bytes del artefacto original nunca se sustituyen por reparaciones de miniaturas o metadatos."],
  ["Search or create — press Enter", "Busca o crea; pulsa Intro"],
  ["Select a user to review printer grants.", "Selecciona un usuario para revisar los permisos de impresora."],
  ["Setup runs once. Additional administrators and storage settings can be managed later.", "La configuración se ejecuta una vez. Más adelante podrás gestionar administradores y ajustes de almacenamiento adicionales."],
  ["spool ·", "carrete ·"],
  ["Streams each archive and checks safe paths, manifest, database member, member counts, and sizes.", "Procesa cada archivo y comprueba rutas seguras, manifiesto, miembro de base de datos, recuentos y tamaños."],
  ["tags, comma separated", "etiquetas separadas por comas"],
  ["The backend will create these directories and probe them for writability before completing setup.", "El backend creará estos directorios y comprobará que permiten escritura antes de completar la configuración."],
  ["Use your username with this API key on", "Usa tu nombre de usuario con esta clave API en"],
  ["View: status and history · Print: send and start jobs · Control: pause, cancel, temperatures, homing, emergency stop · Admin: settings, files, routing, and maintenance", "Ver: estado e historial · Imprimir: enviar e iniciar trabajos · Control: pausar, cancelar, temperaturas, referencia y parada de emergencia · Administración: ajustes, archivos, enrutamiento y mantenimiento"],
  ["Write back anyway (I disabled Moonraker's hook)", "Escribir de todos modos (he desactivado el hook de Moonraker)"],
  ["PRINTER PROFILE", "PERFIL DE IMPRESORA"],
  ["MATERIAL", "MATERIAL"],
  ["FILAMENT PROFILE", "PERFIL DE FILAMENTO"],
  ["LAYER HEIGHT", "ALTURA DE CAPA"],
  ["FIRST LAYER", "PRIMERA CAPA"],
  ["NOZZLE", "BOQUILLA"],
  ["INFILL", "RELLENO"],
  ["WALLS", "PAREDES"],
  ["TOP / BOTTOM", "SUPERIOR / INFERIOR"],
  ["SUPPORTS", "SOPORTES"],
  ["NOZZLE TEMP", "TEMP. BOQUILLA"],
  ["BED TEMP", "TEMP. CAMA"],
  ["EST. TIME", "TIEMPO EST."],
  ["FILAMENT", "FILAMENTO"],
  ["FILAMENT COST", "COSTE DE FILAMENTO"],
  ["PRINTER", "IMPRESORA"],
  ["SLICER", "LAMINADOR"],
  ["Yes", "Sí"],
  ["No", "No"],
  ["History", "Historial"],
  ["Uploading", "Subiendo"],
  ["Success", "Correcto"],
  ["No revision is marked as recommended yet. Mark a known-good G-code as recommended.", "Aún no hay ninguna revisión marcada como recomendada. Marca un G-code conocido como bueno como recomendado."],
  ["No sliced G-code yet. Add a revision to capture the settings that worked.", "Aún no hay ningún G-code laminado. Añade una revisión para capturar los ajustes que funcionaron."],
  ["Layer height", "Altura de capa"],
  ["File count", "Nº de archivos"],
  ["Printer profile", "Perfil de impresora"],
  ["Filament profile", "Perfil de filamento"],
  ["First layer", "Primera capa"],
  ["Infill", "Relleno"],
  ["Walls", "Paredes"],
  ["Top / bottom", "Superior / inferior"],
  ["Supports", "Soportes"],
  ["Nozzle temperature", "Temperatura de la boquilla"],
  ["Bed temperature", "Temperatura de la cama"],
  ["Estimated time", "Tiempo estimado"],
  ["Filament cost", "Coste del filamento"],
  ["Mesh volume", "Volumen de la malla"],
  ["Mesh triangles", "Triángulos de la malla"],
  ["Slicer info", "Información del laminador"],
  ["Version", "Versión"],
  ["source ·", "origen ·"],
  ["Choose printer user", "Elegir usuario de impresora"],
];

const TRANSLATED_PROPS = new Set([
  "aria-label",
  "aria-description",
  "description",
  "hint",
  "label",
  "placeholder",
  "title",
  "confirmLabel",
  "ariaLabel",
]);

// Legacy literals remain isolated by locale until their callers move to typed
// message keys. Entries are intentionally exact: UI translation must never
// rewrite model names, tag names, collection names, or other user content.
const PHRASE_LOOKUPS: Partial<Record<Locale, ReadonlyMap<string, string>>> = {
  es: new Map(ES_PHRASES),
};

export function hasUiTranslation(locale: Locale, value: string): boolean {
  return PHRASE_LOOKUPS[locale]?.has(value.trim()) ?? false;
}

export function translateUiText(locale: Locale, value: string): string {
  const catalog = PHRASE_LOOKUPS[locale];
  if (!catalog || !value.trim()) return value;

  const leading = value.match(/^\s*/)?.[0] ?? "";
  const trailing = value.match(/\s*$/)?.[0] ?? "";
  const message = value.trim();
  const exact = catalog.get(message);
  if (exact) return `${leading}${exact}${trailing}`;

  const dynamic = message
    .match(/^(\d+) models? total$/i)?.[1];
  if (dynamic) return `${leading}${dynamic} modelos en total${trailing}`;

  const storedObjects = message.match(/^(\d+) stored objects?$/i)?.[1];
  if (storedObjects) return `${leading}${storedObjects} objetos guardados${trailing}`;

  const daysAgo = message.match(/^(\d+) days? ago$/i)?.[1];
  if (daysAgo) return `${leading}hace ${daysAgo} días${trailing}`;

  const files = message.match(/^(\d+) files?$/i)?.[1];
  if (files) return `${leading}${files} archivos${trailing}`;

  const source = message.match(/^(\d+) source$/i)?.[1];
  if (source) return `${leading}${source} originales${trailing}`;

  const addedPrinter = message.match(/^Printer "(.+)" added$/i)?.[1];
  if (addedPrinter) return `${leading}Impresora "${addedPrinter}" añadida${trailing}`;

  const removedPrinter = message.match(/^Printer "(.+)" removed$/i)?.[1];
  if (removedPrinter) return `${leading}Impresora "${removedPrinter}" eliminada${trailing}`;

  return value;
}

function localizeNode(node: ReactNode, locale: Locale): ReactNode {
  if (typeof node === "string") return translateUiText(locale, node);
  if (Array.isArray(node)) return node.map((child) => localizeNode(child, locale));
  if (!isValidElement(node)) return node;

  const element = node as ReactElement<Record<string, unknown>>;
  const props: Record<string, unknown> = {};
  for (const [name, value] of Object.entries(element.props)) {
    if (TRANSLATED_PROPS.has(name) && typeof value === "string") {
      props[name] = translateUiText(locale, value);
    }
  }
  if ("children" in element.props) {
    props.children = Children.map(element.props.children as ReactNode, (child) =>
      localizeNode(child, locale),
    );
  }
  return cloneElement(element, props);
}

export function Localized({ children }: { children: ReactNode }) {
  const locale = useOptionalI18n()?.locale ?? "en";
  return <>{localizeNode(children, locale)}</>;
}

const DOM_TRANSLATED_ATTRIBUTES = ["title", "placeholder", "aria-label", "aria-description"] as const;

/**
 * Compatibility boundary for UI still using literal English inside nested
 * components. Exact catalog matches only; user-created content is untouched.
 * New UI should use typed message keys from `lib/i18n` directly.
 */
export function DomLocalization() {
  const { locale } = useI18n();
  const textSources = useRef(new WeakMap<Text, string>());
  const attributeSources = useRef(new WeakMap<Element, Map<string, string>>());

  useEffect(() => {
    const root = document.getElementById("root");
    if (!root) return undefined;

    function localizeText(node: Text) {
      const parent = node.parentElement;
      if (!parent || parent.closest("script, style, code, pre, textarea, [contenteditable='true']")) return;
      const previous = textSources.current.get(node);
      const expected = previous === undefined ? undefined : translateUiText(locale, previous);
      const source = previous === undefined || (node.data !== previous && node.data !== expected) ? node.data : previous;
      textSources.current.set(node, source);
      const translated = translateUiText(locale, source);
      if (node.data !== translated) node.data = translated;
    }

    function localizeAttribute(element: Element, name: string) {
      const current = element.getAttribute(name);
      if (current === null) return;
      const sources = attributeSources.current.get(element) ?? new Map<string, string>();
      const previous = sources.get(name);
      const expected = previous === undefined ? undefined : translateUiText(locale, previous);
      const source = previous === undefined || (current !== previous && current !== expected) ? current : previous;
      sources.set(name, source);
      attributeSources.current.set(element, sources);
      const translated = translateUiText(locale, source);
      if (current !== translated) element.setAttribute(name, translated);
    }

    function localizeTree(node: Node) {
      if (node.nodeType === Node.TEXT_NODE) localizeText(node as Text);
      if (node.nodeType === Node.ELEMENT_NODE) {
        for (const attribute of DOM_TRANSLATED_ATTRIBUTES) localizeAttribute(node as Element, attribute);
      }
      for (const child of node.childNodes) localizeTree(child);
    }

    localizeTree(root);
    const observer = new MutationObserver((records) => {
      for (const record of records) {
        if (record.type === "characterData") localizeText(record.target as Text);
        if (record.type === "attributes" && record.attributeName) localizeAttribute(record.target as Element, record.attributeName);
        for (const node of record.addedNodes) localizeTree(node);
      }
    });
    observer.observe(root, {
      childList: true,
      subtree: true,
      characterData: true,
      attributes: true,
      attributeFilter: [...DOM_TRANSLATED_ATTRIBUTES],
    });
    return () => observer.disconnect();
  }, [locale]);

  return null;
}
