"""Exercise ingest limits, persistence, and generated artifacts through the API.

Failures expose accepted input whose durable result no longer matches the contract.
"""

from __future__ import annotations

import io
import struct
from datetime import timedelta
from pathlib import Path
from typing import Any, Callable

from fastapi.testclient import TestClient
from sqlmodel import Session, select

from app.core.config import _overlay
from app.core.time import utcnow
from app.db.models import (
    BackgroundJob,
    Collection,
    CollectionPermission,
    CollectionRole,
    FilamentProfile,
    File,
    FileType,
    InboxItem,
    InboxItemState,
    Metadata,
    Model,
    PrinterProfile,
    User,
)
from app.services import ingestion as ingestion_service
from app.services.auth import create_access_token, hash_password
from app.services.jobs import registry
from app.services.storage_backend import get_backend
from app.services.storage_ownership import record_creation

PNG_MAGIC = b"\x89PNG\r\n\x1a\n"
WEBP_MAGIC = b"RIFF"


def _cube_stl() -> bytes:
    return b"""solid cube
facet normal 0 0 -1
outer loop
vertex 0 0 0
vertex 1 1 0
vertex 1 0 0
endloop
endfacet
facet normal 0 0 -1
outer loop
vertex 0 0 0
vertex 0 1 0
vertex 1 1 0
endloop
endfacet
facet normal 0 0 1
outer loop
vertex 0 0 1
vertex 1 0 1
vertex 1 1 1
endloop
endfacet
facet normal 0 0 1
outer loop
vertex 0 0 1
vertex 1 1 1
vertex 0 1 1
endloop
endfacet
facet normal 0 -1 0
outer loop
vertex 0 0 0
vertex 1 0 0
vertex 1 0 1
endloop
endfacet
facet normal 0 -1 0
outer loop
vertex 0 0 0
vertex 1 0 1
vertex 0 0 1
endloop
endfacet
facet normal 1 0 0
outer loop
vertex 1 0 0
vertex 1 1 0
vertex 1 1 1
endloop
endfacet
facet normal 1 0 0
outer loop
vertex 1 0 0
vertex 1 1 1
vertex 1 0 1
endloop
endfacet
facet normal 0 1 0
outer loop
vertex 1 1 0
vertex 0 1 0
vertex 0 1 1
endloop
endfacet
facet normal 0 1 0
outer loop
vertex 1 1 0
vertex 0 1 1
vertex 1 1 1
endloop
endfacet
facet normal -1 0 0
outer loop
vertex 0 1 0
vertex 0 0 0
vertex 0 0 1
endloop
endfacet
facet normal -1 0 0
outer loop
vertex 0 1 0
vertex 0 0 1
vertex 0 1 1
endloop
endfacet
endsolid cube
"""


def _large_gcode(min_bytes: int = 1_200_000) -> bytes:
    payload = b"; generated by OrcaSlicer\nG90\nG1 X1 Y1 E1\n"
    payload += b"; padding to exceed nginx default body limit\n" * (min_bytes // 45)
    return payload


def _large_cube_stl(min_bytes: int = 1_200_000) -> bytes:
    lines = _cube_stl().splitlines()
    body = b"\n".join(lines[1:-1]) + b"\n"
    repeat_count = min_bytes // len(body) + 1
    return b"solid large-cube\n" + body * repeat_count + b"endsolid large-cube\n"


def _over_cap_binary_stl(n_triangles: int = 1_001) -> bytes:
    output = io.BytesIO()
    output.write(b"issue-67".ljust(80, b"\x00"))
    output.write(struct.pack("<I", n_triangles))
    record = struct.Struct("<12fH")
    for index in range(n_triangles):
        x = float(index % 100)
        y = float((index // 100) % 100)
        output.write(
            record.pack(
                0,
                0,
                1,
                x,
                y,
                0,
                x + 0.8,
                y,
                0,
                x,
                y + 0.8,
                0,
                0,
            )
        )
    return output.getvalue()


def _configure_storage(tmp_path: Path) -> None:
    _overlay["data_dir"] = tmp_path / "files"
    _overlay["thumb_dir"] = tmp_path / "thumbs"
    _overlay["staging_dir"] = tmp_path / "staging"


def _completed_job(client: TestClient, response) -> dict:
    assert response.status_code == 202, response.text
    job_id = response.json()["job_id"]
    headers = {}
    auth = response.request.headers.get("authorization")
    if auth:
        headers["Authorization"] = auth
    job = client.get(f"/api/v1/ingest/jobs/{job_id}", headers=headers)
    assert job.status_code == 200, job.text
    payload = job.json()
    assert payload["state"] == "completed", payload
    assert payload["model_id"] is not None
    assert payload["file_id"] is not None
    return payload


def _assert_file_created(session: Session, file_id: int, file_type: FileType) -> File:
    file_row = session.get(File, file_id)
    assert file_row is not None
    assert file_row.file_type == file_type
    assert file_row.size_bytes > 0
    assert get_backend().exists(file_row.path)
    metadata = session.exec(select(Metadata).where(Metadata.file_id == file_id)).one()
    assert metadata.file_id == file_id
    model = session.get(Model, file_row.model_id)
    assert model is not None
    assert model.thumbnail_file_id == file_id
    assert model.thumbnail_path
    assert get_backend().exists(model.thumbnail_path)
    return file_row


# --------------------------------------------------------------------------- #
# Validation / error paths (filename, file type, collection permission,
# target library) shared by the orca and mesh upload endpoints.
# --------------------------------------------------------------------------- #
def _regular_user(session: Session, username: str = "regular") -> User:
    user = User(
        username=username,
        hashed_password=hash_password("Password123"),
        is_active=True,
        is_superuser=False,
    )
    session.add(user)
    session.commit()
    session.refresh(user)
    return user


def _headers_for(user: User) -> dict[str, str]:
    scope = "admin" if user.is_superuser else "write"
    token = create_access_token(user.id, user.username, scope=scope)
    return {"Authorization": f"Bearer {token}"}


def _post_empty_filename_multipart(
    client: TestClient, url: str, headers: dict[str, str]
) -> Any:
    """Post a multipart body whose file part has an explicit empty filename.

    ``httpx``'s ``files=`` helper drops the ``filename`` attribute entirely
    when given an empty string (turning the part into a plain form field, not
    an ``UploadFile``), so the empty-filename branch can only be reached by
    building the multipart body by hand.
    """
    boundary = "ingesttestboundary"
    body = (
        f"--{boundary}\r\n"
        'Content-Disposition: form-data; name="file"; filename=""\r\n'
        "Content-Type: text/plain\r\n\r\n"
        "hi\r\n"
        f"--{boundary}--\r\n"
    ).encode()
    return client.post(
        url,
        content=body,
        headers={
            **headers,
            "content-type": f"multipart/form-data; boundary={boundary}",
        },
    )


__all__ = [
    "Any",
    "BackgroundJob",
    "Callable",
    "Collection",
    "CollectionPermission",
    "CollectionRole",
    "FilamentProfile",
    "File",
    "FileType",
    "InboxItem",
    "InboxItemState",
    "Metadata",
    "Model",
    "Path",
    "PrinterProfile",
    "Session",
    "TestClient",
    "User",
    "WEBP_MAGIC",
    "_assert_file_created",
    "_completed_job",
    "_configure_storage",
    "_cube_stl",
    "_headers_for",
    "_large_cube_stl",
    "_large_gcode",
    "_over_cap_binary_stl",
    "_overlay",
    "_post_empty_filename_multipart",
    "_regular_user",
    "get_backend",
    "ingestion_service",
    "io",
    "record_creation",
    "registry",
    "select",
    "timedelta",
    "utcnow",
]
