"""Defends ingest orca gcode creates db blob and thumbnail at the ingest API integration boundary.

A regression could publish an incomplete import or lose its durable job and artifact state.
"""

from __future__ import annotations

from tests.paths import TEST_DATA_DIR

from ._ingest_api_shared import (
    WEBP_MAGIC,
    Any,
    BackgroundJob,
    Callable,
    FilamentProfile,
    File,
    FileType,
    InboxItem,
    InboxItemState,
    Metadata,
    Model,
    Path,
    PrinterProfile,
    Session,
    TestClient,
    User,
    _assert_file_created,
    _completed_job,
    _configure_storage,
    _cube_stl,
    _large_cube_stl,
    _large_gcode,
    _over_cap_binary_stl,
    _overlay,
    get_backend,
    ingestion_service,
    record_creation,
    registry,
    select,
    timedelta,
    utcnow,
)


def test_ingest_orca_gcode_creates_db_blob_and_thumbnail(
    tmp_path: Path,
    client: TestClient,
    db_session: Session,
    auth_headers: dict[str, str],
) -> None:
    _configure_storage(tmp_path)
    gcode = (TEST_DATA_DIR / "sample.gcode").read_bytes()

    payload = _completed_job(
        client,
        client.post(
            "/api/v1/ingest/orca",
            headers=auth_headers,
            files={"file": ("sample.gcode", gcode, "text/plain")},
            data={"model_name": "Sample G-code"},
        ),
    )
    file_id = payload["file_id"]
    _assert_file_created(db_session, file_id, FileType.GCODE)

    download = client.get(f"/api/v1/files/{file_id}/download", headers=auth_headers)
    assert download.status_code == 200, download.text
    assert b"; generated by OrcaSlicer" in download.content

    thumbnail = client.get(f"/api/v1/files/{file_id}/thumbnail", headers=auth_headers)
    assert thumbnail.status_code == 200, thumbnail.text
    assert thumbnail.headers["content-type"] == "image/webp"
    assert thumbnail.content.startswith(WEBP_MAGIC)

    filament_profile = db_session.exec(
        select(FilamentProfile).where(FilamentProfile.name == "Generic PLA")
    ).one()
    assert filament_profile.material_type == "PLA"
    assert filament_profile.cost_per_kg == 28

    printer_profile = db_session.exec(
        select(PrinterProfile).where(PrinterProfile.name == "Ender-3 V3 SE")
    ).one()
    assert printer_profile.slicer_name == "OrcaSlicer"
    assert printer_profile.nozzle_diameter_mm == 0.4


def test_ingest_orca_accepts_payload_over_nginx_default_limit(
    tmp_path: Path,
    client: TestClient,
    db_session: Session,
    auth_headers: dict[str, str],
) -> None:
    _configure_storage(tmp_path)

    payload = _completed_job(
        client,
        client.post(
            "/api/v1/ingest/orca",
            headers=auth_headers,
            files={"file": ("large.gcode", _large_gcode(), "text/plain")},
            data={"model_name": "Large G-code"},
        ),
    )

    file_row = db_session.get(File, payload["file_id"])
    assert file_row is not None
    assert file_row.file_type == FileType.GCODE
    assert file_row.size_bytes > 1_000_000
    assert get_backend().exists(file_row.path)
    metadata = db_session.exec(
        select(Metadata).where(Metadata.file_id == file_row.id)
    ).one()
    assert metadata.file_id == file_row.id


def test_ingest_orca_stages_upload_in_threadpool(
    tmp_path: Path,
    client: TestClient,
    auth_headers: dict[str, str],
    monkeypatch,
) -> None:
    _configure_storage(tmp_path)
    called: dict[str, str] = {}

    async def fake_threadpool(
        func: Callable[..., Any], *args: Any, **kwargs: Any
    ) -> Any:
        called["func"] = func.__name__
        return func(*args, **kwargs)

    monkeypatch.setattr("app.api.v1.ingest.run_in_threadpool", fake_threadpool)

    response = client.post(
        "/api/v1/ingest/orca",
        headers=auth_headers,
        files={"file": ("sample.gcode", b"G28\n", "text/plain")},
        data={"model_name": "Threadpool Check"},
    )

    assert response.status_code == 202
    assert called == {"func": "_stage_upload"}


def test_ingest_stl_creates_db_blob_and_thumbnail(
    tmp_path: Path,
    client: TestClient,
    db_session: Session,
    auth_headers: dict[str, str],
) -> None:
    _configure_storage(tmp_path)

    payload = _completed_job(
        client,
        client.post(
            "/api/v1/ingest/model",
            headers=auth_headers,
            files={"file": ("cube.stl", _cube_stl(), "application/sla")},
            data={"model_name": "Cube"},
        ),
    )
    file_id = payload["file_id"]
    _assert_file_created(db_session, file_id, FileType.STL)

    download = client.get(f"/api/v1/files/{file_id}/download", headers=auth_headers)
    assert download.status_code == 200, download.text
    assert b"solid cube" in download.content

    thumbnail = client.get(f"/api/v1/files/{file_id}/thumbnail", headers=auth_headers)
    assert thumbnail.status_code == 200, thumbnail.text
    assert thumbnail.headers["content-type"] == "image/webp"
    assert thumbnail.content.startswith(WEBP_MAGIC)


def test_ingest_publishes_terminal_only_after_fresh_durability_check(
    tmp_path: Path,
    client: TestClient,
    auth_headers: dict[str, str],
    monkeypatch,
) -> None:
    _configure_storage(tmp_path)
    checkpoints: list[str] = []
    observed_job_ids: list[str] = []
    original_verify = ingestion_service.verify_durable_artifact

    def observe_checkpoint(stage: str, current_job_id: str) -> None:
        if stage == "after_commit":
            observed_job_ids.append(current_job_id)

    def observed_verify(*args, **kwargs) -> None:
        status = ingestion_service.registry.get(observed_job_ids[-1])
        assert status is not None
        assert status.state == "running"
        assert status.progress is None or status.progress < 100
        assert status.committed_at is not None
        checkpoints.append("fresh_session_and_storage")
        original_verify(*args, **kwargs)

    monkeypatch.setattr(
        ingestion_service, "_fault_injection_checkpoint", observe_checkpoint
    )
    monkeypatch.setattr(ingestion_service, "verify_durable_artifact", observed_verify)
    response = client.post(
        "/api/v1/ingest/model",
        headers=auth_headers,
        files={"file": ("durable.stl", _cube_stl(), "application/sla")},
        data={"model_name": "Durable Cube"},
    )
    assert response.status_code == 202
    job_id = response.json()["job_id"]

    status = client.get(f"/api/v1/ingest/jobs/{job_id}", headers=auth_headers).json()
    assert checkpoints == ["fresh_session_and_storage"]
    assert status["state"] == "completed"
    assert status["completion"] == "complete"
    assert status["thumbnail_status"] == "generated"
    assert status["committed_at"] is not None


def test_exception_after_commit_is_a_durable_partial_result(
    tmp_path: Path,
    client: TestClient,
    db_session: Session,
    auth_headers: dict[str, str],
    monkeypatch,
) -> None:
    _configure_storage(tmp_path)

    def inject(stage: str, _job_id: str) -> None:
        if stage == "after_commit":
            raise RuntimeError("injected_after_commit")

    monkeypatch.setattr(ingestion_service, "_fault_injection_checkpoint", inject)
    response = client.post(
        "/api/v1/ingest/model",
        headers=auth_headers,
        files={"file": ("post-commit.stl", _cube_stl(), "application/sla")},
        data={"model_name": "Post Commit Cube"},
    )
    assert response.status_code == 202
    job_id = response.json()["job_id"]
    status = client.get(f"/api/v1/ingest/jobs/{job_id}", headers=auth_headers).json()

    assert status["state"] == "completed"
    assert status["completion"] == "partial"
    assert status["thumbnail_reason"] == "post_commit_exception"
    assert status["retryable"] is True
    assert db_session.get(Model, status["model_id"]) is not None
    assert db_session.get(File, status["file_id"]) is not None


def test_ingest_model_accepts_payload_over_nginx_default_limit(
    tmp_path: Path,
    client: TestClient,
    db_session: Session,
    auth_headers: dict[str, str],
    monkeypatch,
) -> None:
    _configure_storage(tmp_path)
    monkeypatch.setattr(
        "app.services.mesh_processing.analyze_mesh",
        lambda _path, report=None: ({"bbox_x_mm": 1.0}, None),
    )

    payload = _completed_job(
        client,
        client.post(
            "/api/v1/ingest/model",
            headers=auth_headers,
            files={"file": ("large-cube.stl", _large_cube_stl(), "application/sla")},
            data={"model_name": "Large Cube"},
        ),
    )

    file_row = db_session.get(File, payload["file_id"])
    assert file_row is not None
    assert file_row.file_type == FileType.STL
    assert file_row.size_bytes > 1_000_000
    assert get_backend().exists(file_row.path)
    metadata = db_session.exec(
        select(Metadata).where(Metadata.file_id == file_row.id)
    ).one()
    assert metadata.bbox_x_mm == 1.0


def test_issue_67_over_cap_stl_persists_authenticated_webp_fallback(
    tmp_path: Path,
    client: TestClient,
    auth_headers: dict[str, str],
    monkeypatch,
) -> None:
    _configure_storage(tmp_path)
    monkeypatch.setitem(_overlay, "mesh_max_render_triangles", 1_000)

    payload = _completed_job(
        client,
        client.post(
            "/api/v1/ingest/model",
            headers=auth_headers,
            files={
                "file": (
                    "issue-67-over-limit.stl",
                    _over_cap_binary_stl(),
                    "application/sla",
                )
            },
            data={"model_name": "Issue 67 Fallback"},
        ),
    )

    assert payload["completion"] == "complete"
    assert payload["thumbnail_status"] == "fallback_generated"
    thumbnail = client.get(
        f"/api/v1/files/{payload['file_id']}/thumbnail", headers=auth_headers
    )
    assert thumbnail.status_code == 200
    assert thumbnail.headers["content-type"] == "image/webp"
    assert thumbnail.content.startswith(WEBP_MAGIC)


def test_issue_67_upload_survives_pruning_completed_inbox_job(
    tmp_path: Path,
    client: TestClient,
    db_session: Session,
    auth_headers: dict[str, str],
    monkeypatch,
) -> None:
    """A stale terminal inbox link must not turn the next upload into a 500."""
    _configure_storage(tmp_path)
    owner = db_session.exec(select(User).where(User.username == "test-writer")).one()
    old_job = BackgroundJob(
        id="expired-inbox-job",
        owner_user_id=owner.id,
        state="completed",
        status_json='{"state":"completed"}',
        finished_at=utcnow() - timedelta(hours=2),
    )
    db_session.add(old_job)
    db_session.flush()
    db_session.add(
        InboxItem(
            owner_user_id=owner.id,
            state=InboxItemState.COMPLETED,
            background_job_id=old_job.id,
        )
    )
    db_session.commit()
    monkeypatch.setattr(registry, "_last_persisted_prune_at", float("-inf"))

    response = client.post(
        "/api/v1/ingest/model",
        headers=auth_headers,
        files={"file": ("issue-67.stl", _cube_stl(), "application/sla")},
        data={"model_name": "Issue 67 Upload"},
    )

    assert response.status_code == 202, response.text


def test_reuploading_deleted_model_restores_it(
    tmp_path: Path,
    client: TestClient,
    db_session: Session,
    auth_headers: dict[str, str],
) -> None:
    _configure_storage(tmp_path)

    first = _completed_job(
        client,
        client.post(
            "/api/v1/ingest/model",
            headers=auth_headers,
            files={"file": ("cube.stl", _cube_stl(), "application/sla")},
            data={"model_name": "Cube"},
        ),
    )
    model_id = first["model_id"]

    delete = client.delete(f"/api/v1/models/{model_id}", headers=auth_headers)
    assert delete.status_code == 204
    assert (
        client.get(f"/api/v1/models/{model_id}", headers=auth_headers).status_code
        == 404
    )

    second = _completed_job(
        client,
        client.post(
            "/api/v1/ingest/model",
            headers=auth_headers,
            files={"file": ("cube.stl", _cube_stl(), "application/sla")},
            data={"model_name": "Cube"},
        ),
    )

    assert second["model_id"] == model_id
    model = db_session.get(Model, model_id)
    assert model is not None
    assert model.deleted_at is None
    detail = client.get(f"/api/v1/models/{model_id}", headers=auth_headers)
    assert detail.status_code == 200, detail.text
    assert len(detail.json()["files"]) == 2


def test_trash_can_restore_and_purge_model(
    tmp_path: Path,
    client: TestClient,
    db_session: Session,
    auth_headers: dict[str, str],
) -> None:
    _configure_storage(tmp_path)

    payload = _completed_job(
        client,
        client.post(
            "/api/v1/ingest/model",
            headers=auth_headers,
            files={"file": ("cube.stl", _cube_stl(), "application/sla")},
            data={"model_name": "Cube"},
        ),
    )
    model_id = payload["model_id"]
    file_row = db_session.get(File, payload["file_id"])
    assert file_row is not None
    blob_path = file_row.path
    thumb_path = get_backend().thumbnail_key(file_row.id)

    delete = client.delete(f"/api/v1/models/{model_id}", headers=auth_headers)
    assert delete.status_code == 204

    trash = client.get("/api/v1/models/trash", headers=auth_headers)
    assert trash.status_code == 200, trash.text
    assert trash.json()[0]["id"] == model_id
    assert trash.json()[0]["file_count"] == 1
    assert trash.json()[0]["expires_at"] is not None

    restored = client.post(f"/api/v1/models/{model_id}/restore", headers=auth_headers)
    assert restored.status_code == 200, restored.text
    assert restored.json()["id"] == model_id
    assert client.get("/api/v1/models/trash", headers=auth_headers).json() == []

    delete = client.delete(f"/api/v1/models/{model_id}", headers=auth_headers)
    assert delete.status_code == 204
    purged = client.delete(f"/api/v1/models/{model_id}/purge", headers=auth_headers)
    assert purged.status_code == 200, purged.text
    assert purged.json() == {
        "purged_model_ids": [model_id],
        "purged_count": 1,
        "storage_completed": 2,
        "storage_pending": 0,
        "storage_blocked": 0,
        "resources_blocked": 0,
    }
    db_session.expire_all()
    assert db_session.get(Model, model_id) is None
    assert db_session.get(File, payload["file_id"]) is None
    assert not get_backend().exists(blob_path)
    assert not get_backend().exists(thumb_path)


def test_purge_expired_trash_uses_retention_setting(
    tmp_path: Path,
    client: TestClient,
    db_session: Session,
    auth_headers: dict[str, str],
) -> None:
    _configure_storage(tmp_path)
    _overlay["trash_retention_days"] = 30
    old_model = Model(
        name="Old Cube",
        slug="old-cube",
        hash="old-cube".ljust(64, "0"),
        deleted_at=utcnow() - timedelta(days=31),
    )
    fresh_model = Model(
        name="Fresh Cube",
        slug="fresh-cube",
        hash="fresh-cube".ljust(64, "0"),
        deleted_at=utcnow() - timedelta(days=3),
    )
    db_session.add(old_model)
    db_session.add(fresh_model)
    db_session.commit()
    db_session.refresh(old_model)
    db_session.refresh(fresh_model)

    old_file = File(
        model_id=old_model.id,
        path=str(tmp_path / "files" / "old-cube.stl"),
        original_filename="old-cube.stl",
        file_type=FileType.STL,
        version=1,
        size_bytes=4,
        sha256="a" * 64,
    )
    fresh_file = File(
        model_id=fresh_model.id,
        path=str(tmp_path / "files" / "fresh-cube.stl"),
        original_filename="fresh-cube.stl",
        file_type=FileType.STL,
        version=1,
        size_bytes=4,
        sha256="b" * 64,
    )
    db_session.add(old_file)
    db_session.add(fresh_file)
    db_session.commit()
    old_model_id = old_model.id
    fresh_model_id = fresh_model.id
    old_file_path = old_file.path
    fresh_file_path = fresh_file.path
    backend = get_backend()
    record_creation(
        db_session,
        backend.create_bytes(b"old", old_file.path),
        object_kind="artifact",
    )
    record_creation(
        db_session,
        backend.create_bytes(b"new", fresh_file.path),
        object_kind="artifact",
    )
    db_session.commit()

    purged = client.delete("/api/v1/models/trash/expired", headers=auth_headers)

    assert purged.status_code == 200, purged.text
    assert purged.json() == {
        "purged_model_ids": [old_model_id],
        "purged_count": 1,
        "storage_completed": 1,
        "storage_pending": 0,
        "storage_blocked": 0,
        "resources_blocked": 0,
    }
    db_session.expire_all()
    assert db_session.get(Model, old_model_id) is None
    assert db_session.get(Model, fresh_model_id) is not None
    assert not Path(old_file_path).exists()
    assert Path(fresh_file_path).exists()
