"""Synchronous ingestion I/O must leave the ASGI event loop responsive.

The dependency deliberately waits for a callback on the request's event loop.
A synchronous call on that loop cannot satisfy the handshake before its timeout;
a complete request command in the bounded thread pool can. This avoids comparing
fragile wall-clock percentiles on shared CI hosts.
"""

from __future__ import annotations

import asyncio
import io
import json
import zipfile

import httpx
import pytest

from app.db.models import IngestRequestKind, JobState
from app.db.session import get_session_factory, override_session_factory
from app.modules.storage import storage
from tests.factories import build_user
from tests.factories.identity import bearer
from tests.fakes.thread_sessions import ThreadBoundSessionFactory


class TestIngestExecution:
    @pytest.fixture(autouse=True)
    def _thread_owned_command_sessions(self, db_session):
        factory = ThreadBoundSessionFactory(db_session.get_bind())
        previous = get_session_factory()
        override_session_factory(factory)
        try:
            yield factory
            assert factory.opened_count > 0
            assert factory.active_count == 0
        finally:
            override_session_factory(previous)

    @pytest.mark.asyncio
    @pytest.mark.parametrize(
        "endpoint,filename,content",
        [
            pytest.param(
                "model", "source.stl", b"solid source\nendsolid source", id="model"
            ),
            pytest.param(
                "orca", "slice.gcode", b"; generated by OrcaSlicer\nG1 X1 Y1", id="orca"
            ),
        ],
    )
    async def test_keeps_loop_responsive_during_upload_submission(
        self,
        app,
        auth_headers,
        work_engine,
        monkeypatch,
        loop_handshake,
        endpoint,
        filename,
        content,
    ):
        wait_for_loop, observations = loop_handshake
        submit = work_engine.submit

        def delayed_submit(submission):
            wait_for_loop()
            return submit(submission)

        monkeypatch.setattr(work_engine, "submit", delayed_submit)

        async with httpx.AsyncClient(
            transport=httpx.ASGITransport(app=app), base_url="http://test"
        ) as client:
            response = await client.post(
                f"/api/v1/ingest/{endpoint}",
                headers=auth_headers,
                files={"file": (filename, content, "application/octet-stream")},
            )

        assert response.status_code == 202, response.text
        assert observations == [True]

    @pytest.mark.asyncio
    async def test_keeps_loop_responsive_during_url_submission(
        self,
        app,
        auth_headers,
        work_engine,
        monkeypatch,
        loop_handshake,
    ):
        wait_for_loop, observations = loop_handshake
        submit = work_engine.submit

        def delayed_submit(submission):
            wait_for_loop()
            return submit(submission)

        monkeypatch.setattr(work_engine, "submit", delayed_submit)

        async with httpx.AsyncClient(
            transport=httpx.ASGITransport(app=app), base_url="http://test"
        ) as client:
            response = await client.post(
                "/api/v1/ingest/url",
                headers=auth_headers,
                json={"url": "https://8.8.8.8/model.stl"},
            )

        assert response.status_code == 202, response.text
        assert observations == [True]

    @pytest.mark.asyncio
    @pytest.mark.parametrize(
        "endpoint,filename",
        [
            pytest.param("model", "source.stl", id="model"),
            pytest.param("orca", "slice.gcode", id="orca"),
        ],
    )
    async def test_keeps_loop_responsive_during_staging(
        self,
        app,
        auth_headers,
        monkeypatch,
        loop_handshake,
        endpoint,
        filename,
    ):
        wait_for_loop, observations = loop_handshake
        stream_to_path = storage.stream_to_path

        def delayed_stream(*args, **kwargs):
            wait_for_loop()
            return stream_to_path(*args, **kwargs)

        monkeypatch.setattr(storage, "stream_to_path", delayed_stream)

        async with httpx.AsyncClient(
            transport=httpx.ASGITransport(app=app), base_url="http://test"
        ) as client:
            response = await client.post(
                f"/api/v1/ingest/{endpoint}",
                headers=auth_headers,
                files={
                    "file": (
                        filename,
                        b"solid source\nendsolid source",
                        "application/octet-stream",
                    )
                },
            )

        assert response.status_code == 202, response.text
        assert observations == [True]

    @pytest.mark.asyncio
    async def test_keeps_loop_responsive_during_archive_submission(
        self,
        app,
        auth_headers,
        work_engine,
        monkeypatch,
        loop_handshake,
    ):
        wait_for_loop, observations = loop_handshake
        submit = work_engine.submit
        content = io.BytesIO()
        with zipfile.ZipFile(content, "w") as archive:
            archive.writestr("source.stl", b"solid source\nendsolid source")

        def delayed_submit(submission):
            wait_for_loop()
            return submit(submission)

        monkeypatch.setattr(work_engine, "submit", delayed_submit)

        async with httpx.AsyncClient(
            transport=httpx.ASGITransport(app=app), base_url="http://test"
        ) as client:
            response = await client.post(
                "/api/v1/ingest/archive/inspect",
                headers=auth_headers,
                files={"file": ("source.zip", content.getvalue(), "application/zip")},
            )

        assert response.status_code == 202, response.text
        assert observations == [True]

    @pytest.mark.asyncio
    @pytest.mark.parametrize("kind", ["model_files", "collection"])
    async def test_keeps_loop_responsive_during_manifest_selection(
        self,
        app,
        db_session,
        make_ingest_request,
        work_engine,
        monkeypatch,
        loop_handshake,
        kind,
    ):
        owner = build_user(db_session, "selection-owner", superuser=True)
        if kind == "model_files":
            manifest = {
                "kind": kind,
                "page_url": "https://printables.com/model/1",
                "files": [{"file_id": "1", "name": "part.stl", "file_type": "stl"}],
            }
            route = "url/files"
            selection = {"file_ids": ["1"]}
        else:
            manifest = {
                "kind": kind,
                "title": "Parts",
                "target_collection": "Parts",
                "members": [
                    {
                        "source_id": "1",
                        "title": "Part",
                        "page_url": "https://printables.com/model/1",
                    }
                ],
            }
            route = "collection"
            selection = {"member_ids": ["1"]}
        request = make_ingest_request(
            owner,
            kind=IngestRequestKind.URL,
            state=JobState.COMPLETED,
            manifest_json=json.dumps(manifest),
        )
        wait_for_loop, observations = loop_handshake
        submit = work_engine.submit

        def delayed_submit(submission):
            wait_for_loop()
            return submit(submission)

        monkeypatch.setattr(work_engine, "submit", delayed_submit)
        async with httpx.AsyncClient(
            transport=httpx.ASGITransport(app=app), base_url="http://test"
        ) as client:
            response = await client.post(
                f"/api/v1/ingest/{route}/{request.job_id}/select",
                headers=bearer(owner),
                json=selection,
            )

        assert response.status_code == 202, response.text
        assert observations == [True]

    @pytest.mark.asyncio
    async def test_keeps_loop_responsive_during_archive_selection(
        self,
        app,
        auth_headers,
        work_engine,
        monkeypatch,
        loop_handshake,
    ):
        content = io.BytesIO()
        with zipfile.ZipFile(content, "w") as archive:
            archive.writestr("source.stl", b"solid source\nendsolid source")
        async with httpx.AsyncClient(
            transport=httpx.ASGITransport(app=app), base_url="http://test"
        ) as client:
            inspected = await client.post(
                "/api/v1/ingest/archive/inspect",
                headers=auth_headers,
                files={"file": ("source.zip", content.getvalue(), "application/zip")},
            )
            assert inspected.status_code == 202, inspected.text
            # Only ZIP inspection runs here; no model is imported or rendered.
            await asyncio.to_thread(work_engine.drain)
            wait_for_loop, observations = loop_handshake
            submit = work_engine.submit

            def delayed_submit(submission):
                wait_for_loop()
                return submit(submission)

            monkeypatch.setattr(work_engine, "submit", delayed_submit)
            response = await client.post(
                f"/api/v1/ingest/archive/{inspected.json()['job_id']}/select",
                headers=auth_headers,
                json={"names": ["source.stl"]},
            )

        assert response.status_code == 202, response.text
        assert observations == [True]
