"""Getting a file into the library, all the way through, over HTTP.

Ingest is a multi-table write plus two blob writes behind one request, and the
dangerous outcome is not failure — it is a *partial* success. A `File` row whose
bytes were never written, or a model whose thumbnail points at a missing key,
looks fine in the database and breaks at the moment a user opens it. So these
tests assert the whole postcondition together: row, bytes, metadata, and the
owning model's thumbnail.

The durability row is the load-bearing one. A job is published as terminal only
after a *fresh* check that its bytes are on disk — publishing first and verifying
later means a crash in between leaves a job that claims success with nothing to
show.

The rest are cases a real user hits: a mesh over the triangle cap, which must
still get an authenticated preview rather than no preview; an upload that outlives
the pruning of its own completed inbox job; a forced rebuild replacing an existing
thumbnail; and retention actually being read from configuration rather than
hard-coded, since a self-hoster who sets 90 days and loses data at 30 has lost
data.
"""

from __future__ import annotations

import io
import struct
from datetime import timedelta
from pathlib import Path
from typing import Any, Callable

import pytest
from fastapi.testclient import TestClient
from sqlmodel import Session, select

from app.core.config import _overlay
from app.core.time import utcnow
from app.db.models import (
    BackgroundJob,
    CollectionRole,
    FilamentProfile,
    File,
    FileType,
    InboxItem,
    InboxItemState,
    Metadata,
    Model,
    PrinterProfile,
    User,
)
from app.services import ingestion as ingestion_service
from app.services.jobs import registry
from app.services.storage_backend import get_backend
from tests._env import use_local_storage
from tests.factories import (
    bearer,
    build_collection,
    build_user,
    grant_collection_role,
)
from tests.integration.api.v1._ingest_assertions import (
    assert_file_created,
    completed_job,
)
from tests.paths import FIXTURES_DIR

PNG_MAGIC = b"\x89PNG\r\n\x1a\n"
WEBP_MAGIC = b"RIFF"


def _cube_stl() -> bytes:
    return b"""solid cube
facet normal 0 0 -1
outer loop
vertex 0 0 0
vertex 1 1 0
vertex 1 0 0
endloop
endfacet
facet normal 0 0 -1
outer loop
vertex 0 0 0
vertex 0 1 0
vertex 1 1 0
endloop
endfacet
facet normal 0 0 1
outer loop
vertex 0 0 1
vertex 1 0 1
vertex 1 1 1
endloop
endfacet
facet normal 0 0 1
outer loop
vertex 0 0 1
vertex 1 1 1
vertex 0 1 1
endloop
endfacet
facet normal 0 -1 0
outer loop
vertex 0 0 0
vertex 1 0 0
vertex 1 0 1
endloop
endfacet
facet normal 0 -1 0
outer loop
vertex 0 0 0
vertex 1 0 1
vertex 0 0 1
endloop
endfacet
facet normal 1 0 0
outer loop
vertex 1 0 0
vertex 1 1 0
vertex 1 1 1
endloop
endfacet
facet normal 1 0 0
outer loop
vertex 1 0 0
vertex 1 1 1
vertex 1 0 1
endloop
endfacet
facet normal 0 1 0
outer loop
vertex 1 1 0
vertex 0 1 0
vertex 0 1 1
endloop
endfacet
facet normal 0 1 0
outer loop
vertex 1 1 0
vertex 0 1 1
vertex 1 1 1
endloop
endfacet
facet normal -1 0 0
outer loop
vertex 0 1 0
vertex 0 0 0
vertex 0 0 1
endloop
endfacet
facet normal -1 0 0
outer loop
vertex 0 1 0
vertex 0 0 1
vertex 0 1 1
endloop
endfacet
endsolid cube
"""


def _large_gcode(min_bytes: int = 1_200_000) -> bytes:
    payload = b"; generated by OrcaSlicer\nG90\nG1 X1 Y1 E1\n"
    payload += b"; padding to exceed nginx default body limit\n" * (min_bytes // 45)
    return payload


def _large_cube_stl(min_bytes: int = 1_200_000) -> bytes:
    lines = _cube_stl().splitlines()
    body = b"\n".join(lines[1:-1]) + b"\n"
    repeat_count = min_bytes // len(body) + 1
    return b"solid large-cube\n" + body * repeat_count + b"endsolid large-cube\n"


def _over_cap_binary_stl(n_triangles: int = 1_001) -> bytes:
    output = io.BytesIO()
    output.write(b"issue-67".ljust(80, b"\x00"))
    output.write(struct.pack("<I", n_triangles))
    record = struct.Struct("<12fH")
    for index in range(n_triangles):
        x = float(index % 100)
        y = float((index // 100) % 100)
        output.write(
            record.pack(
                0,
                0,
                1,
                x,
                y,
                0,
                x + 0.8,
                y,
                0,
                x,
                y + 0.8,
                0,
                0,
            )
        )
    return output.getvalue()


# --------------------------------------------------------------------------- #
# Validation / error paths (filename, file type, collection permission,
# target library) shared by the orca and mesh upload endpoints.
# --------------------------------------------------------------------------- #
def _regular_user(session: Session, username: str = "regular") -> User:
    user = build_user(
        session, username=username, password="Password123", active=True, superuser=False
    )
    return user


def _post_empty_filename_multipart(
    client: TestClient, url: str, headers: dict[str, str]
) -> Any:
    """Post a multipart body whose file part has an explicit empty filename.

    ``httpx``'s ``files=`` helper drops the ``filename`` attribute entirely
    when given an empty string (turning the part into a plain form field, not
    an ``UploadFile``), so the empty-filename branch can only be reached by
    building the multipart body by hand.
    """
    boundary = "ingesttestboundary"
    body = (
        f"--{boundary}\r\n"
        'Content-Disposition: form-data; name="file"; filename=""\r\n'
        "Content-Type: text/plain\r\n\r\n"
        "hi\r\n"
        f"--{boundary}--\r\n"
    ).encode()
    return client.post(
        url,
        content=body,
        headers={
            **headers,
            "content-type": f"multipart/form-data; boundary={boundary}",
        },
    )


class TestListJobs:
    def test_lists_the_callers_own_ingest_job(
        self,
        tmp_path: Path,
        client: TestClient,
        auth_headers: dict[str, str],
    ) -> None:
        use_local_storage(tmp_path)
        payload = completed_job(
            client,
            client.post(
                "/api/v1/ingest/model",
                headers=auth_headers,
                files={"file": ("cube.stl", _cube_stl(), "application/sla")},
                data={"model_name": "Cube"},
            ),
        )

        jobs = client.get("/api/v1/ingest/jobs", headers=auth_headers)

        assert jobs.status_code == 200, jobs.text
        assert any(job["model_id"] == payload["model_id"] for job in jobs.json())


class TestIngestOrca:
    def test_ingesting_orca_gcode_produces_a_servable_artifact(
        self,
        tmp_path: Path,
        client: TestClient,
        db_session: Session,
        auth_headers: dict[str, str],
    ) -> None:
        use_local_storage(tmp_path)
        gcode = (FIXTURES_DIR / "sample.gcode").read_bytes()

        payload = completed_job(
            client,
            client.post(
                "/api/v1/ingest/orca",
                headers=auth_headers,
                files={"file": ("sample.gcode", gcode, "text/plain")},
                data={"model_name": "Sample G-code"},
            ),
        )
        file_id = payload["file_id"]
        assert_file_created(db_session, file_id, FileType.GCODE)

        download = client.get(f"/api/v1/files/{file_id}/download", headers=auth_headers)
        assert download.status_code == 200, download.text
        assert b"; generated by OrcaSlicer" in download.content

        thumbnail = client.get(
            f"/api/v1/files/{file_id}/thumbnail", headers=auth_headers
        )
        assert thumbnail.status_code == 200, thumbnail.text
        assert thumbnail.headers["content-type"] == "image/webp"
        assert thumbnail.content.startswith(WEBP_MAGIC)

        filament_profile = db_session.exec(
            select(FilamentProfile).where(FilamentProfile.name == "Generic PLA")
        ).one()
        assert filament_profile.material_type == "PLA"
        assert filament_profile.cost_per_kg == 28

        printer_profile = db_session.exec(
            select(PrinterProfile).where(PrinterProfile.name == "Ender-3 V3 SE")
        ).one()
        assert printer_profile.slicer_name == "OrcaSlicer"
        assert printer_profile.nozzle_diameter_mm == 0.4

    def test_ingest_orca_accepts_payload_over_nginx_default_limit(
        self,
        tmp_path: Path,
        client: TestClient,
        db_session: Session,
        auth_headers: dict[str, str],
    ) -> None:
        use_local_storage(tmp_path)

        payload = completed_job(
            client,
            client.post(
                "/api/v1/ingest/orca",
                headers=auth_headers,
                files={"file": ("large.gcode", _large_gcode(), "text/plain")},
                data={"model_name": "Large G-code"},
            ),
        )

        file_row = db_session.get(File, payload["file_id"])
        assert file_row is not None
        assert file_row.file_type == FileType.GCODE
        assert file_row.size_bytes > 1_000_000
        assert get_backend().exists(file_row.path)
        metadata = db_session.exec(
            select(Metadata).where(Metadata.file_id == file_row.id)
        ).one()
        assert metadata.file_id == file_row.id

    def test_ingest_orca_stages_upload_in_threadpool(
        self,
        tmp_path: Path,
        client: TestClient,
        auth_headers: dict[str, str],
        monkeypatch,
    ) -> None:
        use_local_storage(tmp_path)
        called: dict[str, str] = {}

        async def fake_threadpool(
            func: Callable[..., Any], *args: Any, **kwargs: Any
        ) -> Any:
            called["func"] = func.__name__
            return func(*args, **kwargs)

        monkeypatch.setattr("app.api.v1.ingest.run_in_threadpool", fake_threadpool)

        response = client.post(
            "/api/v1/ingest/orca",
            headers=auth_headers,
            files={"file": ("sample.gcode", b"G28\n", "text/plain")},
            data={"model_name": "Threadpool Check"},
        )

        assert response.status_code == 202
        assert called == {"func": "_stage_upload"}

    def test_ingest_orca_rejects_missing_filename(
        self, client: TestClient, auth_headers: dict[str, str]
    ) -> None:
        response = _post_empty_filename_multipart(
            client, "/api/v1/ingest/orca", auth_headers
        )
        assert response.status_code == 400, response.text
        assert response.json()["detail"] == "filename_required"

    def test_ingest_orca_rejects_unsupported_suffix(
        self, client: TestClient, auth_headers: dict[str, str]
    ) -> None:
        response = client.post(
            "/api/v1/ingest/orca",
            headers=auth_headers,
            files={"file": ("notes.txt", b"hello", "text/plain")},
        )
        assert response.status_code == 400, response.text
        assert response.json()["detail"] == "unsupported_file_type"

    def test_ingest_orca_rejects_a_source_hash_that_is_not_a_sha256(
        self, tmp_path: Path, client: TestClient, auth_headers: dict[str, str]
    ) -> None:
        """The hash names an inbox item's bytes, so a malformed one is a client bug."""
        use_local_storage(tmp_path)

        response = client.post(
            "/api/v1/ingest/orca",
            headers=auth_headers,
            files={"file": ("part.gcode", b"G28\n", "text/plain")},
            data={"source_hash": "not-a-hash"},
        )

        assert response.status_code == 422, response.text
        assert response.json()["detail"] == "source_hash_invalid"


class TestIngestModel:
    def test_ingest_model_accepts_payload_over_nginx_default_limit(
        self,
        tmp_path: Path,
        client: TestClient,
        db_session: Session,
        auth_headers: dict[str, str],
        monkeypatch,
    ) -> None:
        use_local_storage(tmp_path)
        monkeypatch.setattr(
            "app.services.mesh_processing.analyze_mesh",
            lambda _path, report=None: ({"bbox_x_mm": 1.0}, None),
        )

        payload = completed_job(
            client,
            client.post(
                "/api/v1/ingest/model",
                headers=auth_headers,
                files={
                    "file": ("large-cube.stl", _large_cube_stl(), "application/sla")
                },
                data={"model_name": "Large Cube"},
            ),
        )

        file_row = db_session.get(File, payload["file_id"])
        assert file_row is not None
        assert file_row.file_type == FileType.STL
        assert file_row.size_bytes > 1_000_000
        assert get_backend().exists(file_row.path)
        metadata = db_session.exec(
            select(Metadata).where(Metadata.file_id == file_row.id)
        ).one()
        assert metadata.bbox_x_mm == 1.0

    def test_ingest_model_rejects_missing_filename(
        self, client: TestClient, auth_headers: dict[str, str]
    ) -> None:
        response = _post_empty_filename_multipart(
            client, "/api/v1/ingest/model", auth_headers
        )
        assert response.status_code == 400, response.text
        assert response.json()["detail"] == "filename_required"

    def test_ingest_model_rejects_unsupported_suffix(
        self, client: TestClient, auth_headers: dict[str, str]
    ) -> None:
        response = client.post(
            "/api/v1/ingest/model",
            headers=auth_headers,
            files={"file": ("notes.txt", b"hello", "text/plain")},
        )
        assert response.status_code == 400, response.text
        assert response.json()["detail"] == "unsupported_file_type"

    def test_ingest_model_requires_collection_for_non_superuser(
        self, tmp_path: Path, client: TestClient, db_session: Session
    ) -> None:
        use_local_storage(tmp_path)
        user = _regular_user(db_session)
        response = client.post(
            "/api/v1/ingest/model",
            headers=bearer(user),
            files={"file": ("cube.stl", _cube_stl(), "application/sla")},
        )
        assert response.status_code == 403, response.text
        assert response.json()["detail"] == "collection_required"

    def test_ingest_model_unknown_collection_denied_for_non_superuser(
        self, tmp_path: Path, client: TestClient, db_session: Session
    ) -> None:
        use_local_storage(tmp_path)
        user = _regular_user(db_session)
        response = client.post(
            "/api/v1/ingest/model",
            headers=bearer(user),
            files={"file": ("cube.stl", _cube_stl(), "application/sla")},
            data={"collection": "does-not-exist"},
        )
        assert response.status_code == 403, response.text
        assert response.json()["detail"] == "collection_permission_denied"

    def test_ingest_model_requires_role_on_existing_collection(
        self, tmp_path: Path, client: TestClient, db_session: Session
    ) -> None:
        use_local_storage(tmp_path)
        user = _regular_user(db_session)
        build_collection(db_session, name="Brackets", slug="brackets", path="brackets")

        response = client.post(
            "/api/v1/ingest/model",
            headers=bearer(user),
            files={"file": ("cube.stl", _cube_stl(), "application/sla")},
            data={"collection": "brackets"},
        )
        assert response.status_code == 403, response.text

    def test_ingest_model_succeeds_with_granted_collection_role(
        self, tmp_path: Path, client: TestClient, db_session: Session
    ) -> None:
        use_local_storage(tmp_path)
        user = _regular_user(db_session)
        collection = build_collection(
            db_session, name="Brackets", slug="brackets", path="brackets"
        )
        grant_collection_role(db_session, user, collection, CollectionRole.EDIT)

        payload = completed_job(
            client,
            client.post(
                "/api/v1/ingest/model",
                headers=bearer(user),
                files={"file": ("cube.stl", _cube_stl(), "application/sla")},
                data={"collection": "brackets"},
            ),
        )
        assert payload["model_id"] is not None

    def test_ingest_model_rejects_disabled_target_library(
        self, tmp_path: Path, client: TestClient, auth_headers: dict[str, str]
    ) -> None:
        use_local_storage(tmp_path)
        response = client.post(
            "/api/v1/ingest/model",
            headers=auth_headers,
            files={"file": ("cube.stl", _cube_stl(), "application/sla")},
            data={"target_library_id": "999"},
        )
        assert response.status_code == 400, response.text
        assert response.json()["detail"] == "external_libraries_disabled"

    def test_ingesting_an_stl_produces_a_servable_artifact(
        self,
        tmp_path: Path,
        client: TestClient,
        db_session: Session,
        auth_headers: dict[str, str],
    ) -> None:
        use_local_storage(tmp_path)

        payload = completed_job(
            client,
            client.post(
                "/api/v1/ingest/model",
                headers=auth_headers,
                files={"file": ("cube.stl", _cube_stl(), "application/sla")},
                data={"model_name": "Cube"},
            ),
        )
        file_id = payload["file_id"]
        assert_file_created(db_session, file_id, FileType.STL)

        download = client.get(f"/api/v1/files/{file_id}/download", headers=auth_headers)
        assert download.status_code == 200, download.text
        assert b"solid cube" in download.content

        thumbnail = client.get(
            f"/api/v1/files/{file_id}/thumbnail", headers=auth_headers
        )
        assert thumbnail.status_code == 200, thumbnail.text
        assert thumbnail.headers["content-type"] == "image/webp"
        assert thumbnail.content.startswith(WEBP_MAGIC)

    def test_ingest_publishes_terminal_only_after_fresh_durability_check(
        self,
        tmp_path: Path,
        client: TestClient,
        auth_headers: dict[str, str],
        monkeypatch,
    ) -> None:
        use_local_storage(tmp_path)
        checkpoints: list[str] = []
        observed_job_ids: list[str] = []
        original_verify = ingestion_service.verify_durable_artifact

        def observe_checkpoint(stage: str, current_job_id: str) -> None:
            if stage == "after_commit":
                observed_job_ids.append(current_job_id)

        def observed_verify(*args, **kwargs) -> None:
            status = ingestion_service.registry.get(observed_job_ids[-1])
            assert status is not None
            assert status.state == "running"
            assert status.progress is None or status.progress < 100
            assert status.committed_at is not None
            checkpoints.append("fresh_session_and_storage")
            original_verify(*args, **kwargs)

        monkeypatch.setattr(
            ingestion_service, "_fault_injection_checkpoint", observe_checkpoint
        )
        monkeypatch.setattr(
            ingestion_service, "verify_durable_artifact", observed_verify
        )
        response = client.post(
            "/api/v1/ingest/model",
            headers=auth_headers,
            files={"file": ("durable.stl", _cube_stl(), "application/sla")},
            data={"model_name": "Durable Cube"},
        )
        assert response.status_code == 202
        job_id = response.json()["job_id"]

        status = client.get(
            f"/api/v1/ingest/jobs/{job_id}", headers=auth_headers
        ).json()
        assert checkpoints == ["fresh_session_and_storage"]
        assert status["state"] == "completed"
        assert status["completion"] == "complete"
        assert status["thumbnail_status"] == "generated"
        assert status["committed_at"] is not None

    def test_issue_67_over_cap_stl_persists_authenticated_webp_fallback(
        self,
        tmp_path: Path,
        client: TestClient,
        auth_headers: dict[str, str],
        monkeypatch,
    ) -> None:
        use_local_storage(tmp_path)
        monkeypatch.setitem(_overlay, "mesh_max_render_triangles", 1_000)

        payload = completed_job(
            client,
            client.post(
                "/api/v1/ingest/model",
                headers=auth_headers,
                files={
                    "file": (
                        "issue-67-over-limit.stl",
                        _over_cap_binary_stl(),
                        "application/sla",
                    )
                },
                data={"model_name": "Issue 67 Fallback"},
            ),
        )

        assert payload["completion"] == "complete"
        assert payload["thumbnail_status"] == "fallback_generated"
        thumbnail = client.get(
            f"/api/v1/files/{payload['file_id']}/thumbnail", headers=auth_headers
        )
        assert thumbnail.status_code == 200
        assert thumbnail.headers["content-type"] == "image/webp"
        assert thumbnail.content.startswith(WEBP_MAGIC)

    def test_issue_67_upload_survives_pruning_completed_inbox_job(
        self,
        tmp_path: Path,
        client: TestClient,
        db_session: Session,
        auth_headers: dict[str, str],
        monkeypatch,
    ) -> None:
        """A stale terminal inbox link must not turn the next upload into a 500."""
        use_local_storage(tmp_path)
        owner = db_session.exec(
            select(User).where(User.username == "test-writer")
        ).one()
        old_job = BackgroundJob(
            id="expired-inbox-job",
            owner_user_id=owner.id,
            state="completed",
            status_json='{"state":"completed"}',
            finished_at=utcnow() - timedelta(hours=2),
        )
        db_session.add(old_job)
        db_session.flush()
        db_session.add(
            InboxItem(
                owner_user_id=owner.id,
                state=InboxItemState.COMPLETED,
                background_job_id=old_job.id,
            )
        )
        db_session.commit()
        monkeypatch.setattr(registry, "_last_persisted_prune_at", float("-inf"))

        response = client.post(
            "/api/v1/ingest/model",
            headers=auth_headers,
            files={"file": ("issue-67.stl", _cube_stl(), "application/sla")},
            data={"model_name": "Issue 67 Upload"},
        )

        assert response.status_code == 202, response.text

    def test_force_rebuild_refreshes_existing_mesh_thumbnail(
        self,
        tmp_path: Path,
        client: TestClient,
        auth_headers: dict[str, str],
        monkeypatch,
    ) -> None:
        from PIL import Image

        use_local_storage(tmp_path)

        payload = completed_job(
            client,
            client.post(
                "/api/v1/ingest/model",
                headers=auth_headers,
                files={"file": ("cube.stl", _cube_stl(), "application/sla")},
                data={"model_name": "Cube"},
            ),
        )
        file_id = payload["file_id"]
        model_id = payload["model_id"]
        replacement_buffer = io.BytesIO()
        Image.new("RGB", (12, 10), (220, 30, 20)).save(replacement_buffer, format="PNG")
        replacement = replacement_buffer.getvalue()

        monkeypatch.setattr(
            "app.services.mesh_processing.render_thumbnail",
            lambda _path: replacement,
        )

        response = client.post(
            "/api/v1/files/thumbnails/rebuild?force=true",
            headers=auth_headers,
        )

        assert response.status_code == 202, response.text
        job_id = response.json()["job_id"]
        job = client.get(f"/api/v1/ingest/jobs/{job_id}", headers=auth_headers)
        assert job.status_code == 200, job.text
        payload = job.json()
        assert payload["state"] == "completed", payload
        assert payload["completion"] == "complete"
        assert payload["thumbnail_status"] == "generated"
        assert payload["succeeded"] == 1
        assert payload["result"]["rebuilt"] == [model_id]

        thumbnail = client.get(
            f"/api/v1/files/{file_id}/thumbnail", headers=auth_headers
        )
        assert thumbnail.status_code == 200, thumbnail.text
        assert thumbnail.content.startswith(WEBP_MAGIC)
        with Image.open(io.BytesIO(thumbnail.content)) as refreshed:
            assert refreshed.convert("RGB").getpixel((0, 0)) == (220, 30, 20)

    def test_ingest_refuses_an_upload_when_staging_is_full(
        self,
        tmp_path: Path,
        client: TestClient,
        auth_headers: dict[str, str],
        monkeypatch,
    ) -> None:
        use_local_storage(tmp_path)
        monkeypatch.setitem(_overlay, "staging_min_free_gb", 1_000_000)

        response = client.post(
            "/api/v1/ingest/orca",
            headers=auth_headers,
            files={"file": ("part.gcode", b"G28\n", "text/plain")},
        )

        # 507, not 500: the request was fine, the disk was not.
        assert response.status_code == 507, response.text
        assert response.json()["detail"] == "staging_capacity_exceeded"

    def test_ingest_fails_the_job_when_the_staging_lease_cannot_be_taken(
        self,
        tmp_path: Path,
        client: TestClient,
        auth_headers: dict[str, str],
        monkeypatch,
    ) -> None:
        from app.api.v1 import ingest as ingest_api

        use_local_storage(tmp_path)
        created: list[str] = []
        real_create = ingest_api.registry.create

        def recording_create(*args: object, **kwargs: object) -> str:
            job_id = real_create(*args, **kwargs)
            created.append(job_id)
            return job_id

        def broken(*_args: object, **_kwargs: object):
            raise RuntimeError("staging ledger unavailable")

        monkeypatch.setattr(ingest_api.registry, "create", recording_create)
        monkeypatch.setattr(ingest_api, "_record_staging_lease", broken)

        with pytest.raises(RuntimeError, match="staging ledger unavailable"):
            client.post(
                "/api/v1/ingest/orca",
                headers=auth_headers,
                files={"file": ("part.gcode", b"G28\n", "text/plain")},
            )

        # A job left pending forever is a queue an operator cannot clear.
        status = registry.get(created[0])
        assert status is not None
        assert status.state == "failed"
        assert status.error == "staging_lease_failed"

    def test_ingest_removes_the_staged_file_when_staging_is_full(
        self,
        tmp_path: Path,
        client: TestClient,
        auth_headers: dict[str, str],
        monkeypatch,
    ) -> None:
        use_local_storage(tmp_path)
        monkeypatch.setitem(_overlay, "staging_min_free_gb", 1_000_000)

        client.post(
            "/api/v1/ingest/orca",
            headers=auth_headers,
            files={"file": ("part.gcode", b"G28\n", "text/plain")},
        )

        # The bytes were written before the capacity check; leaving them would make
        # the next request's check even more likely to fail.
        from app.core.config import settings

        staged = (
            list(settings.incoming_dir.iterdir())
            if settings.incoming_dir.exists()
            else []
        )
        assert staged == []

    def test_exception_after_commit_is_a_durable_partial_result(
        self,
        tmp_path: Path,
        client: TestClient,
        db_session: Session,
        auth_headers: dict[str, str],
        monkeypatch,
    ) -> None:
        use_local_storage(tmp_path)

        def inject(stage: str, _job_id: str) -> None:
            if stage == "after_commit":
                raise RuntimeError("injected_after_commit")

        monkeypatch.setattr(ingestion_service, "_fault_injection_checkpoint", inject)
        response = client.post(
            "/api/v1/ingest/model",
            headers=auth_headers,
            files={"file": ("post-commit.stl", _cube_stl(), "application/sla")},
            data={"model_name": "Post Commit Cube"},
        )
        assert response.status_code == 202
        job_id = response.json()["job_id"]
        status = client.get(
            f"/api/v1/ingest/jobs/{job_id}", headers=auth_headers
        ).json()

        assert status["state"] == "completed"
        assert status["completion"] == "partial"
        assert status["thumbnail_reason"] == "post_commit_exception"
        assert status["retryable"] is True
        assert db_session.get(Model, status["model_id"]) is not None
        assert db_session.get(File, status["file_id"]) is not None

    def test_reuploading_deleted_model_restores_it(
        self,
        tmp_path: Path,
        client: TestClient,
        db_session: Session,
        auth_headers: dict[str, str],
    ) -> None:
        use_local_storage(tmp_path)

        first = completed_job(
            client,
            client.post(
                "/api/v1/ingest/model",
                headers=auth_headers,
                files={"file": ("cube.stl", _cube_stl(), "application/sla")},
                data={"model_name": "Cube"},
            ),
        )
        model_id = first["model_id"]

        delete = client.delete(f"/api/v1/models/{model_id}", headers=auth_headers)
        assert delete.status_code == 204
        assert (
            client.get(f"/api/v1/models/{model_id}", headers=auth_headers).status_code
            == 404
        )

        second = completed_job(
            client,
            client.post(
                "/api/v1/ingest/model",
                headers=auth_headers,
                files={"file": ("cube.stl", _cube_stl(), "application/sla")},
                data={"model_name": "Cube"},
            ),
        )

        assert second["model_id"] == model_id
        model = db_session.get(Model, model_id)
        assert model is not None
        assert model.deleted_at is None
        detail = client.get(f"/api/v1/models/{model_id}", headers=auth_headers)
        assert detail.status_code == 200, detail.text
        assert len(detail.json()["files"]) == 2

    def test_a_model_survives_the_whole_trash_lifecycle(
        self,
        tmp_path: Path,
        client: TestClient,
        db_session: Session,
        auth_headers: dict[str, str],
    ) -> None:
        use_local_storage(tmp_path)

        payload = completed_job(
            client,
            client.post(
                "/api/v1/ingest/model",
                headers=auth_headers,
                files={"file": ("cube.stl", _cube_stl(), "application/sla")},
                data={"model_name": "Cube"},
            ),
        )
        model_id = payload["model_id"]
        file_row = db_session.get(File, payload["file_id"])
        assert file_row is not None
        blob_path = file_row.path
        thumb_path = get_backend().thumbnail_key(file_row.id)

        delete = client.delete(f"/api/v1/models/{model_id}", headers=auth_headers)
        assert delete.status_code == 204

        trash = client.get("/api/v1/models/trash", headers=auth_headers)
        assert trash.status_code == 200, trash.text
        assert trash.json()[0]["id"] == model_id
        assert trash.json()[0]["file_count"] == 1
        assert trash.json()[0]["expires_at"] is not None

        restored = client.post(
            f"/api/v1/models/{model_id}/restore", headers=auth_headers
        )
        assert restored.status_code == 200, restored.text
        assert restored.json()["id"] == model_id
        assert client.get("/api/v1/models/trash", headers=auth_headers).json() == []

        delete = client.delete(f"/api/v1/models/{model_id}", headers=auth_headers)
        assert delete.status_code == 204
        purged = client.delete(f"/api/v1/models/{model_id}/purge", headers=auth_headers)
        assert purged.status_code == 200, purged.text
        assert purged.json() == {
            "purged_model_ids": [model_id],
            "purged_count": 1,
            "storage_completed": 2,
            "storage_pending": 0,
            "storage_blocked": 0,
            "resources_blocked": 0,
        }
        db_session.expire_all()
        assert db_session.get(Model, model_id) is None
        assert db_session.get(File, payload["file_id"]) is None
        assert not get_backend().exists(blob_path)
        assert not get_backend().exists(thumb_path)


class TestGetJob:
    def test_get_job_unknown_id_returns_404(
        self, client: TestClient, auth_headers: dict[str, str]
    ) -> None:
        response = client.get(
            "/api/v1/ingest/jobs/does-not-exist", headers=auth_headers
        )
        assert response.status_code == 404, response.text
        assert response.json()["detail"] == "job_not_found"

    def test_hides_another_users_ingest_job_as_not_found(
        self,
        tmp_path: Path,
        client: TestClient,
        db_session: Session,
        auth_headers: dict[str, str],
    ) -> None:
        use_local_storage(tmp_path)
        completed_job(
            client,
            client.post(
                "/api/v1/ingest/model",
                headers=auth_headers,
                files={"file": ("cube.stl", _cube_stl(), "application/sla")},
                data={"model_name": "Cube"},
            ),
        )
        job_id = client.get("/api/v1/ingest/jobs", headers=auth_headers).json()[0][
            "job_id"
        ]
        other = _regular_user(db_session, "other-owner")

        response = client.get(f"/api/v1/ingest/jobs/{job_id}", headers=bearer(other))

        # 404 rather than 403: a job id is guessable, and confirming one exists tells
        # the caller that somebody else uploaded something.
        assert response.status_code == 404, response.text
