name: Manual Docker Images

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/container-publish.yml
    secrets: inherit
