"""Opt-in authentication for browser importer device credentials.

This intentionally does not participate in the normal JWT/user dependencies:
only the two importer routes explicitly opting in can accept a paired browser.
"""

from __future__ import annotations

import hashlib

from fastapi import Depends, HTTPException, status
from sqlmodel import Session, select

from app.core.security import oauth2_scheme
from app.core.time import utcnow
from app.db.models import BrowserDevice, User
from app.db.session import get_session
from app.services.auth import verify_access_token
from app.services.provider_connections import credential_matches


def require_browser_import_user(
    credential: str | None = Depends(oauth2_scheme),
    session: Session = Depends(get_session),
) -> User:
    """Return the paired device owner for explicitly browser-import routes only."""
    invalid = HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED, detail="invalid_browser_credential"
    )
    if not credential:
        raise invalid
    # The lookup value is deterministic but the stored value is never returned.
    credential_hash = hashlib.sha256(credential.encode("utf-8")).hexdigest()
    device = session.exec(
        select(BrowserDevice).where(BrowserDevice.credential_hash == credential_hash)
    ).first()
    # Keep the secret comparison explicit even though the indexed lookup narrows
    # candidates. Never report whether the credential, device, or user failed.
    if device is None or not credential_matches(credential, device.credential_hash):
        raise invalid
    if device.revoked_at is not None:
        raise invalid
    user = session.get(User, device.user_id)
    if user is None or not user.is_active:
        raise invalid
    device.last_used_at = utcnow()
    session.flush()
    return user


def require_user_or_browser_import_user(
    credential: str | None = Depends(oauth2_scheme),
    session: Session = Depends(get_session),
) -> User:
    """Accept a normal write JWT or a paired device, only on import routes."""
    # Access JWTs have three compact-JWS segments; opaque browser credentials
    # generated by the pairing service do not. Do not let a malformed JWT fall
    # through to a normal user dependency or widen its scope.
    if credential and credential.count(".") == 2:
        payload = verify_access_token(credential)
        if payload and payload.get("scope") in {"write", "admin"}:
            subject = payload.get("sub")
            try:
                user_id = int(subject) if isinstance(subject, (str, int)) else None
            except (TypeError, ValueError):
                user_id = None
            user = session.get(User, user_id) if user_id is not None else None
            if (
                user
                and user.is_active
                and payload.get("auth_version") == user.auth_version
            ):
                return user
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED, detail="not_authenticated"
        )
    return require_browser_import_user(credential, session)
